### ISSUE TITLE
Capitalization in gui

### ISSUE THREAD

**Issue by micwoj92** [nullworks/cathook#1013]
Currently Most of GUI is Capitalized Like This (Title case) but it is inconsistent and looks weird (at least for me).
 Shouldn't all text in gui be formatted in titlr case?

**Comment by xXTevinOfficialXx** [comment]
If you don't like it the way it is, just modify every file in it and capitalize every letter in every string.

**Comment by TotallyNotElite** [comment]
I really dislike title case. Everything should be capitalized normally.

**Comment by micwoj92** [comment]
> I really dislike title case. Everything should be capitalized normally.

Same, but it seems like most is in title case.

**Comment by micwoj92** [comment]
This was fixed in #1047 thx @LightPower392
