### ISSUE TITLE
Install-all error

### ISSUE THREAD

**Issue by xeeth** [nullworks/cathook#1017]
Sorry for this noob question here, I see that you don't yet have open support for 20.04, but when i run install-all on Pop-OS, CMake can't compile because of these dependencies. If I try to install them manually then some other dependencies get removed, and so on and so forth.
Could you help?

The following packages have unmet dependencies:
 libfreetype6-dev:i386 : Depends: libfreetype-dev:i386 (= 2.10.1-2) but it is not going to be installed
 libsdl2-dev:i386 : Depends: libibus-1.0-dev:i386 but it is not going to be installed
                    Depends: libpulse-dev:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by BenCat07** [comment]
PopOS is not Ubuntu 20.04, and is missing required packages

**Comment by xeeth** [comment]
> PopOS is not Ubuntu 20.04, and is missing required packages

Could you provide the packages required then? I will try to add them manually.

**Comment by BenCat07** [comment]
it tells you which.

**Comment by xeeth** [comment]
Seems to be 32-bit architecture issue, closed
