### ISSUE TITLE
Smooth Aimbot when Spectated

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#1021]
Cathook recently added the option to disable aimbot when spectated.
This is fine, and really great, but for "closet" cheaters with 10-30 fov aimbot it can cause them to loose a match and die too fast just because someone was spectating them.

Something that I've always wanted would be the ability to switch to smooth aimbot when spectated. So when no one is spectating you, and you're just mowing people down, your team can't risk the time to watch you and your enemies are too busy dieing by you. But when a player spectates you, you have to choose between being detected and getting kicked or having your aimbot completely be disabled which makes it look like you're either toggling or you're really shit.

Don't get me wrong, having someone spectate you and then see you miss nearly every single one of your shots and then die helps you a lot when it comes to looking legit. I often have that happen to me, in which the person who spectates me will then go on to claim that I suck too bad to be hacking.
But to be honest with you, the fact that I lost that little matchup just because someone spectated me fills me with more rage than I'd like to risk looking legit.

So my suggestion is to have an option that switches you to smooth aim mode when someone spectates you. You can still cheat as normal, but now when someone spectates you, you can still have that slight edge that still lets you win some fights and still look legit.

**Comment by LightPower392** [comment]
I'm planning on adding an option for spectated FOV and spectated aimbot slow. How does that sound?

**Comment by SylveonBottle** [comment]
Would just be fine to set it to slow mode but that'd be great!

**Comment by BenCat07** [comment]
also pr'd
