### ISSUE TITLE
[Bug]Bots move around dispenser (instead of standing still)

### ISSUE THREAD

**Issue by Freezgam03** [nullworks/cathook#1024]
Before bots used to move to dispensers when nearby and stand still until they got full hp, now they move away from the dispenser and go back to it and repeat till they have enough health, which is obv not how its suppose to work

![giphy](https://user-images.githubusercontent.com/65787083/82764735-57080f00-9e11-11ea-81fd-19d13f02bdad.gif)

**Comment by BenCat07** [comment]
Fixed recently
