### ISSUE TITLE
[Bug] Crit text doesn't move with the Crit bar properly

### ISSUE THREAD

**Issue by Freezgam03** [nullworks/cathook#1031]
As you can see in the screen below, the crit text on how much damage needs to be dealt in order for a new crit doesn't move properly with the crit bar.

![Screenshot_20200524_130733](https://user-images.githubusercontent.com/65787083/82752669-e5ec3b80-9dbf-11ea-94af-6759efd17f3c.png)

**Comment by BenCat07** [comment]
Fixed recently
