### ISSUE TITLE
[Bug] Bots behaviour against sentries

### ISSUE THREAD

**Issue by Freezgam03** [nullworks/cathook#1038]
As far as I know before they used to find spots where they outrange the sentry to shoot at it but now they avoid it alltogether?

I saw this multiple times on turbine.

**Comment by SylveonBottle** [comment]
Could be a suggestion.

1. Check if a navmesh square is right next to one that is within detection of a sentry
2. Walk into the navmesh with the sentry, crouching
3. Keep walking until you can see a peace of the sentry, then stop
4. Fuck their shit up

 
If this was added previously (but then removed), the previous method of finding sentries could possibly be better. Maybe, like, _actually_ finding where the sentry range ends and shit.

**Comment by iraizo** [comment]
Its probaly easier for the bots to just ignore it if thats the case right now anyways

**Comment by iraizo** [comment]
Closing this until one of the maintainers says otherwise.

**Comment by SylveonBottle** [comment]
Is this issue fixed / a 'fix''/workaround implimented, or are you just closing inactive issues?

**Comment by TotallyNotElite** [comment]
This has been re-added to cathook recently so closing this is a good call.

**Comment by BenCat07** [comment]
bots actively hunt sentries now
