### ISSUE TITLE
[SUGGESTION] Minimum entity distance from sticky

### ISSUE THREAD

**Issue by KaylinOwO** [nullworks/cathook#1044]
Custom minimum entity distance for when the sticky auto detonates, atm min distance is the distance of the local player. Would be useful for getting maximum damage possible on the player.

**Comment by BenCat07** [comment]
Nope, it's the distance to the target

**Comment by BenCat07** [comment]
See AutoSticky.cpp Line 175
`                if (bomb->m_vecOrigin().DistTo(*position) < *min_dist)`
