### ISSUE TITLE
New Slow Aim is Bad

### ISSUE THREAD

**Issue by LightPower392** [nullworks/cathook#1049]
The new version of slow aim doesn't smooth the aim enough. I changed `float step_amount = 40.0f / std::max(1, slow_aim);` to `float step_amount = 4.0f / std::max(1, slow_aim);` and it helped, but it still had too blatant tracking when your crosshair is near an enemy.

**Comment by BenCat07** [comment]
What suggestion do you have to fix it? decreasing the 40.0f to 4.0f is about the equivalent as just using a higher value. The old slow aim had serious problems, and in some cases did not work correctly or at all.

**Comment by LightPower392** [comment]
At the very least it needs to be slower when the crosshair is close to an enemy. Even at a high slow setting it snaps around.

**Comment by TotallyNotElite** [comment]
Closed because it was reverted.
