### ISSUE TITLE
Can't attach

### ISSUE THREAD

**Issue by nightmarestar1** [nullworks/cathook#1055]
I am unable to get cathook to attach to tf2. This is the error im getting when I attempt to attach
Running instances: 2110 2263
Attaching to 2110
loading /tmp/.glwDX7B4 to 2110
[New LWP 2256]
[New LWP 2264]
[New LWP 2265]
[New LWP 2266]
[New LWP 2267]
[New LWP 2268]
[New LWP 2269]
[New LWP 2270]
[New LWP 2271]
[New LWP 2272]
[New LWP 2273]
[New LWP 2274]
[New LWP 2275]
[New LWP 2276]
[New LWP 2277]
[New LWP 2278]
[New LWP 2279]
warning: Could not load shared library symbols for 2 libraries, e.g. /tmp/.glUhFmej.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0xf7ef1ed9 in __kernel_vsyscall ()
[New Thread 0xdf8a9b40 (LWP 2453)]
$1 = (void *) 0x9e04b00
'dlerror' has unknown return type; cast the call to its declared return type
History has not yet reached $2.
[Inferior 1 (process 2110) detached]

**Comment by BenCat07** [comment]
Looks like a normal attach log to me

**Comment by nightmarestar1** [comment]
It doesn't show the menu in game when attached, cat console commands also don't work

**Comment by nightmarestar1** [comment]
nevermind its suddenly working lol tried fixing for hours yesterday. mb

**Comment by BenCat07** [comment]
If it works it works
