### ISSUE TITLE
catbots stuck in account state

### ISSUE THREAD

**Issue by nightmarestar1** [nullworks/cathook#1056]
Hey I used the account generator and setup the accounts.cg.json folder with the account:password setup. I'm still getting bots stuck at the ACCOUNT state. I'm not sure what I've messed up on. 
![image](https://user-images.githubusercontent.com/66652892/84162115-9f404780-aa35-11ea-860a-cb0d75d888d2.png)

**Comment by BenCat07** [comment]
ACCOUNT state means no accounts were found which means you didn't copy the **accounts0.cg.json file** to the **account-generator folder** and also may have forgot to rename it, removing the "0".

**Comment by nightmarestar1** [comment]
I removed the 0 and placed it into the account generator folder

**Comment by BenCat07** [comment]
You need to have the whole thing stopped before you do that, that might be why

**Comment by nightmarestar1** [comment]
I stopped the bots, remade the accounts file, and restarted the bots and i'm still getting the ACCOUNT state

**Comment by BenCat07** [comment]
then your accounts.cg.json must be empty/have no accounts

**Comment by nightmarestar1** [comment]
They seem to have gotten past the account stage now but now they keep cycling between starting waiting and restarting themselves

**Comment by BenCat07** [comment]
Auto restart might be the cause, or you have not updated your catbot-setup in a while

**Comment by nightmarestar1** [comment]
everything with the profiles is working now but their not finding matches. It says their in queue but its 10 minutes long for each one

**Comment by BenCat07** [comment]
I recommend following OneTrick's guide. you have to have a config set up to load for the bots so they actually know what to do, where to queue, etc. His guide also tells you that you need to save a map list first.

**Comment by nightmarestar1** [comment]
I am going through OneTrick's guide. I set up a config for them and I saved my map list for them too. Do I have to do anything other than change the cat auto exec in my tf2?

**Comment by BenCat07** [comment]
there is an autoqueue option in the menu, maybe you forgot to check it

**Comment by nightmarestar1** [comment]
its checked in config that was one of the first things I checked since I thought I might have forgotten it

**Comment by BenCat07** [comment]
Did you get it to work or?

**Comment by nightmarestar1** [comment]
they still just get stuck in queue, i'm retrying some stuff to maybe see if it works
