### ISSUE TITLE
TF2 crashes at inject

### ISSUE THREAD

**Issue by ghost** [nullworks/cathook#1068]
Hello, I'm normally injecting cheat but when it finishes attaching it just crashes without anything.
I'm using Binary version
Ubuntu 20.04
Tried source version but its not even injecting

Terminal UI NOT supported! Install "dialog"! 
Running instances: 8530
Attaching to 8530
cp: cannot stat 'bin/libcathook.so': No such file or directory
loading /tmp/.gl63O3Z2 to 8530
[New LWP 8531]
[New LWP 8532]
[New LWP 8533]
[New LWP 8534]
[New LWP 8535]
[New LWP 8537]
[New LWP 8538]
[New LWP 9202]
[New LWP 9217]
[New LWP 9218]
[New LWP 9219]
[New LWP 9220]
[New LWP 9645]
[New LWP 9646]
[New LWP 9647]
[New LWP 9648]
[New LWP 9649]
[New LWP 9650]
[New LWP 9651]
[New LWP 9654]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0xf7f47b49 in __kernel_vsyscall ()
$1 = (void *) 0x0
'dlerror' has unknown return type; cast the call to its declared return type
History has not yet reached $2.
[Inferior 1 (process 8530) detached]
rm: cannot remove '/tmp/.gl63O3Z2': No such file or directory

**Comment by Codefreak64** [comment]
PERFECT, now we have less bots to kick that ruin our games
