### ISSUE TITLE
[Question] Can you make bots join a specific server and become pocket medics?

### ISSUE THREAD

**Issue by TheCrazyInsanity** [nullworks/cathook#1069]
I would like to have pocket medics and since i have no friends bots will work too. All i need them to do is follow me and heal me.

**Comment by Freezgam03** [comment]
Yes you can.

Configure the bot to use Followbot and then follow STEAMID, just put your STEAMID in. After that once you have the bot online just type "connect (ip from server) (without the symbols))"" into the "command" box.

**Comment by TheCrazyInsanity** [comment]
> Yes you can.
> 
> Configure the bot to use Followbot and then follow STEAMID, just put your STEAMID in. After that once you have the bot online just type "connect (ip from server) (without the symbols))"" into the "command" box.

Thanks alot. I will be installing virtualbox right now

**Comment by TotallyNotElite** [comment]
> > Yes you can.
> > Configure the bot to use Followbot and then follow STEAMID, just put your STEAMID in. After that once you have the bot online just type "connect (ip from server) (without the symbols))"" into the "command" box.
> 
> Thanks alot. I will be installing virtualbox right now

As always, the developers highly recommend "dual booting" which means having both Linux and windows installed. The installer of most distros, including cathookos will guide you thru this easily.

**Comment by TheCrazyInsanity** [comment]
> > > Yes you can.
> > > Configure the bot to use Followbot and then follow STEAMID, just put your STEAMID in. After that once you have the bot online just type "connect (ip from server) (without the symbols))"" into the "command" box.
> > 
> > 
> > Thanks alot. I will be installing virtualbox right now
> 
> As always, the developers highly recommend "dual booting" which means having both Linux and windows installed. The installer of most distros, including cathookos will guide you thru this easily.

Yes i know. I have dual booted many times before. But all im doing is hosting some catbots to heal me. I dont plan on actually using cathook

**Comment by TheCrazyInsanity** [comment]
> > > Yes you can.
> > > Configure the bot to use Followbot and then follow STEAMID, just put your STEAMID in. After that once you have the bot online just type "connect (ip from server) (without the symbols))"" into the "command" box.
> > 
> > 
> > Thanks alot. I will be installing virtualbox right now
> 
> As always, the developers highly recommend "dual booting" which means having both Linux and windows installed. The installer of most distros, including cathookos will guide you thru this easily.

As a reply to that this vm is hella slow and i will burn a disc overnight to install.
