### ISSUE TITLE
[Question] Does cathook os contain catbot software?

### ISSUE THREAD

**Issue by TheCrazyInsanity** [nullworks/cathook#1070]
I am to stupid to install catbot so just asking before i waste an hour trying to use a software that isnt there.

**Comment by Freezgam03** [comment]
To make this simpler be sure to join our Telegram group so we can help you a bit easier, instead of making comments on here all the time. https://t.me/nullworks

**Comment by TheCrazyInsanity** [comment]
> To make this simpler be sure to join our Telegram group so we can help you a bit easier, instead of making comments on here all the time. https://t.me/nullworks

Just did
