### ISSUE TITLE
Add auto backtrack feature

### ISSUE THREAD

**Issue by Footsiefat** [nullworks/cathook#1072]
So for spy's you can have backtrack + auto backtrack stab. But the latency is set to a set time. Meaning you still need to get behind the projection. Instead I'm thinking you add an option to automatically bring the projections as close to the player as possible by automatically guessing and setting the backtrack latency.

**Comment by xXTevinOfficialXx** [comment]
Backtrack already tries to get closest to player as possible, you can see it if you enable backtrack and backtrack chams

**Comment by BenCat07** [comment]
^

**Comment by SylveonBottle** [comment]
OP is asking for you to add dynamic latency, not "auto backtrack".

As it currently stands, if you enable backtrack, you can see all of the backtrack chams behind the enemy. But if you're chasing someone and you're too far behind them, it would be sick if cathook could automatically increase your fake latency so you can backstab him. 

Re-open issue or I'll make a new one with more detail lol
