### ISSUE TITLE
Cathook not attaching to TF2

### ISSUE THREAD

**Issue by CovertGoose** [nullworks/cathook#1074]
I am new to Cathook and Linux.

I have booted my linux on Cathook OS and am currently trying to attach Cathook to TF2 by doing sudo ./attach in the Konsole after typing cd cathook. When I try to attach it, I get this message:

Running instances: 1750
Attaching to 1750
loading /tmp/.glmJ2AHa to 1750
gdb: error while loading shared libraries: libicudata.so.67: cannot open shared object file: No such file or directory
[goose@goose-vmwarevirtualplatform cathook]$ remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
HEAD is now at ab709f7 Update migrations to remove gitlab migration
~/cathook/build ~/cathook
-- Found Boost: /usr/lib/cmake/Boost-1.72.0/BoostConfig.cmake (found suitable version "1.72.0", minimum required is "1.70.0")  
-- Found Boost: /usr/lib/cmake/Boost-1.72.0/BoostConfig.cmake (found version "1.72.0")  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/goose/cathook/build
[100%] Built target cathook
Installing cathook data to /opt/cathook/data
sending incremental file list
./
fonts/
menu/
menu/nullifiedcat/
menu/nullifiedcat/misc/
menu/nullifiedcat/trigger/
menu/nullifiedcat/visuals/
sound/
textures/

sent 2.45K bytes  received 282 bytes  5.46K bytes/sec
total size is 7.30M  speedup is 2,672.90
sending incremental file list

sent 212 bytes  received 12 bytes  448.00 bytes/sec
total size is 657  speedup is 2.93
chown: changing ownership of '/opt/cathook/data/dominatesay.txt': Operation not permitted
chown: changing ownership of '/opt/cathook/data/names.txt': Operation not permitted
chown: changing ownership of '/opt/cathook/data/teamspam.txt': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/ludicrouskill.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/monsterkill.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/firstblood.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/godlike.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/perfect.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/ultrakill.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/prepare.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/humiliation.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/headhunter.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/megakill.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/multikill.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/unstoppable.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/rampage.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/combowhore.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/dominating.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/killingspree.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/impressive.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/piss.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/headshot.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/wickedsick.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/holyshit.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/doublekill.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/triplekill.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/teamkiller.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/play.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound/hattrick.wav': Operation not permitted
chown: changing ownership of '/opt/cathook/data/sound': Operation not permitted
chown: changing ownership of '/opt/cathook/data/killsays.txt': Operation not permitted
chown: changing ownership of '/opt/cathook/data/fonts/tf2build.ttf': Operation not permitted
chown: changing ownership of '/opt/cathook/data/fonts/opensans.ttf': Operation not permitted
chown: changing ownership of '/opt/cathook/data/fonts/megasans.ttf': Operation not permitted
chown: changing ownership of '/opt/cathook/data/fonts/verasans.ttf': Operation not permitted
chown: changing ownership of '/opt/cathook/data/fonts/roboto.ttf': Operation not permitted
chown: changing ownership of '/opt/cathook/data/fonts/unispace.ttf': Operation not permitted
chown: changing ownership of '/opt/cathook/data/fonts': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullified-ui.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/debug.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/aimbot.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/misc.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/chat.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/visuals/bullettracers.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/visuals/world.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/visuals/uicolors.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/visuals/esp.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/visuals/ui.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/visuals/glow.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/visuals/tracers.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/visuals/playerinfo.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/visuals/chams.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/visuals/radar.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/visuals': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/movement.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/crits.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/visuals.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/triggerbot.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/misc/autoload.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/misc/catbot.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/misc/datacenters.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/misc/buildings.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/misc/spyalert.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/misc/anticheat.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/misc/collective.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/misc/autoequip.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/misc': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/hackinfo.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/nospread.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/trigger/autopyro.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/trigger/autospy.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/trigger/autosticky.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/trigger/autoheal.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/trigger': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat/antiaim.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/nullifiedcat': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/color-picker.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/VerdanaBold.ttf': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/Verdana.ttf': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/menu.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/player-list-row.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/window-settings.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/player-list-window.xml': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu/cross.png': Operation not permitted
chown: changing ownership of '/opt/cathook/data/menu': Operation not permitted
chown: changing ownership of '/opt/cathook/data/critsay.txt': Operation not permitted
chown: changing ownership of '/opt/cathook/data/spam.txt': Operation not permitted
chown: changing ownership of '/opt/cathook/data/textures/atlas.xcf': Operation not permitted
chown: changing ownership of '/opt/cathook/data/textures/idspec.png': Operation not permitted
chown: changing ownership of '/opt/cathook/data/textures/atlas.png': Operation not permitted
chown: changing ownership of '/opt/cathook/data/textures': Operation not permitted
chown: changing ownership of '/opt/cathook/data': Operation not permitted
Built target data
~/cathook

Cathook updated successfully

And then Cathook does not attach to TF2. If anyone has a fix for this please let me know!

I am new to linux and Cathook so I may need some extra help.

Thanks!

**Comment by Codefreak64** [comment]
Good, lets keep this bug of not connecting in
Why is this still being refined, do you know how much pain us normal players have to go through, bot many bots we have to kick? and for what, to get a cheap laugh? if you want TF2 to DIE! then by all means please continue, but i'm not going to let a whole bunch of salty players try to KILL A GOOD GAME!!

**Comment by aUniqueUser** [comment]
mad

**Comment by dankdonk** [comment]
I get this exact bug with Fedora 32. When attaching it gives some error about some obscure missing .so in /tmp/ and about how tf2 is in a different namespace. Are you using the steam flatpak/snap?

> Good, lets keep this bug of not connecting in
> Why is this still being refined, do you know how much pain us normal players have to go through, bot many bots we have to kick? and for what, to get a cheap laugh? if you want TF2 to DIE! then by all means please continue, but i'm not going to let a whole bunch of salty players try to KILL A GOOD GAME!!

Your opinion is worth less than manure, html kiddie

**Comment by TotallyNotElite** [comment]
> Are you using the steam flatpak/snap?

Are you?

> When attaching it gives some error about some obscure missing .so in /tmp/

Sounds like cathook was never compiled. Do you get any errors while running ./update?

**Comment by dankdonk** [comment]
> Are you?

Yes. That seems to be the cause of the namespace related errors. I'll try rpm steam later.
> Sounds like cathook was never compiled. Do you get any errors while running ./update?

The same ones goose did with Boost

**Comment by TotallyNotElite** [comment]
> The same ones goose did with Boost

I don't see an error related to boost, enlighten me please?

**Comment by dankdonk** [comment]
> I don't see an error related to boost, enlighten me please?

Fick I misread his log. It said something along the lines it finding boost 1.69.0 and it being an unsuitable version with the minimum being 1.70. Then it supposedly fetched it and gave no errors after.

**Comment by dankdonk** [comment]
> And then Cathook does not attach to TF2. If anyone has a fix for this please let me know!
> 
> I am new to linux and Cathook so I may need some extra help.
> 
> Thanks!

It appears you are also missing libicudata. According to the Arch wiki, the package that provides it is "icu", which can be installed using this command (case sensitive):

    sudo pacman -S icu

If this doesn't work, please post the compilation log.
