### ISSUE TITLE
Running the cathook

### ISSUE THREAD

**Issue by Charlinquent** [nullworks/cathook#1081]
There are 3 questions i have:
1) How do i sync my cathook to a steam account?
2) Where do all the files get placed? Do i place them inside the tf2 game files? Or can i put them wherever you want?
And finally...
3) How do i start up the bot!

**Comment by BenCat07** [comment]
1. Cathook is not "synced to steam"
2. You don't place any files usually, read the readme
3. See catbot-setup's install script, it tells you everything for bots


Also, cathook is not for windows

**Comment by Charlinquent** [comment]
I am fully aware that cathook is a Linux program

**Comment by Codefreak64** [comment]
are you fully aware that you are trying to kill TF2?

**Comment by Charlinquent** [comment]
> are you fully aware that you are trying to kill TF2?

I'm actually trying to make a bot which does nothing but stand and "observe"!
