### ISSUE TITLE
Quality of Life: make zoomed sensetivity match normal sensitivity when using Custom FOV

### ISSUE THREAD

**Issue by buyBread** [nullworks/cathook#1084]
It's distracting and quite annoying to suddenly have your sensitivity become extremely low. I am pretty much always forced to set the `zoom_sensitivity_ratio` convar to the same value as my `sensitivity` value. It would be nice if this was automated while using Custom FOV.

**Comment by SylveonBottle** [comment]
I agree that this should've been something that nozoom already does, but- simple solution: put the zoom command in autoexec? Or maybe bind it to the same button as aimbot

**Comment by BenCat07** [comment]
Duplicate of #958.
