### ISSUE TITLE
Engineer Auto-Repair/Auto Upgrade Bug

### ISSUE THREAD

**Issue by Neko-LoverDisc** [nullworks/cathook#1089]
**Describe the Bug**
Whenever using the Engineer's Auto Repair/Auto Upgrade, he will only repair his priority building; nothing else. 

**To Reproduce**
1. Enable Engineer Auto Repair
2. Have two different buildings next to you
3. Change the priority

**Expected Behavior**

It's expected that the engineer bot would repair/upgrade all of his buildings

**Comment by BenCat07** [comment]
Will be fixed with navbot rewrite
