### ISSUE TITLE
TF2C Cheat Crashes Instantly When Injecting

### ISSUE THREAD

**Issue by gunguy831** [nullworks/cathook#1096]
read title

**Comment by BenCat07** [comment]
Tf2 classic is currently not supported

**Comment by gunguy831** [comment]
I was told by my friend it was, sorry.

**Comment by debagos** [comment]
OT:
@BenCat07 
How do you know he tried to use it with TF2 classic?

**Comment by BenCat07** [comment]
Idk you tell me, have you tried reading the title?

**Comment by TotallyNotElite** [comment]
Why was this not closed?
