### ISSUE TITLE
Error installing dependancies on Gentoo

### ISSUE THREAD

**Issue by TheRyeGuyWhoWillNowDie** [nullworks/cathook#1097]
When you run the dependency check on gentoo, portage freaks out because of the -a option. Removing -a from the portage command in scripts/dependancycheck will fix this!

**Comment by TotallyNotElite** [comment]
Could you make a pull request for it? That'd be cool. File: scripts/dependencycheck

**Comment by TheRyeGuyWhoWillNowDie** [comment]
ok

**Comment by BenCat07** [comment]
(he made a pr)
