### ISSUE TITLE
catbots stuck in "waiting" and even if restarted just go back to waiting

### ISSUE THREAD

**Issue by gunguy831** [nullworks/cathook#1099]
catbots stuck in "waiting" and even if restarted just go back to waiting

**Comment by TheCrazyInsanity** [comment]
This happens to me also

**Comment by iraizo** [comment]
the WAITING status is when tf2 is starting, how often does this occur?

**Comment by TotallyNotElite** [comment]
This issue is way too old, there have been a few web panel bot.js rewrites since then.
