### ISSUE TITLE
Ubuntu 20.04 - Gcc 9.3.0, compile error. 

### ISSUE THREAD

**Issue by Footsiefat** [nullworks/cathook#1102]
![Error log](https://cdn.discordapp.com/attachments/692143753397403704/751354840457805934/20200904_201538.png)

So a friend tried to get cathook on Ubuntu 20.04 but he got the error above when compiling. He also has gcc 9.3.0.

He isnt the most creative so if u know how to fix this could you show a step by step way please?

**Comment by BenCat07** [comment]
We have no step by step way, the error is pretty much random, try deleting the "build" folder and doing ./update again

**Comment by Footsiefat** [comment]
Uh OK. Has that fixed the problem in the past?

**Comment by BenCat07** [comment]
Yes
