### ISSUE TITLE
Auto strafer moves you sideways when double jumping

### ISSUE THREAD

**Issue by NotAnUser1** [nullworks/cathook#1126]
**Describe the Bug**
Auto strafer works when double jumping as scout making you move sideways if you move your mouse

**To Reproduce**
1. Enable auto strafe
2. Play as Scout
3. Double jump and move your mouse sideways
4. You move sideways (result)

**Expected behavior**
Auto strafer shouldn't work when double jumping so you don't move to unwanted places

**Comment by TotallyNotElite** [comment]
I don't understand why people use autostrafer in the first place, just strafe yourself.
