### ISSUE TITLE
Chat logs come out as "

### ISSUE THREAD

**Issue by explowz** [nullworks/cathook#1128]
**Describe the Bug**
From what I've seen these messages aren't real messages, nor corrupted chat messages. They randomly appear.

**To Reproduce**
1. Turn on chat log
2. Join a match
3. Wait a little bit while it gathers some logs
9. Check chat logs
10. See many " messages (result)

**Expected behavior**
For these " messages to not appear.

**Comment by BenCat07** [comment]
Not real? Alright, can just filter those out then

**Comment by iraizo** [comment]
Havent found those in my `.csv` file, shouldnt be a real issue anyways
