### ISSUE TITLE
error: Partition / too full: 141581 blocks needed, 71706 blocks free

### ISSUE THREAD

**Issue by foamlinux** [nullworks/cathook#1136]
Im using vmware and I have set the parition to 50 gb and theres alot of free space yet I get this error when trying to attach

(17/17) checking keys in keyring                   [######################] 100%
(17/17) checking package integrity                 [######################] 100%
(17/17) loading package files                      [######################] 100%
(17/17) checking for file conflicts                [######################] 100%
(17/17) checking available disk space              [######################] 100%
error: Partition / too full: 141581 blocks needed, 71706 blocks free
error: not enough free disk space
error: failed to commit transaction (not enough free disk space)
Errors occurred, no packages were upgraded.

**Comment by TotallyNotElite** [comment]
Well using a VM is your first problem :smile:

**Comment by foamlinux** [comment]
> Well using a VM is your first problem smile

oh is this an issue?

**Comment by TotallyNotElite** [comment]
Well:
1. You can not expect playable FPS
2. You can not expect a usable mouse in game.

I suggest that you set up dual-booted CathookOS, if you need help you can join our Telegram group.

**Comment by foamlinux** [comment]
I wanna use catbots and farm xp whats the best way to do that

**Comment by BenCat07** [comment]
Either you did not assign all your space you gave the vm or you installed alot of steams, thus filling all the disk space. in both cases you need more space in tge vm.

**Comment by lihaib** [comment]
Have you solved the problem？I had the same problem.
