### ISSUE TITLE
slow aimbot and look at path

### ISSUE THREAD

**Issue by EngineerGaming69** [nullworks/cathook#1141]
**Describe the Bug**
Slow aimbot and look at path break each other.
**Expected behavior**
 Look at path should turn off when an enemy is in sight range so it doesnt keep the slow aimbot from ever looking at a target.

**Comment by BenCat07** [comment]
i've tested slow aimbot and look at path though, slow aimbot takes priority

**Comment by EngineerGaming69** [comment]
what about the engis giving up and just standing near their buildings

**Comment by TotallyNotElite** [comment]
Not quite sure why you'd combine two completely separate issues into one issue. You should edit this issue and create a new one for the engi issue.

**Comment by EngineerGaming69** [comment]
idk either but rn im trying to fix the bots not even working at all. they just restart the second they run and no one in the telegram is saying anything,
