### ISSUE TITLE
stuck at "Could NOT find Freetype" on Pop os

### ISSUE THREAD

**Issue by xXTevinOfficialXx** [nullworks/cathook#1143]
got into pop os 20.10 to try it's performance. wanted to use cathook with tf2, but it all started great, missing dependencies, manually installing alot of things i didnt even know it existed, and now im stuck on this
trying on master branch because stable didnt work too

`remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
HEAD is now at 46e139a Fix truce and enable aimbot to aim at npcs (#1137)
~/cathook/build ~/cathook
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindFreetype.cmake:157 (find_package_handle_standard_args)
  CMakeLists.txt:117 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/tevin/cathook/build/CMakeFiles/CMakeOutput.log".
 
 
Failed to compile cathook`

**Comment by TotallyNotElite** [comment]
PopOS is not officially supported for Cathook. We currently officially support Fedora 32, Manjaro/CathookOS, Arch and Ubuntu 20.04.

**Comment by BenCat07** [comment]
you are missing libfreetype for 32 bit, install it

**Comment by TotallyNotElite** [comment]
IDK what performance gain you are expecting from PopOS compared to a rolling release distro like Manjaro either so :shrug:
