### ISSUE TITLE
[Question] How do I make the code I edited work?

### ISSUE THREAD

**Issue by EngineerGaming69** [nullworks/cathook#1148]
I tried doing the `cmake .. && make -j$(grep -c '^processor' /proc/cpuinfo)` and putting the edited navbot in build/src/hacks and it wont change anything.

**Comment by TotallyNotElite** [comment]
1. You need to switch your update channel to developer
2. You need to modify the files normally, not in the build folder.
3. Run ./update or build cathook manually.

**Comment by EngineerGaming69** [comment]
omg the only thing i forgot was developer and i was looking at it.

**Comment by EngineerGaming69** [comment]
so what code do i edit tho? cuz theres master and normal cathook

**Comment by TotallyNotElite** [comment]
I'm not sure what your question is.

**Comment by EngineerGaming69** [comment]
theres cathook in home/cathook and cathook the one u start bots with

**Comment by TotallyNotElite** [comment]
In general, you should always modify the cathook you use to play TF2 yourself. After you made your modifications, you can copy those files into the bot's cathook folder.

**Comment by EngineerGaming69** [comment]
ok thx

**Comment by EngineerGaming69** [comment]
nothing changed still. and i have no idea y

**Comment by iraizo** [comment]
Im guessing you have fixed this, closing it.
