### ISSUE TITLE
projectiles weapons don't work with anti-aim

### ISSUE THREAD

**Issue by SuperGamingBros4** [nullworks/cathook#1149]
Projectile weapons don't work with Anti-aim because it shoots projectiles everywhere when It's on.

choose a class that shoots projectiles like the soldier
turn on anti-aim
turn on thirdperson with show angles
then when you try to shoot, the projectiles go whereever the playermodel is looking

What should happen is that the player snaps on to where it's going to shoot, then fires, then snaps back.

For some weird reason it doesn't work when you can't see the anti-aim angles. I don't have a clue about why this happens, I just know it happens under these conditions.

**Comment by BenCat07** [comment]
probably a pSilent issue

**Comment by Trapacid** [comment]
Bug probably fixed as it doesn't seem to happen anymore even with fakelag.

**Comment by BenCat07** [comment]
it was the Projectile silent i added pretty sure, i removed it due to its bugginess later on.
