### ISSUE TITLE
[Suggestion] ESP: Merasmus hiding props

### ISSUE THREAD

**Issue by somecheater** [nullworks/cathook#1153]
ESP should have an option to show where Merasmus may be hiding, and if possible: the correct one.

**Comment by iraizo** [comment]
Added wontfix to this until one of the maintainers say otherwise, because im pretty sure nobody plays halloween maps

**Comment by SylveonBottle** [comment]
Just for curiosity's sake, how would we even identify which prop would be merasmus? Isn't it always the last one alive regardless of order, or is there some sort of special flag on the specific prop?
