### ISSUE TITLE
[Suggestions] Namestealer fix and improvements

### ISSUE THREAD

**Issue by explowz** [nullworks/cathook#1167]
Add an option to namestealer called «F2P» which would basically fix namestealing for f2ps. All you need to do is retry after a name has be stolen.

Improvement: Prioritize players playing a specific class. A setting that would prioritize stealing the name of a player playing a specific class (usually sniper because this is thought for bots) making it more confusing for people trying to kick the bot and giving the bot more chances of survival.

Improvement 2: Try and immediately kick the person you've stolen the name of. This could create a bunch of confusion and not give the real player a chance to kick the bot. If certain player is not kickable because they are P2P then just start kicking randoms.

**Comment by EngineerGaming69** [comment]
yeah this would be cool but i feel like people would kick the bot/you before they can do anything ~engineer gaming

**Comment by explowz** [comment]
Its not really like that. Namesteal bots get kicked harder than other bots as it confuses people.

**Comment by iraizo** [comment]
This improvement is really useless people kick based on avatars not on their class

**Comment by SylveonBottle** [comment]
I've seen on multiple occasions people kicking the wrong person despite the avatar being different.

If you want to do something cool like this, have two bots that steal two other people's names. Then have one bot votekick the other bot's stolen name user.

Bot A, Bot B.
Bot A joins, steals Player3's name.
BotB joins, steals Player4's name.
Bot A starts a votekick for Player3. 
BotB ("Player3" in chat) says "F1 F1 F1 bot stole my name"
BotB then proceeds to kick Player4, etc etc.

Of course if you have multiple bots then chances are you probably have them in a group of 6 and this doesn't really matter.

**Comment by SylveonBottle** [comment]
And, I'm just going to put this here.
It's not hard to make an automated avatar stealer. It's just a few http get/post's.

**Comment by iraizo** [comment]
> I've seen on multiple occasions people kicking the wrong person despite the avatar being different.
Yes that is correct, people with no brain do that, but most of the time somebody just spams F1 its not really worth it to add somehing like that

**Comment by iraizo** [comment]
I do agree on the avatar stealer tho, that should be a good enhancement

**Comment by TotallyNotElite** [comment]
Avatar stealer is not something you can really do in cpp cathook (unless you want to do https requests from inside cathook haha)

**Comment by iraizo** [comment]
> Avatar stealer is not something you can really do in cpp cathook (unless you want to do https requests from inside cathook haha)

would that be a problem doing them inside of cathook tho

**Comment by TotallyNotElite** [comment]
You'd also have to obtain the appropriate cookies, learn some boost::beast, etc. I don't think this qualifies as d:easy personally.

**Comment by iraizo** [comment]
Youre correct, i will change that, i did not know about the cookies and personally dont use boost either to send requests

**Comment by Auditormadness9** [comment]
> This improvement is really useless people kick based on avatars not on their class

I thought you said avatar stealer is useless xd
