### ISSUE TITLE
My cat bots wont work anymore

### ISSUE THREAD

**Issue by EngineerGaming69** [nullworks/cathook#1170]
compilation terminated.
make[2]: *** [CMakeFiles/cathook.dir/build.make:1538: CMakeFiles/cathook.dir/src/hooks/FireGameEvent.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:614: CMakeFiles/cathook.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

idk what to do and this is the only error I get when i try to install catbots. It happens with any OS I use

**Comment by DerpChest** [comment]
Good because cheating ruins the fun for everyone
