### ISSUE TITLE
cathook updates with an older commit

### ISSUE THREAD

**Issue by SuperGamingBros4** [nullworks/cathook#1184]
Why does cathook update with a commit from october 8?
To me it doesn't make sense and it should always use the newest commit.
And looking at the terminal during cathook updating it says "HEAD is now at 0a0f9ca Remove tmp/dumps chmod". And while I'm using cathook in game it says the 0a0f9ca commit is the version that's running.

**Comment by BenCat07** [comment]
stable branch. Intentional behaviour.

**Comment by TotallyNotElite** [comment]
Cathook by default tracks the "stable" cathook version, as defined by the "stable" git tag. You can change this behaviour by running the configuration script and selecting "master" as your update channel.

**Comment by SuperGamingBros4** [comment]
oh thanks
