### ISSUE TITLE
[Help] catbots won't join my server

### ISSUE THREAD

**Issue by SuperGamingBros4** [nullworks/cathook#1186]
The catbots I setup don't join the server I opened using the create server button. I have used the connect command in so many variants like connect localhost, connect localhost:27015, and connect (my ip).

**Comment by EngineerGaming69** [comment]
is auto abandon on?

**Comment by SuperGamingBros4** [comment]
Sorry I took so long but no auto abandon is not enabled.

**Comment by BenCat07** [comment]
bots have no direct access to your localhost, they do however have an ip that points to your local network, check scripts/ns-inet

**Comment by SuperGamingBros4** [comment]
scripts in the cathook directory?

**Comment by SuperGamingBros4** [comment]
where is the ns-inet file?

**Comment by SuperGamingBros4** [comment]
I found the file and saw that it was setting up a network device and the ip is how to bot connects to my network.
