### ISSUE TITLE
Fakelag sometimes fails to do anything

### ISSUE THREAD

**Issue by G-4-M-3-R** [nullworks/cathook#1194]
Reproduction steps: enable fakelag
Notes: nospread is disabled

**Comment by TotallyNotElite** [comment]
Kindly fuck off, thanks and have fun :)

https://streamable.com/5z0jzd

**Comment by d3fc0n6** [comment]
> Kindly fuck off, thanks and have fun :)
> 
> https://streamable.com/5z0jzd

It literally doesn't work at times. If it didn't have issues why are there so many reports of this?

**Comment by TotallyNotElite** [comment]
I only see this one report on github, can you link me to a report which shows reproduction steps that can help diagnose this issue, or perhaps point me to the lines of code responsible?

**Comment by TotallyNotElite** [comment]
I tried this with a config file that was provided to me, but I still was not able to reproduce this issue :/

**Comment by BenCat07** [comment]
nospread issue, fixed once tne merges my pr.
if you disable nospread mid-sync it happens.

**Comment by yupyup0666** [comment]
> Kindly fuck off, thanks and have fun :)
> 
> https://streamable.com/5z0jzd

"its not broken"
**3 ppl including me have said its broken**
"show me how its broken?"
**bencat has already pushed a fix**
epic fail! posted on r/ProgrammerFacepalms
thx for free karma

**Comment by TotallyNotElite** [comment]
@yupyup0666

I don't think you understand how this works. It is not the responsibility of bencat and I to try every possible combination of configurations to find an issue you are having. When you create a GitHub issue you are under obligation to provide the developers with reproduction steps that allow the developers to identify and solve the issue. If you take a look at the issue created above, there is no useful information (in fact, the informati

P.s.: Who do you think found the problem: https://t.me/nullworks/499857

**Comment by TotallyNotElite** [comment]
Wrong button
