### ISSUE TITLE
[SUGGESTION] Seperate Font For Crit Info

### ISSUE THREAD

**Issue by KaylinOwO** [nullworks/cathook#123]
I like having TF2 Build Font as my ESP font but having it for crit-info makes it kinda hard for me to see my target.

**Comment by BenCat07** [comment]
if ya're still alive, could i have a font for that?

**Comment by waxxyTF2** [comment]
What do you mean? A font suggestion? my suggestion would be to have an option for different fonts like Arial, Tohama, etc.

The link to TF2 Build if thats what you need: https://www.dafont.com/tf2-build.font

**Comment by BenCat07** [comment]
Well uhhh, we already have a ton of fonts, if youwant i can add a optiin to
choose one

waxxyTF2 <notifications@github.com> schrieb am Mo., 26. März 2018, 18:10:

**Comment by waxxyTF2** [comment]
This post was before you did, also I no longer have linux to use the cheat.
