### ISSUE TITLE
TF2 crashes everytime I want to load my config

### ISSUE THREAD

**Issue by mysistercalledmehitler** [nullworks/cathook#1294]
Alright this should be easy to explain, I got bored, so I decided to inject cathook in TF2. Now I wanted to load my config, so I typed in the console "cat_load [my config]", but everytime I do that TF2 crashes.
Sooo, what do I have to do?

**Comment by aUniqueUser** [comment]
Run the ./report-crash script and one of the maintainers will review it

**Comment by TotallyNotElite** [comment]
Can you also post the config file here please?

**Comment by mysistercalledmehitler** [comment]
I got my ID now, so do I send it here? Or I shouldn't?

**Comment by mysistercalledmehitler** [comment]
Nevermind, I got it fixed now

**Comment by TotallyNotElite** [comment]
Hey, we would still like to fix the issue however.

**Comment by Stopthebots** [comment]
Please stop the bots, the game is unplayable because of you guys

**Comment by TotallyNotElite** [comment]
The cathook developers have no control over the bot hosters, I don't know why you are asking us about that.
