### ISSUE TITLE
I made some catbots, however...

### ISSUE THREAD

**Issue by mysistercalledmehitler** [nullworks/cathook#1297]
I just made some catbots, did the navbot, aimbot, etc. As I went to localhost, I applied the quota for the bots, but the bots were stuck at "starting". Am I doing something wrong, or am I just stupid?
![Screenshot_2020-12-31_03-33-23](https://user-images.githubusercontent.com/76728682/103401955-0e3bd580-4b19-11eb-984c-6411cafb1553.png)

**Comment by Stopthebots** [comment]
Please stop the bots, the game is unplayable because of you guys

**Comment by aUniqueUser** [comment]
pls use the cathook telegram (t.me/nullworks) for support with catbots, easier to help there

**Comment by BenCat07** [comment]
> I just made some catbots, did the navbot, aimbot, etc. As I went to localhost, I applied the quota for the bots, but the bots were stuck at "starting". Am I doing something wrong, or am I just stupid?
> ![Screenshot_2020-12-31_03-33-23](https://user-images.githubusercontent.com/76728682/103401955-0e3bd580-4b19-11eb-984c-6411cafb1553.png)

would need logs from cathook-ipc-web-panel to tell

**Comment by mysistercalledmehitler** [comment]
> pls use the cathook telegram (t.me/nullworks) for support with catbots, easier to help there

I tried, but my SIM is locked which means I can't receive any messages from unknown people. So in other words, I can't verify my phone number when signing up.

**Comment by BenCat07** [comment]
> > I just made some catbots, did the navbot, aimbot, etc. As I went to localhost, I applied the quota for the bots, but the bots were stuck at "starting". Am I doing something wrong, or am I just stupid?
> > ![Screenshot_2020-12-31_03-33-23](https://user-images.githubusercontent.com/76728682/103401955-0e3bd580-4b19-11eb-984c-6411cafb1553.png)
> 
> would need logs from cathook-ipc-web-panel to tell

this then

**Comment by BenCat07** [comment]
main.log, a game log, and a steam log. Please ensure you censor login credentials on the last two (at the very start they may be)

**Comment by mysistercalledmehitler** [comment]
Alright.

**Comment by mysistercalledmehitler** [comment]
Tried everything, nothing is happening to my bots.

**Comment by BenCat07** [comment]
Please provide me logs like i asked you, else i cannot help you either :/

**Comment by mysistercalledmehitler** [comment]
Sure. 
![Screenshot_2021-01-03_15-18-21](https://user-images.githubusercontent.com/76728682/103487997-5c7dfc80-4dd7-11eb-9c0f-c3fca3d42399.png)
![Screenshot_2021-01-03_15-19-13](https://user-images.githubusercontent.com/76728682/103487999-5f78ed00-4dd7-11eb-9572-54918f3dfd8a.png)

**Comment by mysistercalledmehitler** [comment]
I do not see a game log tho.

**Comment by mysistercalledmehitler** [comment]
The password is useless if you're wondering, I already typed ./stop in the terminal

**Comment by mysistercalledmehitler** [comment]
Sooo, is it fixable?

**Comment by BenCat07** [comment]
Hmm that is strange

**Comment by BenCat07** [comment]
I cannot tell why this would happen, and github issues really is not a good way to fix this, it would require alot of debugging.

**Comment by mysistercalledmehitler** [comment]
What do I have to do then?

**Comment by krutojPacan** [comment]
Stop ruining the game for example

**Comment by BenCat07** [comment]
> What do I have to do then?

Sorry i had to time recently. join the discord we have on https://cathook.club and contact LightCat (me) in the discord.

**Comment by mysistercalledmehitler** [comment]
Nevermind, this took so long but I finally fixed it. 
![Screenshot_2021-01-17_13-25-48](https://user-images.githubusercontent.com/76728682/104852247-d0d09980-58c7-11eb-9c2f-fba8682313c4.png)
Thanks everyone for the help!

**Comment by TotallyNotElite** [comment]
(Actually, it was me who fixed this :laughing:)

**Comment by TotallyNotElite** [comment]
https://github.com/nullworks/cathook-ipc-web-panel/commit/b40bb85d4a12ee0bb24b744ff8fc02bc2fbb7433

**Comment by mysistercalledmehitler** [comment]
Thanks then.
