### ISSUE TITLE
Hello, I cannot attach the cheat to TF2. Please help

### ISSUE THREAD

**Issue by lDIOTBOX** [nullworks/cathook#1303]
So today I've installed that CathookOS and did everything it tells me to do in the guide (at least I think I did). However when it comes to attaching cathook to the game this happens:

Running instances: 26763
Attaching to 26763
loading /tmp/.gl252JNO to 26763
gdb: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory

And it won't attach. Am I doing something wrong? How can I fix this?

**Comment by TotallyNotElite** [comment]
Your system needs to be fully updated. Update your system.

**Comment by lDIOTBOX** [comment]
Okay, I just opened Software Update. There's a lot of stuff that needs to be updated. Do I just update it all and I'm good to go?

**Comment by BenCat07** [comment]
yws

**Comment by lDIOTBOX** [comment]
yaaay it worked! Thank you =}
