### ISSUE TITLE
anti auto balance sometimes doesnt work

### ISSUE THREAD

**Issue by mr-nv** [nullworks/cathook#1307]
**Describe the Bug**
anti auto balance sometimes doesnt reconnect when "You will be moved to team %team% in %seconds% seconds if the teams are still not balanced" appears

**Additional context**
happened both to me and my friend multiple times
dont have a vid of it happening unfortunately

**Comment by BenCat07** [comment]
usually it only fails when you get auto balanced while dead

**Comment by TotallyNotElite** [comment]
> usually it only fails when you get auto balanced while dead
Yes, but he clearly isn't dead

> anti auto balance sometimes doesnt reconnect when "You will be moved to team %team% in %seconds% seconds if the teams are still not balanced" appears
Since you can only reconnect a limited amount of times before your "permission" to be on the server is withdrawn by GC, we need to track it. Can you confirm that you didn't auto reconnect 2 times before that already?

**Comment by mr-nv** [comment]
> > usually it only fails when you get auto balanced while dead
> 
> Yes, but he clearly isn't dead
> 
> > anti auto balance sometimes doesnt reconnect when "You will be moved to team %team% in %seconds% seconds if the teams are still not balanced" appears
> 
> Since you can only reconnect a limited amount of times before your "permission" to be on the server is withdrawn by GC, we need to track it. Can you confirm that you didn't auto reconnect 2 times before that already?

oh fuck me then, yeah i dont have premium on the account im playing with cathook on and yes the last time it happened anti autobalance did reconnect me 2 times before
my friend has premium though and he probably got autobalanced after he died, so ill close this

**Comment by mr-nv** [comment]
came back to this issue to realize that i cant read
does the reconnect counter reset if the map changes? i think it happened again but this time i reconnected only once (after a map change on the same server)
