### ISSUE TITLE
Source Engine error: (allegedly) OOM

### ISSUE THREAD

**Issue by debagos** [nullworks/cathook#1316]
**The Bug**

TF2 crashes with this message:
`Engine Error: Out of memory or address space. Texture quality setting may be too high.`

![crash](https://user-images.githubusercontent.com/24960652/104042777-2f688a00-51db-11eb-9e67-5b04fc1b81d2.png)
This happens very soon after joining a server.
One time it crashed even while connecting. But most times it crashes after a few seconds in game, rarely after a minute or later.

**To Reproduce**

1. Start TF2
2. Attach cathook
3. Join server
4. Start playing
5. BOOM (most times after ~20-40 seconds)

To be clear, this bug/problem is definitely linked to using cathook and not (what you guys may think) because of too high TF2 graphics settings or low end sys specs. I use the exact same settings on my main account and played over 1K hours on this setup.

**Things I tried out**

- Using the lowest possible settings in TF2
- Using highest possible settings in TF2, to see if it makes any difference
- Played for almost two hours multiple rounds and servers without using cathook, no crash
- Switching from `stable` to `master` update channel
- Running a resource monitor in background to see RAM and VRAM usage, nothing unusual, not even close to OOM

**Logs**

[cathook-hookcat-56087.log](https://github.com/nullworks/cathook/files/5788519/cathook-hookcat-56087.log)
[cathook-hookcat-56087-segfault.log](https://github.com/nullworks/cathook/files/5788521/cathook-hookcat-56087-segfault.log)

Are these logs sufficient? If not, please tell me what other logs you guys need.
Thanks for your support guys! I appreciate it :grinning:

**Comment by BenCat07** [comment]
this is caused by running out of memory in tf2 in general. cathook uses alot of memory to allocate specific things, and some maps like tr walkway may then be the finishing blow to overload it and cause that error. @TotallyNotElite already did alot for memory optimization, not much else to do.

**Comment by debagos** [comment]
That is interesting.
I should have mentioned in my OP below the "**Things I tried out**" section that I was running my resource monitor in the background to see if my RAM goes BOOM, but that wasn't the case. I can't tell you exact numbers, but running TF2 with cathook attached didn't used more than a third of my 16GB RAM iirc.
Or are you talking about the VRAM?

**Comment by BenCat07** [comment]
limit is 2gb for 32 bit, vram wise

**Comment by TotallyNotElite** [comment]
That's not true. Vram is not limited in 32 bit applications.

**Comment by debagos** [comment]
I monitored VRAM usage now. Highest reported usage was: `vram 55.77% 2267.96mb`
(You can tell by these numbers that I have 4GB VRAM)

**Comment by TotallyNotElite** [comment]
I don't see how vram is even remotely relevant in this scenario anyway. It clearly says out of memory address space.

**Comment by debagos** [comment]
Well, bear with me, I'm a noob, I just try to give you as much information as I can. And since my RAM never gets close to OOM, I thought maybe the VRAM goes OOM.
The error message from TF2 itself strengthened my assumption ("Texture quality setting may be too high").

**Comment by TotallyNotElite** [comment]
You did well, you provided a lot of information, but I unfortunately can't tell the cause of the TF2 crash :/

**Comment by debagos** [comment]
I have to admit that all this doesn't make much sense at all...
My best guess is that my whole OS/GFX (driver) configuration is just borked.
Next week my new SSD will arrive, then I will start fresh on that new drive and report back if that problem still exists.
Until then, have a nice time and thanks for your help guys! :cowboy_hat_face:

**Comment by debagos** [comment]
Okay, here is my report:
**It works™**

Jokes aside, I played for ~2 hours without any problems at all.
I didn’t use cathook for roughly one year and the only major change since then was that I switched from a open-source graphics driver to a proprietary one. That's why I think the graphics driver was the culprit.

Thanks for your support and for making cathook so awesome, it got many good improvements!

Conclusion:
Stay away from proprietary graphics drivers (cathook not working wasn't the only problem it caused).
If anyone has the same problem in the future and is reading this, try to remove the proprietary graphics driver and use the open-source one. Good luck.

Greetings and have a nice day :smiley:

**Comment by TotallyNotElite** [comment]
Alright. Out of curiosity, what manufacturer is your GPU from?

**Comment by debagos** [comment]
Advanced Micro Devices, **AMD**.
To be honest, I wasn't expecting that. I always thought AMD proprietary Linux drivers are well tested and developed...

**Comment by TotallyNotElite** [comment]
Oh no, that's not correct. AMD's proprietary drivers are near abandoned and should only be used if you require a specific feature which is licensed to AMD under a license that does not allow open source implementations (unlikely).

The AMD open source drivers are maintained by AMD staff themselves and are in fact recommended by AMD itself.

**Comment by debagos** [comment]
Oh good to know!
Well, I learned my lesson :satisfied:
But just FYI, the proprietary driver for my card gets updates pretty frequently. Last update was in December.

**Comment by BenCat07** [comment]
from what i know calayst only works on very specific gpus and kernel versions and xorg versions, ans shouldn't be used

**Comment by TotallyNotElite** [comment]
Catalyst is abandonware and not what @debagos is talking about...
