### ISSUE TITLE
Let us attach cathook while bots are running

### ISSUE THREAD

**Issue by Auditormadness9** [nullworks/cathook#1320]
Heya!

It gets really irritating to restart the bots everytime, given an unstable TF2 and crashing is much more common and frequent when cathook is injected or bots are running, and the fact that bot setup is quite buggy and it takes multiple restarts (or ./stop-./start cycles) to actually finally get it to work and not have issues like multiple bots using same account, all bots having same PID, bots stuck at WAITING, etc.

Thanks in advance!^^

**Comment by TotallyNotElite** [comment]
You need to add your TF2 PID after the attach command.

**Comment by TotallyNotElite** [comment]
also, why is all bots having the same PID a problem?

**Comment by BenCat07** [comment]
> also, why is all bots having the same PID a problem?

the bots write to same log

**Comment by iraizo** [comment]
Wont be fixed, closing this.
