### ISSUE TITLE
Autoblast isn't working

### ISSUE THREAD

**Issue by willien3lson** [nullworks/cathook#1325]
I'm trying to use it on dodgeball servers, autoshoot and blast are enabled but it isn't working.

**Comment by TotallyNotElite** [comment]
https://github.com/nullworks/cathook/blob/8caa3e1bd12d2d72910fb079e74b07bf9fc710c6/src/hacks/AutoReflect.cpp#L16 and https://github.com/nullworks/cathook/blob/8caa3e1bd12d2d72910fb079e74b07bf9fc710c6/src/hacks/AutoReflect.cpp#L29 perhaps?

**Comment by willien3lson** [comment]
fixed, that was my fault
