### ISSUE TITLE
Help with cathook OS

### ISSUE THREAD

**Issue by dan2005sh** [nullworks/cathook#1333]
Ok ao basically i flashed the iso into the usb and booted the usb, but when i try to boot the manjaro it gets this error:
https://prnt.sc/xvfle8

**Comment by BenCat07** [comment]
use balena etcher and verify the iso is formatted correctly, because that looks like a failes flash

**Comment by dan2005sh** [comment]
![image](https://user-images.githubusercontent.com/20836946/106390136-97337e80-63ef-11eb-87ba-59e0eaecc6f1.png)


> use balena etcher and verify the iso is formatted correctly, because that looks like a failes flash

**Comment by BenCat07** [comment]
option a) usb (port or stick) is broken/bad
option b) iso is damaged/bad

**Comment by dan2005sh** [comment]
> option a) usb (port or stick) is broken/bad
> option b) iso is damaged/bad

guess my usb is bad

**Comment by dan2005sh** [comment]
> option a) usb (port or stick) is broken/bad
> option b) iso is damaged/bad

thx for help tried it with another usb and it worked
