### ISSUE TITLE
Can I run this Program on an IP that already has a VAC ban?

### ISSUE THREAD

**Issue by JohnyBoy47** [nullworks/cathook#1334]
This is not so much a bug as it is a question. I had recently acquired a Linux Mint and I decided it would be fun to try Cathook on it with a throw away account. The problem is, on this IP address I already have a VAC ban after running some faulty cheating program thinking I wouldn't be caught. After I had been banned (about 4 years ago) I created a new account in 2018 which does not have a VAC ban and I use extensively to trade with people. So, since I already have a VAC ban on this IP address, if I get caught on this new computer, will my IP  be flagged or something and my trading account will be banned? Is VAC an account specific thing and it's alright if I get caught on this computer? I simply do not want to lose 400$ I traded and I don't have a phone number (I use hangouts) so I cannot access Telegram. Thanks.

**Comment by TotallyNotElite** [comment]
To be safe(ish):
1. never log into your trading account from your Linux Mint system, if you did, wipe .steam and .local/share/Steam
2. Just change your IP address every time you switch between Linux mint and the system you use for your trading account. My IP changes every few days or after a router reboot, inquire with your ISP about that.

**Comment by JohnyBoy47** [comment]
> To be safe(ish):
> 
>     1. never log into your trading account from your Linux Mint system, if you did, wipe .steam and .local/share/Steam
> 
>     2. Just change your IP address every time you switch between Linux mint and the system you use for your trading account.
> 
> 
> My IP changes every few days or after a router reboot, inquire with your ISP about that.

Can I use a VPN to change my IP address?

**Comment by TotallyNotElite** [comment]
Go ahead.
