### ISSUE TITLE
can someone FULLY explain me to fix this shitty error?

### ISSUE THREAD

**Issue by willien3lson** [nullworks/cathook#1336]
im still having this fckn error ![image](https://user-images.githubusercontent.com/75445197/106654772-98101000-65a9-11eb-9285-5547e646add6.png)

**Comment by willien3lson** [comment]
yes, i installed everything in the wiki article

**Comment by TotallyNotElite** [comment]
You need to install cathook first before you can use cathook.

**Comment by willien3lson** [comment]
i already using cathook i'm not a retard

**Comment by willien3lson** [comment]
cathook is on my desktop

**Comment by willien3lson** [comment]
but still you are not helping me

**Comment by willien3lson** [comment]
can some other staff help me because really you are only wasting my time

**Comment by TotallyNotElite** [comment]
Welp, that's a block from the nullworks issue trackers. Not with that attitude.
