### ISSUE TITLE
[Suggestion] Autoheal priority

### ISSUE THREAD

**Issue by iraizo** [nullworks/cathook#1343]
I think it would be less suspicious if the bot would heal other users while following them or when the friend/party leader/you die.

This would fix the medic bot getting vote kicked, if the bot goes near a friend/party leader/you, the bot should start pocketing you only.

**Comment by TotallyNotElite** [comment]
This already describes the default behaviour, what do you mean?

**Comment by iraizo** [comment]
I can do some testing tomorrow, but from what ive seen is that when heal friends only is disabled the bot will just heal anybody in sight, which should be normal, but its supposed to pocket the player when in range, i may be wrong tho.
