### ISSUE TITLE
cat_autovote

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#135]
Simple: 
If votekick is initiated by a party member, ipc bot, steam friend, or friend via cathook userlist, vote yes.
If votekick is against any of them, vote no.

This new idea would be useful for catbots to automatically vote against kicking eachother if they're in the same game.

**Comment by julianacat** [comment]
Did you consider that if you were lobbying with some other cheaters that you didn't have on friends list, what then? Not everyone that you lobby with will be on friends list, so its best to vote manually.

**Comment by nullifiedcat** [comment]
Use ISteamMatchmaking interface to get list of players you are lobbying with.

**Comment by julianacat** [comment]
:thinking:

**Comment by SylveonBottle** [comment]
Updated op with more relevant information. 

This new idea would be useful for catbots to automatically vote against kicking eachother if they're in the same game.

**Comment by TotallyNotElite** [comment]
Already done.
