### ISSUE TITLE
[bug/suggestion] 

### ISSUE THREAD

**Issue by KreeshTon** [nullworks/cathook#1358]
This isn't that important but it should probably fixed/added in the future

Some parts of the map dosent change color
![Screenshot from 2021-02-18 15-20-17](https://user-images.githubusercontent.com/78846360/108462822-3ee9f100-72b8-11eb-935c-3fa665a82a82.png)

When changing the resolution, The Esp and glow breaks
![Screenshot from 2021-02-19 12-47-31](https://user-images.githubusercontent.com/78846360/108463229-faab2080-72b8-11eb-807c-4d0f15b36b8a.png)

Add an option to ignore people in the playerlist
Add a color changer for the radar and the crit bucket
Add Ignore DIsguises

:D

**Comment by BenCat07** [comment]
ignore people in playerlist is done. Just click their status and rotate to friend. Ignore disguises is done aswell. changing resolution isn't the problem, using some sort of stretched resolution is.
