### ISSUE TITLE
Engineer needs his best weapon switched.

### ISSUE THREAD

**Issue by EngineerGaming69** [nullworks/cathook#1360]
engineer Best Weapon uses his pistol from close range and shotgun from far

unless you can change best weapon with changeable ranges then that would be cool.
something like this 

primary - max range
secondary - 500
melee - 20 (or what ever melee range is)

**Comment by EngineerGaming69** [comment]
simulink should have this fixed

**Comment by BenCat07** [comment]
Simulink may, but we do not.

**Comment by EngineerGaming69** [comment]
this was added with the engineer bots, close it or wait for it to be added to stable?

**Comment by BenCat07** [comment]
This can be closed pretty much
