### ISSUE TITLE
Assistance Only Fails

### ISSUE THREAD

**Issue by relaybots** [nullworks/cathook#1368]
**Problem**
Assist Only mose Fails To Move Towards An Enemy, And Causes Many CathookFeatures To Fail.

**Details**
_In Depth Of What Is Failing_

- Auto Shoot, Auto Zoom/Rezoom, Auto Rev, Tap "Almost All Aimbot Features Break"
- Trigger Shoot, Auto Reflect, Trigger Melee "Fail In Trigger"
- Warp, And Fast Shoot Fail.
- Follow Bot Breaks. (issue creator did not specify what fails)

**Note** This Only Happens When Assist Only Is On.

**System Details**
_**Manjaro KDE (Cathook OS Edition) Lastest Version**_

- Latest Kernel With Cathook OS
- Latest Updates To Manager

**Cathook Version**

- Latest Version With The Update Of "Config Tab"
- Configs Are Also Up-To Date.

**Comment by BenCat07** [comment]
The chat feature does nor fail.

**Comment by LightPower392** [comment]
I looked into it and found that #1306 broke the assistance only feature of the aimbot. When I reversed that change, the option seemed to work fine. Can someone tell me why it was gutted?

**Comment by BenCat07** [comment]
> I looked into it and found that #1306 broke the assistance only feature of the aimbot. When I reversed that change, the option seemed to work fine. Can someone tell me why it was gutted?

you're right, @TotallyNotElite seems to had gutted it for no specific reason

**Comment by relaybots** [comment]
So you gutted the one the one thing this cheat has for silent cheating LOL

**Comment by relaybots** [comment]
Well at least we know why its fucked

**Comment by LightPower392** [comment]
This issue has been solved now

**Comment by iraizo** [comment]
This has been inactive since 18 days and @LightPower392 says its solved, so im going to close this.
