### ISSUE TITLE
Two new suggestions

### ISSUE THREAD

**Issue by Auditormadness9** [nullworks/cathook#1372]
- [ ] 1. Auto kick people I stole name from.
- [ ] 2. Auto cat_mm_abandon when auto-balanced.

**Comment by explowz** [comment]
1. Yeah makes sense.
2. Makes no sense. Why would you want to do that?

**Comment by BenCat07** [comment]
2. is meant for when you make a party

**Comment by iraizo** [comment]
Duplicate of https://github.com/nullworks/cathook/issues/1167
