### ISSUE TITLE
[Bug] 1 bot can't get into its account

### ISSUE THREAD

**Issue by mysistercalledmehitler** [nullworks/cathook#1373]
So basically, I'm using one of my premium bots, all the other bots worked until I got a error that looked like this.
I haven't changed anything to my bots account. Anyone got an idea?
![Screenshot_2021-03-09_20-00-15](https://user-images.githubusercontent.com/76728682/110560064-537d1480-8113-11eb-9fc6-8a580e7b34aa.png)

**Comment by EngineerGaming69** [comment]
do u have 2 bots using the same account in the txt file

**Comment by mysistercalledmehitler** [comment]
I'm not a idiot dude, they're both different accounts.

**Comment by BenCat07** [comment]
that error means that they are indeed both using the same acc

**Comment by mysistercalledmehitler** [comment]
> that error means that they are indeed both using the same acc

dude im literally not lying, i checked the txt file, they aren't the same account...

**Comment by leKamikaze1** [comment]
Remove the account and create another one then, what's the deal?

**Comment by iraizo** [comment]
Inactive since 18 days, closing.
