### ISSUE TITLE
(Suggestion) Hvh should have 2 options for yaw

### ISSUE THREAD

**Issue by KreeshTon** [nullworks/cathook#1377]
That's it. Fake and Real yaw.

**Comment by KreeshTon** [comment]
![Screenshot from 2021-03-15 20-21-36](https://user-images.githubusercontent.com/78846360/111152800-1c53ab00-85cc-11eb-8812-cc12b7e1338d.png)

and please fix the nightmode world color to include props

**Comment by BenCat07** [comment]
the nightmode issue is caused by stuff that isn't actual a pop but a dynamic entity
