### ISSUE TITLE
optimize aimbot

### ISSUE THREAD

**Issue by dotqurter** [nullworks/cathook#1382]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/243848-heavily-optimizing-aimbot.html

tl;dr sort through entities for possible players (health/fov/dist) and then run vischeck on the sorted entities

**Comment by TotallyNotElite** [comment]
This won't help in cases where there are no valid targets, it will still loop thru all players. And besides, cathook's aimbot is not expensive at all. A waste of time.

**Comment by dotqurter** [comment]
bencat told me to make the issue

**Comment by TotallyNotElite** [comment]
Discussed in detail: https://t.me/nullworks/602566

**Comment by BenCat07** [comment]
TL;DR
only useful in "legit" play, everywhere else it would degrade the performance.
