### ISSUE TITLE
Projectile Silent Aimbot Improvement 

### ISSUE THREAD

**Issue by KreeshTon** [nullworks/cathook#1391]
Correct me if I am wrong but silent aim still work for projectiles right? 

If it does, then I think silent aim should be improved for projectiles so that it is completely silent.

**Comment by iraizo** [comment]
a pSilent variable was a thing, I dont find it but i guess its still there but now fully implemented in the projectile aimbot

**Comment by Trapacid** [comment]
Yes true perfect silent still works for projectiles. If it doesn't work, please show a video.

**Comment by KreeshTon** [comment]
I cant upload a video more than 10 mb here so I uploaded a video on youtube

https://www.youtube.com/watch?v=qhRKrwQfeBM

**Comment by iraizo** [comment]
@TotallyNotElite

**Comment by BenCat07** [comment]
it still works for projectiles, i removed the previous perfect silent option due to it being very glitchy, to make it wok you need to choke a packet on the tick you shoot, which can cause several side-effects if you do not think about a bunch of special cases.
