### ISSUE TITLE
Navbot does not work on cp_egypt_final

### ISSUE THREAD

**Issue by explowz** [nullworks/cathook#1392]
## System Information
**OS:**  CathookOS
**DE:**  The one CathookOS uses. I dunno what it's called. KDE Plasma 5 I think?
**Cathook Version:**  latest master as of 30.03.2021 (0a42c0b)

## Logs / Crash Report  
No crashes

## Description  
Navbot doesn't work on cp_egypt_final Stage 1, Point A (https://wiki.teamfortress.com/w/images/3/3f/Egypt01.jpg) in BLU team's spawn. The bot simply does not move.

## Steps to reproduce  
- [x] I am able to consistently reproduce this error

1. Start a local server with bots on the map cp_egypt_final
2. Let the bot play until it gets to play on team BLU
3. Notice that it does not move anymore

## Additional context 

No.

## Screenshot of cheats enabled  
No cheats enabled. Happens on any server running the map cp_egypt_final.

## Checklist  
- [X] I have included my DE, WM, and version of Cathook.
- [X] I have included the steps to reproduce and my logs to the best I am able to share.
- [X] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need to. (@explowz)

**Comment by explowz** [comment]
Make a pull request on https://github.com/nullworks/catbot-database then. I'd help out a bunch.

**Comment by EngineerGaming69** [comment]
https://cdn.discordapp.com/attachments/813542220283379776/813571114734845972/cp_egypt_final.nav

i have no idea if that link will work because i just took the download link from discord

**Comment by explowz** [comment]
Althought where did you take this nav mesh from? It's 6.2 MiB. That's huge. Did you take it from bot overhaul on gamebanana, or is it just the official one?

**Comment by explowz** [comment]
Did you just edit the one from cathook-database? What changes did you make? What was the issue?

**Comment by EngineerGaming69** [comment]
i could make a new one with only a fixed spawn if u want

**Comment by explowz** [comment]
What do you mean by a new one? I was just asking what was added into that one that you sent me. So it's not only the fixed spawn?

**Comment by EngineerGaming69** [comment]
> What do you mean by a new one? I was just asking what was added into that one that you sent me. So it's not only the fixed spawn?

i forgot that the nav i gave u had more then just a spawn fix. like adding nav where it could be. ima just going to make a new nav

**Comment by explowz** [comment]
Just fix the spawn and create a pull request on cathook-database to add it.

**Comment by BenCat07** [comment]
Editing nav meshes sadly is not easy at all. Valve packages their own nav meshes which are used before user made ones, so editing one is impossible unless you remove the nav meshes from your tf2 misc vpk

**Comment by BenCat07** [comment]
i will fix egypt and 2fort meshes, let me just repack my whole tf2 misc vpk first

**Comment by EngineerGaming69** [comment]
> i will fix egypt and 2fort meshes, let me just repack my whole tf2 misc vpk first

ok if u want to fix the navmesh theres also a bug on the point he should where the bots try to jump up where they cant

**Comment by BenCat07** [comment]
be specific

**Comment by EngineerGaming69** [comment]
and they cant get up

**Comment by BenCat07** [comment]
After some research (and fixing the above) i found out that bots indeed do not get stuck in blue spawn, under normal conditions. What COULD have happened is the bots being given the entity flag FL_FROZEN, which means they cannot move, if bots have that flag they will not bother moving because they can't anyways.

FL_FROZEN is applied:
- Preround (after side switch)
- At the 10 second countdown before the match start

Note that tf2 is well coded so if someone leaves in the 10 second countdown you can get frozen permanently (until you switch weapons), which may be the case here.

Please update me on details, and try if just sending a kill command to your bot fixes the issue.

**Comment by iraizo** [comment]
Why has this been closed?

**Comment by explowz** [comment]
Since it stopped happening.

**Comment by iraizo** [comment]
My bad, the PR wasn’t linked
