### ISSUE TITLE
(Suggestion) More ESP customization

### ISSUE THREAD

**Issue by KreeshTon** [nullworks/cathook#1406]
More customization for the ESP like the ability to change the color of the conditions, weapons and etc. This could also include more customization to the text positions.

The player list is also pretty messy. It should be sorted by teams.

**Comment by EngineerGaming69** [comment]
ngl playerlist is missing out. all other cheats list by team/rage/friend or other conditions

**Comment by KreeshTon** [comment]
The ESP looks pretty "outdated" to me. It's like something you see on UC.

**Comment by iraizo** [comment]
I will be sorting the playerlist when i got time to do so.

**Comment by LightPower392** [comment]
What's an example of a cheat that you think has a better looking ESP? @KreeshTon

**Comment by LightPower392** [comment]
I made a change that sorts the playerlist by team. I need more details about the ESP though.

**Comment by KreeshTon** [comment]
I'm really sorry for the late reply lol but I think one example of a cleaner esp is to have an option to turn the esp text and health bar into one color only. This also includes an option to turn off the rainbow esp for cathook users :D

**Comment by KreeshTon** [comment]
An option for a different esp font maybe? 🤔
