### ISSUE TITLE
Duplicate IPC ids

### ISSUE THREAD

**Issue by iraizo** [nullworks/cathook#1407]
When restarting multiple catbots at once the ID of the bots can be the same most of the time resulting in bots having the same ID.
This happens because the bots get the next free slot (next ID) at the start before really starting up and becoming functional, now multiple bots try to get the same ID, the ID is only "claimed" after the bot is in the `RUNNING` state.

**Comment by iraizo** [comment]
Fixed, PR is in the making the issue was the wrong usage of a mutex.

**Comment by BenCat07** [comment]
Issue was the mutex being used twice, once for finding an ipc slot, and once for assigning itself one. It should instead use one mutex for both operations, since else it will lead to conflicts.

**Comment by Auditormadness9** [comment]
Still not fixed.

**Comment by iraizo** [comment]
I had the same issue 2 weeks ago but i cant reproduce it now since windows broke grub.

**Comment by Auditormadness9** [comment]
> I had the same issue 2 weeks ago but i cant reproduce it now since windows broke grub.

will the "ipc fix" branch help?

**Comment by BenCat07** [comment]
this issue is not so easily resolved, will have to "fix" it by making sure no more than 1 bot launches at a time

**Comment by BenCat07** [comment]
did the above in webpanel
