### ISSUE TITLE
Consider the moral implications of this software

### ISSUE THREAD

**Issue by TheMoralCrusader** [nullworks/cathook#1409]
This isn't a suggestion to improve the software. It's an opportunity to think of the moral implications of this software. TF2 has been hit hard by bots and the players haven't had a fair chance to explain how they feel.

As a TF2 player myself I've had the misfortune of joining servers and not having any fun because the bots are there to wreak havoc. I mean, they aren't even manned by players most of the time. It's completely sick!

I want there to be an opportunity to talk about this in a way where we can all benefit, not just the bot authors. The rest of us are there to have fun, while the bot authors want to ruin it for us for their enjoyment. This can't stand! Please don't close this but at least consider having a conversation.

**Comment by d3fc0n6** [comment]
> This isn't a suggestion to improve the software.
then why did you mark it as enhancement

**Comment by TheMoralCrusader** [comment]
Well it's clearly not a bug report, and there's no other option than those two.

**Comment by BenCat07** [comment]
Note: there is no solution since even if this github were deleted, it's a git which many people have the whole repo of, so similarily to a torrent you cannot just remove it

**Comment by TheMoralCrusader** [comment]
Sorry to make this completely out of the blue. I and a lot of others are sick of the bot issue, and there doesn't appear to be a conversation about it, just news articles here and there.

**Comment by EngineerGaming69** [comment]
why do legits do this lol

**Comment by KreeshTon** [comment]
Thank you xX_Moralcrusader_Xx for sharing your thoughts :)

**Comment by iraizo** [comment]
Why is this even open, just close this redditor post.
