### ISSUE TITLE
Make A Slight Change With no_zoom, and no_scope

### ISSUE THREAD

**Issue by advance24th** [nullworks/cathook#1427]
**Straight To The Point**
can a feature like this be implemented for no_zoom, and scope?

```
if (no_zoom), (no_scope)
    Sendconsole("zoom_sensitivity_ratio 4")
else
    Sendconsole("zoom_sensitivity_ratio 1")
```

**What Is It?**
And Off/On Script, that basically when you turn on both, zoom sensitivy in console gets rasied to a high value, so you dont move slow, and when its off it goes back to sensitvity 1.
 ik its not easy to explain well, but id hope you get the point.

**Comment by relaybots** [comment]
I have waited so long for an issue like this to showuo

**Comment by advance24th** [comment]
```red
This issue is gonna close cause Zoom sensitivity ratio tweak, header file modifications #1428 Was made for this and a different issue, regarding the same thing

**Comment by iraizo** [comment]
Can you stop closing issues when a pr didn't get accepted, it will automatically close.
