### ISSUE TITLE
How does force slot work?

### ISSUE THREAD

**Issue by mrballgaming** [nullworks/cathook#1432]
Ive been using cathook for about 2 months and I'm just wondering, How does force slot work? I've been working on a spycrab follow bot for a while without any knowledge of anything. Right when I was finishing up I noticed that everything works BUT force slot. I have tried navbot enabled and disabled and I still cant get a single thing to happen. I just need spy to hold pda. Is this a known bug or...?

**Comment by BenCat07** [comment]
It's only for navbot, not followbot, and it will force the bot to use that specific weapon. The only way it would break is if you also enabled followbot, or disabled fast weapon switch in their tf2 config (and removed it from the autoexec)
