### ISSUE TITLE
Fix Aimbot Snapping Without A Bind

### ISSUE THREAD

**Issue by advance24th** [nullworks/cathook#1434]
### About
Silent Aimbot which keeps the local players camera from snapping, is usually used with the Aimbot itself keeping other players from seeing snapping until you shoot.

### Problem
Cathook has Silent Aimbot, which keeps users cameras from snapping to players, but does not stop the snapping even tho silent is on. **enless binding a button to aimbot** it can become a problem, as anyone around you will obviously see it, while you cannot enless you are Thirdperson

### Example's
**[If Silent On] => Stop Snapping To Other Players => Stop Snapping From Local Camera => Only Snap When 
(Toggled-Button-Used-To-Fire) is used.**

_Basically_,
If (aimbot && silent) is on, make (plain aimbot) for Local Camera & Player AA not snap at targeted player enless FIREBUTTON or  what button is binded(from tf2 binding settings) to shoot is used.

## **idea Code**
```c#
// bools "dont use these, im unprofessional"
bool local_force_player_aa('Default State'); = forcelocal_aa 
// Default State, like keep aa from snapping enless fire button is used

bool bind_local_tf2_settings('Look For Primary Fire State Button Bind'); = localbinded_player
// looks for Primary Fire Bind, and automatically sets it.

bool local_player_camera('No Snap's'); =  localcamera_player
// keep snapping from the local players camera.


If (aimbot && silent == true) {
   // use your code for aimbot, and certaint parts of silent
   g_pLocalPlayer_Do(localbinded_player && localcamera_player && forcelocal_aa);
}
   
```
#

### How does this help?
Specifically to cathook users, this would help keep them from being noticed, and may end up allowing users to more simply use cathook.

##### Expected Questions

> What do you mean the aimbot is snapping?

**When using silent aimbot, if you go thirdperson you can see it automatically snap to people. even though your camera does not move, your Player Model does.**

###### little note
i do not know if you the developers of cathook intentionally did this with aimbot, and made it snap even if you have silent on, but id hope not as i like how silent works with other cheats and would like if it was also added in cathook.

**I DO NOT KNOW IF THIS IS A BUG OR SUGGESTION!!!!**

**Comment by BenCat07** [comment]
i cannot make it not snap and i have no idea what you want from me

**Comment by iraizo** [comment]
the fix is to not use silent aimbot, what the hell is this issue, thats literally how the feature is supposed to work.

**Comment by Zanthed** [comment]
> Cathook has Silent Aimbot, which keeps users cameras from snapping to players, but does not stop the snapping even tho silent is on.

So.... you're asking for pSilent?

**Comment by KreeshTon** [comment]
Is this what you're saying?
For Heavy, The aimbot locks or looks at people when not firing or revved
For Scout, The aimbot dosent lock at people, it only locks on when firing

**Comment by iraizo** [comment]
> 
> 
> Is this what you're saying?
> For Heavy, The aimbot locks or looks at people when not firing or revved
> For Scout, The aimbot dosent lock at people, it only locks on when firing

Can you show me a video about it because I've never seen that happen before with the heavy

**Comment by KreeshTon** [comment]
https://youtu.be/fLlyPp5VMxQ

**Comment by iraizo** [comment]
Just.. disable aimbot when you dont want to AIM at him? what.

**Comment by KreeshTon** [comment]
Yeah I don't really think that this is an issue too. Just use a bind
