### ISSUE TITLE
How to carry configs over?

### ISSUE THREAD

**Issue by mrballgaming** [nullworks/cathook#1437]
I have made a lot of configurations (or whatever they are called under cat_load command)  over the past months I have had cat hook and I recently got a new PC and would like to carry all the configs over. I have spent a long time perfecting these so it would be great if I got a answer. Thank you.

**Comment by BenCat07** [comment]
/opt/cathook/data/configs


copy them over


if you have a non cathook native distro the path will be in ~/.local/share/cathook instead
