### ISSUE TITLE
Request to remove my past commits to the Cathook repo

### ISSUE THREAD

**Issue by leKamikaze1** [nullworks/cathook#1439]
Hello there peeps, I would kindly ask if it is possible to get my past contributions to the Cathook repo removed due to personal concerns. A simple revert of my past pr's would be enough. Thanks, and sorry for the trouble

**Comment by iraizo** [comment]
Reverting the code is going to help what?

**Comment by iraizo** [comment]
Let alone the fact that git is a version control meaning as soon as you pushed / pr'd to the repo you shouldve decided if you should do this or not, your commits will always be in this repo, nobody can remove them.

**Comment by Zanthed** [comment]
Simply remove the email on your account that is associated with the patches. 
In your case it's: 77033690+leKamikaze1@users.noreply.github.com

This can probably be changed with a GitHub username change.

As for the name attached to the patch that cannot be changed. Again a GitHub name change can disassociate these patches to you.

Be sure to update your Git client locally:
git config --global user.name
and user.email

It should be possible to delete commits by a user and retain code changes, but it's a bit unnecessary.

**Comment by BenCat07** [comment]
> Hello there peeps, I would kindly ask if it is possible to get my past contributions to the Cathook repo removed due to personal concerns. A simple revert of my past pr's would be enough. Thanks, and sorry for the trouble

"revert" will not remove you from the contributor list nor from the history, and a force push onto master and stable sounds like a horrible idea.

**Comment by BenCat07** [comment]
Also note that due to the license i can just recommit your changes under my name aftera revert.

**Comment by leKamikaze1** [comment]
In that case, I'll just better leave it as it is. Thanks
