### ISSUE TITLE
Failed to compile cathook error message upon trying to Install Cathook using the GUI

### ISSUE THREAD

**Issue by haIfway** [nullworks/cathook#1442]
## System Information
**OS:** Ubuntu 20.04.2 LTS x86_64
**DE:** GNOME
**Cathook Version:**  recent version edited byTotallyNotElite on Jul 1, 2020

## Logs / Crash Report  

[CMakeError.log](https://github.com/nullworks/cathook/files/6431009/CMakeError.log)
[CMakeOutput.log](https://github.com/nullworks/cathook/files/6431011/CMakeOutput.log)

## Description  
It repeatedly gives me a "failed to compile" error message upon attempting to use the GUI to install cathook.

**FULL ERROR MESSAGE:**
Cloning into 'cathook'...
~/Desktop/cathook ~/Desktop
From https://github.com/nullworks/cathook
 * [new tag]         stable     -> stable
HEAD is now at 3979a6c Update dependencycheck
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Hit:3 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 https://apt.kitware.com/ubuntu bionic InRelease
Fetched 109 kB in 1s (85,7 kB/s)
Reading package lists...
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Hit:3 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 https://apt.kitware.com/ubuntu bionic InRelease
Fetched 109 kB in 1s (95,3 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libsdl2-dev:i386
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  1 7664k    1 98304    0     0  72602      0  0:01:48  0:00:01  0:01:47 72549
 76 7664k   76 5888k    0     0  2433k      0  0:00:03  0:00:02  0:00:01 2432k
100 7664k  100 7664k    0     0  2767k      0  0:00:02  0:00:02 --:--:-- 2766k
Submodule 'external/MicroPather' (https://github.com/nullworks/MicroPather) registered for path 'external/MicroPather'
Submodule 'external/TF2_NavFile_Reader' (https://github.com/nullworks/TF2_NavFile_Reader) registered for path 'external/TF2_NavFile_Reader'
Submodule 'external/boost-cmake' (https://github.com/Orphis/boost-cmake.git) registered for path 'external/boost-cmake'
Submodule 'external/clip' (https://github.com/nullworks/clip) registered for path 'external/clip'
Submodule 'libglez' (https://github.com/nullworks/libglez) registered for path 'external/libglez'
Submodule 'external/libnullnexus' (https://github.com/nullworks/libnullnexus) registered for path 'external/libnullnexus'
Submodule 'libxoverlay' (https://github.com/nullworks/libxoverlay) registered for path 'external/libxoverlay'
Submodule 'simple-ipc' (https://github.com/nullworks/simple-ipc) registered for path 'external/simple-ipc'
Submodule 'source-sdk-2013-headers' (https://github.com/nullworks/source-sdk-2013-headers) registered for path 'external/source-sdk-2013-headers'
Cloning into '/home/a/Desktop/cathook/external/MicroPather'...
Cloning into '/home/a/Desktop/cathook/external/TF2_NavFile_Reader'...
Cloning into '/home/a/Desktop/cathook/external/boost-cmake'...
Cloning into '/home/a/Desktop/cathook/external/clip'...
Cloning into '/home/a/Desktop/cathook/external/libglez'...
Cloning into '/home/a/Desktop/cathook/external/libnullnexus'...
Cloning into '/home/a/Desktop/cathook/external/libxoverlay'...
Cloning into '/home/a/Desktop/cathook/external/simple-ipc'...
Cloning into '/home/a/Desktop/cathook/external/source-sdk-2013-headers'...
Submodule path 'external/MicroPather': checked out 'c3960ea5af374f2ed6195eb39f803f2611b882a9'
Submodule path 'external/TF2_NavFile_Reader': checked out '55ae8047a24203cec834f54fd67ee6d571f497f6'
From https://github.com/Orphis/boost-cmake
 * branch            d3951bc7f0b9d09005f92aedcf6acfc595f050ea -> FETCH_HEAD
Submodule path 'external/boost-cmake': checked out 'd3951bc7f0b9d09005f92aedcf6acfc595f050ea'
Submodule path 'external/clip': checked out 'be4f5461f7308497f5c687c2516a2dbcf23ccd33'
From https://github.com/nullworks/libglez
 * branch            a278b5ce6debd1e5580cb41b3a018a5da9b66263 -> FETCH_HEAD
Submodule path 'external/libglez': checked out 'a278b5ce6debd1e5580cb41b3a018a5da9b66263'
Submodule path 'external/libnullnexus': checked out '64edb7774a88a57f53368849126e8b886689449f'
Submodule path 'external/libxoverlay': checked out '97462b57c80eb36adda47d1390da16ce29ac2823'
Submodule path 'external/simple-ipc': checked out '085ec77f13ac8143116fe57317d9b7275fe16a57'
Submodule path 'external/source-sdk-2013-headers': checked out 'c80b09c1b6f40dc58b0a1d408832abb2b027d897'
~/Desktop/cathook/build ~/Desktop/cathook
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - broken
CMake Error at /usr/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/a/Desktop/cathook/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make -f Makefile cmTC_d19a8/fast && /usr/bin/make  -f CMakeFiles/cmTC_d19a8.dir/build.make CMakeFiles/cmTC_d19a8.dir/build
    make[1]: Entering directory '/home/a/Desktop/cathook/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_d19a8.dir/testCCompiler.c.o
    /usr/bin/cc   -m32  -o CMakeFiles/cmTC_d19a8.dir/testCCompiler.c.o -c /home/a/Desktop/cathook/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_d19a8
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d19a8.dir/link.txt --verbose=1
    /usr/bin/cc -m32  -m32 -L/usr/lib32  CMakeFiles/cmTC_d19a8.dir/testCCompiler.c.o -o cmTC_d19a8 
    /usr/bin/ld: cannot find Scrt1.o: No such file or directory
    /usr/bin/ld: cannot find crti.o: No such file or directory
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libgcc.a when searching for -lgcc
    /usr/bin/ld: cannot find -lgcc
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libgcc.a when searching for -lgcc
    /usr/bin/ld: cannot find -lgcc
    collect2: error: ld returned 1 exit status
    make[1]: *** [CMakeFiles/cmTC_d19a8.dir/build.make:99: cmTC_d19a8] Error 1
    make[1]: Leaving directory '/home/a/Desktop/cathook/build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:127: cmTC_d19a8/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:24 (project)

-- Configuring incomplete, errors occurred!
See also "/home/a/Desktop/cathook/build/CMakeFiles/CMakeOutput.log".
See also "/home/a/Desktop/cathook/build/CMakeFiles/CMakeError.log".
 
 
Failed to compile cathook

~/Desktop
Done

## Checklist  
- [yes ] I have included my DE, WM, and version of Cathook.
- [yes ] I have included the steps to reproduce and my logs to the best I am able to share.
- [yes ] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need to. (Half)

**Comment by auyylaso** [comment]
Just noticed this. I get the exact same error on the same version as well
