### ISSUE TITLE
Auto Crouch On Jump

### ISSUE THREAD

**Issue by Lewdcifer** [nullworks/cathook#1445]
Would be nice if theres an option under movement to automatically crouch while jumping.

**Comment by EngineerGaming69** [comment]
They already crouch when jumping?

**Comment by iraizo** [comment]
> 
> 
> They already crouch when jumping?

He means as a user not a navmesh bot

**Comment by EngineerGaming69** [comment]
> > They already crouch when jumping?
> 
> He means as a user not a navmesh bot

oh i see but y

**Comment by SylveonBottle** [comment]
```
alias +crouchjump "+jump; +duck"
alias -crouchjump "-duck; -jump"
bind "space" "+crouchjump"
```

Put this in autoexec.cfg

**Comment by iraizo** [comment]
> 
> 
> ```
> alias +crouchjump "+jump; +duck"
> alias -crouchjump "-duck; -jump"
> bind "space" "+crouchjump"
> ```
> 
> Put this in autoexec.cfg

Actually since you reminded me this exists this issue is useless.
