### ISSUE TITLE
Aimbot Target Cloaked Spies That Are On Fire

### ISSUE THREAD

**Issue by Lewdcifer** [nullworks/cathook#1446]
Have aimbot stop ignoring cloaked spies if they are set on fire.

**Comment by EngineerGaming69** [comment]
This is also already a thing.

**Comment by iraizo** [comment]
> 
> 
> This is also already a thing.


Is it? because shouldaim() returns false on cloaked

**Comment by EngineerGaming69** [comment]
> > This is also already a thing.
> 
> Is it? because shouldaim() returns false on cloaked

ive seen my bots shoot spys that were on fire

**Comment by iraizo** [comment]
> ive seen my bots shoot spys that were on fire. but it might be triggerbot

wow.

**Comment by EngineerGaming69** [comment]
> > ive seen my bots shoot spys that were on fire. but it might be triggerbot
> 
> wow.

not trigger bot cuz i have ignore cloaked spys on so i guess they just know to shoot spys on fire

**Comment by iraizo** [comment]
> not trigger bot cuz i have ignore cloaked spys on so i guess they just know to shoot spys on fire

Im either blind or there isnt a onfire check in aimbot

**Comment by Lewdcifer** [comment]
> > > ive seen my bots shoot spys that were on fire. but it might be triggerbot
> > 
> > 
> > wow.
> 
> not trigger bot cuz i have ignore cloaked spys on so i guess they just know to shoot spys on fire

havent seen cathook code but Im pretty sure it wasnt shooting the cloaked Spy on fire from personal experience
