### ISSUE TITLE
NavBot getting stuck on buildings

### ISSUE THREAD

**Issue by EngineerGaming69** [nullworks/cathook#1450]
Thats it navbot just gets stuck on buildings

I tried fixing this myself but could never do it. At first I was thinking it could be the nav trying to wait until it hit the ground to move again but im probably wrong.

**Comment by SylveonBottle** [comment]
Can we get the map + area that it does this in? Just a screenshot of the spot bots get stuck in (you don't need to run the bots) would help.

Some of us are trying to improve the nav meshes for bots, but we can't fix what we can't find. Just saying "there's problems with the nav mesh" doesn't really help when we already know there's problems _somewhere_.

**Comment by EngineerGaming69** [comment]
> Can we get the map + area that it does this in? Just a screenshot of the spot bots get stuck in (you don't need to run the bots) would help.
> 
> Some of us are trying to improve the nav meshes for bots, but we can't fix what we can't find. Just saying "there's problems with the nav mesh" doesn't really help when we already know there's problems _somewhere_.

It has nothing to do with navmesh. I already make my own navmeshes. Its bots just getting on buildings and it takes them until they die or run to get health to get down. Theres also another bug where they don't avoid running into buildings like how they avoid running into each other so they just sit there.

**Comment by BenCat07** [comment]
send an example image kthx

**Comment by EngineerGaming69** [comment]
do i really need a screenshot of a bot on a sentry? they just dont get off until disturbed or by chance

**Comment by BenCat07** [comment]
I can see why, i f ixed this in a previous iteration of navbot but i guess it didn't stick through, the bot is trying to walk downwards to the nav mesh, which is counter-productive when it isn't falling at all
