### ISSUE TITLE
c367dc1 Crashing when joining game on Garuda Linux

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#1465]
## System Information
**OS:**  Garuda Linux x86_64 
**DE:**  GNOME 40.1
**Cathook Version:**  c367dc1 

## Config used
[rocketjump.conf](https://github.com/nullworks/cathook/files/6469282/rocketjump.conf.txt)

## Logs / Crash Report  
[cathook-23109-segfault.log](https://github.com/nullworks/cathook/files/6469313/cathook-leafeon-23109-segfault.log)

## Description  
Crashing in casual matches a few seconds after spawning in.

## Steps to reproduce  
- [x] I am able to consistently reproduce this error

1. `cat_load rocketjump` after attaching cathook
2. Join a casual server
3. Spawn in
4. Crash after a few seconds

## Additional context 
I have no idea what could be causing this.

## Checklist  
- [x] I have included my DE, WM, and version of Cathook.
- [x] I have included the steps to reproduce and my logs to the best I am able to share.
- [x] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need to. (SylveonBottle)

**Comment by BenCat07** [comment]
You cannot send the segfault log itself, you need to instead send a sentry.io link gotten from ./report-crash, else we cannot identify the crash.
