### ISSUE TITLE
Region list doesn't get saved when using cat_save <configname>

### ISSUE THREAD

**Issue by haIfway** [nullworks/cathook#1472]
Just as the title states, after setting a specific region list and saving the config, it gets reset after the saved config is loaded: 
before: https://i.imgur.com/76BdF5c.png
after: https://i.imgur.com/BVkaGmg.png

**Comment by EngineerGaming69** [comment]
try only having the region typed. dont select any

**Comment by haIfway** [comment]
ah seems like it works, thanks <3
