### ISSUE TITLE
Avatar Stealer

### ISSUE THREAD

**Issue by Auditormadness9** [nullworks/cathook#1479]
**Quick Description**

I would like to suggest an Avatar Stealer. It would help with not getting votekicked very quickly when you botroll a match with low numbers since a full party takes days to queue and eventually gets botrolled.

**The Issue**

I do manual namestealing until namesteal gets a fix, but what would be cool is to have an avatar stealer as I have seen many bots do, which confuses a lot of people and 2 bots with AS are enough to get everyone kicked.

**My Suggestion for Developers**

There should be a simple toggle in Collective called "Avatarsteal" just like there is Namesteal. I imagine it functioning by hooking Steam, but I have no knowledge of that. It should probably have 3 options such as "Off", "Random" and "Accurate", the latter of which will try to cooperate with the namesteal feature and steal the avatar of the person namesteal stole a name from.

**Additional Context**

A lot of other bots who solo for 2fort use this. It's not meta necessary, but would be an amazing addition and will make things much more fun and popcorny in the chat. It will really help a lot.

**Comment by Zanthed** [comment]
See https://github.com/nullworks/cathook/issues/1167#issuecomment-808950140 and https://github.com/nullworks/cathook/issues/1167#issuecomment-808950295
