### ISSUE TITLE
Crit hack discrepencies 

### ISSUE THREAD

**Issue by no-boot-device** [nullworks/cathook#148]
1. The GUI crit indicator and "show crit info" don't show the same thing. If your crit indicator is grey, show crit info may still think you can crit. For example: Gunslinger.
2. Sometimes, the unstable crithack (GUI crit indicator) will think you can't crit, but you can. For example, if you have direct hit, sometimes you'll spawn with grey, but then if you removecond you'll suddenly get a crit bucket. Sometimes, you can still randomly crit even when grey and when removecond doesn't fix it.
3. why do we even have "show crit info" still what is this why do we need this dumb white text when we have a nice nonecore gooey

**Comment by BenCat07** [comment]
Obsolete
