### ISSUE TITLE
auto retry when being kicked?

### ISSUE THREAD

**Issue by seeerrrrr** [nullworks/cathook#1481]
is this a feature or no? really need it for my bots when they are being kicked. i only see crash when kick but i just want the retry command to be executed. there way of doing this or does it need to be added?

**Comment by BenCat07** [comment]
Literally has no function whatsoever.

**Comment by BenCat07** [comment]
It would be like adding a feature that pings you in discord when someone votes a player with more than two E's in their name, there is no reason to add it
