### ISSUE TITLE
Bots crash randomly when you let them run, regardless of whether they are playing or just idle in menu

### ISSUE THREAD

**Issue by Auditormadness9** [nullworks/cathook#1482]
## System Information
**OS:** Linux
**DE:** CathookOS
**Cathook Version:** Latest

## Branch used

Master branch.

## Crash Report

![image](https://user-images.githubusercontent.com/71278545/120381776-ee147a80-c333-11eb-956b-533214d31219.png)

## Description  

Bots simply crash for no reason, it doesn't matter if you constantly alt tab out of the game or are even playing the game. Heck, a few minutes ago my game was closed and I only let the bots run in the main menu for 2 hours and they have crashed like 18 times (screenshotted).
## Steps to reproduce  
☑ I am able to consistently reproduce this error

1. Use Master Branch.
2. Start the bots.
3. Make sure you have turned on "Auto-Restart when unresponsive".
4. Leave for an hour, just let them stay in menu, no need to even pressurize them via playing.
5. Come back.
6. Check the number of restarts that have occurred.

## Additional context 

I honestly am in stock of neither any idea nor imagination about how or why they crash even when idle.

## Checklist  
- ☑ I have included my DE, WM, and version of Cathook.
- ☑ I have included the steps to reproduce and my logs to the best I am able to share.
- ☑ The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need to at @Auditormadness9.

**Comment by BenCat07** [comment]
Intentional behaviour to prevent bots from being stuck in queue.

**Comment by Auditormadness9** [comment]
Huh? Why would you even do that? You won't realize how many times my entire Linux (along with tf2) crashed because of the mass bot crashes, it becomes really unplayable, have to restart each time.

**Comment by iraizo** [comment]
thats why you wont start more bots than your hardware can handle

**Comment by d3fc0n6** [comment]
> thats why you wont start more bots than your hardware can handle

That's not even the issue here. I have no idea why you would even say this. The "issue" is that there is a check to restart if queue time is >= 20 minutes

**Comment by BenCat07** [comment]
This is done so your bots are not just stuck soing nothing for a year.

**Comment by Auditormadness9** [comment]
> This is done so your bots are not just stuck doing nothing for a year.

Can I modify the code by removing this for myself?

**Comment by Auditormadness9** [comment]
> thats why you wont start more bots than your hardware can handle

I have been told my hardware can run 20 bots and I'm only running 10.

**Comment by Auditormadness9** [comment]
Fixed by self modification.
