### ISSUE TITLE
Duplicate Bot PIDs

### ISSUE THREAD

**Issue by Auditormadness9** [nullworks/cathook#1487]
## System Information
**OS:** Manjaro
**DE:** KDE
**Cathook Version:** Latest

## Description  

It's simple. 2-6 bots randomly could just acquire the same PID, and it's never really a static situation since there could be a lucky boot up where every bot has a unique PID, but it's simply luck and sadly not how it's programmed yet.
## Steps to reproduce  
- ☑ I am able to consistently reproduce this error

1. Start bots
2. Look at the PIDs

## Reasons To Bother

The issue is simple, acquiring the same PID means they write to the same log, they probably might condump the same text file when they're on different servers, etc.
## Branch used

Master.

## Checklist  
- ☑ I have included my DE, WM, and version of Cathook.
- ☑ I have included the steps to reproduce and my logs to the best I am able to share.
- ☑ The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need to.  @Auditormadness9

**Comment by iraizo** [comment]
Duplicate pids exactly like this issue (https://github.com/nullworks/cathook/issues/1407)
