### ISSUE TITLE
So TF2 got an update.

### ISSUE THREAD

**Issue by mysistercalledmehitler** [nullworks/cathook#1489]
**Numerous security and stability improvements**
Added a cooldown before a player can create a vote when they join a match already in-progress
sv_vote_late_join_time controls the grace period after the match starts before the cooldown is applied: default 90 secs
sv_vote_late_join_cooldown controls the length of the cooldown: default 5 min
Kick votes will end early and automatically pass if the vote target leaves the match during the vote
Added a ConVar to control players changing their name during a match
tf_allow_player_name_change: default is 1
Matchmaking servers will set this to 0

Do I have to worry about my account being VAC banned?

**Comment by SammCheese** [comment]
yes.

**Comment by xdfchvbjknml** [comment]
no

**Comment by Mido830** [comment]
> Do I have to worry about my account being VAC banned?

**Comment by BenCat07** [comment]
tf2 is not vac

**Comment by BenCat07** [comment]
tf2 update is not a vac update

**Comment by mysistercalledmehitler** [comment]
> > Do I have to worry about my account being VAC banned?
> 
> If you're worrying about getting banned, why do you even cheat?

people do still worry about their accounts while cheating. they know that valve is gonna do anything to their account sooner or later.

**Comment by mysistercalledmehitler** [comment]
> tf2 update is not a vac update

Gotcha

**Comment by Auditormadness9** [comment]
> > Do I have to worry about my account being VAC banned?
> 
> If you're worrying about getting banned, why do you even cheat?

Some people cheat on their main since tf2 is lax at defending itself.
