### ISSUE TITLE
No insert buttom

### ISSUE THREAD

**Issue by ClaudioPanConQueso** [nullworks/cathook#1512]
## Quick Description  
I'm on laptop, and i don't have the insert buttom, which buttom should i press?

**Comment by Zanthed** [comment]
Inject, open TF2 console, bind it to something like F11 using cat set:

`cat set visual.open-gui-button F11`

**Comment by ClaudioPanConQueso** [comment]
thanks. 
oh wait, i remember i can't open appimage because i'm on windows, what do i do?

**Comment by Zanthed** [comment]
@ClaudioPanConQueso 
This is Linux-only software. There is zero support for any other operating system. You need to install a Linux distro of some kind to use this.

Read this wiki page fully for the installation process of your choice: https://github.com/nullworks/cathook/wiki/Installing,-Attaching-And-General-Infos

**Comment by ClaudioPanConQueso** [comment]
oh, well i'm dumb xD. thanks
