### ISSUE TITLE
Cathook not installing

### ISSUE THREAD

**Issue by WheeledCord** [nullworks/cathook#1515]
Every time i try to install cathook it instantly displays the words "done" without installing anything.

i use arch btw
DE: cinnamon

edit: it does create a cathook folder with only one file called settings.conf in it.
```
contents of settings.conf:

[cathook-gui]
mode=0
```

**Comment by Zanthed** [comment]
More information is required.
How are you installing this? Are you using the AppImage? Are you installing from master? If so, make sure you're actually cloning the repo and not downloading the zip. What are the commands you're running? Are you following the wiki?

**Comment by WheeledCord** [comment]
nvm i fixed it

**Comment by WheeledCord** [comment]
nvm i fixed it
