### ISSUE TITLE
Engi bots try to build in spawns.

### ISSUE THREAD

**Issue by EngineerGaming69** [nullworks/cathook#1528]
## System Information
**Manjaro**
**Cathook Version: latest**  

## Config used
Any config with engi mode.

## Description  
Engineer bots will run all the way to enemy spawn rooms to try and build in them which gets them killed or stuck in a forever jumping loop.

## Steps to reproduce  
Turn on engineer mode
Wait for them to find a place to build and half the time its in the enemy spawn or inside your spawn.

## Additional context 
This happens more on non ctf maps.
Also this bug happens because of the spawn checks not working in the code.

## Checklist  
- [x] I have included my DE, WM, and version of Cathook.
- [x] I have included the steps to reproduce and my logs to the best I am able to share.
- [x] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need to. (pipmilly)

**Comment by BenCat07** [comment]
There is no way for a client to check if a point is in  spawn area or not

**Comment by EngineerGaming69** [comment]
> There is no way for a client to check if a point is in spawn area or not

dang thats trash. what about forcing the build spots to near the obj and near there own flag on ctf

**Comment by EngineerGaming69** [comment]
> dang thats trash. what about forcing the build spots to near the obj and near their own flag on ctf

this is what tf2 bots do to keep the engis near the obj

**Comment by BenCat07** [comment]
The latter is already being done
