### ISSUE TITLE
Bots unable to load cathook config

### ISSUE THREAD

**Issue by Identidade** [nullworks/cathook#1530]
## System Information
**OS:CathookOS  
**DE:Kde  
**Cathook Version:Latest**  

## Config used

[bot.txt](https://github.com/nullworks/cathook/files/6996781/bot.txt)

## Description  

![Screenshot_20210816_211012](https://user-images.githubusercontent.com/46310153/129658037-def89e34-4f16-45bc-8607-539441f28275.png)

It says they are queuing, but they never find a match.

I have the casual map/gamemode list saved, Auto-Queue, Auto-Requeue ON and cat_autoexec_textmode.cfg is set to automatically load the bot config

**Comment by BenCat07** [comment]
if they queue for over 20 mins, they do find a match but are stuck joining it for some reason, e.g. gc issue or server is down

**Comment by Identidade** [comment]
My problem was fixed by issuing the following command in terminal:

sudo chmod -R a=rwx /opt/cathook

The real problem was that the bots weren't loading the configs which made them not know what to do, thanks for the help anyway!

**Comment by Zanthed** [comment]
This is highly unlikely the solution as the world already has read permissions on every file in there. Just no write or execute. Linux permissions set to 777 are absolutely unnecessary and never the solution.

**Comment by BenCat07** [comment]
chown -R $USER:$USER (path) 

is the better solution normally
