### ISSUE TITLE
Cathook crashes TF2 if the latter has been started with a custom SDL2 lib

### ISSUE THREAD

**Issue by taago27** [nullworks/cathook#1550]
## System Information
**OS:**  Gentoo Linux
**DE:**  KDE Plasma 5.22.1
**Cathook Version:**  https://github.com/nullworks/cathook/commit/5da556c7942ea5816fb5ecaa625b353f9bd88ba7
**Custom SDL2 version:**  2.0.16

## Logs / Crash Report  
[cathook-taago-13708.log](https://github.com/nullworks/cathook/files/7151121/cathook-taago-13708.log)
[cathook-taago-13708-segfault.log](https://github.com/nullworks/cathook/files/7151124/cathook-taago-13708-segfault.log)

Thread 28 "hl2_linux" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 14246]
0xbad1610c in sdl_hooks::applySdlHooks () at /mnt/Vabakasutus/Projektid/cathook/src/visual/SDLHooks.cpp:27
27          *pointers::SDL_GL_SwapWindow                = hooked_methods::methods::SDL_GL_SwapWindow;
#0  0xbad1610c in sdl_hooks::applySdlHooks () at /mnt/Vabakasutus/Projektid/cathook/src/visual/SDLHooks.cpp:27
#1  0xbaa941e0 in hack::Hook () at /mnt/Vabakasutus/Projektid/cathook/src/hack.cpp:265
#2  0xbaa964df in hack::Initialize () at /mnt/Vabakasutus/Projektid/cathook/src/hack.cpp:399
#3  0xbab0d494 in MainThread (arg=0xbaf86a78 <mutex_quit>) at /mnt/Vabakasutus/Projektid/cathook/src/core/entry.cpp:34
#4  0xf7e57e4f in start_thread () from /lib/libpthread.so.0
#5  0xf7d67c96 in clone () from /lib/libc.so.6
[Inferior 1 (process 13708) detached]

## Description  
If TF2 has been launched with a newer SDL2 lib than provided by Valve, Cathook will immediately crash the game after attaching.

## Steps to reproduce  
- [x] I am able to consistently reproduce this error

1. Replace current libSDL2-2.0.so.0 with newer one in **Team Fortress 2/bin**
2. Attach Cathook to game process
3. (Now it'll crash)

## Checklist  
- [x] I have included my DE, WM, and version of Cathook.
- [x] I have included the steps to reproduce and my logs to the best I am able to share.
- [ ] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need to.

**Comment by BenCat07** [comment]
cannot fix this because making a signature for this isn't really possible
