### ISSUE TITLE
Pocket Immunity

### ISSUE THREAD

**Issue by EzzyCrafts** [nullworks/cathook#1551]
There should be a feature where if you get pocketed, the person pocketing you will get immunity.

**Comment by EngineerGaming69** [comment]
are you anti botting

**Comment by EzzyCrafts** [comment]
no, i just think it'd be cool for people that are healing bots get immunity from them

**Comment by CatholicGod** [comment]
This will be easily abuseable

**Comment by EzzyCrafts** [comment]
How? I think it would be an ultimate positive because nothing bad can really happen if you have someone pocketing a bot.

**Comment by CatholicGod** [comment]
Medic will heal first bot, quickly kill second bot, then reheal first bot.

**Comment by CatholicGod** [comment]
Sure, there could be a betray system but still.

**Comment by EzzyCrafts** [comment]
then we suppose something, very strict, bot will instantly kill medic if unpocket even for a milisecond.

**Comment by CatholicGod** [comment]
tbh, it's still pretty useless.

**Comment by iraizo** [comment]
I dont see a use for this.
