### ISSUE TITLE
Holy fucking fuck cathook crashes too much

### ISSUE THREAD

**Issue by EngineerGaming69** [nullworks/cathook#1555]
holy fucking shit balls cathook crashes too much

**Comment by CatholicGod** [comment]
Please give more info, like what it crashes to.

**Comment by EngineerGaming69** [comment]
all

**Comment by Zanthed** [comment]
Really useful.
Thanks for posting crash reports and logs, sentry IDs, what you were doing when it crashed, your config(s), your distro and hardware, etc.

**Comment by EngineerGaming69** [comment]
> Really useful. Thanks for posting crash reports and logs, sentry IDs, what you were doing when it crashed, your config(s), your distro and hardware, etc.

shoot gun pc on fire

**Comment by EngineerGaming69** [comment]
https://github.com/nullworks/cathook/issues/1548
https://github.com/nullworks/cathook/issues/1547
https://github.com/nullworks/cathook/issues/1510
https://github.com/nullworks/cathook/issues/1500

no one is doing anything about these LOL

**Comment by iraizo** [comment]
Don’t spam this repo with garbage issues please

**Comment by EngineerGaming69** [comment]
> Don’t spam this repo with garbage issues please

enjoy your crashing cheat i guess

**Comment by Zanthed** [comment]
This isn't a useful or helpful issue in any way. You were asked to give more details or information or anything for us to work with. In which you gave more ambiguous un-useful information. We can't work with this. The cheat works fine for many others. If it didn't, there would be more awareness raised.

Judging by the lack of detail here, this is very likely a user issue with their distro and/or hardware. We would love to help diagnose this with you, but help us help you.

**Comment by iraizo** [comment]
Ah yes, having useless issues like that with no information surely helps

**Comment by BenCat07** [comment]
I know of these issues, but do not have the time. Melee aimbot i will be fixing in a bit, the aimbot freze issue is hardware specific, and i'll need access to the machine of someone that has it in order to debug it. The projectile pred error can be fixed alongside melee aimbot, yet again, once i have the time. I do not currently, i have other stuff to do besides working on cathook. That's all.

I'll fix these issues, just not right now.
