### ISSUE TITLE
Unable to download on PopOs

### ISSUE THREAD

**Issue by TrentonBarrant** [nullworks/cathook#1568]
## System Information
**OS: Linux**  
**DE: PopOs**  
**Cathook Version: Current**  

## Config used
None

> ## Logs / Crash Report  
> what@pop-os:~$ 
>     bash <(wget -qO- https://raw.githubusercontent.com/nullworks/One-in-all-cathook-install/master/install-all)
> Cloning into 'cathook'...
> remote: Enumerating objects: 684, done.
> remote: Counting objects: 100% (684/684), done.
> remote: Compressing objects: 100% (654/654), done.
> remote: Total 684 (delta 52), reused 260 (delta 20), pack-reused 0
> Receiving objects: 100% (684/684), 6.70 MiB | 3.81 MiB/s, done.
> Resolving deltas: 100% (52/52), done.
> ~/cathook ~
> Terminal UI NOT supported! Install "dialog"! 
> remote: Enumerating objects: 53, done.
> remote: Counting objects: 100% (53/53), done.
> remote: Compressing objects: 100% (27/27), done.
> remote: Total 27 (delta 26), reused 1 (delta 0), pack-reused 0
> Unpacking objects: 100% (27/27), 2.48 KiB | 77.00 KiB/s, done.
> From https://github.com/nullworks/cathook
>  * [new tag]         stable     -> stable
> HEAD is now at 6463ff2 Fix the same issue on melee aimbot which is also in backtrack
> Terminal UI NOT supported! Install "dialog"! 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 7664k  100 7664k    0     0  3460k      0  0:00:02  0:00:02 --:--:-- 3460k
> Submodule 'external/MicroPather' (https://github.com/nullworks/MicroPather) registered for path 'external/MicroPather'
> Submodule 'external/TF2_NavFile_Reader' (https://github.com/nullworks/TF2_NavFile_Reader) registered for path 'external/TF2_NavFile_Reader'
> Submodule 'external/boost-cmake' (https://github.com/Orphis/boost-cmake.git) registered for path 'external/boost-cmake'
> Submodule 'external/clip' (https://github.com/nullworks/clip) registered for path 'external/clip'
> Submodule 'libglez' (https://github.com/nullworks/libglez) registered for path 'external/libglez'
> Submodule 'external/libnullnexus' (https://github.com/nullworks/libnullnexus) registered for path 'external/libnullnexus'
> Submodule 'libxoverlay' (https://github.com/nullworks/libxoverlay) registered for path 'external/libxoverlay'
> Submodule 'simple-ipc' (https://github.com/nullworks/simple-ipc) registered for path 'external/simple-ipc'
> Submodule 'source-sdk-2013-headers' (https://github.com/nullworks/source-sdk-2013-headers) registered for path 'external/source-sdk-2013-headers'
> Cloning into '/home/what/cathook/external/MicroPather'...
> Cloning into '/home/what/cathook/external/TF2_NavFile_Reader'...
> Cloning into '/home/what/cathook/external/boost-cmake'...
> Cloning into '/home/what/cathook/external/clip'...
> Cloning into '/home/what/cathook/external/libglez'...
> Cloning into '/home/what/cathook/external/libnullnexus'...
> Cloning into '/home/what/cathook/external/libxoverlay'...
> Cloning into '/home/what/cathook/external/simple-ipc'...
> Cloning into '/home/what/cathook/external/source-sdk-2013-headers'...
> Submodule path 'external/MicroPather': checked out 'c3960ea5af374f2ed6195eb39f803f2611b882a9'
> Submodule path 'external/TF2_NavFile_Reader': checked out '55ae8047a24203cec834f54fd67ee6d571f497f6'
> remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
> remote: Enumerating objects: 5, done.
> remote: Counting objects: 100% (5/5), done.
> remote: Compressing objects: 100% (3/3), done.
> remote: Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
> Unpacking objects: 100% (3/3), 360 bytes | 120.00 KiB/s, done.
> From https://github.com/Orphis/boost-cmake
>  * branch            7f97a08b64bd5d2e53e932ddf80c40544cf45edf -> FETCH_HEAD
> Submodule path 'external/boost-cmake': checked out '7f97a08b64bd5d2e53e932ddf80c40544cf45edf'
> Submodule path 'external/clip': checked out 'be4f5461f7308497f5c687c2516a2dbcf23ccd33'
> remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
> remote: Enumerating objects: 1, done.
> remote: Counting objects: 100% (1/1), done.
> remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
> Unpacking objects: 100% (1/1), 167 bytes | 167.00 KiB/s, done.
> From https://github.com/nullworks/libglez
>  * branch            a278b5ce6debd1e5580cb41b3a018a5da9b66263 -> FETCH_HEAD
> Submodule path 'external/libglez': checked out 'a278b5ce6debd1e5580cb41b3a018a5da9b66263'
> Submodule path 'external/libnullnexus': checked out '64edb7774a88a57f53368849126e8b886689449f'
> Submodule path 'external/libxoverlay': checked out '97462b57c80eb36adda47d1390da16ce29ac2823'
> Submodule path 'external/simple-ipc': checked out '085ec77f13ac8143116fe57317d9b7275fe16a57'
> Submodule path 'external/source-sdk-2013-headers': checked out 'ec9aaa1514eef4a9fc7406acc7dd3b0cea05161a'
> ~/cathook/build ~/cathook
> ./scripts/updater: line 160: cmake: command not found
>  
>  
> Failed to compile cathook
> 
> ~

## Description  
I can't download cathook

## Steps to reproduce  
Download cathook, crashes TF2 when injecting from github, uses terminal version, failed to compile cathook, :unjel" 

1. Installed from Github
2. Uses another method 
3. Both dont work.

## Additional context 
idk lol xd xd xd 

## Screenshot of cheats enabled  
None

## Checklist  
- [x] I have included my DE, WM, and version of Cathook.

**Comment by iraizo** [comment]
Closed due to inactivity

**Comment by TrentonBarrant** [comment]
dont care + didnt ask + dont email me + ratio
