### ISSUE TITLE
Old gcc version

### ISSUE THREAD

**Issue by thesavagen** [nullworks/cathook#1569]
## System Information
**OS:**  Linux
**DE:**  ubuntu 20.04 LTS
**Cathook Version:**  59a0e4b

## Description  

So I was trying to install cathook and in the tutorial I was watching on how to do it has me do cd cathook and then run ./install-all and it runs the code and says failed to compile cathook

## Steps to reproduce  
I ran these commands in this order
git clone --recursive https://github.com/nullworks/cathook.git
cd cathook
./install-all
<pre>./install-all

remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
HEAD is now at 6463ff25 Fix the same issue on melee aimbot which is also in backtrack
** Resuming transfer from byte position 7848376
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 7664k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
~/cathook/build ~/cathook
-- Found Boost: /usr/include (found suitable version &quot;1.71.0&quot;, minimum required is &quot;1.70.0&quot;)  
-- Found Boost: /usr/include (found version &quot;1.71.0&quot;)  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nick/cathook/build
[  0%] <font color="#4E9A06">Building CXX object CMakeFiles/cathook.dir/cmake_pch.hxx.gch</font>
<b>cc1plus:</b> <font color="#CC0000"><b>error: </b></font>bad value (‘<b>tigerlake</b>’) for ‘<b>-march=</b>’ switch
<b>cc1plus:</b> <font color="#06989A"><b>note: </b></font>valid arguments to ‘<b>-march=</b>’ switch are: i386 i486 i586 pentium lakemont pentium-mmx winchip-c6 winchip2 c3 samuel-2 c3-2 nehemiah c7 esther i686 pentiumpro pentium2 pentium3 pentium3m pentium-m pentium4 pentium4m prescott nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm geode k6 k6-2 k6-3 athlon athlon-tbird athlon-4 athlon-xp athlon-mp x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 native
<b>cc1plus:</b> <font color="#CC0000"><b>error: </b></font>bad value (‘<b>tigerlake</b>’) for ‘<b>-mtune=</b>’ switch
<b>cc1plus:</b> <font color="#06989A"><b>note: </b></font>valid arguments to ‘<b>-mtune=</b>’ switch are: i386 i486 i586 pentium lakemont pentium-mmx winchip-c6 winchip2 c3 samuel-2 c3-2 nehemiah c7 esther i686 pentiumpro pentium2 pentium3 pentium3m pentium-m pentium4 pentium4m prescott nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm intel geode k6 k6-2 k6-3 athlon athlon-tbird athlon-4 athlon-xp athlon-mp x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 generic native
make[3]: *** [CMakeFiles/cathook.dir/build.make:64: CMakeFiles/cathook.dir/cmake_pch.hxx.gch] Error 1
make[2]: *** [CMakeFiles/Makefile2:733: CMakeFiles/cathook.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:740: CMakeFiles/cathook.dir/rule] Error 2
make: *** [Makefile:177: cathook] Error 2
<font color="#CC0000"><b> </b></font>
<font color="#CC0000"><b> </b></font>
<font color="#CC0000"><b>Failed to compile cathook</b></font>
</pre>

## Checklist  
- [ ] I have included my DE, WM, and version of Cathook.
- [ ] I have included the steps to reproduce and my logs to the best I am able to share.
- [ ] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need to. (thensavagen) (new to linux and github so lmk if there's any other information you need)

**Comment by Zanthed** [comment]
Yes. GCC 10 and above has support for Intel Tigerlake. Anything below does not.

**Comment by iraizo** [comment]
Closed due to inactivity
