### ISSUE TITLE
how

### ISSUE THREAD

**Issue by TrentonBarrant** [nullworks/cathook#1577]
how the hell do I even use the dependencycheck script

im kinda stupid ngl!!!11

**Comment by BenCat07** [comment]
you don't, you run the way to install shown i the readme. Why do you need to run dependencycheck?

**Comment by TrentonBarrant** [comment]
> you don't, you run the way to install shown i the readme. Why do you need to run dependencycheck?

Cause I am trying every method, because Cmake error when I already have Cmake.

-- Configuring incomplete, errors occurred!
See also "/home/what/Desktop/cathook-gui/public/cathook/build/CMakeFiles/CMakeOutput.log".
 
 
Failed to compile cathook

~/Desktop/cathook-gui/public
Done

**Comment by Zanthed** [comment]
Please post the full error. This is a completely generic error by CMake. Your last issue #1568 was also inactive, but your unnecessary shitpost made it seem like it was solved instead of doing the solution I gave you, and helping me figure out what kind of output lsb_release gives.

**Comment by TrentonBarrant** [comment]
> Fuck you give me the full error

Cloning into 'cathook'...
~/Desktop/cathook-gui/public/cathook ~/Desktop/cathook-gui/public
Terminal UI NOT supported! Install "dialog"! 
From https://github.com/nullworks/cathook
 * [new tag]         stable     -> stable
HEAD is now at 6463ff2 Fix the same issue on melee aimbot which is also in backtrack
Terminal UI NOT supported! Install "dialog"! 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 20 7664k   20 1552k    0     0  1505k      0  0:00:05  0:00:01  0:00:04 1505k
 88 7664k   88 6768k    0     0  3296k      0  0:00:02  0:00:02 --:--:-- 3295k
100 7664k  100 7664k    0     0  3501k      0  0:00:02  0:00:02 --:--:-- 3499k
Submodule 'external/MicroPather' (https://github.com/nullworks/MicroPather) registered for path 'external/MicroPather'
Submodule 'external/TF2_NavFile_Reader' (https://github.com/nullworks/TF2_NavFile_Reader) registered for path 'external/TF2_NavFile_Reader'
Submodule 'external/boost-cmake' (https://github.com/Orphis/boost-cmake.git) registered for path 'external/boost-cmake'
Submodule 'external/clip' (https://github.com/nullworks/clip) registered for path 'external/clip'
Submodule 'libglez' (https://github.com/nullworks/libglez) registered for path 'external/libglez'
Submodule 'external/libnullnexus' (https://github.com/nullworks/libnullnexus) registered for path 'external/libnullnexus'
Submodule 'libxoverlay' (https://github.com/nullworks/libxoverlay) registered for path 'external/libxoverlay'
Submodule 'simple-ipc' (https://github.com/nullworks/simple-ipc) registered for path 'external/simple-ipc'
Submodule 'source-sdk-2013-headers' (https://github.com/nullworks/source-sdk-2013-headers) registered for path 'external/source-sdk-2013-headers'
Cloning into '/home/what/Desktop/cathook-gui/public/cathook/external/MicroPather'...
Cloning into '/home/what/Desktop/cathook-gui/public/cathook/external/TF2_NavFile_Reader'...
Cloning into '/home/what/Desktop/cathook-gui/public/cathook/external/boost-cmake'...
Cloning into '/home/what/Desktop/cathook-gui/public/cathook/external/clip'...
Cloning into '/home/what/Desktop/cathook-gui/public/cathook/external/libglez'...
Cloning into '/home/what/Desktop/cathook-gui/public/cathook/external/libnullnexus'...
Cloning into '/home/what/Desktop/cathook-gui/public/cathook/external/libxoverlay'...
Cloning into '/home/what/Desktop/cathook-gui/public/cathook/external/simple-ipc'...
Cloning into '/home/what/Desktop/cathook-gui/public/cathook/external/source-sdk-2013-headers'...
Submodule path 'external/MicroPather': checked out 'c3960ea5af374f2ed6195eb39f803f2611b882a9'
Submodule path 'external/TF2_NavFile_Reader': checked out '55ae8047a24203cec834f54fd67ee6d571f497f6'
From https://github.com/Orphis/boost-cmake
 * branch            7f97a08b64bd5d2e53e932ddf80c40544cf45edf -> FETCH_HEAD
Submodule path 'external/boost-cmake': checked out '7f97a08b64bd5d2e53e932ddf80c40544cf45edf'
Submodule path 'external/clip': checked out 'be4f5461f7308497f5c687c2516a2dbcf23ccd33'
From https://github.com/nullworks/libglez
 * branch            a278b5ce6debd1e5580cb41b3a018a5da9b66263 -> FETCH_HEAD
Submodule path 'external/libglez': checked out 'a278b5ce6debd1e5580cb41b3a018a5da9b66263'
Submodule path 'external/libnullnexus': checked out '64edb7774a88a57f53368849126e8b886689449f'
Submodule path 'external/libxoverlay': checked out '97462b57c80eb36adda47d1390da16ce29ac2823'
Submodule path 'external/simple-ipc': checked out '085ec77f13ac8143116fe57317d9b7275fe16a57'
Submodule path 'external/source-sdk-2013-headers': checked out 'ec9aaa1514eef4a9fc7406acc7dd3b0cea05161a'
~/Desktop/cathook-gui/public/cathook/build ~/Desktop/cathook-gui/public/cathook
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Freetype (missing: FREETYPE_LIBRARY) (found version
  "2.10.4")
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.18/Modules/FindFreetype.cmake:157 (find_package_handle_standard_args)
  CMakeLists.txt:96 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/what/Desktop/cathook-gui/public/cathook/build/CMakeFiles/CMakeOutput.log".
 
 
Failed to compile cathook

~/Desktop/cathook-gui/public
Done
