### ISSUE TITLE
VMWare not letting me run cathook OS

### ISSUE THREAD

**Issue by StabbyHam** [nullworks/cathook#1586]
![image](https://user-images.githubusercontent.com/92562411/145073732-746ea5e4-809e-42f0-82d0-792d5f3e3ebd.png)

**Comment by iraizo** [comment]
Im not sure what im looking at

**Comment by BenCat07** [comment]
you set it to Ubuntu core, it's arch however

**Comment by StabbyHam** [comment]
tf is arch

**Comment by StabbyHam** [comment]
> you set it to Ubuntu core, it's arch however

what is arch

**Comment by iraizo** [comment]
> what is arch

a linux distro

**Comment by StabbyHam** [comment]
> > what is arch
> 
> a linux distro

where is it found in VMWare, or is it an external download?

**Comment by LDzik** [comment]
> > > what is arch
> > 
> > 
> > a linux distro
> 
> where is it found in VMWare, or is it an external download?

![obraz](https://user-images.githubusercontent.com/63643405/149417031-fbc3053a-8f71-4b44-a1f5-89fb172bb98a.png)

**Comment by DrFluffery** [comment]
also CathookOS is an outdated version of Manjaro, for similar effects use default manjaro

**Comment by iraizo** [comment]
Closed due to inactivity
