### ISSUE TITLE
Vote kick immunity

### ISSUE THREAD

**Issue by PabdeyG** [nullworks/cathook#1587]
**Quick Description**

Vote kick immunity is out

Allows player to gain immunity against vote kick

LMAO Box has got this feature, can we please get it too?

**Comment by Gught** [comment]
That feature Already exists in cathook, named remove match join timer

**Comment by Gught** [comment]
Please don't scold me if I wrote it wrong, I have bad English

**Comment by BenCat07** [comment]
Already added
