### ISSUE TITLE
Please add Airstuck feature

### ISSUE THREAD

**Issue by Gught** [nullworks/cathook#1590]
**Quick Description**
I've seen this feature in Nullcore. This hack can be abused to avoid teleportation after warm-up and capturing a point on "cp_*" maps. 

And tell me please if it still works.

**Comment by BenCat07** [comment]
Airstuck has been removed,as it broke about 4 years ago

**Comment by BenCat07** [comment]
Aka, they patched it

**Comment by Gught** [comment]
Oh ok
