### ISSUE TITLE
How do you use micspam for bots

### ISSUE THREAD

**Issue by bruisfat** [nullworks/cathook#1591]
I was wondering how can you micspam bots because I saw an option on utilities and it would be useful for me to troll around with it.

**Comment by STG7754** [comment]
1.You need input microphone

2.set config to misc/cat-bot/Micspam

3.after Bot running. play music or Micspam stuff.

**Comment by STG7754** [comment]
and yes you need Premium accounts with 5$

**Comment by bruisfat** [comment]
How do I start playing music. Do I need to download a video with mp4 and play the music?

**Comment by yelnyaface** [comment]
@STG7754 the input microphone, do u mean actually using a real microphone? and record from speaker?

**Comment by yelnyaface** [comment]
@bruisfat did you managed to make it work? because I think no other person here even knows how to make it work

**Comment by bruisfat** [comment]
I'm still confused to the part of playing music. Do I need to install an application online to use music for bots (If so, can you please tell me the name) or download mp4 music and play it.

**Comment by yelnyaface** [comment]
@bruisfat 

here are the tutorials I followed:
https://unix.stackexchange.com/questions/174379/how-can-i-create-a-virtual-output-in-pulseaudio
https://askubuntu.com/questions/650278/automate-creation-of-pulseaudio-null-sinks
https://askubuntu.com/questions/388570/how-do-i-route-the-output-of-a-single-program-to-a-mic-input

you need to use `pulseaudio`, but so far I only can micspam with a single instance of `cathook` not with `catbots`, I think most that claims to be able to micspam here can only do it in the single instance of `cathook` not with catbots

**Comment by vicinity-gush8** [comment]
Follow this steam community guide https://steamcommunity.com/sharedfiles/filedetails/?id=249772871 then it should work fine. 

Only issue is with the default pulseaudio config making pulseaudio exit after idling for 20 seconds. To circumvent this you should just keep pavucontrol open after starting pulseaudio and having created the null sink.

**Comment by yelnyaface** [comment]
@vicinity-gush8 single `cathook` instance only? or it works for all `catbots` without the host? because many here claims they know how to micspam but it only works for single instance

**Comment by vicinity-gush8** [comment]
@yelnyaface Single cathook and catbots.

**Comment by yelnyaface** [comment]
@vicinity-gush8 may I know which Linux OS you using? I am using Ubuntu, and my issue is the `Recording Tab` is always empty if I use IPC `catbots` and the `Recording Tab` only shows 1x recording if I use a single instance of `cathook`, will each `catbot` create a new recording row in the `Recording Tab`?

**Comment by vicinity-gush8** [comment]
@yelnyaface Each catbot will create a new recording row in the Recording Tab. Did you try doing what I wrote here?
> Only issue is with the default pulseaudio config making pulseaudio exit after idling for 20 seconds. To circumvent this you should just keep pavucontrol open after starting pulseaudio and having created the null sink.

**Comment by STG7754** [comment]
idk. because i have not a input microphone.

**Comment by yelnyaface** [comment]
@vicinity-gush8 yea, but I did. but there is still no recording rows in the tab, I am starting to suspect that I have either messed up my OS config or the `Ubuntu` OS cannot do that

**Comment by yelnyaface** [comment]
@vicinity-gush8 do you mind sharing which OS you using? is it `Manjaro`? if so which? `XFCE`? `KDE Plasma`? `GNOME`?

**Comment by vicinity-gush8** [comment]
@yelnyaface I'm using Void Linux with Xfce.

**Comment by yelnyaface** [comment]
@vicinity-gush8 can show us the screenshot of how the `Pulse Audio Volumn Control` recording tab look like with `catbots`?

**Comment by yelnyaface** [comment]
I got 3x friends who tried `https://steamcommunity.com/sharedfiles/filedetails/?id=249772871` and the `recording tab` is blank for them, 1x uses Manjaro VM, 2x others using Manjaro XFECE

**Comment by vicinity-gush8** [comment]
@yelnyaface 
![image](https://user-images.githubusercontent.com/88168049/147616903-a560acfd-430c-411d-a8cc-b36230bc8d11.png)
I made a short video showing me doing it, if it helps.
https://streamable.com/1yifzo (Sorry about the low quality, it's streamable doing it)

**Comment by yelnyaface** [comment]
I see, that was exactly how we did it, but the issue is the recording tab is always blank, why are you joining a private/community server? can you micspam in casual servers?

**Comment by yelnyaface** [comment]
![Screenshot_20211230_112104](https://user-images.githubusercontent.com/16500322/147696816-af765cca-c37b-4b41-bc18-203976f7799c.png)
![Screenshot_20211230_112432](https://user-images.githubusercontent.com/16500322/147696819-d81133c1-2a03-41ef-bfe3-6c40045c11d8.png)

this is all we get, no recording rows as usual, I am using Manjaro CathookOS, even that wont work

**Comment by yelnyaface** [comment]
![Uploading Screenshot_20211230_113209.png…]()

**Comment by yelnyaface** [comment]
thanks for all the amazing assistances, I have found out what went wrong, it is actually the `autoexec_textmode`, I was using the bot `.conf` from my friend, and inside it contains command that disabled the voice chat

**Comment by iraizo** [comment]
This issue seems to be resolved, if not please reopen it or comment on it.
