### ISSUE TITLE
taking too long to launch

### ISSUE THREAD

**Issue by StabbyHam** [nullworks/cathook#1595]
![image](https://user-images.githubusercontent.com/92562411/150889624-9b431238-0bcb-4344-b996-a256b1060169.png)
how do i fix this.

**Comment by iraizo** [comment]
not cathook related.

**Comment by StabbyHam** [comment]
literally me running cathook os

**Comment by StabbyHam** [comment]
> not cathook related.

literally me running cathook os

**Comment by iraizo** [comment]
what service is related to cathook exactly?

**Comment by Zanthed** [comment]
Cathook OS is reskinned Manjaro and works just fine for everyone else. You need to give more information, otherwise this screenshot and a pointless "please help" is not a way to ask for support and this is unlikely related to Cathook.

**Comment by Zanthed** [comment]
If you're running this in a VM, you didn't set it up properly.

If you're running this on bare-metal, you might have problematic hardware. Again we don't know because this screenshot is pointless and no one has reported anything.

**Comment by SylveonBottle** [comment]
I'm pretty sure the developers of this project themselves stated not to use cathook os as it is heavily outdated. It should be about 2 years outdated by now. 
You should just install your own instance of manjaro and then install cathook on top of it.

**Comment by BenCat07** [comment]
> I'm pretty sure the developers of this project themselves stated not to use cathook os as it is heavily outdated. It should be about 2 years outdated by now. You should just install your own instance of manjaro and then install cathook on top of it.

Actually we haven't, but it has some issues updating. However this issue seems to be unrelated, slow start = I/O or CPU issue, from experience, caused by using a vm most likely
