### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by shitbinarymemorydatastringdatatypename** [nullworks/cathook#1600]
crashing when enabling linux

**Comment by shitbinarymemorydatastringdatatypename** [comment]
I tried injecting windows into linux and then injecting cathook into tf2 but It didnt solved my issue

**Comment by shitbinarymemorydatastringdatatypename** [comment]
and then I tried injecting lithium into tf2 before injecting cathook but it also didn't fucking work

**Comment by shitbinarymemorydatastringdatatypename** [comment]
any advice ?

**Comment by shitbinarymemorydatastringdatatypename** [comment]
I also fucking injected windows kernel into linux but guess what

**Comment by shitbinarymemorydatastringdatatypename** [comment]
It didn't work

**Comment by iraizo** [comment]
@BenCat07 Might aswell limit this person from the organization, it seems i dont have permission or cant find the option to do so.
