### ISSUE TITLE
Cannot attach Cathook without a freeze/crash

### ISSUE THREAD

**Issue by sanchez198** [nullworks/cathook#1604]
## System Information
Manjaro
XFCE  
Most Recent Cathook Version  

## Description  
Whenever I attach cathook, it freezes my TF2, and a moment later it crashes.

## Checklist  
- [ ] I have included my DE, WM, and version of Cathook.
- No TG account

**Comment by iraizo** [comment]
Wheres the crashlog?

**Comment by iraizo** [comment]
Closed due to inactivity, reopen this if needed.
