### ISSUE TITLE
Crash after attaching

### ISSUE THREAD

**Issue by davielachesis** [nullworks/cathook#1607]
I've just installed cathook via its OS. Whenever I try to attach it to the game, it freezes after the process, and the game eventually crashes, making it impossible. I've tried using the manual attaching commands as well, but still, the result is the same. In rare cases, the attaching succeeds, but whenever I press the toggle key, the screen freezes, and the game crashes, and it turns out to be impossible for me to even insert any config.

**Comment by iraizo** [comment]
Wheres the crashlog?

**Comment by davielachesis** [comment]
Where can I find the crashlog file? Is it contained in the crashreport, or another directory of the software files?

**Comment by STG7754** [comment]
/tmp/

**Comment by davielachesis** [comment]
[cathook-dicks-1789.log](https://github.com/nullworks/cathook/files/8256818/cathook-dicks-1789.log)
[cathook-dicks-1789-segfault.log](https://github.com/nullworks/cathook/files/8256819/cathook-dicks-1789-segfault.log)
[cathook-dicks-3898.log](https://github.com/nullworks/cathook/files/8256820/cathook-dicks-3898.log)
[cathook-dicks-3898-segfault.log](https://github.com/nullworks/cathook/files/8256821/cathook-dicks-3898-segfault.log)

Here they are.
I've talked to a friend of mine, and he told me it seems to be a problem involving Manjaro Linux as a whole, since he can't even use cathook in his machine with the same OS that I have. that being the reason of such problems. 
Is there any explanation over that?

**Comment by mikasathecloset** [comment]
clean installation manjaro 21.2.5

[cathook-mik-9159.log](https://github.com/nullworks/cathook/files/8258492/cathook-mik-9159.log)

[cathook-mik-9159-segfault.log](https://github.com/nullworks/cathook/files/8258493/cathook-mik-9159-segfault.log)

**Comment by patioprimate** [comment]
> 

I'm on arch and have the same issue.

**Comment by nopalfi** [comment]
Same, I'm on Arch, and it also crashed after a few seconds the script work.
I tried everything like change to run in window or changing the graphic setting but it still crash, and in log file it didn't say something error.
A few months ago it worked.

**Comment by BenCat07** [comment]
fixed now
