### ISSUE TITLE
Does the old item schema modification glitch work?

### ISSUE THREAD

**Issue by hellidox** [nullworks/cathook#1609]
**Quick Description**

Context: https://wiki.teamfortress.com/wiki/October_15,_2014_Patch

**My Suggestion for Developers**
If you can edit the item schema in memory, what stops you from blocking connection to item servers and, say, making a key out of a name tag?

**Comment by hellidox** [comment]
The way the old glitch worked is you would block the item servers, IIRC.

**Comment by BenCat07** [comment]
those same item servers process your requests, it's not client-sided
