### ISSUE TITLE
ipc bots dont open in textmode.

### ISSUE THREAD

**Issue by ofashy** [nullworks/cathook#1611]
## System Information
**OS:**  manjaro 21.2.0 xcfe
**Cathook Version:**  
latest one

## Description  
bots dont properly load and always forget to load in textmode.

## Steps to reproduce  
start up a bot

1. Enable X
2. Do Y
3. Notice Z

**Comment by STG7754** [comment]
Manjaro Lastest Version making cathook broken

you need to use Old version of Manjaro or wait to fix

**Comment by ofashy** [comment]
> Manjaro Lastest Version making cathook broken
> 
> you need to use Old version of Manjaro or wait to fix

any good versions?

**Comment by STG7754** [comment]
yes dont use lastest version 

but if you go away use lastest version Disable Nullnexus type in console `cat set nullnexus.enable false`

**Comment by ofashy** [comment]
im using a different version and disabled nullnexus, it still doesn't open it

**Comment by STG7754** [comment]
AS well idk to fix that.

**Comment by yelnyaface** [comment]
so, no fix I guess? not even `older` version of Manjaro actually fix anything

**Comment by STG7754** [comment]
idk. bro i cant fix that is now after i updating System to lastest version just chrash on inject

**Comment by yelnyaface** [comment]
@ofashy

goto `Desktop/catbot-setup/cathook/` folder, and open `terminal`, type `./config`

`update channel > Developer ( possible git issues... etc ) > save`

 goto `Desktop/catbot-setup/cathook/src/core/sharedobj.cpp`

find the line:
```
while (!(lmap = (link_map *) dlopen(path.c_str(), RTLD_NOLOAD)))
```

replace it with:
```
while (!(lmap = (link_map *) dlopen(path.c_str(), RTLD_LAZY | RTLD_NOLOAD)))
```

save file.

goto `Desktop/catbot-setup/` folder > open `terminal` > type `./update`

run `./start`, have fun
