### ISSUE TITLE
I have followed about five different installation guides and none of them work.

### ISSUE THREAD

**Issue by Master1Rabbit** [nullworks/cathook#1612]
Here is a print screen moments before I raged and quit trying.

I have managed to use your appimage to attach the hook into TF2, but I am having troubles with getting the menu to pop up pressing 'INSERT'. Trying to attach the hook through the terminal executable which came with the github clone leaves me with this message
![Screenshot_2022-03-19_05-18-55](https://user-images.githubusercontent.com/78775899/159070147-7628d3c8-72b4-415b-895f-7942175a42ce.png)

Please make this process easier so I can keep my hairline for longer.

OS: Artix Linux x86_64

**Comment by inthecatsdreams** [comment]
i'm having the same error as you on Vanilla Arch with XFCE. It happens when I want to attach to TF2, then the game crashes.
![pic-selected-220319-0701-06](https://user-images.githubusercontent.com/68013505/159109413-f26182ec-c67c-4b16-9463-8976d40b8929.png)
