### ISSUE TITLE
Add Custom Achievements

### ISSUE THREAD

**Issue by Auditormadness9** [nullworks/cathook#1623]
**Quick Description**

Add custom achievements either made by users or by AI into Cathook which will make it more fun and rewarding to play the game and actually grind for something.

Examples: 
(All Class) RED Alert: Win a Payload Round without leaving the cart at all.
(Engi) Engines Ready: Build a Level 3 Sentry, Dispenser, and Teleporter before setup phase ends.
(Pyro) Of all Trades: In one Airblast, Reflect an Rocket, Grenade, and another Projectile.

**The Issue**

No issue, just that I came up with the idea of custom achievements when I realized they actually add up to the fun and challengeness of the game and actually give you more "objectives" you can say to complete which gives you a reason to grind in the game rather than braindeadedly requeue and play the same thing multiple times.

**My Suggestion for Developers**

I'm very glad to give advice! Simply take a look at the comments of [this thread](https://www.reddit.com/r/tf2/comments/2ii22j/make_up_your_own_tf2_achievements/), or use [this](https://www.reddit.com/r/tf2/comments/opgfqg/heres_a_small_list_of_custom_tf2_achievements_ive/) thread as inspiration or source. I even managed to copy all of those comments and the entire list of the latter thread into an AI text generator and managed to create a few new ones from AI:

**The Old Man**: _Block a Rocket with your teammate._
**Drop The Dead Donkey**: _Survive a round with your whole team._
**Metalize the city**: _Kill your teammates._ (lmfao)
**Escape The Gap**: _Earn 5000 points in 5 minutes or less._ (lol good luck with that)
**The Pause That Refreshes**: _Kill three or more enemy players with a single shot from the sniper._
**Hollywood-Sized Explosions**: _Deal damage to 12 enemies with an explosion._
**One Tzu**: _Win an entire match without ever healing or dying._
**Gypsy Crusader**: _Dominate an enemy with all the four kills being done with their own weapon they dropped._

**Additional Context**

All of that would be fun af, but thought that sadly other than Valve nobody can keep count of this and you have to do it manually, which is kinda lame, but then I remembered that Cathook can hook a lotta stuff and modify/read crap from the game so I thought it definitely can hook this and properly create custom achievements and I believe it can be done solely clientside and no serverside access is needed, correct if wrong of course.

In the future when this sees the light, we can make a thread where you can suggest/add new custom achievements, or we could simply make our own.

Thanks in advance!

**Comment by Lesshy** [comment]
no cathook is not made for fun

**Comment by Auditormadness9** [comment]
> no cathook is not made for fun

What is it made for then?

**Comment by iraizo** [comment]
I will close this for now since I think most people are not interested in this.
