### ISSUE TITLE
How can I replicate GetEngineSignature outside of cathook?

### ISSUE THREAD

**Issue by Footsiefat** [nullworks/cathook#1624]
I want to be able to use `gSignatures.GetEngineSignature("...")` to locate variables in tf2 I cannot get anywhere else but when I use the provided memory signatures they don't return any addresses in `gdb find`.

When I load the variable in memory (I modified cathook to debug the memory location to chat as a hacky temp way of doing it) I cannot see anything in that memory area that matchs the signature like `"A3 ? ? ? ? A1 ? ? ? ? 8B 10 89 04 24 FF 52 ? 83 C4 2C"`

So my question is, how does that function use the signature and how can I replicate that memory search externally?

**Comment by Footsiefat** [comment]
Memory signature: `"A3 ? ? ? ? A1 ? ? ? ? 8B 10 89 04 24 FF 52 ? 83 C4 2C"`

![Screenshot_20220518_164730](https://user-images.githubusercontent.com/12180913/168959327-0bb47f09-e8e6-400d-91e6-30972f2fac90.png)
![image](https://user-images.githubusercontent.com/12180913/168959373-93de98f9-7716-439a-99da-228ed6c4f1e7.png)

**Comment by BenCat07** [comment]
Well that is simply not the address then

**Comment by Footsiefat** [comment]
Well yea but even when I debug that core address it still doesn't match the pattern for some reason when I look it up in the memory dump

```
    uint32_t sig_addr           = gSignatures.GetEngineSignature("A3 ? ? ? ? A1 ? ? ? ? 8B 10 89 04 24 FF 52 ? 83 C4 2C");
    static int *gHostSpawnCount = *reinterpret_cast<int **>(sig_addr + sizeof(char));
    PrintChat("[DEBUG]: %p", (void *) &gHostSpawnCount);
    PrintChat("[DEBUG]: %p", (void *) &sig_addr);
    PrintChat("[DEBUG]: %d", gHostSpawnCount);
```
![Screenshot_20220519_102329](https://user-images.githubusercontent.com/12180913/169165446-97a1c6d6-6fc2-448f-accc-81c0042060dc.png)
![image](https://user-images.githubusercontent.com/12180913/169165501-0d805015-fc97-424a-b865-6b9448bbf99c.png)

So could you potentially tell me what im doing wrong please? Especially since I can't find that memory pattern with gdb(within engine.so in the memory map), I'm not sure what im doing wrong.

@BenCat07

**Comment by BenCat07** [comment]
you are not printing the address, you are printing the address to the address

**Comment by BenCat07** [comment]
&gHostSpawnCount -> pointer to pointer to host spawn count
&sig_addr -> pointer to pointer to signature

**Comment by BenCat07** [comment]
Simply use %p with sig_addr and gHostSpawnCount

**Comment by Footsiefat** [comment]
![Screenshot_20220522_232311](https://user-images.githubusercontent.com/12180913/169692791-3e886d58-2edb-4ffe-b2e7-b168695db8bb.png)
Holy shit ur right man, tysm. Also I have one other question @BenCat07 if thats alright. 

`0xe3a9f000 0xe3f83000   0x4e4000   0x315000  r-xp   /home/james@nsa.gov/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so`

I only need to search within the engine.so mappings don't I?

**Comment by BenCat07** [comment]
For GetEngnineSignature, Yes. Also, note that cathook loads engine.so and client.so into memory a second time, the part where there are ALOT of sections for engine.so/client.so is the one of the game originally.

**Comment by Footsiefat** [comment]
Thank you very much, and noted.
