### ISSUE TITLE
Crash Report -- Lenovo 81YE V15-IWL laptop -- Made for lithi

### ISSUE THREAD

**Issue by DrFluffery** [nullworks/cathook#1626]
## bug report made for lithi000
Arch Linux 
xfce4
Latest

## Config used
[rage.conf.log](https://github.com/nullworks/cathook/files/8747989/rage.conf.log)

## Logs / Crash Report  
[cathook-lithi-2081.log](https://github.com/nullworks/cathook/files/8747990/cathook-lithi-2081.

- I am able to consistently reproduce this error
autoshoot on mouse9 
put it on head, no multipoint, and auto
crashes

## Additional context 
happens on a 81YE Lenovo V15-IWL laptop issue was not reported on an alternative laptop

contact @Lithi000 on telegram

**Comment by BenCat07** [comment]
Crash report linked is invalid

**Comment by DrFluffery** [comment]
[cathook-lithi-2081.log](https://github.com/nullworks/cathook/files/8748004/cathook-lithi-2081.log)
try that if not i will send it to you on telegram

**Comment by AsE710** [comment]
what a mouse9?

**Comment by DrFluffery** [comment]
Mouse5 for cathook

**Comment by DrFluffery** [comment]
@BenCat07 any reason why this may be happening?

**Comment by BenCat07** [comment]
well i have no crash log, only a standard cathook log, i do not have any info whatsoever to work with

**Comment by DrFluffery** [comment]
i dont have the crash log as it isnt mine so yea just going to close this for now
