### ISSUE TITLE
This Software Should Be Deleted

### ISSUE THREAD

**Issue by Zack-Green** [nullworks/cathook#1629]
This Is The Reason The TF2 Bots Are Everywhere

Please Stop Giving Away This Software And Help #SaveTF2

You Are Supporting Bots And Making The Game Unplayable

**Comment by DrFluffery** [comment]
I am not a project admin but, please close this issue and don't make issue's that waste our time

**Comment by hellidox** [comment]
i like using anti aim while taunting and having unlimited backpack slots, am i the scourge of tf2?

**Comment by Zack-Green** [comment]
You Should Be Ashamed 
You Are Ruining TF2

**Comment by DrFluffery** [comment]
I asked nicely and your saying I should be ashamed?
Your just saying I am ruining TF2? What did I do? Help with github issues? Look towards actual common cheats, not many bots and players use CatHook now
While yes, I understand your frustration but what can we do if bots don't even use the project in 2922?

**Comment by ann4belle** [comment]
@DrFluffery yes, you should be ashamed. There is no legitimate use for this, it's cheating in a pvp multiplayer game. You ruin the experience for everyone when you use this, and even if you *don't* use it, you're enabling those who do by helping to develop it. You can try and justify it all you want, but at the end of the day you know this is true.

**Comment by hellidox** [comment]
> You Should Be Ashamed You Are Ruining TF2

you're cringe hvh is fun try it
