### ISSUE TITLE
Textmode are broke after TF2 update

### ISSUE THREAD

**Issue by AsE710** [nullworks/cathook#1633]
## System Information
**OS : Manjaro**  
**DE : xcfe**  
**Cathook Version : Lastest [i test of my private fork]**  

## Config used
about default bots

## Logs / Crash Report  
[Injecting log](https://github.com/nullworks/cathook/files/8956923/cathook-etc-262.log)
[Crash log](https://github.com/nullworks/cathook/files/8956985/cathook-etc-603-segfault.log)

## Description  
As well inject Normally on User mode not crashing
but on Textmode have not Running just keep crash on waiting after TF2 update

Edit : at preload btw

## Steps to reproduce  
1. Update on my fork
2. Start the bots
3. my bots keep waiting a long time. 

## Checklist  
- [yes] I have included my DE, WM, and version of Cathook.
- [yes] I have included the steps to reproduce and my logs to the best I am able to share.
- [no] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need it. (Put your username here)

**Comment by AsE710** [comment]
idk. how about check Debug on Textmode.

**Comment by AsE710** [comment]
i will close because fixed

**Comment by BenCat07** [comment]
The pr fixed one issue, there may be more

**Comment by Lesshy** [comment]
its an issue with #if ENABLE_TEXTMODE only idk what but its also probably a signature there aswell

**Comment by Lesshy** [comment]
lol its sad many people are as impatient as they are

**Comment by BenCat07** [comment]
Should be fixed, tell me if anything else pops up

**Comment by AsE710** [comment]
this is fine alright thats fixed i will need close a issue because are now not a my time.
