### ISSUE TITLE
cathook crashes on inject

### ISSUE THREAD

**Issue by hellidox** [nullworks/cathook#1634]
## System Information
**OS: Ubuntu 20.04 LTS**  
**DE: Gnome 3.36.8 w/ x11**  
**Cathook Version: latest dev**  

## Config used

Crashes on inject, no config
## Logs / Crash Report  

[cathook-atrius-144109.log](https://github.com/nullworks/cathook/files/8971139/cathook-atrius-144109.log)
[cathook-atrius-144109-segfault.log](https://github.com/nullworks/cathook/files/8971140/cathook-atrius-144109-segfault.log)

## Description  

crashes on inject
## Steps to reproduce  
- [ ] I am able to consistently reproduce this error

inject

## Checklist  
- [X] I have included my DE, WM, and version of Cathook.
- [X] I have included the steps to reproduce and my logs to the best I am able to share.
- [ ] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need it. (Put your username here)

**Comment by Grimgob** [comment]
What you get for cheating pussy
ripbozo

**Comment by RedFire512** [comment]
the fact that you use cathook is just said

just play the game lol

**Comment by obbyfus** [comment]
lets hope it stays that way lmao

**Comment by darkst0rm223** [comment]
> the fact that you use cathook is just said
> 
> just play the game lol

get good get lmaobox :troll:

**Comment by darkst0rm223** [comment]
> What you get for cheating pussy ripbozo

i have you're ip address + i live in you're walls

**Comment by womblee** [comment]
> lets hope it stays that way lmao

legit salt

**Comment by womblee** [comment]
> the fact that you use cathook is just said
> 
> just play the game lol

it's just a game

**Comment by Dashie17** [comment]
Damn that explains why my three can't run anymore rn

**Comment by Taureon** [comment]
> > the fact that you use cathook is just said
> > just play the game lol
> 
> it's just a game

games can't be fun in their intended way if cheaters exist, you know?
i think cheaters are forgetting the reason games exist, which is sad...

**Comment by StuckInThePast** [comment]
Its fun to see stupid ppl like you who wear rose colored glasses and delude yourself into thinking that Valve will suddenly start caring about TF2 all of a sudden when they haven't for 3 years.

**Comment by aUniqueUser** [comment]
fixed with https://github.com/nullworks/cathook/pull/1641
