### ISSUE TITLE
you guys are not very xqcL

### ISSUE THREAD

**Issue by badoge** [nullworks/cathook#1635]
admin how to delet this repo its not very xqcL :'(
![3](https://user-images.githubusercontent.com/18620902/175422307-4367f62f-7e57-4f61-a5a9-abc00fc86655.png)

**Comment by StuckInThePast** [comment]
@badoge you need some cream for that butthurt?  https://i.etsystatic.com/6864396/r/il/777bb8/1065972535/il_300x300.1065972535_pm6n.jpg

**Comment by badoge** [comment]
@StuckInThePast nyoo dont say that thats not very xqcL 😭 
![PEKLVGs](https://user-images.githubusercontent.com/18620902/175423297-9c8007bd-df89-4f70-882f-07b749c7a458.png)

**Comment by StuckInThePast** [comment]
@badoge  Cry more! This is the internet nerd. Get thicker skin

**Comment by badoge** [comment]
github pls ban this guy @StuckInThePast 😭saying not xqcL things to me

**Comment by StuckInThePast** [comment]
Does the baby need a bottle or a tissue?

**Comment by Fijxu** [comment]
Put me in the screencap
![1654723466433](https://user-images.githubusercontent.com/61166695/175424934-77fbc476-a656-4784-891f-c83ab2317428.gif)

![image](https://user-images.githubusercontent.com/61166695/175424898-c9fb9b64-c9e5-40bd-b9cf-1c9d22b669ab.png)

**Comment by d3fc0n6** [comment]
![photo_2022-06-22_01-43-52](https://user-images.githubusercontent.com/73117766/175424996-3b6d8e33-beaf-467a-83d1-1fc4a63c4a8e.jpg)

**Comment by AsE710** [comment]
wdym by that?

**Comment by d3fc0n6** [comment]
joe mama
