### ISSUE TITLE
Crash on inject after TF2 Lastest update [again AND STOP HARASSMENT ME]

### ISSUE THREAD

**Issue by AsE710** [nullworks/cathook#1636]
## System Information
**OS : Manjaro**  
**DE : XCFE**  
**Cathook Version : Lastest Version inject on debug mode**  

## Config used
about same default bots

## Logs / Crash Report  
[cathook-etc-2450.log](https://github.com/nullworks/cathook/files/8971807/cathook-etc-2450.log)
[cathook-etc-2450-segfault.log](https://github.com/nullworks/cathook/files/8971808/cathook-etc-2450-segfault.log)

## Description  
after inject on the cathook after lastest TF2 update game crashed again.

## Steps to reproduce  
Normally injecting

## Checklist  
- [yes] I have included my DE, WM, and version of Cathook.
- [yes] I have included the steps to reproduce and my logs to the best I am able to share.
- [no] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need it. (Put your username here)

**Comment by AsE710** [comment]
yesterday of update not crashing but this update make cathook right now crash.

**Comment by Glonko8** [comment]
yeah you deserve it for being a dick and cheating

**Comment by Yushe** [comment]
cope

**Comment by KingKrouch** [comment]
Cope, Seethe, Mald, Morb

**Comment by d3fc0n6** [comment]
> Cope, Seethe, Mald, Morb

its ur mom time

**Comment by lnx00** [comment]
Where are all these funny trolls coming from?

**Comment by RedFire512** [comment]
get a life maybe instead of trying to bot tf2 matches 

oh wait sorry you're a nuisance to society

**Comment by obbyfus** [comment]
death to cathook! death to cathook! death to cathook! 

may all traces of cathook be eliminated permanently

**Comment by Idontcodeeither** [comment]
suck a fat dick bot hosters

**Comment by ayesc9000** [comment]
lol. lmao.

seeing these bug reports puts a smile on my face :)

**Comment by womblee** [comment]
so many salty legits in issues, it's just a game

**Comment by womblee** [comment]
> yeah you deserve it for being a dick and cheating

you sound like this fully ruined everything, typical 1-2 day fix

**Comment by Idontcodeeither** [comment]
> so many salty legits in issues, it's just a game

considering I've had shittons of issues concerning bots for the past year I definitely would be a bit salty

**Comment by knownforit** [comment]
> so many salty legits in issues, it's just a game

going under every thread and crying about "salty people" makes you seem like the much more saltier one tbh. cope and seethe :)

**Comment by AsE710** [comment]
what the fuck this happening?

**Comment by AsE710** [comment]
ALRIGHT STOP A FUCKING HARASSMENT AT TO ME ALL OF DEEP SHIT

I WILL NEED TO STOP HOSTING A MOMENTS AND KYS OF LEGIT PLAYER

**Comment by AsE710** [comment]
> suck a fat dick bot hosters

nice type faggots

**Comment by womblee** [comment]
> > so many salty legits in issues, it's just a game
> 
> going under every thread and crying about "salty people" makes you seem like the much more saltier one tbh. cope and seethe :)

Especially when you guys register new accounts to dump some salt 😝

**Comment by AsE710** [comment]
TIME TO ASK WHY I HOST THE BOTS NOW IF YOU DONT KNOW 

1.No Major Update 
i have a oldest legit player before hosting bots 
5 year for no biggest of the update I've been waiting for a long time. Finally, I can't stand it. So I come to Host bots on 2020-2021

2.Tryhard player , Toxic player and Harass
i really bored at playing TF2 on about Tarhard , Toxic and Harassment a LOT 
Throughout the game I've encountered Tryhard players and I can't fight because they're too good.
Having accumulated resentment for a long time, I decided to Host bots to express my feelings.

3.For fun
VAC are still shit

Thanks you and fuck off legit

**Comment by AsE710** [comment]
If possible, I want this comment to be a useful comment for everyone.

And it's a hidden reason since last year.

**Comment by AsE710** [comment]
I don't want to hear legit bastards scolding me because I'm pretty busy in real life right now.

If anyone is a Cheater together, don't curse and harass with me. I want privacy as much as possible.

**Comment by StuckInThePast** [comment]
All you crybaby losers need to accept the fact that Valve only cares about the money and move on and find a new game that cares  about its users and releases updates for new content.

**Comment by StuckInThePast** [comment]
What are you doing besides making fake bug reports on github?
