### ISSUE TITLE
YOU STOLE FIRE FROM THE GODS AND NOW YOU PAY

### ISSUE THREAD

**Issue by sirattano** [nullworks/cathook#1637]
**Quick Description**

 I'd like you to take this page down. You have caused so much torment to this community
that it seriously baffles me to imagine that you have a normal, or at least, typical life. 

Example: I would like to suggest white-hat hacking. A person with such talent at breaking a system and screwing around with this kind of coding magic seriously ought to apply for a legit job or at least an apprenticeship in security, coding, programming, anything that works in computer science, really. In your penchant for causing misery, there exists the potential for a great career. 

**The Issue**

 I cannot imagine a productive human being running this account. You are hatred. You are replaceable. You are one out of a million like you that have died before you, and finally, FINALLY, your time has come.
How does it feel? How does it feel to finally have your empire crumble like soggy bread balanced on an egg? Do you feel satisfied? Will you take the fall with grace? Are you dedicating yourself to reviving your work to bring back the pain and torment? Are you even listening to me right now? 

Example: Nothing beside remains. As I laugh at his downfall, I can't help but feel at least a little sympathy for King Ozymandias. It feels like walking out of a hospital for the first time in weeks: unaccustomed to the outside world, but at the same time, the memories of glory and riches past all come flooding back in the wake of your captors. But then, if noone is there to look on the works of a king and despair, did the king ever really exist?

**My Suggestion for Developers**

 Save as much face as you can. I foresee you getting doxxed in the near future. That's never okay, even against someone like you. You don't have any excuses, so please don't try to make them. The word you are looking for is **humble.** You will take your punishment, in whatever form it will come in, you will accept cathook as part of your legacy, and you will have to live with the experience, knowledge, and memories made over the past few years. 

Example: Not everyone is so lucky. At the very least, you get to go home. Lucky you. 

**Additional Context**

 I want to see you succeed in life. Like so many talented artists on Deviantart pouring away so many hours and years simultaneously showcasing their talent and skill as well as their severely altered minds, I look at cathook, and I think, "wooooooow. i really want them to make it big after they do something for real." The humiliation will never fade. You will always be "the cathook guy". All I can hope for is that you find a place of employment that can look past that fact, and hire genuine talent, instead of "the cathook guy." I can't believe that I'm telling *you* this, but I have big hopes for your future.
You have talent. All of us just want to see it somewhere else. 

Example: 

When I'm shot through heart and head,
And there's no choice but to die,
The last word I'll hear, no doubt,
Won't be "Charge!" or "Sentry down!"
Nor the Kritzkrieg-pocket's cry,
"Let that body be, he's dead!"
But a voice cruel and flat
Saying for ever, "Good shot mate!... Good shot mate!... Good shot mate!..."

**Comment by darkst0rm223** [comment]
> **Quick Description**
> 
> **The Issue**
> 
> **My Suggestion for Developers**
> 
> **Additional Context**

bruh its just an game

**Comment by sirattano** [comment]
Quick Description

 I'd like you to take this page down. You have caused so much torment to this community
that it seriously baffles me to imagine that you have a normal, or at least, typical life. 

Example: I would like to suggest white-hat hacking. A person with such talent at breaking a system and screwing around with this kind of coding magic seriously ought to apply for a legit job or at least an apprenticeship in security, coding, programming, anything that works in computer science, really. In your penchant for causing misery, there exists the potential for a great career. 



**The Issue**

 I cannot imagine a productive human being running this account. You are hatred. You are replaceable. You are one out of a million like you that have died before you, and finally, FINALLY, your time has come.
How does it feel? How does it feel to finally have your empire crumble like soggy bread balanced on an egg? Do you feel satisfied? Will you take the fall with grace? Are you dedicating yourself to reviving your work to bring back the pain and torment? Are you even listening to me right now? 

Example: Nothing beside remains. As I laugh at his downfall, I can't help but feel at least a little sympathy for King Ozymandias. It feels like walking out of a hospital for the first time in weeks: unaccustomed to the outside world, but at the same time, the memories of glory and riches past all come flooding back in the wake of your captors. But then, if noone is there to look on the works of a king and despair, did the king ever really exist?



**My Suggestion for Developers**

 Save as much face as you can. I foresee you getting doxxed in the near future. That's never okay, even against someone like you. You don't have any excuses, so please don't try to make them. The word you are looking for is **humble.** You will take your punishment, in whatever form it will come in, you will accept cathook as part of your legacy, and you will have to live with the experience, knowledge, and memories made over the past few years. 





**Additional Context**

 I want to see you succeed in life. Like so many talented artists on Deviantart pouring away so many hours and years simultaneously showcasing their talent and skill as well as their severely altered minds, I look at cathook, and I think, "wooooooow. i really want them to make it big after they do something for real." The humiliation will never fade. You will always be "the cathook guy". All I can hope for is that you find a place of employment that can look past that fact, and hire genuine talent, instead of "the cathook guy." I can't believe that I'm telling *you* this, but I have big hopes for your future.
You have talent. All of us just want to see it somewhere else. 

 Example: 


When I'm shot through heart and head,
And there's no choice but to die,
The last word I'll hear, no doubt,
Won't be "Charge!" or "Sentry down!"
Nor the Kritzkrieg-pocket's cry,
"Let that body be, he's dead!"
But a voice cruel and flat
Saying for ever, "Good shot mate!... Good shot mate!... Good shot mate!..."

**Comment by sirattano** [comment]
> > **Quick Description**
> > **The Issue**
> > **My Suggestion for Developers**
> > **Additional Context**
> 
> bruh its just an game
bruh its just necromsis

**Comment by darkst0rm223** [comment]
> > > **Quick Description**
> > > **The Issue**
> > > **My Suggestion for Developers**
> > > **Additional Context**
> > 
> > 
> > bruh its just an game
> 
> bruh its just necromsis

wtf is an necromsis

**Comment by womblee** [comment]
salt

**Comment by pp0236** [comment]
why there is a lot of legit ppl making issue

**Comment by sirattano** [comment]
> why there is a lot of legit ppl making issue

because it's funny

**Comment by pp0236** [comment]
> > why there is a lot of legit ppl making issue
> 
> because it's funny

funni br
