### ISSUE TITLE
cathook crash upon realizing y'all are fat

### ISSUE THREAD

**Issue by moderntroll** [nullworks/cathook#1638]
## System Information
**OS:**  Joemama 4.20 LTS
**DE:**  Generic Gay Tool 0.69
**Cathook Version:**  oh the misery

## Config used
Cope

## Logs / Crash Report  
[cathook-atrius-144109.log](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
[cathook-atrius-144109-segfault.log](https://www.youtube.com/watch?v=Rhe5D6sRwzo)

## Description  
I injected and she crashed loud afff

## Steps to reproduce  
- [x] You expected another sex joke but you get no bitches

1. Absolutely no bitches

## Additional context 
ah yes, there's another thing: you're ugly

## Checklist  
- [x] TF2 Lives on
- [x] This is the end for you
- [ ] Get rekt

**Comment by womblee** [comment]
mad?

**Comment by sirattano** [comment]
Not bad m8

**Comment by snipergaming888** [comment]
> mad?

Imagine making hacks for a fossil game
