### ISSUE TITLE
CaN yOu NoT fIlL tHe IsSuEs WiTh RaNdoM cRaP

### ISSUE THREAD

**Issue by sirattano** [nullworks/cathook#1645]
Uh, no.

https://youtu.be/NNgpBbZGZnk
https://youtu.be/0teMbkFS2c8
https://youtu.be/hpounLPaBVI

**Comment by sirattano** [comment]
![AEE385B8-ADFE-4668-876F-C906B9C524FD](https://user-images.githubusercontent.com/82298734/175471961-6f66889b-3cd5-442d-8c9f-82147ca8a207.png)
![15AC53A0-22D2-4FFE-A6C7-0953328BFED4](https://user-images.githubusercontent.com/82298734/175471962-b8e5b9fb-0469-4b2a-b644-bac008d69ff2.jpeg)
![D21132F5-574E-4AFB-B00D-EFC79BDF0C24](https://user-images.githubusercontent.com/82298734/175471964-249015b1-bd95-4f71-9f1d-4f7b528579b0.png)
![9828EA32-76B2-48A5-A7DD-CBFE4216F19D](https://user-images.githubusercontent.com/82298734/175471966-ffe3bdc1-48e6-4b1b-903f-9e3c769025d7.png)
![0B9FBBDE-70EB-417A-9C29-CF048064BB86](https://user-images.githubusercontent.com/82298734/175471967-9f858da4-a600-4d00-9f1c-1c0c21123946.jpeg)
![FB5CA5D1-B471-42A5-B187-A8C940A14426](https://user-images.githubusercontent.com/82298734/175471968-9731592a-fa15-4d1e-aeb2-fa28bfb68a01.jpeg)

**Comment by Pichulol** [comment]
lol and funny :DDD
