### ISSUE TITLE
ㄚ乇ㄒ 爪ㄖ尺乇 尺卂几ᗪㄖ爪 匚尺卂卩

### ISSUE THREAD

**Issue by sirattano** [nullworks/cathook#1647]
![19F176AB-73A8-425C-8235-BCB66FC9574A](https://user-images.githubusercontent.com/82298734/175473276-deeab410-a4f3-4323-ad0a-3d9a7bce1a08.jpeg)
![29FC4968-EF56-4624-8F54-17390E839370](https://user-images.githubusercontent.com/82298734/175473284-2f5942ab-5a2e-4b12-82de-503ce0bde8a2.jpeg)
![E295D963-AED0-4D6B-BF40-40A5B548AC54](https://user-images.githubusercontent.com/82298734/175473286-7eeb9486-5813-4d9d-8722-a644f551373a.jpeg)
![10C7EAB8-A3BB-42C2-8A50-7E481CE43E77](https://user-images.githubusercontent.com/82298734/175473290-b672f689-d196-4e8c-b6c0-0a79957dface.jpeg)
![B51546FD-6079-4571-880A-3A157E02A566](https://user-images.githubusercontent.com/82298734/175473304-52a55db4-9c56-4dc4-adb3-ed0bf5095cd6.jpeg)
![F01F6C49-A00B-4C89-9074-64A614B30DEB](https://user-images.githubusercontent.com/82298734/175473312-1995f80a-6803-43ad-bac9-629a9ff84626.jpeg)
![87B36D33-C866-4F09-AE43-A3808C322C9D](https://user-images.githubusercontent.com/82298734/175473314-b93b2e62-7298-4684-a7b2-8e4dd7f6bea9.jpeg)
![0F722017-F3A1-45D9-8102-2B3B3762D8E6](https://user-images.githubusercontent.com/82298734/175473315-b97d3479-092b-4d81-a5a3-5146c5083394.jpeg)

**Comment by aUniqueUser** [comment]
\nice chicken
