### ISSUE TITLE
Unable to compile due to CMakeLists.txt requiring an specific version of the boost library 

### ISSUE THREAD

**Issue by vbedesu** [nullworks/cathook#1649]
## System Information
**OS: Gentoo Linux Base System 2.8**  
**DE: None**
**WM: i3**  
**Cathook Version: Latest git commit from Jun 24, 2022, 5:38 AM GMT.**  

## Logs / Crash Report  

-- Could NOT find Boost (missing: Boost_INCLUDE_DIR) (Required is exact version "1.71.0")
-- Fetching Boost (and then it gets stuck on "fetching boost", forever)

## Description  
Unable to compile due to CMakeLists.txt requiring an specific version of the boost library. since I have a newer library release of boost it does not want to compile, I'm pretty sure this can be fixed by doing a few changes in CMakeLists.txt

## Steps to reproduce  
- [ yup ] I am able to consistently reproduce this error

Get on any bleeding edge linux distribution
Install the latest version of the boost developer library
Try to compile cathook

## Additional context 

A way to fix this is by tricking CMakeLists.txt into thinking you have a newer version of the boost library by doing a few changes on the CMakeLists.txt file and make it not explicitly specific to 1.17.0

## Checklist  
- [ yup ] I have included my DE, WM, and version of Cathook.
- [ yup ] I have included the steps to reproduce and my logs to the best I am able to share.
- [ nope ] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need it. (Put your username here)
I don't use the instant messaging platform named telegram.

**Comment by vbedesu** [comment]
You're right, my bad. all I had to do was wait. I just ctrl c'd like an idiot because it took like 20 seconds or so.

**Comment by sweaty-basement-dweller** [comment]
Try this to fix your life:

..... ▄▄ ▄▄
......▄▌▒▒▀▒▒▐▄
.... ▐▒▒▒▒▒▒▒▒▒▌
... ▐▒▒▒▒▒▒▒▒▒▒▒▌
....▐▒▒▒▒▒▒▒▒▒▒▒▌
....▐▀▄▄▄▄▄▄▄▄▄▀▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
...▄█▓░░░░░░░░░▓█▄
..▄▀░░░░░░░░░░░░░ ▀▄
.▐░░░░░░░▀▄▒▄▀░░░░░░▌
▐░░░░░░░▒▒▐▒▒░░░░░░░▌
▐▒░░░░░▒▒▒▐▒▒▒░░░░░▒▌
.▀▄▒▒▒▒▒▄▀▒▀▄▒▒▒▒▒▄▀
.. ▀▀▀▀▀ ▀▀▀▀▀
