### ISSUE TITLE
99 Problems

### ISSUE THREAD

**Issue by sweaty-basement-dweller** [nullworks/cathook#1654]
## System Information
**OS:**  Windows 10
**DE:** 
**Cathook Version:**  the latest one

## Logs / Crash Report  
Game crashes when I try to inject white liquid.

## Description  
It starts shaking very enthusiastically but no white fluid comes out.

Pic for proof:
...............…………………………._¸„„„„_
…………………….…………...„--~*'¯…….'\
………….…………………… („-~~--„¸_….,/ì'Ì
…….…………………….¸„-^"¯ : : : : :¸-¯"¯/'
……………………¸„„-^"¯ : : : : : : : '\¸„„,-"
**¯¯¯'^^~-„„„----~^*'"¯ : : : : : : : : : :¸-"
.:.:.:.:.„-^" : : : : : : : : : : : : : : : : :„-"
:.:.:.:.:.:.:.:.:.:.: : : : : : : : : : ¸„-^¯
.::.:.:.:.:.:.:.:. : : : : : : : ¸„„-^¯
:.' : : '\ : : : : : : : ;¸„„-~"
:.:.:: :"-„""***/*'ì¸'¯
:.': : : : :"-„ : : :"\
.:.:.: : : : :" : : : : \,
:.: : : : : : : : : : : : 'Ì
: : : : : : :, : : : : : :/
"-„_::::_„-*__„„~"

## Steps to reproduce  
Stroke up and down, multiple times, for a healthy erection.

1) grip girth with your strong hand
2) stroke up
3) stroke down
4) repeat steps 2 & 3 until desired outcum

## Additional context 
Touch grass

## Checklist  
- [ ] did it get hard?
- [ ] did it stay hard?
- [ ] did it eject the white fluid?

**Comment by aUniqueUser** [comment]
ur really boring
