### ISSUE TITLE
Cannot Crash Servers Because of the Dump

### ISSUE THREAD

**Issue by Basement-Dweller69** [nullworks/cathook#1681]
But you can crash Deez Nuts!

………………………………………._¸„„„„_
…………………….…………...„--~*'¯…….'\
………….…………………… („-~~--„¸_….,/ì'Ì
…….…………………….¸„-^"¯ : : : : :¸-¯"¯/'
……………………¸„„-^"¯ : : : : : : : '\¸„„,-"
**¯¯¯'^^~-„„„----~^*'"¯ : : : : : : : : : :¸-"
.:.:.:.:.„-^" : : : : : : : : : : : : : : : : :„-"
:.:.:.:.:.:.:.:.:.:.: : : : : : : : : : ¸„-^¯
.::.:.:.:.:.:.:.:. : : : : : : : ¸„„-^¯
:.' : : '\ : : : : : : : ;¸„„-~"
:.:.:: :"-„""***/*'ì¸'¯
:.': : : : :"-„ : : :"\
.:.:.: : : : :" : : : : \,
:.: : : : : : : : : : : : 'Ì
: : : : : : :, : : : : : :/
"-„_::::_„-*__„„~"

**Comment by tobac123** [comment]
![image](https://user-images.githubusercontent.com/71644433/177891608-bdf32bcf-7b83-454a-aa28-cfe53fd352a6.png)

**Comment by iraizo** [comment]
your name perfectly represents your behaviour
