### ISSUE TITLE
Imagine spending hours and hours of your time developing cheats and being a loser...

### ISSUE THREAD

**Issue by Basement-Dweller69** [nullworks/cathook#1682]
And now you have no legacy....

Suck my balls!

　　　　　　　　　　▄█▀█▀█▄
　　　　　　　　▄█▀　　█　　▀█▄
　　　　　　　▄█▀　　　　　　　▀█▄
　　　　　　　█　　　　　　　　　　　█
　　　　　　　█　　　　　　　　　　　█
　　　　　　　▀█▄▄　　█　　　▄█▀
　　　　　　　　　█　　▄▀▄　　█
　　　　　　　　　█　▀　　　▀　█
　　　　　　　　　█　　　　　　　█
　　　　　　　　　█　　　　　　　█
　　　　　　　　　█　　　　 　　 █
　　　　　　　　　█　　　　　　　█
　　　　　　　　　█　　　　　　　█
　　　▄█▀▀█▄█　　　　　　　█▄█▀█▄
　▄█▀▀　　　　▀　　　　　　　　　　　　▀▀█
█▀　　　　　　　　　　　　　　　　　　　　　　▀█
█　　　　　　　　　　　　　　　　　　　　　　　　█
█　　　　　　　　　　　▄█▄　　　　　　　　　　█
▀█　　　　　　　　　█▀　▀█　　　　　　　　█▀
　▀█▄　　　　　　█▀　　　▀█　　　　　▄█▀
　　　▀█▄▄▄█▀　　　　　　▀█▄▄▄█▀

**Comment by iraizo** [comment]
What legacy lol
