### ISSUE TITLE
Yet another broken signature

### ISSUE THREAD

**Issue by BlueSnoopT** [nullworks/cathook#1694]
In BulletTracers.cpp in ADDR4 this signature [E8 ? ? ? ? 8D 85 ? ? ? ? 89 7C 24 0C 89 44 24 10] is the cause of the new crash.

idk how you guys find the signatures but there you go.

**Comment by BenCat07** [comment]
Sorry for the late note, working on it now.

**Comment by BenCat07** [comment]
c24d3cd488ca6f1e8125398f3bdb4f853cc51520
