### ISSUE TITLE
AppImage does not generate a "cathook" folder mentioned in the Wiki

### ISSUE THREAD

**Issue by hunter2k01** [nullworks/cathook#1707]
## System Information
**OS:**  Devuan Chimaera GNU/Linux
**DE:**  [Trinity](https://trinitydesktop.org/)
**Cathook Version:**  https://github.com/nullworks/cathook/commit/735b853c948d79307b00fed3adf8866f2da71d84

## Description  

I have just started using Cathook and the AppImage obtained in the Wiki page does not create a cathook folder next to the AppImage itself, which the Wiki mentions (so I assume it is needed). I also noticed that the GUI in videos such as [the following](https://www.youtube.com/watch?v=oziFCU38mOE) has an Install, Config, and Preload option. Mine can only attach. I read that a compatibility mode is enabled for non-Manjaro/Ubuntu distributions, could this be the culprit or do newer versions not have these options? Forgive me as I am new to Cathook and just now trying to learn how to set up bots.

## Steps to reproduce  
- [X] I am able to consistently reproduce this error

1. Use the AppImage on the aforementioned distribution
2. Notice it does not generate a folder.

## Checklist  
- [X] I have included my DE, WM, and version of Cathook.
- [X] I have included the steps to reproduce and my logs to the best I am able to share.
- [ ] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need it. (I use Matrix, not Telegram)

**Comment by Pichulol** [comment]
It could be the compatibility thing. One way i could think to fix this is to install it manually by doing "git clone https://github.com/nullworks/cathook.git" in terminal in the same directory then it should download and create a folder called cathook then you should be able to inject it. If that doesnt work you could also dual boot with manjaro with burning the iso on a usb or use unetbootin (https://unetbootin.github.io/linux_download.html) if you dont have a extra usb. just woke up so sorry if its hard to read

**Comment by BenCat07** [comment]
Only attach being presented means that you are in binary, and not in source mode. This can be changed in the top left corner, however, if you miss any of the dependencies, it will not compile.
Binary mode is only used when the Distro is not detected as supported, yours isn't.

AppImage sandboxing may also cause issues with attaching, but that depends on your Distro yet again.

**Comment by hunter2k01** [comment]
I ran into the following issue, even though I looked at scripts/dependencycheck and downloaded all the dependencies needed by Debian:

```
Auto Updater: Updating cathook in the background

Running instances: 19770
Attaching to 19770
cp: cannot stat 'bin/libcathook.so': No such file or directory
loading /tmp/.gl5fUIqt to 19770
[New LWP 19772]
[New LWP 19773]
[New LWP 19774]
[New LWP 19775]
[New LWP 19776]
[New LWP 19777]
[New LWP 19778]
[New LWP 19779]
[New LWP 19780]
[New LWP 19781]
[New LWP 19782]
[New LWP 19783]
[New LWP 19784]
[New LWP 19785]
[New LWP 19786]
[New LWP 19787]
[New LWP 19788]
[New LWP 19789]
[New LWP 19790]
[New LWP 19795]
[New LWP 19797]
[New LWP 19798]
[New LWP 19800]
[New LWP 19854]
[New LWP 19855]
[New LWP 19856]
[New LWP 19857]
[New LWP 19913]
[New LWP 19914]
[New LWP 19916]
[New LWP 19917]
[New LWP 19918]
[New LWP 19919]
[New LWP 19924]
[New LWP 19928]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0xf7e48fff in ?? () from /lib/i386-linux-gnu/libc.so.6
Calling dlopen
$1 = (void *) 0x0
Calling dlerror
$2 = 0x41a1eae0 "/tmp/.gl5fUIqt: cannot open shared object file: No such file or directory"
[Inferior 1 (process 19770) detached]
rm: cannot remove '/tmp/.gl5fUIqt': No such file or directory
```
The cloned cathook project is in the same directory as the AppImage.

**Comment by hunter2k01** [comment]
Ended up using chimaera-backports to get the newer CMake and everything builds fine. I will close this now.

**Comment by BenCat07** [comment]
Yes, cause is this distro not being supported
