### ISSUE TITLE
Automatically switches weapon to melee

### ISSUE THREAD

**Issue by 2poor2day** [nullworks/cathook#1710]
## System Information
**OS:**  Linux
**DE:**  
**Cathook Version:**  

## Description  
As soon as I spawn it locks weapon into melee

## Steps to reproduce  
Change class, locks to melee. Cannot change to primary or secondary 

Press comma to switch class, select a different class like 4 for demo, it will switch to my melee (in this case frying pan). Press comma again, press 6 for example for engineer, switches automatically to wrench.

## Additional context 
No

## Checklist  
- [ ] I have included my DE, WM, and version of Cathook.
- [ ] I have included the steps to reproduce and my logs to the best I am able to share.
- [ ] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need it. (Put your username here)

**Comment by hellidox** [comment]
send config
follow the checklist

**Comment by iraizo** [comment]
Closed due to inactivity
