### ISSUE TITLE
THERE ARE BOTS WITH THIS THAT INVADE CASUAL

### ISSUE THREAD

**Issue by Randomllyin** [nullworks/cathook#1719]
**Quick Description**

BOTS THAT USE THIS INVADE CASUAL AND HAVE THIS SITE IN THE SNIPER DESCRIPTION

**The Issue**

THERE ARE BOTS THAT KEEP INVADING CASUAL USING THIS

**My Suggestion for Developers**

TRY TO DO SOMETHING TO GET THE BOTS TO STOP

**Additional Context**

I found a hydro map with 4 bots on the enemy team all using this. also WHY ARE YOU MAKING A PUBLIC CHEAT ENGINE?!

**Comment by xxmyn** [comment]
I second this!

**Comment by iloev** [comment]
> **Quick Description**
> 
> BOTS THAT USE THIS INVADE CASUAL AND HAVE THIS SITE IN THE SNIPER DESCRIPTION
> 
> **The Issue**
> 
> THERE ARE BOTS THAT KEEP INVADING CASUAL USING THIS
> 
> **My Suggestion for Developers**
> 
> TRY TO DO SOMETHING TO GET THE BOTS TO STOP
> 
> **Additional Context**
> 
> I found a hydro map with 4 bots on the enemy team all using this. also WHY ARE YOU MAKING A PUBLIC CHEAT ENGINE?!

Wtf is going into your head man... the purpose of that public cheat is to destroy tf2 (obviously making it public and free)

**Comment by TheCrazyInsanity** [comment]
holy shit is this guy retarded

**Comment by D4ead3ye** [comment]
> **Quick Description**
> 
> BOTS THAT USE THIS INVADE CASUAL AND HAVE THIS SITE IN THE SNIPER DESCRIPTION
> 
> **The Issue**
> 
> THERE ARE BOTS THAT KEEP INVADING CASUAL USING THIS
> 
> **My Suggestion for Developers**
> 
> TRY TO DO SOMETHING TO GET THE BOTS TO STOP
> 
> **Additional Context**
> 
> I found a hydro map with 4 bots on the enemy team all using this. also WHY ARE YOU MAKING A PUBLIC CHEAT ENGINE?!

fcking desperate F2P XD
