### ISSUE TITLE
Cathook cannot inject.

### ISSUE THREAD

**Issue by haxnoob** [nullworks/cathook#1747]
## System Information
**OS: Arch Linux x86_64**  
**DE: Mate 1.26.0**  
**Cathook Version: Unknown (Most likely Latest version)**  

Hello, I can't inject Cathook for some reason, and I would like some help please.
Here's my Injection log, let me know if anyone can't access it for whatever reason.
I'll edit this issue report/post whenever I have more info or anything to show.
[Cathook Injection Log](https://github.com/nullworks/cathook/files/9690315/Cathook.Injection.Log)

## Steps to reproduce the bug/issue.
1. Open the Cathook GUI (AppImage)
2. Download the Cathook source code or whatever that the GUI downloads (If you haven't already)
3. Open TF2 and click on the Attach button then enter your User (or Root/Sudo) password.

**Comment by Glebux** [comment]
check if there's "cat" concommand

**Comment by haxnoob** [comment]
Sorry for the late reply, but yeah there is I think.
