### ISSUE TITLE
How do you fix this? This is the only issue I seem to be having while updating and attaching with cathook gui

### ISSUE THREAD

**Issue by Dashie17** [nullworks/cathook#1748]
“The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.”

**Comment by BenCat07** [comment]
not a bug, not an error
