### ISSUE TITLE
Well done for ruining TF2 for everyone, f*****g moon crickets geeks

### ISSUE THREAD

**Issue by Brxho** [nullworks/cathook#1749]
you guys should once, just ONCE. leave your house and witness sunlight, you pieces of shitheads, also doing all of this shit for free? how fucking low life can yall be? don't you have anything else to do with your lives besides hosting bots?

**Comment by kyappyy** [comment]
You fork random shit

Come back when you learn how to 'else if' and 'hello world'

**Comment by d3fc0n6** [comment]
> you guys should once, just ONCE. leave your house and witness sunlight, you pieces of shitheads, also doing all of this shit for free? how fucking low life can yall be? don't you have anything else to do with your lives besides hosting bots?

![halo](https://user-images.githubusercontent.com/73117766/193875990-f648c9d2-e27a-42bc-9abd-3c190e5bf69c.jpg)
