### ISSUE TITLE
kill yourselves

### ISSUE THREAD

**Issue by reg0lith** [nullworks/cathook#1767]
you assholes are ruining tf2. nobody likes you

**Comment by ToppHatty** [comment]
L

**Comment by joe20050108** [comment]
> you assholes are ruining tf2. nobody likes you

Ok?

**Comment by shrosterneduryden** [comment]
> you assholes are ruining tf2. nobody likes you
Uninstall brah.

**Comment by loipiop224** [comment]
> you assholes are ruining tf2. nobody likes you

If you don't like it, just uninstall the game  bro

**Comment by DoesHotter** [comment]
😂👌

**Comment by iloev** [comment]
> you assholes are ruining tf2. nobody likes you

😎 😎 😎 😎 😎 😎 yes i ruin tf2 😎 😎 😎 😎 😎 😎  im a cybercriminal, try to stop me fbi 😎 😎 😎 😎 😎 😎

**Comment by DoesHotter** [comment]
I will host boats to the police department. My boats will defend me.
