### ISSUE TITLE
Can you leave a pre-compiled library for Debian?

### ISSUE THREAD

**Issue by hecker2000** [nullworks/cathook#1769]
Can you leave a pre-compiled library for Debian?
I use kali Linux, and I seem to have Cmake issues.

**Comment by shrosterneduryden** [comment]
Cathook still busted I think. I went manjaro in order to run this :P  See also https://github.com/explowz/cathook ( but as of writing that's busted too )

**Comment by lnx00** [comment]
> [don't use kali dumbshit](https://www.kali.org/docs/introduction/should-i-use-kali-linux/)

But it's the cool hacker distro 😎

**Comment by hecker2000** [comment]
I actually got it compiled, it just took 2 hours
