### ISSUE TITLE
Cathook keeps failing to compile

### ISSUE THREAD

**Issue by JoeMcCheater** [nullworks/cathook#1808]
HEAD is now at 33a382b0 Minor tweaks
~/Desktop/Cheat Zone/cathook/build ~/Desktop/Cheat Zone/cathook
-- Could NOT find Boost: Found unsuitable version "1.81.0", but required is exact version "1.76.5" (found /usr/include, )
-- Fetching Boost
-- Fetching Boost - done
CMake Error at external/boost-cmake/cmake/Modules/CheckBoostVersion.cmake:2 (file):
  file STRINGS file "/home/cheater/Desktop/Cheat
  Zone/cathook/build/_deps/boost-src/boost/version.hpp" cannot be read.
Call Stack (most recent call first):
  external/boost-cmake/CMakeLists.txt:26 (include)

CMake Error at external/boost-cmake/cmake/Modules/CheckBoostVersion.cmake:6 (math):
  math cannot parse the expression: " / 100000": syntax error, unexpected
  exp_DIVIDE (2).
Call Stack (most recent call first):
  external/boost-cmake/CMakeLists.txt:26 (include)

CMake Error at external/boost-cmake/cmake/Modules/CheckBoostVersion.cmake:7 (math):
  math cannot parse the expression: " / 100 % 1000": syntax error, unexpected
  exp_DIVIDE (2).
Call Stack (most recent call first):
  external/boost-cmake/CMakeLists.txt:26 (include)

CMake Error at external/boost-cmake/cmake/Modules/CheckBoostVersion.cmake:8 (math):
  math cannot parse the expression: " % 100": syntax error, unexpected
  exp_MOD (2).
Call Stack (most recent call first):
  external/boost-cmake/CMakeLists.txt:26 (include)

-- Boost found: ERROR.ERROR.ERROR /home/cheater/Desktop/Cheat Zone/cathook/build/_deps/boost-src
-- Could NOT find Boost: Found unsuitable version "1.81.0", but required is exact version "1.76.5" (found /usr/include, )
-- Configuring incomplete, errors occurred!
 
 
Failed to compile cathook

**Comment by JoeMcCheater** [comment]
can i just get the files for 1.76.5 or something because i can't find it anywhere online

**Comment by daw0rld** [comment]
### Anyone got any awnsers? I ALWAYS get the same errors. 

(If anyone is interested, here's what Cathook says:) (Word for word)

> $ bash <(wget -qO- https://raw.githubusercontent.com/nullworks/One-in-all-cathook-install/master/install-all)
> Cloning into 'cathook'...
> remote: Enumerating objects: 687, done.
> remote: Counting objects: 100% (687/687), done.
> remote: Compressing objects: 100% (655/655), done.
> remote: Total 687 (delta 52), reused 218 (delta 22), pack-reused 0
> Receiving objects: 100% (687/687), 6.71 MiB | 4.59 MiB/s, done.
> Resolving deltas: 100% (52/52), done.
> ~/cathook ~
> remote: Enumerating objects: 31, done.
> remote: Counting objects: 100% (31/31), done.
> remote: Compressing objects: 100% (16/16), done.
> remote: Total 16 (delta 15), reused 1 (delta 0), pack-reused 0
> Unpacking objects: 100% (16/16), 2.47 KiB | 194.00 KiB/s, done.
> From https://github.com/nullworks/cathook
>  * [new tag]         stable     -> stable
> HEAD is now at a0d0742 missing module changes
> Submodule 'external/MicroPather' (https://github.com/nullworks/MicroPather) registered for path 'external/MicroPather'
> Submodule 'external/TF2_NavFile_Reader' (https://github.com/nullworks/TF2_NavFile_Reader) registered for path 'external/TF2_NavFile_Reader'
> Submodule 'external/boost-cmake' (https://github.com/STEVE4git/boost-cmake.git) registered for path 'external/boost-cmake'
> Submodule 'external/clip' (https://github.com/nullworks/clip) registered for path 'external/clip'
> Submodule 'libglez' (https://github.com/nullworks/libglez) registered for path 'external/libglez'
> Submodule 'external/libnullnexus' (https://github.com/nullworks/libnullnexus) registered for path 'external/libnullnexus'
> Submodule 'libxoverlay' (https://github.com/nullworks/libxoverlay) registered for path 'external/libxoverlay'
> Submodule 'simple-ipc' (https://github.com/nullworks/simple-ipc) registered for path 'external/simple-ipc'
> Submodule 'source-sdk-2013-headers' (https://github.com/nullworks/source-sdk-2013-headers) registered for path 'external/source-sdk-2013-headers'
> Cloning into '/home/da_world/cathook/external/MicroPather'...
> Cloning into '/home/da_world/cathook/external/TF2_NavFile_Reader'...
> Cloning into '/home/da_world/cathook/external/boost-cmake'...
> Cloning into '/home/da_world/cathook/external/clip'...
> Cloning into '/home/da_world/cathook/external/libglez'...
> Cloning into '/home/da_world/cathook/external/libnullnexus'...
> Cloning into '/home/da_world/cathook/external/libxoverlay'...
> Cloning into '/home/da_world/cathook/external/simple-ipc'...
> Cloning into '/home/da_world/cathook/external/source-sdk-2013-headers'...
> Submodule path 'external/MicroPather': checked out 'c3960ea5af374f2ed6195eb39f803f2611b882a9'
> remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
> remote: Enumerating objects: 7, done.
> remote: Counting objects: 100% (7/7), done.
> remote: Compressing objects: 100% (4/4), done.
> remote: Total 4 (delta 3), reused 1 (delta 0), pack-reused 0
> Unpacking objects: 100% (4/4), 991 bytes | 495.00 KiB/s, done.
> From https://github.com/nullworks/TF2_NavFile_Reader
>  * branch            55ae8047a24203cec834f54fd67ee6d571f497f6 -> FETCH_HEAD
> Submodule path 'external/TF2_NavFile_Reader': checked out '55ae8047a24203cec834f54fd67ee6d571f497f6'
> remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
> remote: Enumerating objects: 7, done.
> remote: Counting objects: 100% (7/7), done.
> remote: Compressing objects: 100% (4/4), done.
> remote: Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
> Unpacking objects: 100% (4/4), 592 bytes | 197.00 KiB/s, done.
> From https://github.com/STEVE4git/boost-cmake
>  * branch            7f97a08b64bd5d2e53e932ddf80c40544cf45edf -> FETCH_HEAD
> Submodule path 'external/boost-cmake': checked out '7f97a08b64bd5d2e53e932ddf80c40544cf45edf'
> Submodule path 'external/clip': checked out 'be4f5461f7308497f5c687c2516a2dbcf23ccd33'
> remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
> remote: Enumerating objects: 1, done.
> remote: Counting objects: 100% (1/1), done.
> remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
> Unpacking objects: 100% (1/1), 167 bytes | 167.00 KiB/s, done.
> From https://github.com/nullworks/libglez
>  * branch            a278b5ce6debd1e5580cb41b3a018a5da9b66263 -> FETCH_HEAD
> Submodule path 'external/libglez': checked out 'a278b5ce6debd1e5580cb41b3a018a5da9b66263'
> remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
> remote: Enumerating objects: 11, done.
> remote: Counting objects: 100% (11/11), done.
> remote: Compressing objects: 100% (5/5), done.
> Unpacking objects: 100% (6/6), 1.54 KiB | 394.00 KiB/s, done.
> remote: Total 6 (delta 3), reused 3 (delta 0), pack-reused 0
> From https://github.com/nullworks/libnullnexus
>  * branch            64edb7774a88a57f53368849126e8b886689449f -> FETCH_HEAD
> Submodule path 'external/libnullnexus': checked out '64edb7774a88a57f53368849126e8b886689449f'
> Submodule path 'external/libxoverlay': checked out '97462b57c80eb36adda47d1390da16ce29ac2823'
> Submodule path 'external/simple-ipc': checked out '085ec77f13ac8143116fe57317d9b7275fe16a57'
> remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
> remote: Enumerating objects: 17, done.
> remote: Counting objects: 100% (17/17), done.
> remote: Compressing objects: 100% (8/8), done.
> Unpacking objects: 100% (9/9), 711 bytes | 118.00 KiB/s, done.
> remote: Total 9 (delta 7), reused 2 (delta 0), pack-reused 0
> From https://github.com/nullworks/source-sdk-2013-headers
>  * branch            ec9aaa1514eef4a9fc7406acc7dd3b0cea05161a -> FETCH_HEAD
> Submodule path 'external/source-sdk-2013-headers': checked out 'ec9aaa1514eef4a9fc7406acc7dd3b0cea05161a'
> ~/cathook/build ~/cathook
> CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
>   CMake 3.20 or higher is required.  You are running version 3.16.3
> 
> 
> -- Configuring incomplete, errors occurred!
>  
>  
> Failed to compile cathook
> 
> ~
>

**Comment by iraizo** [comment]
CMake 3.20 or higher is required. You are running version 3.16.3.

read the error message ffs.

**Comment by JoeMcCheater** [comment]
> CMake 3.20 or higher is required. You are running version 3.16.3.
> 
> read the error message ffs.

you didn't give an answer to my problem
