### ISSUE TITLE
Vac bypass on linux

### ISSUE THREAD

**Issue by Pandoroeo** [nullworks/cathook#1821]
I'm trying to find a vac bypass for linux so I dont get banned immediately. (Or at least make it less likely for me to get banned, I don't want to host bots but I do want to use cathook as a cheat.) I'm not sure if this exists but if it does please tell me.

**Comment by Skilightt** [comment]
https://github.com/nullworks/just-disable-vac

Also VAC can't detect the GDB injector anyway

**Comment by cowhookdev** [comment]
> https://github.com/nullworks/just-disable-vac
> 
> Also VAC can't detect the GDB injector anyway

VAC rarely bans GUI users

**Comment by Skilightt** [comment]
> VAC rarely bans GUI users

Congratulations, that might have been the first sentence I've seen you write without a spelling mistake!
