### ISSUE TITLE
Complie Error

### ISSUE THREAD

**Issue by MCPEnguXD** [nullworks/cathook#1829]
## System Information
**OS:**  Ubuntu
**DE:**  
**Cathook Version:**  Master And Stable

## Logs / Crash Report  
HEAD is now at 26593d6 whoever added this boost jank is insane
~/Downloads/cathook/build ~/Downloads/cathook
-- Fetching Boost
-- Fetching Boost - done
-- Boost found: 1.76.0 /home/mcpengu/Downloads/cathook/build/_deps/boost-src
CMake Warning (dev) at build/_deps/boost-src/tools/boost_install/BoostConfig.cmake:141 (find_package):
  Ignoring EXACT since no version is requested.
Call Stack (most recent call first):
  build/_deps/boost-src/tools/boost_install/BoostConfig.cmake:215 (boost_find_component)
  CMakeLists.txt:107 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at build/_deps/boost-src/tools/boost_install/BoostConfig.cmake:141 (find_package):
  Could not find a package configuration file provided by "boost_headers"
  with any of the following names:

    boost_headersConfig.cmake
    boost_headers-config.cmake

  Add the installation prefix of "boost_headers" to CMAKE_PREFIX_PATH or set
  "boost_headers_DIR" to a directory containing one of the above files.  If
  "boost_headers" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  build/_deps/boost-src/tools/boost_install/BoostConfig.cmake:215 (boost_find_component)
  CMakeLists.txt:107 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/mcpengu/Downloads/cathook/build/CMakeFiles/CMakeOutput.log".
See also "/home/mcpengu/Downloads/cathook/build/CMakeFiles/CMakeError.log".
 
 
Failed to compile cathook

## Description  
Tried compiling cathook multiple times and first got an error like the one in this post: https://github.com/nullworks/cathook/issues/1820
I then followed a commend from this thread: https://github.com/nullworks/cathook/issues/1801 which now gives me this error.

## Steps to reproduce  
Compile Cathook with a fresh Ubuntu minimal installation

## Checklist  
- [x ] I have included my DE, WM, and version of Cathook.
- [x ] I have included the steps to reproduce and my logs to the best I am able to share.
- [ @mcpengu] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need it. (Put your username here)

**Comment by MCPEnguXD** [comment]
Going to try to download manjaro and see if that improves anything... will report back

**Comment by MCPEnguXD** [comment]
turns out manjaro does not like vmware for whatever reason so i cannot download that, if someone responds with a fix il boot up a new ubuntu vm and try again.

**Comment by SuperVitu64** [comment]
so in a nutshell cathook is unusable atm, am i right?

**Comment by jeteki** [comment]
> so in a nutshell cathook is unusable atm, am i right?

somewhat but people somehow compile it with custom boost libs and versions

**Comment by snipergaming134** [comment]
ah so i'm not the only one

**Comment by Congenial4048** [comment]
> so in a nutshell cathook is unusable atm, am i right?

No, it works for me. You just have to not use the install script.
git clone https://github.com/nullworks/cathook.git
cd cathook
./config
Say No to the prompt asking you if you want to restore
Go into "Update channel"
Select "Master (Bleeding Edge)"
Press Ok and it should update and compile, then just exit the config menu by pressing Cancel.

**Comment by SuperVitu64** [comment]
> > so in a nutshell cathook is unusable atm, am i right?
> 
> No, it works for me. You just have to not use the install script. git clone https://github.com/nullworks/cathook.git cd cathook ./config Say No to the prompt asking you if you want to restore Go into "Update channel" Select "Master (Bleeding Edge)" Press Ok and it should update and compile, then just exit the config menu by pressing Cancel.

What OS have you used?

**Comment by Congenial4048** [comment]
> > > so in a nutshell cathook is unusable atm, am i right?
> > 
> > 
> > No, it works for me. You just have to not use the install script. git clone https://github.com/nullworks/cathook.git cd cathook ./config Say No to the prompt asking you if you want to restore Go into "Update channel" Select "Master (Bleeding Edge)" Press Ok and it should update and compile, then just exit the config menu by pressing Cancel.
> 
> What OS have you used?

I used void linux

**Comment by SuperVitu64** [comment]
> > > > so in a nutshell cathook is unusable atm, am i right?
> > > 
> > > 
> > > No, it works for me. You just have to not use the install script. git clone https://github.com/nullworks/cathook.git cd cathook ./config Say No to the prompt asking you if you want to restore Go into "Update channel" Select "Master (Bleeding Edge)" Press Ok and it should update and compile, then just exit the config menu by pressing Cancel.
> > 
> > 
> > What OS have you used?
> 
> I used void linux

ah alright
alright imma follow that and update on the result

**Comment by SuperVitu64** [comment]
it kinda gets stuck on fetching boost though

**Comment by SuperVitu64** [comment]
welp, it failed, should i make a new issue thread and show the error files?

**Comment by RandomTNT** [comment]
pengu, you gotta  build the boost libs from their github, not download ubuntu's boost, its old and doesnt work

**Comment by RandomTNT** [comment]
> > so in a nutshell cathook is unusable atm, am i right?
> 
> No, it works for me. You just have to not use the install script. git clone https://github.com/nullworks/cathook.git cd cathook ./config Say No to the prompt asking you if you want to restore Go into "Update channel" Select "Master (Bleeding Edge)" Press Ok and it should update and compile, then just exit the config menu by pressing Cancel.

Aaaand you gotta use smth like arch or endevaour
or have the latest boost libs

**Comment by STEVE4git** [comment]
Was due to a change with how it downloads boost, fixed recently
