### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by ghost** [nullworks/cathook#1833]
## System Information
**OS: Ubuntu 22**  
**DE:**  
**Cathook Version: Latest stable**  

## Description  
This thing doesn't compile properly, i dont know what is causing it

## Steps to reproduce  
- [X] I am able to consistently reproduce this error

## Checklist  
- [x] I have included my DE, WM, and version of Cathook.
- [x] I have included the steps to reproduce and my logs to the best I am able to share.
- [ ] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need it. (Put your username here)
[CMakeError.log](https://github.com/nullworks/cathook/files/12268219/CMakeError.log)
[CMakeOutput.log](https://github.com/nullworks/cathook/files/12268220/CMakeOutput.log)

**Comment by SuperVitu64** [comment]
Updating to Master branch doesnt work either

**Comment by Muffinmaker2** [comment]
U have to give us maybe like a log or something. or it cant be helped :(

**Comment by STEVE4git** [comment]
Fixed in recent PR
