### ISSUE TITLE
TF2 Casual Longevity Plummeting == Continued Development Practically Asinine

### ISSUE THREAD

**Issue by Kacey2k** [nullworks/cathook#1853]
**Quick Description**

Realistically, if Casual dies, matchmaking automation becomes obsolete. It would be similar to developing automated clients for 1980s tetris except you have no audience. Unless of course, the end goal here is to maximally populate matchmaking with your bots navigating servers blind, without any reaction from the TF2 community abroad.

**The Issue**

We are all well aware no one here cares about clambering casuals complaining, this is different. This project only exists due to TF2 having an audience, you would not be here developing this otherwise. If casual players threw in the white flag and abandoned casual entirely, what purpose would this entire project serve? Surely training for TF2 would not make sense if there is no TF2 left to train on. I know no one here caters an ounce of empathy, otherwise you would not be here, however, consider the logical implications at the very least.

**My Suggestion for Developers**

Cease development, alter development goals, or increase the bar of entry for the public to actively engage with this project. Such as, ceasing support for GUI, Manjaro, introducing abstract methods of initializing the program, etc.

**Additional Context**

Open source will be open source, so this ultimately would not achieve much. However, let it rattle in the back of your mind sometime. Matchmaking will one day die, and that is a fact that only speeds by closer the further this project goes.

**Comment by iraizo** [comment]
this project is basically in maintenance mode already,
