### ISSUE TITLE
Reinstall won't help

### ISSUE THREAD

**Issue by gitbgrand** [nullworks/cathook#1857]
os: manjaro/cathookos
cathook version: cant check latest at time of writing

error:
----------------

git: /usr/lib/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by git)
git: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by git)
git: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by git)
git: /usr/lib/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by git)
git: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by git)
git: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by git)
git: /usr/lib/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by git)
git: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by git)
git: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by git)
git: /usr/lib/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by git)
git: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by git)
git: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by git)

Failed to pull from github! Trying alternative pull (legacy)

git: /usr/lib/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by git)
git: /usr/lib/libc.so.6: version `GLIBC_2.38' not found (required by git)
git: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by git)

Failed to pull from github! A reinstall is recommended. https://cathook.club

----------------
how to reproduce
1. open cathook
2. install
3. fail
4. install missing libraries

problem:
3 libraries are missing required by git that i cant install and it asks me to try to reinstall or use legacy but i cant find legacy and reinstall wont work

**Comment by iraizo** [comment]
`sudo pacman -S glibc`

**Comment by gitbgrand** [comment]
error: failed to prepare transaction (could not satisfy dependencies)
:: installing glibc (2.39-1.1) breaks dependency 'glibc=2.33' required by lib32-glibc
