### ISSUE TITLE
An issue with your computer is blocking the VAC system. You cannot play on secure servers

### ISSUE THREAD

**Issue by temmieyayA** [nullworks/cathook#1861]
## System Information
**OS:arch**  
**DE:plasma**  
**Cathook Version:main branch, latest**  

## Config used
i can't even get into a game, so i didn't use one yet

## Description  
queues auto cancel, and training tells me "An issue with your computer is blocking the VAC system. You cannot play on secure servers."

## Steps to reproduce  
- [yes ] I am able to consistently reproduce this error

launch tf2, inject cathook (i built from source, gui didn't work) and try to go into training

## Additional context 
no

## Checklist  
- [ yes] I have included my DE, WM, and version of Cathook.
- [yes] I have included the steps to reproduce and my logs to the best I am able to share.

**Comment by MasterCatPL** [comment]
probably your steam account issue try changing steam account and restart computer

**Comment by temmieyayA** [comment]
> probably your steam account issue try changing steam account and restart computer

can't be that, without cathook injected everything works fine.

**Comment by temmieyayA** [comment]
seems it somehow fixed itself ?
