### ISSUE TITLE
cat_fb_crouch

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#208]
Have bot crouch when target is crouching. Maybe add a check to only do so when they're crouching for more than half a second, that way you don't crouch with someone that has a crouch/jump script.

Also, have bot crouch when target is heavy spinning up. Walks just as fast if not faster than a heavy attacking, so it'll help keep the bot a little more hidden/smaller target to hit.

**Comment by julianacat** [comment]
why would this help the aimbot, would this be good for cs:s?

**Comment by SylveonBottle** [comment]
Aimbot? It's got nothing to do with aimbot. I just want my medic followbot to stop being stupid and sticking its head out the window or above a ledge when I'm trying to crouch/sneak by.

**Comment by julianacat** [comment]
OHHH, I can do this no problem, just give me a few.
