### ISSUE TITLE
cat_fb_roaming to ignore certain players based on class/situation

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#210]
Let's not have followbot follow disguised/invisible spies and stuff.
Engineers that are near their sentries, too. Medic is useless if he's just gonna cap a sentry - that's what dispensers are for.
Snipers that are zoomed in would appreciate the help, but I'm sure the entire team would agree with kicking a medic who's pocketing a sniper.

There's probably more examples.

**Comment by BenCat07** [comment]
I actually added class priority to my old own branch, might readd.

**Comment by TotallyNotElite** [comment]
Class priority is a thing now.

**Comment by SylveonBottle** [comment]
Could I get some information on the class priority? Pretty interested.
