### ISSUE TITLE
cat_fb_retrace 1

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#212]
Instead of completely deleting them, have followbot document/save the previous 30-50 breadcrumbs. If current target dies, retrace those breadcrumbs to retreat back until you find a new target.

Seems like a super advanced AI bullshit to me.

Edit: 30-50 breadcrumbs is a rough estimate. I mean basically whatever can get you to walk half way back to spawn or whatever. Maybe some math shit to remove half of the breadcrumbs created since respawn idk

Oh and if you jumped down from a height then rip. The current breadcrumb system would just delete the breadcrumbs - if cat_fb_retrace can't continue retracing the path for whatever reason, may as well stop and wait for someone to pick you up.

**Comment by julianacat** [comment]
The point of the roaming mode is to solve the problem of your followbots staying at spawn as other people can lead them back to you. I already explained how this would be hard in #213

**Comment by SylveonBottle** [comment]
They're rare, but there's certain situations where your followbots may be spawned in a weird location and are unable to follow anyone back to get to you. This issue was created so we could try fixing that small problem. 

But, I agree with what you said: the current code for breadcrumbs kinda makes this hard/impossible.

**Comment by TotallyNotElite** [comment]
Navparser makes this obsolete. (Other than ent being dormant)

**Comment by TotallyNotElite** [comment]
Sound esp completely fixes this issue.
