### ISSUE TITLE
cat_fb_retrace 2

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#213]
Based off of #212

Could be its own optional thingy.

Basically, save breadcrumbs from your last spawn-in to when you died.
When you spawn in the next time, have followbot retrace those breadcrumbs from start to finish until you find a new target. Maybe even combine it with #212 to auto-retreat back if an enemy is nearby.

This would get followbot to start walking to the end of the map (or at least where they died at) in search for a new follow target so you don't have to keep coming back for it constantly.

**Comment by julianacat** [comment]
The current crumb followbot just uses a array of 55 vectors, Its constantly writing and removing from that array. When you use the draw feature for the crumb followbot, it only shows the vectors in the array that is important, everything else in it is trash meant to just be overwritten when we need that space. Im not sure how I would do this as it would probable require some major changes of how the bot works and having the bot use something like nav maps would be more efficient than this.

**Comment by SylveonBottle** [comment]
The point of _this_ issue was so that the followbots could back off a tad bit when you died. If nav maps can work like I've suggested (going from a random point in the map back to spawn) then feel free to close this issue in favor of nav maps. Otherwise, still interested in the bot following breadcrumbs backwards upon target's death.

**Comment by BenCat07** [comment]
Just use two vectors, a temp and a current one.

**Comment by TotallyNotElite** [comment]
Navparser makes this obsolete. (Other than ent being dormant)

**Comment by TotallyNotElite** [comment]
See #212
