### ISSUE TITLE
[Suggestion] Optimize retrieval of CatVars for InfoPanel

### ISSUE THREAD

**Issue by Retarded-Skid** [nullworks/cathook#219]
I couldn't find where the class `CatVar` was declared or where they are stored, but this snippet makes it abundantly clear they're stored in a list.

```cpp
CatVar* GetCatVar(const std::string name) {
	for (auto var : CatVarList()) {
		if (var->name == name) return var;
	}
	return nullptr;
}
```

If you're going to need a name-lookup that doesn't kill performance, why not use [a map](https://stackoverflow.com/questions/3578083/what-is-the-best-way-to-use-a-hashmap-in-c)? If you were to migrate CatVar storage to a map, you would [still be able to iterate over the CatVars as a list if you chose to](https://stackoverflow.com/questions/13087028/can-i-easily-iterate-over-the-values-of-a-map-using-a-range-based-for-loop). If you don't need to keep the CatVars in order *(Just skimming over usages of `CatVarList` I don't see any reason to keep an ordering)* the first link says `std::unordered_map` provides `O(1)` access. By comparison the list has `O(n)` where `n` is the size of the list.

This would change the `GetCatVar` code to look something like:

```cpp
CatVar* GetCatVar(const std::string name) {
	if (m.find("world") != m.end())
		return m["hello"];
	return nullptr;
}
```

This would make the accessing CatVars per-tick in InfoPanel a non-issue.

**Comment by BenCat07** [comment]
what cat vars
