### ISSUE TITLE
Hitbox visibility check only checks center of hitbox

### ISSUE THREAD

**Issue by no-boot-device** [nullworks/cathook#22]
This means that effectively, if you can see someone's head, but not the center of their head, the aimbot won't shoot them.

**Comment by nullifiedcat** [comment]
Yes. I'll add multipoint as an option later - but keep in mind that it'll HEAVILY reduce your FPS.

**Comment by julianacat** [comment]
One idea for multi-point is to take the hitbox max and min, shrinking it a little, then using all the corners from the shrunken hitbox as the "multi-points" to vis check.
I currently don't know enough about the hitbox cache system to attempt to implement this
