### ISSUE TITLE
Reset config?

### ISSUE THREAD

**Issue by Alkaris** [nullworks/cathook#233]
How can I reset the config for cathook? I can't move my mouse cursor around because it keeps locking it to the center of the screen. I was trying to figure out how to stop the system mouse cursor showing while in-game because it's limiting my mouse control to the edges of the game window screen, not allowing me to have normal full 360° mouse movement.

**Comment by nullifiedcat** [comment]
This mouse bug has nothing to do with config of cathook. You can reset config by `exec cat_defaults` btw.

You can try using `cat_experimental_cursor_fix 1` or `cl_software_cursor 1` to fix the mouse issue.

**Comment by Alkaris** [comment]
I see... well I just tried to run `exec cat_defaults` but my cursor is still being trapped to the center of the screen. and I did try `cl_software_cursor 1` too, I can't get my proper mouse control back. :/

**Comment by nullifiedcat** [comment]
Try using `cat_experimental_cursor_fix 1`

**Comment by Alkaris** [comment]
Still doesn't work.... I'm getting some stupid grey cursor thing which is causing it to lock into the centre of the screen.

![shutter__2017yyy_28_07-28-17__09_34_09_pm](https://user-images.githubusercontent.com/6682988/28716468-981f7bfc-73dc-11e7-97f3-f292c46e8c34.png)

**Comment by nullifiedcat** [comment]
This is tf2's software cursor.

**Comment by Alkaris** [comment]
Whelp... I can't take control of the mouse cursor, because it's being locked to the centre of the screen. I need to uninstall cathook and try again with a fresh compiled version.

**Comment by nullifiedcat** [comment]
It's not a cathook bug (probably), it's a tf2 cursor bug. Try different settings for cl_software_cursor, opening/closing the menu, etc. Reinstalling cathook won't help.

**Comment by Alkaris** [comment]
This started happening after changing a setting in cathook which kept causing the cursor to lock into place, and now it wont turn off, whatever it was that got set. There was some option in Miscellaneous I think.

**Comment by nullifiedcat** [comment]
If it is really caused by a setting, a tf2 restart will help.

**Comment by Alkaris** [comment]
I've tried this multiple times, it's caused by a bug in cathook, everything was running fine until cathook was injected to the game.

**Comment by BenCat07** [comment]
cat_load an empty config
