### ISSUE TITLE
Make walkbots ignore other cathook users

### ISSUE THREAD

**Issue by massivenoob** [nullworks/cathook#236]
Exactly as it sounds in the title. Cathook user sends "ignore me" in crypto chat, the bot (or one of them if there are multiple) replies with a random string, if the user replies with that string in crypto chat within 10 seconds, the bot(s) ignore them.

**Comment by HappyDOGE** [comment]
Or just make a database like in nullcore

**Comment by nullifiedcat** [comment]
This is basically handshake system and it is way better than database one.

**Comment by massivenoob** [comment]
In order to prevent a regular player from just figuring out how it works and proceeding to dominate the bots while they do nothing, there should at least be some confirmation that the ignored player is actually cheating. Something like having them send a newline in chat.

**Comment by HappyDOGE** [comment]
Database is better in that case since there will be output only for hack users.
In other words:
In-Chat Handshake - prefornance,
Database - security

**Comment by nullifiedcat** [comment]
What do you mean by security? Legit players won't be able to convince the bot they can read crypto-chat (unless they download UCCCCCP package and make a decryptor). And database of users will impact privacy.

**Comment by RaggedCaster** [comment]
They theoretically can (cathook is open-source).

**Comment by nullifiedcat** [comment]
Alternative method would be handshake-over-viewangles.

**Comment by HappyDOGE** [comment]
Security means that legit players wont be able to enable ignoring without understanding how database request works. Also, this allows to mark cathook user on esp, as NCC did. Privacy - only steamids can be collected

**Comment by nullifiedcat** [comment]
No. I will not collect user's steamids. This feature will be implemented with either chat or viewangle handshake.

**Comment by Retarded-Skid** [comment]
How about this:

``` (all in uccccp)
Person: ignore me
Bot: Are stawberries fruits or vegstables
Person: Fruit
Bot: Ignoring confirmed

(If fail)

(Not ucccp) Bot: Nope, get fucked, <person name>
```

Possible validation questions would be simple. Like:

* what is the square root of 100
* what is 5 x 5
* who is the current president of the usa
* what game are we playing
* what hack looks at players

This prevents nomie users from figuring out a single catch-phrase to copy paste in order to stomp bots. Also if you kill a bot, it should reset ignoring whoever killed it.

**Comment by HappyDOGE** [comment]
Just send the random letters and numbers and require that string, but in base64. PROFIT

**Comment by massivenoob** [comment]
Exactly what I suggested.

(ucccccp) Cheater: ignore me
(plain text) Bot: wE11P
(ucccccp with newline before message) Cheater: wE11P
(plain text) Bot: Ignoring

If cheater doesn't send a newline, sends the wrong message or doesn't reply within 10 seconds, bot doesn't ignore.

**Comment by Blackfire62** [comment]
It should be something that non cathook users cant do. So the response should be encoded as well, at least.

**Comment by BenCat07** [comment]
Crypto chat broke. And this is partially done.

**Comment by TotallyNotElite** [comment]
IRC to the rescue! Cathook users will now identify eachother in IRC.
