### ISSUE TITLE
Improve crypto chat security

### ISSUE THREAD

**Issue by massivenoob** [nullworks/cathook#237]
Right now, any redditor can just make a tool to use crypto chat while not even cheating. Make cathook append a newline after a message in crypto chat so that can't happen.

**Comment by nullifiedcat** [comment]
It is secure enough already. And who even uses crypto chat?

To decrypt cathook's crypto chat, legit player must

1. Know that this is some sort of encrypted message and not just spam
2. Know about cathook's encrypted chat message
3. Find UCCCCCP repository
4. Write a decryptor in C/C++
5. Decrypt message

Most players will fail at level 2. And those who'll make it to 5 can be considered true gamers.

**Comment by nullifiedcat** [comment]
Honestly this should be moved to UCCCCCP issues, not cathook's.
