### ISSUE TITLE
cat_ipc_exec_sync <command>

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#245]
Update:
have `cat_ipc_sync` run `cat_ipc_exec_all <command> <current variable>` whenever the command is currently being synced, and the variable changes

Synchronize convars of specific commands for your catbots with your own instance of cathook.

Example: `cat_ipc_exec_sync cat_aimbot_enabled` will sync your variable for cat_aimbot_enabled with the bots'.

**Comment by BenCat07** [comment]
Easy pEasy

**Comment by TotallyNotElite** [comment]
@BenCat07 can this be closed?

**Comment by iraizo** [comment]
@TotallyNotElite can this be closed?

**Comment by SylveonBottle** [comment]
Was this ever added? Or are we just closing it due to inactivity?

**Comment by iraizo** [comment]
> Was this ever added? Or are we just closing it due to inactivity?

I was asking because of inactivity since this is unplanned anyways

**Comment by iraizo** [comment]
I normally like to configure bots while playing with them or change things temporarily so I might add that myself if i figure out how the IPC between bots work since I never used it.

**Comment by SylveonBottle** [comment]
My apologies, didn't see the unplanned tag.

Feel free to reopen if this is planned in the future.

**Comment by iraizo** [comment]
Might do :)

**Comment by iraizo** [comment]
Working on this atm
