### ISSUE TITLE
cat_autoheal_singletarget

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#246]
too lazy to write more descriptions, have copy/paste log
Leafeon - Today at 1:04 AM
`Also, didn't autoheal used to heal only you?`
nullifiedcat - Today at 1:04 AM
`no`
Leafeon - Today at 1:04 AM
`Like, is there a way to only heal target?`
nullifiedcat - Today at 1:04 AM
`not yet`
Leafeon - Today at 1:04 AM
`o`
nullifiedcat - Today at 1:04 AM
`it heals IPC targets first tho`
Leafeon - Today at 1:04 AM
`pls? x3 dun want suspicious bots following me around`
nullifiedcat - Today at 1:05 AM
`make an issue`
`xd`
Leafeon - Today at 1:05 AM
`would rather people angry at pocket medic rather than kicking medic for hacking`
`mind if I just copy/paste this chat for that issue, then?`
nullifiedcat - Today at 1:05 AM
`well uhh`
`ok`
`basically a rage-only aimbot but for autoheal`
Leafeon - Today at 1:06 AM
`Basically basically, have healbots heal target literally always. Then have autoheal rename to heal_others or something`
`good?`
`So autoheal will always heal follow target, unless they toggle the healing of others`
nullifiedcat - Today at 1:07 AM
`yeah`
`no`
`I'll add cat_autoheal_singletarget or something`
Leafeon - Today at 1:08 AM
`<_> that's fine then`

**Comment by BenCat07** [comment]
done
