### ISSUE TITLE
[Suggestion]make wb able to work on cp and pl

### ISSUE THREAD

**Issue by cheddar-cheeze** [nullworks/cathook#251]
Make conditional wb connections that only allow the bot to go through if a certian point is captured

**Comment by BenCat07** [comment]
*Poke* REALLY needs to be added.

**Comment by BenCat07** [comment]
Pretty simple to make actually, option 1: Cart/Enemy CP Followbot, Option 2: Count Captured Ents on the map

**Comment by TotallyNotElite** [comment]
Navbot tm

**Comment by cheddar-cheeze** [comment]
:3
