### ISSUE TITLE
Register tf2 as ksm app

### ISSUE THREAD

**Issue by oneechanhax** [nullworks/cathook#252]
https://wiki.archlinux.org/index.php/QEMU#Enabling_KSM
It would be interesting to see multiple tf2 instances using one shared pool of memory instead of having their own. It could be great for running more catbots than ever but I dont know how this could be rolled out in practice or how performance will be affected.

**Comment by BenCat07** [comment]
use uksm instead, auto runs andd auto scans, no need to preload either, better overall, needs to have a freshly compiled kernel tho

**Comment by oneechanhax** [comment]
Good idea, but how will performance system wide be :thinking:

**Comment by BenCat07** [comment]
it decreases ram but increases cpu usage a bit

**Comment by BenCat07** [comment]
closing, UKSM is the way to go
