### ISSUE TITLE
[suggestion] Spectator warning

### ISSUE THREAD

**Issue by cheddar-cheeze** [nullworks/cathook#265]
None of the tf2 cheats out there have spectator warning so why not be the first, similar to like to aimtux or bigpackets.

**Comment by SylveonBottle** [comment]
Do you have any idea on how we would make such a thing? Why not suggest godmode, too?

Then again, I wouldn't know where to begin with this. If there's actually a way to tell when someone's spectating you, then by all means I apologies.

**Comment by SylveonBottle** [comment]
> **lbox - Last Sunday at 5:57 AM**
> woha
> I guess its because
> the target wasnt dormant when u shoot at it(edited)
> so why would it be dormant after its dead? unless forced to be dormant.
> 
> **Blackfire - Last Sunday at 5:58 AM**
> That was from context that chrys said, something about csgo spectator list
> another quote, from this server
> While spectators arent netwroked, people in your and other team are, so you can see if any of these are speccing you.
> 
> **lbox - Last Sunday at 5:59 AM**
> yeah I know that, it worked for me, but before releasing the feature I was testing it with loog and it didnt work at all.
> because he was only testing it by going to spectators.
> so i just commented the code and moved on.

------------------------------------------------


> **Leafeon - Today at 7:30 PM**
> So, from that, I can understand that:
> 1.) Someone has thought of this, tested it, and it works
> 2.) Somebody added it to their client, tested it (but only in spectator team), it didn't work for them, so they uncommented it - but it's still in their client
> So, it doesn't work for spectator team, but only if they're on your team and in deathcam spectating you :thinking: if it exists, that is
> 
> **massive noob - Today at 7:31 PM**
> Yeah, probably that
> 
> **⸻Apoda⸻ - Today at 7:31 PM**
> Seems so
> 
> **Leafeon - Today at 7:31 PM**
> So, either we find out how the second person got their hand on the code (first person shared it, maybe?)
> or we find the second person's client and grab that code
> So, somewhere out there is a client that has a working spectator mode, and another client that has the code but is commented out
> 
> **massive noob - Today at 7:32 PM**
> Well it's probably just getting the observer target of dead players (on your team) and checking if it's you

**Comment by BenCat07** [comment]
uhm, added tm
