### ISSUE TITLE
Teleporter Exit Direction

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#274]
Based off of #273.

Let's display an arrow where teleporter exits are facing, so you know which way you'll come out at. We can use this to camp at enemy teleporter as a spy for easy backstab, or check if friendly teleporter exit is trying to get you off a cliff.

**Comment by oneechanhax** [comment]
Teleporters already have a small arrow on them btw

**Comment by SylveonBottle** [comment]
If that's the case, they're completely invisible or are too small. I've never noticed them - even when looking for them.

**Comment by BenCat07** [comment]
Adding tomorrow.

**Comment by BenCat07** [comment]
Already a thing in esp

**Comment by BenCat07** [comment]
Added

**Comment by BenCat07** [comment]
in bafd9d19d82b6d06c1aa01fa01bedebe7824605b
