### ISSUE TITLE
[Question] Cathook on Mac?

### ISSUE THREAD

**Issue by ghost** [nullworks/cathook#302]
Theoretical question... since Mac OS X is based on UNIX, is it possible to get it up and running? Might answer my own question here and close it in 2 hours, but you never know.

**Comment by NoireCS** [comment]
I don't believe it would work on Mac without some editing to the factories and shit. So short answer, probably not.

**Comment by mrsteyk** [comment]
Cathook can work on Mac (in theory) if it has POSIX libs.

**Comment by plasmafart** [comment]
I might start working on darkstorm for mac, and see if I can get anywhere, might be able to port it over.

**Comment by nullifiedcat** [comment]
If I had a Mac, I'd probably make it work there, but I don't.

**Comment by mrsteyk** [comment]
@nullifiedcat hackintosh 🌚

**Comment by iraizo** [comment]
This could defenitly work on osx, the problem is it would take somebody much time to get it running by changing the signatures, vtable indexes (if they change i dont know). I also dont see the demand for osx, just dual boot.
