### ISSUE TITLE
Render while zoomed in doesn't render while zoomed in all the time

### ISSUE THREAD

**Issue by no-boot-device** [nullworks/cathook#34]
Sometimes, render while zoomed in will not render while zoomed in. Like it just won't work. No clue why. On tr_walkway.

However, render while zoomed in never renders if you have cl_autorezoom 1 and auto-rezoom:

steps to reproduce
1. have render while zoomed in and third person
2. enable cl_autorezoom 
3. zoom
4. fire a shot
5. sniper rifle will rezoom but not render your body

Also, if you have cosmetics on it doesn't render those either.

**Comment by nullifiedcat** [comment]
I've fixed the main part, but cosmetics still won't render - I have to hook C_TFWearable too

**Comment by BenCat07** [comment]
Fixed with bytepatching Render zoomed
