### ISSUE TITLE
Implement motd spam block

### ISSUE THREAD

**Issue by lotasgonsalaz** [nullworks/cathook#360]
Some community servers spam with motd ads, even if you set cl_disablehtmlmotd 1 (in which case server just spam you with motd windows)
Moreover, there are servers detecting value of cl_disablehtmlmotd. If they see you've disabled HTML motds, they either kick you after some time or restrict you from playing until you enable HTML motds.

**Comment by BenCat07** [comment]
Adblocker

Am 01.03.2018 16:04 schrieb "lotasgonsalaz" <notifications@github.com>:

**Comment by BenCat07** [comment]
Also, simpy Spoof set cl_disablehtmlmotd

**Comment by TotallyNotElite** [comment]
Stale and out of scope.
