### ISSUE TITLE
Anti-Backstab via cl_pitchup/cl_pitchdown

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#374]
https://lmaobox.net/forum/v/discussion/12769/feature-addition-suggestion-anti-backstab-via-cl-pitchup-cl-pitchdown#latest

> Not sure if a lot of people already know this or not, but when you look "upside down" with a high cl_pitchup or cl_pitchdown value, you can make it so that you're unable to be backstabbed, but your model stays in the exact same position the entire time. So, if a Spy were to come up behind you and the cheat automatically forced one of those commands to be at a value like that, the spy wouldn't really notice anything until he tries to backstab you. Which will end up doing 40 damage. Only way he could actually backstab you is if he stabs you from the front.
>
> Perhaps this would be a more "legit" looking anti-backstab or something? I don't know. Just thought it'd be fun to mention. 

This feature was added to LMAObox on April 20th.

**Comment by BenCat07** [comment]
Lbox also told me this. Will add after i fixed auto queue and a few other issues, i also don't know how the vars more precisely work.

Btw you should join the telegram.

**Comment by BenCat07** [comment]
done.
