### ISSUE TITLE
ReWrite menu to support xoverlay

### ISSUE THREAD

**Issue by mrsteyk** [nullworks/cathook#386]
Title says it all! :copyright:
Don't you dare to put wontfix on this one. This is actually important, since why to have xoverlay and not utilize it completly and you also have a great ogl wrapper called glez! :nice:

**Comment by BenCat07** [comment]
I won't put a wontfix on this, i would fix it if i had all the dras funcs to port them to libglez

**Comment by thinkingmaster** [comment]
I am working on a menu rewrite, it will be done eventually (and will use glez)
