### ISSUE TITLE
`GLIBCXX_3.4.22' not found

### ISSUE THREAD

**Issue by buyBread** [nullworks/cathook#387]
everytime i try the preload.sh script
$ ~ cd cathook   
$ ~/cathook sudo ./preload.sh   
Success! Launching TF2.   
/home/buybread/.local/share/Steam/steamapps/common/Team Fortress 2/hl2_linux: /home/buybread/.steam/steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/buybread/cathook/bin/libcathook.so)

**Comment by BenCat07** [comment]
:disappointed_relieved:

**Comment by buyBread** [comment]
sad

**Comment by BenCat07** [comment]
Wait

**Comment by BenCat07** [comment]
You built cathook on gcc 3?
