### ISSUE TITLE
self glow & chams broken

### ISSUE THREAD

**Issue by buyBread** [nullworks/cathook#391]
title

**Comment by BenCat07** [comment]
More info or wontfix, chams work fine, just not selfchams entierly

**Comment by buyBread** [comment]
self chams and glow dont work
yes chams works on other players but there is an option to have chams on yourself and it doesnt work (same with glow)

**Comment by TotallyNotElite** [comment]
Gentlemen we have done it! Almost a year later we managed to fix this bug xddd
