### ISSUE TITLE
sliders crash the game

### ISSUE THREAD

**Issue by buyBread** [nullworks/cathook#404]
uhh for example if you try to increase aimbot fov it crashes (using console commands it doesnt crash)
idk if this affects all sliders since i only tried aimbot and zoomed fov sliders
[backtrace](https://pastebin.com/3pWFdisF)

**Comment by buyBread** [comment]
ok so not all sliders are effected only the ones that increase like fov or smthing like that
going through aimkey modes doesnt crash

**Comment by BenCat07** [comment]
In fix, is a cmane static removal issue which just never occured before for
sole odd reason

.bread <notifications@github.com> schrieb am Mo., 30. Apr. 2018, 14:12:

**Comment by BenCat07** [comment]
fixed in #408
