### ISSUE TITLE
Chams colored black

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#405]
Hello,

Sometimes chams turned to black. All players, buildings. I can't do reproductions. Usually it cames out  after respawns. Sometimes after any respawns, this problem gone and coloring gets back.
My conf:
cat_chams_self_rainbow "1"
cat_chams_recursive "1"
cat_chams_buildings "1"
cat_chams_players "1"
cat_chams_enable "1"
Rest is 0.

**Comment by BenCat07** [comment]
yeah, i can relate, trying to fix right now.

**Comment by Astr0n4ut** [comment]
Meanwile: I noticed when chams are black glows are ceased.

**Comment by BenCat07** [comment]
cat_fix_black_chams
&
cat_fix_black_glow

Fixes it.
