### ISSUE TITLE
Metamod version

### ISSUE THREAD

**Issue by r3muxd** [nullworks/cathook#435]
Can there be a metamod ver of Cathook (for followbots)?

**Comment by BenCat07** [comment]
What is metamod?

**Comment by r3muxd** [comment]
metamod is a server plugin that handles other server plugins. Currently, there's no real good way to hook FireGameEvent in metamod, but cathook mainly solves that problem. sourcehook is supposed to fix this, but it's buggy and unstable.

**Comment by BenCat07** [comment]
Cathook is not made for serverside actions at all.

r3muxd <notifications@github.com> schrieb am Sa., 12. Mai 2018, 22:37:
