### ISSUE TITLE
[Question] Cathook on Windows ?

### ISSUE THREAD

**Issue by GravelPootis1** [nullworks/cathook#436]
Do you honesly think im that stupid to ask this shit ?

I started rewriting code month ago and i need to know how much shit is there to rework.

**Comment by BenCat07** [comment]
Basically everything. Inject method,signatures, offset, bruteforcing, asm,
gcc compiler only options,....

**Comment by GravelPootis1** [comment]
Thanks faggot. Nice to meet linux user.

**Comment by Midnoclose** [comment]
Calm down homophobe. He was just trying to help you idiot

**Comment by BenCat07** [comment]
hm, i think this is a wontfix and invalid.

**Comment by Midnoclose** [comment]
Thank you BenCat07
