### ISSUE TITLE
cat_esp_box_text_position for ESP should work without cat_esp_box set to 1

### ISSUE THREAD

**Issue by snipermain** [nullworks/cathook#44]
I feel that changing the text position of the data displayed by the ESP with the cvar "cat_esp_box_text_position" should also change the position of the ESP text without the box being necessary.

(ie cat_esp_box_text_position should work with cat_esp_box set to 0)

I also propose that it be renamed to "cat_esp_text_position" to support this change.

**Comment by nullifiedcat** [comment]
This will still require calculating the box, but not rendering it, if you want to use textpos without a box rn try cat_esp_3d_box_nodraw 1

**Comment by iraizo** [comment]
Maintainer reopen this if this is still relevant.
