### ISSUE TITLE
What do the lag bots do to lag servers? Can you please comment a snippet of the code that does it?

### ISSUE THREAD

**Issue by duckymomo360** [nullworks/cathook#442]
I really want to know how they work.

**Comment by duckymomo360** [comment]
I cant find the function that lags

**Comment by duckymomo360** [comment]
Is it the micspam part?

**Comment by hkva** [comment]
https://github.com/nullworks/cathook/blob/master/src/hooks/CreateMove.cpp#L512

**Comment by duckymomo360** [comment]
thanks!
