### ISSUE TITLE
mouse sometimes does not reintegrate into game after opening cathook menu

### ISSUE THREAD

**Issue by snipermain** [nullworks/cathook#45]
Occasionally my mouse tends to not re-integrate properly into the game after opening the cathook menu, causing my head movement to be locked to around 45 degrees, and my mouse to stay visible. After waiting a seemingly random amount of time (usually less than a minute) the problem disappears and I can play the game normally. This usually only ever happens once per injection, then never bothers me again until I relaunch tf2.

**Comment by nullifiedcat** [comment]
Can be fixed by using cl_software_cursor 1, I've tried to fix this bug before but no success, just use software cusror.

**Comment by daniel11609** [comment]
For me cl_software_cursor 0 helps fixing a weird mouse bug main menu where my cursor is locked in the middle of the screen

**Comment by nullifiedcat** [comment]
That's source engine weirdness.

**Comment by nullifiedcat** [comment]
I've added `cat_experimental_cursor_fix` convar recently btw,you should try it

**Comment by BenCat07** [comment]
Fixed since a while and i added a con command to lock the cursor (cat_fix_cursor)
