### ISSUE TITLE
uh ik im retarded but help

### ISSUE THREAD

**Issue by Clairnet** [nullworks/cathook#451]
clairnet@clairnet-OptiPlex-7010:~/cathook$ sudo ./attach-backtrace
Running instances: 23409
Attaching to 23409
Running instances: 23409
Detaching from 23409
realpath: bin/libcathook.so: No such file or directory
realpath: bin/libcathook.so: No such file or directory
[New LWP 23410]
[New LWP 23412]
[New LWP 23417]
[New LWP 23418]
[New LWP 23430]
[New LWP 23432]
[New LWP 23439]
[New LWP 23440]
[New LWP 23441]
[New LWP 23442]
[New LWP 23458]
[New LWP 23459]
[New LWP 23460]
[New LWP 23461]
[New LWP 23462]
[New LWP 23463]
[New LWP 23465]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0xef89ac2d in ?? () from /home/clairnet/.steam/steam/steamapps/common/Team Fortress 2/bin/shaderapidx9.so
$1 = (void *) 0xf7f78940
$2 = 0
$3 = 0
Detached
realpath: bin/libcathook.so: No such file or directory
already loaded

**Comment by BenCat07** [comment]
You didn't compile cathook

**Comment by Clairnet** [comment]
uh how?

**Comment by buyBread** [comment]
to compile cathook:  
`mkdir build && cd build && cmake .. && make && sudo make data`  
and if you have any errors `git clone` [libxoverlay](https://github.com/nullworks/libxoverlay), [libglew](https://github.com/nullworks/libglez) and [simple-ipc](https://github.com/nullworks/simple-ipc) cd into them and do `mkdir build && cd build && cmake .. && make && sudo make install` if you havent installed them.

**Comment by Clairnet** [comment]
CMake Error: The source directory "/home/clairnet/cathook" does not appear to contain CMakeLists.txt. i did everything above but that happens after i try to build cathook

**Comment by BenCat07** [comment]
simply means you deleted CMakeLists.txt or using a stone age cathook version

2018-05-25 12:08 GMT+02:00 Clairnet <notifications@github.com>:

**Comment by TotallyNotElite** [comment]
If you are still having problems, I suggest that you use the install script for ubuntu/ubuntu based systems. `wget https://raw.githubusercontent.com/nullworks/cathook/master/install-all && bash install-all`

**Comment by Clairnet** [comment]
no work @TotallyNotElite  wget https://raw.githubusercontent.com/nullworks/cathook/master/install-all && bash install-all
--2018-06-04 04:40:08--  https://raw.githubusercontent.com/nullworks/cathook/master/install-all
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.48.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.48.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 986 [text/plain]
Saving to: ‘install-all.2’

install-all.2       100%[===================>]     986  --.-KB/s    in 0s      

2018-06-04 04:40:09 (119 MB/s) - ‘install-all.2’ saved [986/986]

rm: cannot remove '../install-all': No such file or directory
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://dl.google.com/linux/chrome/deb stable Release                     
Hit:3 http://us.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:4 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease              
Ign:6 http://ppa.launchpad.net/noobslab/themes/ubuntu bionic InRelease         
Hit:8 http://archive.canonical.com/ubuntu bionic InRelease                     
Hit:9 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease           
Hit:10 http://ppa.launchpad.net/numix/ppa/ubuntu bionic InRelease              
Hit:11 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic InRelease
Err:12 http://ppa.launchpad.net/noobslab/themes/ubuntu bionic Release          
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/noobslab/themes/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
mkdir: cannot create directory ‘build’: File exists
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindPNG.cmake:144 (find_package_handle_standard_args)
  CMakeLists.txt:17 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/clairnet/libglez/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
mkdir: cannot create directory ‘build’: File exists
CMake Error at /usr/share/cmake-3.10/Modules/FindX11.cmake:429 (message):
  Could not find X11
Call Stack (most recent call first):
  CMakeLists.txt:17 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/clairnet/libxoverlay/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
mkdir: cannot create directory ‘build’: File exists
-- Configuring done
-- Generating done
-- Build files have been written to: /home/clairnet/simple-ipc/build
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/lib/SimpleIPC-0.0.1/SimpleIPC.cmake
-- Up-to-date: /usr/local/include/SimpleIPC-0.0.1/include
-- Up-to-date: /usr/local/include/SimpleIPC-0.0.1/include/cmp.hpp
-- Up-to-date: /usr/local/include/SimpleIPC-0.0.1/include/ipcb.hpp
-- Up-to-date: /usr/local/include/SimpleIPC-0.0.1/include/util.hpp
-- Up-to-date: /usr/local/lib/SimpleIPC-0.0.1/SimpleIPCConfig.cmake
mkdir: cannot create directory ‘build’: File exists
CMake Error: The source directory "/home/clairnet" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'data'.  Stop.

**Comment by TotallyNotElite** [comment]
Uhm what GNU/Linux distribution are you running?

**Comment by Clairnet** [comment]
ubuntu

**Comment by TotallyNotElite** [comment]
For some reason your ubuntu installation isn't able to install cathooks dependencies using apt and for some reason it also isn't able to clone cathook. Are you behind a strict firewall or something?

**Comment by TotallyNotElite** [comment]
For some reason your ubuntu installation isn't able to install cathooks dependencies using apt and for some reason it also isn't able to clone cathook. Are you behind a strict firewall or something?
