### ISSUE TITLE
ESP sometimes breaks, causing it to only display when the tf2 menu is displayed

### ISSUE THREAD

**Issue by snipermain** [nullworks/cathook#46]
Another weird issue - sometimes (usually after quitting a game before it ends) the next map I load into the ESP will only appear if I open the tf2 menu overlay (such as by hitting escape, tab or the console key). This issue tends to fix itself the second the match starts - for example In the pre-match esp is broken, but it recovers after the match starts. I will add screenshots if necessary when it happens again.

**Comment by nullifiedcat** [comment]
hud_reloadscheme in tf2 console!
