### ISSUE TITLE
Memory problem?

### ISSUE THREAD

**Issue by Astr0n4ut** [nullworks/cathook#474]
Hello,

Current version crashes many times. Here's an output: https://pastebin.com/h7t0B93x

"[New Thread 0xdb28bb40 (LWP 6190)]

Thread 1 "hl2_linux" received signal SIGSEGV, Segmentation fault.
tcmalloc::SLL_Pop (list=<optimized out>) at src/linked_list.h:59
59      src/linked_list.h: Nincs ilyen fájl vagy könyvtár.
#0  tcmalloc::SLL_Pop (list=<optimized out>) at src/linked_list.h:59
#1  tcmalloc::ThreadCache::FreeList::Pop (this=0x9566930) at src/thread_cache.h:216
#2  tcmalloc::ThreadCache::Allocate (cl=<optimized out>, size=48, this=<optimized out>) at src/thread_cache.h:368
#3  (anonymous namespace)::do_malloc_small (size=48, heap=<optimized out>) at src/tcmalloc.cc:1103
#4  (anonymous namespace)::do_malloc_no_errno (size=33) at src/tcmalloc.cc:1110
#5  (anonymous namespace)::do_malloc (size=33) at src/tcmalloc.cc:1119
#6  (anonymous namespace)::do_malloc_or_cpp_alloc (size=33) at src/tcmalloc.cc:1039
#7  tc_malloc (size=33) at src/tcmalloc.cc:1578
#8  0xf451dfa2 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/libtier0.so
#9  0xf1b5cf33 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#10 0xf1b5cf7a in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#11 0xf1b5cfe9 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#12 0xf1b0fd36 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#13 0xf1b0f646 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#14 0xf1b157b9 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#15 0xf1b0f646 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#16 0xf1b15a89 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#17 0xf1b0f646 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#18 0xf1b15a89 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#19 0xf1b0f646 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#20 0xf1b15a89 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#21 0xf1b0f646 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#22 0xf1b15a89 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#23 0xf1b0f646 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#24 0xf1b157b9 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#25 0xf1b0f646 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#26 0xf1b1185c in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#27 0xe14f68ba in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#28 0xf1ab7f65 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/materialsystem.so
#29 0xf0617ce7 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/studiorender.so
#30 0xf061a015 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/studiorender.so
#31 0xf2b8a24c in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#32 0xd7b5b1f0 in hooked_methods::methods::DrawModelExecute (this_=0xf31fd800, state=..., info=..., bone=0xcdcb3e0) at /home/l/cathook5/cathook/src/hooks/visual/DrawModelExecute.cpp:74
#33 0xe1201213 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#34 0xe12018ee in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#35 0xe1200d42 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#36 0xe1218c6a in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#37 0xe1770282 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#38 0xe177c6b8 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#39 0xe177ca48 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#40 0xe177f0b1 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#41 0xe17782a3 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#42 0xe1778e39 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#43 0xe177c093 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#44 0xe175f342 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#45 0xe11c0a71 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#46 0xf2c8b0b0 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#47 0xf2b4767b in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#48 0xf2b57c79 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#49 0xf2b5d8d5 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#50 0xf2b77447 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#51 0xf2b777a6 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#52 0xf2b777ed in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#53 0xf2c6839b in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#54 0xf2c64010 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#55 0xf2c6413d in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#56 0xf2cce3a8 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#57 0xf2c65e0f in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#58 0xf456f118 in ?? ()
#59 0xf456f118 in ?? ()
#60 0xf454e7cf in ?? ()
#61 0x080487ed in main ()"

**Comment by BenCat07** [comment]
in fixing

**Comment by BenCat07** [comment]
this seems to be fixed/not a cathook issue
