### ISSUE TITLE
Hard framedrop, visual & sound bug

### ISSUE THREAD

**Issue by Astr0n4ut** [nullworks/cathook#475]
Hello,

At Thunder Mountain map this bug comes out often:
Hard framrdrop: fps is 3-5, red lines everywhere, sounds of steps sound like accelerated to double.
Meanwhile backstrace has this line:
Thread 6 "SDLAudioDev2" hit Catchpoint 1 (call to syscall exit), 0xf7fc0db9 in __kernel_vsyscall ()

Here's a screenshot
![spectacle j14329](https://user-images.githubusercontent.com/38861107/40640656-40c61926-6317-11e8-9ec2-7a7757ff557a.png)

**Comment by BenCat07** [comment]
i need the whole backtrace

**Comment by BenCat07** [comment]
also, show me what setting you use (preferrably save with cat_save cfgname and attach here)

**Comment by Astr0n4ut** [comment]
Ok.: 
l@ASZTALI:~/catjook3/cathook$ sudo ./attach-backtrace
[sudo] l jelszava: 
Running instances: 14239
Attaching to 14239
Running instances: 14239
Detaching from 14239
not found!
loading /home/l/catjook3/cathook/bin/libcathook.so to 14239
[New LWP 14240]
[New LWP 14242]
[New LWP 14243]
[New LWP 14250]
[New LWP 14252]
[New LWP 14254]
[New LWP 14255]
[New LWP 14256]
[New LWP 14257]
[New LWP 14271]
[New LWP 14272]
[New LWP 14273]
[New LWP 14274]
[New LWP 14275]
[New LWP 14276]
[New LWP 14277]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0xf7fc0db9 in __kernel_vsyscall ()
[New Thread 0xd6e4fb40 (LWP 14300)]
$1 = (void *) 0x38ef4680
$2 = 0
$3 = 0x0
Catchpoint 1 (syscalls 'exit' [1] 'exit_group' [252])
[New Thread 0xd3cdfb40 (LWP 14301)]
[New Thread 0xe2cbdb40 (LWP 14307)]
[New Thread 0xd953bb40 (LWP 14309)]
[Switching to Thread 0xe777eb40 (LWP 14252)]

Thread 6 "SDLAudioDev2" hit Catchpoint 1 (call to syscall exit), 0xf7fc0db9 in __kernel_vsyscall ()
#0  0xf7fc0db9 in __kernel_vsyscall ()
#1  0xf7f1f361 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#2  0xf7e4a0ae in clone () from /lib/i386-linux-gnu/libc.so.6

And (saved complete):

cat_anti_votekick "0"
cat_votelog_requeue "1"
cat_votelog "0"
cat_crit_experimental "1"
cat_crit_force_gameplay "0"
cat_crit_melee "1"
cat_crit_key "107"
cat_crit_info "0"
cat_fast_outline "0"
cat_gui_ncc_font_title_family "4"
cat_gui_ncc_font_family "3"
cat_gui_ncc_scale "1.350000"
cat_gui_rainbow "0"
cat_gui_color_a "130"
cat_gui_color_b "150"
cat_gui_color_g "150"
cat_gui_color_r "15"
cat_gui_bounds "0"
cat_gui_visible "0"
cat_events "0"
cat_disconnect_reason ""
cat_rollspeedhack "0"
cat_log "0"
cat_thirdperson "0"
cat_thirdperson_angles "1"
cat_ignore_taunting "1"
cat_enabled "1"
cat_name ""
cat_fidgetspinner_min_speed "2"
cat_fidgetspinner_scale "32"
cat_fidgetspinner_decay_speed "0.1"
cat_fidgetspinner_speed_scale "0.03"
cat_fidgetspinner_speed_cap "30"
cat_nullcore_mode "0"
cat_fidgetspinner "0"
cat_aimbot_fov_draw "1"
cat_aimbot_auto_unzoom "0"
cat_aimbot_auto_zoom "0"
cat_aimbot_spin_up "1"
cat_debug_aimbot_engine_pp "0"
cat_aimbot_debug "0"
cat_aimbot_miss_chance "0.000000"
cat_aimbot_huntsman_charge "0.5"
cat_aimbot_proj_speed "0"
cat_aimbot_proj_gravity "0"
cat_aimbot_projectile "1"
cat_aimbot_slow "0"
cat_aimbot_extrapolate "1"
cat_aimbot_maxrange "0"
cat_aimbot_only_when_can_shoot "0"
cat_aimbot_zoomed "0"
cat_aimbot_hitbox "0"
cat_aimbot_target_lock "1"
cat_aimbot_silent "1"
cat_aimbot_teammates "0"
cat_aimbot_rage_only "0"
cat_aimbot_stickys "0"
cat_aimbot_buildings_other "1"
cat_aimbot_buildings_sentry "1"
cat_aimbot_ignore_deadringer "1"
cat_aimbot_ignore_cloak "1"
cat_aimbot_ignore_hoovy "0"
cat_aimbot_ignore_vaccinator "1"
cat_aimbot_charge "0"
cat_aimbot_prioritymode "3"
cat_aimbot_fov_draw_opacity "0.660000"
cat_aimbot_fov "14.400000"
cat_aimbot_hitboxmode "0"
cat_aimbot_autoshoot "1"
cat_aimbot_aimkey_mode "0"
cat_aimbot_aimkey "0"
cat_aimbot_enabled "1"
cat_deadringer_auto "0"
cat_cbu_micspam_off_interval "60"
cat_cbu_micspam_on_interval "3"
cat_cbu_micspam "0"
cat_cbu_random_votekicks "0"
cat_cbu_mark_human_threshold "2"
cat_cbu_abandon_if_players_lte "0"
cat_cbu_abandon_if_humans_lte "0"
cat_cbu_abandon_if_ipc_bots_gte "0"
cat_cbu_abandon_if_bots_gte "0"
cat_cbu "0"
cat_uberspam_file "uberspam.txt"
cat_uberspam_team "1"
cat_uberspam_build "25"
cat_uberspam_ended "1"
cat_uberspam_used "1"
cat_uberspam_ready "1"
cat_uberspam "0"
cat_detonator_legit "1"
cat_detonator_enabled "1"
cat_autoqueue "0"
cat_autojoin_class "0"
cat_autojoin_team "0"
cat_bhop_enabled "1"
cat_aa_aaaa_flip_key "0"
cat_aa_aaaa_mode "0"
cat_aa_aaaa_interval_low "3"
cat_aa_aaaa_interval_high "15"
cat_aa_aaaa_interval "0"
cat_aa_aaaa_enabled "0"
cat_aa_spin "10.0"
cat_aa_no_clamp "0"
cat_aa_roll "0"
cat_aa_pitch_mode_real "0"
cat_aa_yaw_mode_real "0"
cat_aa_pitch_mode "0"
cat_aa_yaw_mode "0"
cat_aa_pitch_real "-89.0"
cat_aa_yaw_real "0.0"
cat_aa_pitch "-89.0"
cat_aa_yaw "0.0"
cat_aa_realfakes "0"
cat_aa_enabled "0"
cat_identify "0"
cat_killstreak "1"
cat_autotaunt_chance "8"
cat_autotaunt "0"
cat_infinite_packs "1"
cat_se_cap_range "200.0f"
cat_se_value "900"
cat_se_master "0"
cat_se_switch_delay2 "0"
cat_se_switch_delay1 "0"
cat_se_switch_key "0"
cat_se_key "0"
cat_se_switch "0"
cat_se_cart "1"
cat_se_cap "0"
cat_se_cloak "0"
cat_se_stickyspam "1"
cat_se_antirazorback "0"
cat_se_piss "0"
cat_se_doom "0"
cat_se_shoot "0"
cat_se_toggle "0"
cat_antibackstab_nope "1"
cat_antibackstab_angle "150"
cat_antibackstab_silent "1"
cat_antibackstab_distance "200"
cat_antibackstab "1"
cat_spyalert_interval "3"
cat_spyalert_sound "0"
cat_spyalert_backstab "200.0"
cat_spyalert_warning "500.0"
cat_spyalert_enabled "1"
cat_no_invis "0"
cat_antidisguise "1"
cat_fb_switch "1"
cat_fb_sync_taunt "0"
cat_fb_always_medigun "0"
cat_fb_mimic_slot "0"
cat_fb_steam "0"
cat_fb_activation "175"
cat_fb_distance "175"
cat_fb_draw "1"
cat_fb_roaming "0"
cat_fb "0"
cat_reflect_fov_draw_opacity "0.7"
cat_reflect_fov_draw "0"
cat_reflect_fov "85"
cat_reflect_teammates "0"
cat_reflect_stickybombs "0"
cat_reflect_key "0"
cat_reflect_dodgeball "0"
cat_reflect_legit "0"
cat_reflect_only_idle "0"
cat_reflect_enabled "0"
cat_announcer "0"
cat_esp_entity_id "1"
cat_esp_model_name "0"
cat_esp_entity "0"
cat_esp_proj_enemy "1"
cat_esp_proj_stickies "1"
cat_esp_proj_pipes "1"
cat_esp_proj_arrows "1"
cat_esp_proj_rockets "1"
cat_esp_proj "1"
cat_esp_item_adrenaline "0"
cat_esp_weapon_spawners "1"
cat_esp_spellbooks "1"
cat_esp_money_red "1"
cat_esp_money "1"
cat_esp_item_powerups "1"
cat_esp_item_health "1"
cat_esp_item_ammo "0"
cat_esp_item_weapons "0"
cat_esp_item "1"
cat_esp_powerups "1"
cat_esp_followbot_id "1"
cat_esp_ubercharge "1"
cat_esp_conds "1"
cat_esp_class "1"
cat_esp_name "1"
cat_esp_distance "1"
cat_esp_weapon "0"
cat_esp_show_tank "1"
cat_esp_teammates "0"
cat_esp_buildings "1"
cat_esp_local "1"
cat_esp_legit "0"
cat_esp_vischeck "1"
cat_esp_expand "0"
cat_esp_text_position "0"
cat_esp_sightlines "0"
cat_esp_bones "0"
cat_esp_health "3"
cat_esp_emoji_min_size "20"
cat_esp_emoji_scaling "1"
cat_esp_emoji_size "32"
cat_esp_okhand "0"
cat_esp_emoji "0"
cat_esp_tracers "0"
cat_esp_box_corner_size "10"
cat_esp_box "2"
cat_esp_enabled "0"
cat_ac_ignore_local "1"
cat_ac_chat "0"
cat_ac_enabled "0"
cat_achievement_safety "1"
cat_wb_leave_if_empty "0"
cat_wb_force_slot "1"
cat_wb_connection_flags "1"
cat_wb_replay_reach_distance "32"
cat_wb_replay_max_distance "100"
cat_wb_node_spawn_distance "54"
cat_wb_freemove "1"
cat_wb_indices "0"
cat_wb_nodes "1"
cat_wb_path "1"
cat_wb_info "1"
cat_wb_recording "0"
cat_killsay_file "killsays.txt"
cat_killsay "0"
cat_ac_aimbot_detections "3"
cat_ac_aimbot_angle "30"
cat_ac_aimbot "1"
cat_ac_bhop_count "4"
cat_spam_teamname "0"
cat_spam_voicecommand "0"
cat_spam_delay "800"
cat_spam_file "spam.txt"
cat_spam_random "0"
cat_spam "0"
cat_autobackstab_range "110.0f"
cat_autobackstab "1"
cat_noisemaker "0"
cat_trigger_delay "2.000000"
cat_trigger_maxrange "0"
cat_trigger_zoomed "0"
cat_trigger_charge "0"
cat_trigger_teammates "0"
cat_trigger_stickys "0"
cat_trigger_buildings_other "1"
cat_trigger_buildings_sentry "1"
cat_trigger_ignore_cloak "1"
cat_trigger_ignore_hoovy "1"
cat_trigger_ignore_vaccinator "1"
cat_trigger_accuracy "1"
cat_trigger_hitboxmode "0"
cat_trigger_key_mode "0"
cat_trigger_key "0"
cat_trigger_enabled "1"
cat_auto_vacc "0"
cat_auto_vacc_default_resist "0"
cat_auto_vacc_blast_pop_ubers "0"
cat_auto_vacc_fire_pop_ubers "0"
cat_auto_vacc_bullet_pop_ubers "0"
cat_auto_vacc_reset_timer "200"
cat_auto_vacc_rocket_range "650"
cat_auto_vacc_blast "1"
cat_auto_vacc_blast_pop_crit "1"
cat_auto_vacc_blast_pop_health "80"
cat_auto_vacc_pyro_range "450"
cat_auto_vacc_afterburn "1"
cat_auto_vacc_fire_pop_pyro "1"
cat_auto_vacc_fire "1"
cat_autoheal_ignore ""
cat_auto_vacc_sniper_pop "1"
cat_auto_vacc_bullets "1"
cat_autoheal_share_uber "1"
cat_autoheal_uber_health "30"
cat_autoheal_uber "1"
cat_autoheal_silent "1"
cat_autoheal_enabled "0"
cat_godmode "0"
cat_show_spectators "0"
cat_tauntslide_tf2 "0"
cat_tauntslide "0"
cat_no_homo "1"
cat_nopush_enabled "0"
cat_render_zoomed "0"
cat_auto_strafe "1"
cat_anti_afk "1"
cat_request_balance_spam "0"
cat_flashlight "0"
cat_debug_info "0"
cat_skinchanger_debug "0"
cat_skinchanger "1"
cat_sticky_legit "0"
cat_sticky_buildings "1"
cat_sticky_enabled "0"
cat_healarrow_callout_text "Hey %%, I've just healed you for $$ HP! Your health is now ##."
cat_healarrow_callout "0"
cat_healarrow "0"
cat_healarrow_timeout "2"
cat_healarrow_charge "0.25"
cat_debug_pp_rocket_time_ping "0"
cat_debug_pp_extrapolate "0"
cat_debug_engine_pred_others "0"
cat_debug_tcm "1"
cat_chat_log_noipc "1"
cat_chat_log_nospam "1"
cat_chat_log "0"
cat_bptf_enable "0"
cat_autoqueue_mode "7"
cat_setupbones_time "3"
cat_chams_self_b "0"
cat_chams_self_g "0"
cat_chams_self_r "0"
cat_chams_self_team "0"
cat_chams_self_rainbow "1"
cat_chams_self "0"
cat_chams_singlepass "0"
cat_chams_legit "0"
cat_chams_weapons_white "0"
cat_chams_recursive "1"
cat_chams_teammate_buildings "0"
cat_chams_stickies "0"
cat_chams_buildings "1"
cat_chams_ammo "0"
cat_chams_medkits "0"
cat_chams_players "1"
cat_chams_teammates "0"
cat_chams_health "0"
cat_chams_flat "0"
cat_chams_enable "1"
cat_nullcore_mode_logo "1"
cat_info_min "1"
cat_info "1"
cat_glow_solid_when "0"
cat_glow_blur_scale "5"
cat_glow_self_b "200"
cat_glow_self_g "200"
cat_glow_self_r "200"
cat_glow_self_team "0"
cat_glow_self_rainbow "1"
cat_glow_self "0"
cat_glow_weapons_white "1"
cat_glow_powerups "1"
cat_glow_teammate_buildings "0"
cat_glow_stickies "0"
cat_glow_buildings "0"
cat_glow_ammo "0"
cat_glow_medkits "0"
cat_glow_players "1"
cat_glow_teammates "0"
cat_glow_health "0"
cat_glow_enable "0"
cat_esp_color_blue_r "0"
cat_esp_color_blue_g "0"
cat_esp_color_blue_b "0"
cat_esp_color_red_r "0"
cat_esp_color_red_g "0"
cat_esp_color_red_b "0"
cat_hitrate "1"
cat_cat_event_hurt "1"
cat_software_cursor_mode "0"
cat_pure_bypass "0"
cat_no_zoom "0"
cat_no_visuals "0"
cat_clean_screenshots "1"
cat_experimental_cursor_fix "1"
cat_halloween_mode "0"
cat_skybox_changer "0"
cat_debug_log_usermessages "0"
cat_clean_chat "0"
cat_nightmode "0"
cat_name_ipc ""
cat_name_stealer "0"
cat_resolver "0"
cat_die_if_vac "0"
cat_crash_server "0"
cat_chat_censor_enabled "0"
cat_chat_censor ""
cat_chat_crypto "1"
cat_airstuck "0"
cat_chat_newlines "0"
cat_debug_log_sent_messages "0"
cat_debug_freecam "0"
cat_fov "0"
cat_fov_zoomed "0"
cat_no_hats "1"
cat_no_arms "1"
cat_medal_flip "1"
cat_servercrash "0"
cat_semiauto "0"
cat_serverlag "0"
cat_fakelag "0"
cat_debug_projectiles "0"
cat_engine_prediction "0"
cat_nolerp "0"
cat_fb_autoclass "spy"
cat_fb_autoteam "1"
cat_minigun_jump "0"
cat_ipc_update_list "1"
cat_ipc_server "cathook_followbot_server"
cat_fast_vischeck "0"
cat_debug_ve_averaging "8"
cat_debug_ve_smooth "1"
cat_debug_ve_window "0"

**Comment by BenCat07** [comment]
uhm, i am afraid the "Backtrace" does not have any crash information, i need a backtrace of when you crash

**Comment by BenCat07** [comment]
no answer. closing.
