### ISSUE TITLE
Add "Show last vote-caller" option

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#480]
This should be a useful feature... I guess.

**Comment by TotallyNotElite** [comment]
Where should this be shown? I mean, you could just activate cl_vote_ui_active_after_voting.

**Comment by Astr0n4ut** [comment]
Hmm.. I didn't know cl_vote_ui_active_after_voting option, but that doesn't work.

**Comment by BenCat07** [comment]
willadd.club

**Comment by TotallyNotElite** [comment]
Fixed in #584 by @surepy
