### ISSUE TITLE
Radar rendering issues

### ISSUE THREAD

**Issue by nullifiedcat** [nullworks/cathook#492]
Radar looks seriously messed up, some icons are invisible, some are solid color filled.

**Comment by BenCat07** [comment]
I attempted fixing it but seems likw it really doesn't wanna load the
icons, i will attempt storing the positions instead and directly loading
the textures.

nullifiedcat <notifications@github.com> schrieb am Fr., 8. Juni 2018, 21:22:

**Comment by BenCat07** [comment]
done
