### ISSUE TITLE
Buildings have 3d boxes with 2d boxes on

### ISSUE THREAD

**Issue by nullifiedcat** [nullworks/cathook#493]

**Comment by BenCat07** [comment]
That should indeed not ever happen, lemme fix that

nullifiedcat <notifications@github.com> schrieb am Fr., 8. Juni 2018, 21:40:

**Comment by TotallyNotElite** [comment]
CatVar box_3d_building is enabled by default. It souldn't render 3d boxes if this setting is disabled.
