### ISSUE TITLE
hitbox: auto-closest unreliable

### ISSUE THREAD

**Issue by FeynmanTech** [nullworks/cathook#5]
usually works well when aiming at the head, but not at the body

**Comment by no-boot-device** [comment]
It might be locking onto arm and hand hitboxes, which will basically just mean if you're off by even a bit you'll miss. Perhaps spine_* and pelvis hitboxes should be prioritized?

**Comment by BenCat07** [comment]
uhhh well basically nothing can be done about these hitboxes
https://www.youtube.com/watch?v=cE40EKyiONo
