### ISSUE TITLE
ESP distance limits

### ISSUE THREAD

**Issue by nullifiedcat** [nullworks/cathook#504]
This is one of the suggestions I got from responses to "how to improve cathook" question.

"ESP could only show players from certain distance"

**Comment by BenCat07** [comment]
Todo.tm


nullifiedcat <notifications@github.com> schrieb am Do., 14. Juni 2018,
13:30:

**Comment by TotallyNotElite** [comment]
I think I can do this one.

**Comment by BenCat07** [comment]
added
