### ISSUE TITLE
Chams and non-chams at same time

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#518]
Hello,

Build: 2018.06.22.18:40 UTC

At same time there are "champed" and "non-champed" players from same team.
https://youtu.be/1I-QuOWUvmw

**Comment by BenCat07** [comment]
poof, need to fix

**Comment by nullifiedcat** [comment]
Chams, not champs

**Comment by Riflerat** [comment]
From newui I never met this bug again. I close it, if you don't mind.
