### ISSUE TITLE
effect_chams::flat bug but Chams off, crash by saving

### ISSUE THREAD

**Issue by Astr0n4ut** [nullworks/cathook#519]
Hello,

By "cat_chams_enable 0" option the effect_chams::flat caused a crash. It's reproducable: cat_save blah, or cat_save_completed.
Build: 2018.06.27.09:00 .

Thread 1 "hl2_linux" received signal SIGSEGV, Segmentation fault.
0xd6688d90 in ConVar::GetString (this=0x17051d0) at /home/l/catjook7/cathook/external/source-sdk-2013-headers/mp/src/public/tier1/convar.h:445
445             if ( m_nFlags & FCVAR_NEVER_AS_STRING )
#0  0xd6688d90 in ConVar::GetString (this=0x17051d0) at /home/l/catjook7/cathook/external/source-sdk-2013-headers/mp/src/public/tier1/convar.h:445
#1  0xd6688de8 in CatVar::GetString (this=0xd7dafba0 <effect_chams::flat>) at /home/l/catjook7/cathook/include/core/cvwrapper.hpp:135
#2  0xd66f2341 in hacks::tf2::global::runcfg () at /home/l/catjook7/cathook/src/core/cvwrapper.cpp:80
#3  0xd6818e73 in hooked_methods::methods::CreateMove (this_=0xe216d040, input_sample_time=0.00532624312, cmd=0x2e641284) at /home/l/catjook7/cathook/src/hooks/CreateMove.cpp:164
#4  0xe11ae8b5 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#5  0xe0f7f74d in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#6  0xf267930a in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so

**Comment by BenCat07** [comment]
duplicate
