### ISSUE TITLE
Unable to inject

### ISSUE THREAD

**Issue by skverbox** [nullworks/cathook#524]
Every time i try to inject i receive an error: 
/build/gcc/src/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/ext/new_allocator.h: No such file or directory.
And tf2 terminates.

OS: Arch Linux x86_64
Kernel: 4.17.3-1-ARCH

**Comment by BenCat07** [comment]
gcc -v
g++ -v

must be 7 minimum

skverbox <notifications@github.com> schrieb am Do., 5. Juli 2018, 22:28:

**Comment by skverbox** [comment]
gcc -v returns gcc version 7.3.1 20180406 (GCC) 
g++ -v returns gcc version 7.3.1 20180406 (GCC)
i have gcc 7 installed and i receive the same error

**Comment by skverbox** [comment]
Running instances: 23873
Attaching to 23873
loading /tmp/.glXskVvx to 23873
[New LWP 23874]
[New LWP 23875]
[New LWP 23876]
[New LWP 23877]
[New LWP 23878]
[New LWP 23879]
[New LWP 23880]
[New LWP 23881]
[New LWP 23885]
[New LWP 23887]
[New LWP 23888]
[New LWP 23891]
[New LWP 23893]
[New LWP 23898]
[New LWP 23899]
[New LWP 23900]
[New LWP 23901]
[New LWP 23914]
[New LWP 23915]
[New LWP 23916]
[New LWP 23917]
[New LWP 23918]
[New LWP 23919]
[New LWP 23920]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0xf7f06de9 in __kernel_vsyscall ()
[New Thread 0xda187b40 (LWP 23956)]

Thread 1 "hl2_linux" received signal SIGSEGV, Segmentation fault.
0xf7e40eee in std::string::_Alloc_hider::_Alloc_hider (__a=..., __dat=0xf7f02144 <std::string::_Rep::_S_empty_rep_storage+12> "", this=0xf058b310 <clear>) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/bits/basic_string.h:3277
3277	/build/gcc/src/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/bits/basic_string.h: No such file or directory.
The program being debugged was signaled while in a function called from GDB.
GDB remains in the frame where the signal was received.
To change this behavior use "set unwindonsignal on".
Evaluation of the expression containing the function
(dlopen) will be abandoned.
When the function is done executing, GDB will silently stop.
'dlerror' has unknown return type; cast the call to its declared return type
History has not yet reached $2.
Catchpoint 1 (syscalls 'exit' [1] 'exit_group' [252])

**Comment by nullifiedcat** [comment]
Try attach-backtrace

**Comment by skverbox** [comment]
Thread 1 "hl2_linux" received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
#0  0x00000000 in ?? ()
#1  0xed883af3 in ?? () from /home/skver/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#2  0xed8851f5 in ?? () from /home/skver/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#3  0xed8858d9 in ?? () from /home/skver/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#4  0xed9e7928 in ?? () from /home/skver/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#5  0xf64180ab in ?? () from /home/skver/.local/share/Steam/steamapps/common/Team Fortress 2/bin/libtier0.so
#6  0xf6418599 in Msg () from /home/skver/.local/share/Steam/steamapps/common/Team Fortress 2/bin/libtier0.so
#7  0xf641c843 in CThread::~CThread() () from /home/skver/.local/share/Steam/steamapps/common/Team Fortress 2/bin/libtier0.so
#8  0xf7d4180b in ?? () from /lib32/libc.so.6
#9  0xf7d41876 in exit () from /lib32/libc.so.6
#10 0xce4f3fcb in crit_err_hdlr (sig_num=11, info=0xffd2e88c, ucontext=0xffd2e90c) at /home/skver/cathook/src/hack.cpp:304
#11 <signal handler called>
#12 0xf7b5d6ec in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) () from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/32/libstdc++.so.6
#13 0xce68bd17 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /home/skver/cathook/src/hooks/DispatchUserMessage.cpp:25
#14 0xce68ca5b in _GLOBAL__sub_I_DispatchUserMessage.cpp(void) () at /home/skver/cathook/src/hooks/DispatchUserMessage.cpp:277
#15 0xf7faff93 in ?? () from /lib/ld-linux.so.2
#16 0xf7fb00a5 in ?? () from /lib/ld-linux.so.2
#17 0xf7fb42c3 in ?? () from /lib/ld-linux.so.2
#18 0xf7e4fe75 in _dl_catch_error () from /lib32/libc.so.6
#19 0xf7fb3a49 in ?? () from /lib/ld-linux.so.2
#20 0xf7f11adb in ?? () from /lib32/libdl.so.2
#21 0xf7e4fe75 in _dl_catch_error () from /lib32/libc.so.6
#22 0xf7f1145e in ?? () from /lib32/libdl.so.2
#23 0xf7f11b65 in dlopen () from /lib32/libdl.so.2
#24 0xf7f8635b in dlopen () from /home/skver/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so
#25 <function called from gdb>
#26 0xf7f9faf9 in __kernel_vsyscall ()
#27 0xf7f02923 in nanosleep () from /lib32/libpthread.so.0
#28 0xf5dacb1b in ?? () from /home/skver/.local/share/Steam/steamapps/common/Team Fortress 2/bin/libSDL2-2.0.so.0
#29 0xf5d2940e in ?? () from /home/skver/.local/share/Steam/steamapps/common/Team Fortress 2/bin/libSDL2-2.0.so.0
#30 0xf5d241a6 in SDL_WaitEventTimeout () from /home/skver/.local/share/Steam/steamapps/common/Team Fortress 2/bin/libSDL2-2.0.so.0
#31 0xed9ecb2a in ?? () from /home/skver/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#32 0xed9e8b40 in ?? () from /home/skver/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#33 0xed9e8c6d in ?? () from /home/skver/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#34 0xeda50d88 in ?? () from /home/skver/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#35 0xed9ea9bf in ?? () from /home/skver/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#36 0xf646e428 in ?? ()
#37 0xf646e428 in ?? ()
#38 0xf644e896 in ?? ()
#39 0x080487ed in main ()

**Comment by skverbox** [comment]
What should I do

**Comment by TotallyNotElite** [comment]
Fixing soon™ when I PR my changes.

**Comment by TotallyNotElite** [comment]
Fixed in 3d7842033f36dcb7e65c7b3e3576faa982a0081a
