### ISSUE TITLE
For Followbot: running more clients of TF2. How?

### ISSUE THREAD

**Issue by Astr0n4ut** [nullworks/cathook#527]
Hello,

I watched the "how-to https://www.youtube.com/watch?v=kns5-nw7xUg" and at beginning of video seems like the guy runs 2 different TF2 clients. The configuration and setup of Followbot is not difficult  to me, but I can't find out how to run parallel 2 clients on a PC without virtualization. (Renaming of hl2_linux if is not good idea...)
How do you do that?

**Comment by BenCat07** [comment]
/tmp/source-engine*.lock

Astr0n4ut <notifications@github.com> schrieb am Di., 10. Juli 2018, 18:47:

**Comment by Astr0n4ut** [comment]
oh, my!  Yes, thx.
