### ISSUE TITLE
Crash when injecting

### ISSUE THREAD

**Issue by nekafn** [nullworks/cathook#528]
System: Arch linux
All packages is up to date.
Used an automatic install script to install.
Output from gdb: https://pastebin.com/jdQjKTPH
And also i found some log files from /tmp. idk do i need to include them, but i'll include them anyway:
https://pastebin.com/SpBS1pVK
https://pastebin.com/UQb0UXZj

**Comment by TotallyNotElite** [comment]
Idk what causes this but the relevant line is https://github.com/nullworks/libglez/blob/cxx/src/detail/font.cpp#L11

**Comment by nekafn** [comment]
btw, i just tried to build without gui, but it didnt work either.

**Comment by BenCat07** [comment]
make data?

**Comment by BenCat07** [comment]
chmod -R 777 /opt/cathook
?

**Comment by nekafn** [comment]
did both of it, multiple times. same results

**Comment by TotallyNotElite** [comment]
Please verify that `rsync` is installed and run `make data`. After that please show us the content of the directory `/opt/cathook/data`. The current install script currently does not install rsync by default (this is fixed in my dev branch).

**Comment by nekafn** [comment]
i found something interesting!
when trying to run preload.sh, it gives this: https://pastebin.com/N6mixchK
and when im trying to run /usr/lib/libstdc++.so.6, it gives this: Segmentation fault (core dumped)

**Comment by nekafn** [comment]
btw!
there's no libstdc++.so.6 in /usr/lib/i386-linux-gnu/
but in /usr/lib/
atleast for me

**Comment by BenCat07** [comment]
always depends, for me it was there, i took a list of attached libs in i386, preload.sh is kinda buggy, use attach libnamed

**Comment by BenCat07** [comment]
you are also missing some (sub)dependencies?

**Comment by BenCat07** [comment]
And in general, VM = no go for this

**Comment by nekafn** [comment]
>you are also missing some (sub)dependencies?
if just dependencies, i have them all. but i dont really understand what do you mean by sub-dependencies.
>And in general, VM = no go for this
i dont have vm, its just my shitty computer.

**Comment by nekafn** [comment]
also i found out that even 16 gb of ram wont help, atleast i found one guy with that amount of ram and with the same segmentation error.

**Comment by nekafn** [comment]
[nekafn@nekafn ~]$ glxinfo | grep "OpenGL version"
OpenGL version string: 3.3.0 NVIDIA 340.107

**Comment by nekafn** [comment]
or this

GLX version: 1.4
OpenGL core profile version string: 3.3.0 NVIDIA 340.107
OpenGL core profile shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL version string: 3.3.0 NVIDIA 340.107
OpenGL shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL ES profile version string: OpenGL ES 2.0 NVIDIA 340.107 340.107
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.00

**Comment by BenCat07** [comment]
Your openGL version is too Old, you NEED 1.30 in GLSL or above

**Comment by nekafn** [comment]
and... how do i update it?

**Comment by BenCat07** [comment]
1. Get a New PC
2. Replace the Graphics card
3. Try getting drivers for your specific Graphic card and look if it helps

**Comment by BenCat07** [comment]
one of these

**Comment by nekafn** [comment]
my gpu is too old for cheat lol
anyways, gonna try and play with drivers with hope. thanks for the answer.

**Comment by BenCat07** [comment]
rip

**Comment by BenCat07** [comment]
the error is a error in glez++, which uses OpenGL to redner shaders and stuff, it segfaults because your GLSL version is too old

**Comment by nekafn** [comment]
oh ok lol
