### ISSUE TITLE
libglez won't compile

### ISSUE THREAD

**Issue by betocarrero** [nullworks/cathook#532]
https://pastebin.com/wbb65tVc
cmake 3.12

**Comment by BenCat07** [comment]
properly link gcc-7 and g++-7 to your usr/lib/{gcc, g++}

**Comment by BenCat07** [comment]
to test: g++ -v
gcc -v

**Comment by betocarrero** [comment]
That was it, thanks.

**Comment by BenCat07** [comment]
np
