### ISSUE TITLE
Content of memory saves into cfg files

### ISSUE THREAD

**Issue by Astr0n4ut** [nullworks/cathook#533]
(The Subject of this issue wanted to be the Cathook saves content of memory into the cfg files. Please edit that.)

Hello, Developers,

More times happened by saving cfg, the cfg file's size will be very large (now 818 MB) and those contains a part of memory. Those begins with real cfg lines after the elements of memory.

That's a sample:

(Just for the easier visibility selected the lines longer than 30 chars):

$strings cat_cat_sniper.cfg | awk 'length($0) > 30'

https://pastebin.com/1FnJc09m

-rw-rw-r-- 1 l l 858529792 júl   24 14:03 cat_sniper.cfg

Not every time, but sometimes after the save the TF2 crashed:

Thread 1 "hl2_linux" received signal SIGSEGV, Segmentation fault.
0xd6e7dd90 in ConVar::GetString (this=0x11d3040) at /home/l/catjook7/cathook/external/source-sdk-2013-headers/mp/src/public/tier1/convar.h:445
445             if ( m_nFlags & FCVAR_NEVER_AS_STRING )
#0  0xd6e7dd90 in ConVar::GetString (this=0x11d3040) at /home/l/catjook7/cathook/external/source-sdk-2013-headers/mp/src/public/tier1/convar.h:445
#1  0xd6e7dde8 in CatVar::GetString (this=0xd85a4d80 <effect_chams::ammobox>) at /home/l/catjook7/cathook/include/core/cvwrapper.hpp:135
#2  0xd6ee7750 in hacks::tf2::global::runcfg () at /home/l/catjook7/cathook/src/core/cvwrapper.cpp:115
#3  0xd700de73 in hooked_methods::methods::CreateMove (this_=0xe1d4c040, input_sample_time=0.0124420086, cmd=0x2f7b30c4) at /home/l/catjook7/cathook/src/hooks/CreateMove.cpp:164
#4  0xe0d8d815 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#5  0xe0b5e3dd in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#6  0xf265864a in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#7  0xf270ca61 in ?? () from /mnt/large/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so

**Comment by Astr0n4ut** [comment]
I met same situation when the program uses simple line db and the,  file db was opened too early gratuitously.

**Comment by BenCat07** [comment]
CatVar issue...

**Comment by nullifiedcat** [comment]
Will be fixed with new variable system.
