### ISSUE TITLE
Crash for cat_load command

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#557]
Hello,

I just gave the `cat_load blah` command out, where blah.conf exists, a conf that was working earlier.

Segfault.log: https://pastebin.com/Mzay2KH0
Version: 9cb761a

**Comment by TotallyNotElite** [comment]
I don't really know what the cause of these issues could be. Pinging @nullifiedcat to take a look at this and #547 cat_save issue. I didn't crash on cat_load yet (thank god) but cat_save is something that happened to me as well.

**Comment by Astr0n4ut** [comment]
None of both is reproducible easily. When my client was running (with cathook) over 2-3 rounds, the chance of crash for cat_save and cat_load is more higher. (So I think a variable with too high value may causes the crash... Or similar. )

**Comment by BenCat07** [comment]
https://github.com/nullworks/cathook/issues/566 is now the main thread for save/load crashes
