### ISSUE TITLE
Projectile prediction needs manual configuration to actually work well

### ISSUE THREAD

**Issue by no-boot-device** [nullworks/cathook#56]
Okay, so, if you actually put in the projectile speed and such for weapons if you're, say, using loch n load, it'll either aim a bit too high or just not predict where the player's going to be that well.
Apparently, leaving the projectile stuff at 0 doesn't automatically make the numbers for each weapon you use fill in correctly.

Honestly,
1. this isn't clear at all and I only found out when Fuccy pointed it out
2. this makes it annoying to switch classes/weapons
3. I'm pretty sure this isn't even intended

Apparently the pill aimbot just either doesn't account for air-drag or has too high of a default gravity, according to them. Honestly, I'd have no clue.

(Oh, also, there's no way to set your gravity to 0 and not just "auto", so there's that too.)

EDIT: Yeah ok, apparently this is a TODO? I'm still leaving this issue here because it's still definitely an issue. https://github.com/nullifiedcat/cathook/blob/master/src/helpers.cpp#L519

**Comment by nullifiedcat** [comment]
Projectile prediction is fucked up in general - it works good with direct hit and rocket launcher, decent with huntsman and it sucks with pills. I'll have to do a lot of work to make it good on all weapons.

**Comment by BenCat07** [comment]
Fixed pills huntsman and many more, so closing i guess
