### ISSUE TITLE
cat_pl_set_state and cat_pl_load doesn't work.

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#567]
Hello,

In current (b224125) version cat_pl_set_state and cat_pl_load doesn't work.

**Comment by Riflerat** [comment]
Sorry, I have to correct my issue: The cat_pl_set_state doesn't work, the cat_pl_load does.
(I manipulated the plist file and that is readable by the cathook, so cat_pl_load works.)
The cat_pl_set_state used by me earlier (2018.09.11 version) and that worked.
Now seems like end of rounds the plist writer subroutine runs but new key-values pairs are not included.

**Comment by BenCat07** [comment]
cat_pl_set_state was changed in a recent commit, type cat_pl_set_state
(username) (state name) instead

**Comment by Riflerat** [comment]
Ooops! That was my mistake....
Cathook really need user manual. :-)

**Comment by Riflerat** [comment]
Oh, no!

Please make that we can use cat_pl_set_state with steamID ([U:1:8x9x2x83] format) 'cos with the very idiot unicode names the command doesn't work. (Like `cat_pl_set_state ɖɤǟͣƀŁơ RAGE`... )

**Comment by TotallyNotElite** [comment]
Will look into this soon.
