### ISSUE TITLE
Stop!

### ISSUE THREAD

**Issue by Hampusm** [nullworks/cathook#568]
# Stop this madness!

Don’t you realize that this ruins the game for everyone? 
What you are doing makes tf2 a pain to play because of you people who come ruin everything by using this piece of software.

But you might not even care. You might just think ”Who cares. I’m just having fun”. But what you dont see is that you ruin Team Fortress 2. A lot of people care. A lot of people love this game. A lot of people care for this game. For you to come ruin everything is so darn cold hearted and cruel.

And if your purpose of using this is too kill tf2 then i have a question. 
Why? Why would you want to kill such a great game?

Never the less. i’ll just say. **stop**. Please **stop**. This isnt fun for anyone. You will eventually grow bored of using cathook and it wont be fun for you either.

**Comment by Riflerat** [comment]
LOL

**Comment by Hampusm** [comment]
> LOL. It's for training and who are able to use and to make build of cathook are just a few people. I guess you wanted to write your opinion to lmaobox git hub :-).

Training for what exactly?

**Comment by Riflerat** [comment]
> Training for what exactly?

Helps: knowing of: bash, Linux package handling, script writing, aiming, C programming, triggering, ergonomy of Linux, git hub using, xml format, gdb, endurance, community work etc.

**Comment by Hampusm** [comment]
> > Training for what exactly?
> 
> Helps: knowing of: bash, Linux package handling, script writing, aiming, C programming, triggering, ergonomy of Linux, git hub using, xml format, gdb, endurance, community work etc.

You can learn all of that by anything that isnt cheats

**Comment by Riflerat** [comment]
> You can learn all of that by anything that isnt cheats

Only God can be perfect.

**Comment by Hampusm** [comment]
> > You can learn all of that by anything that isnt cheats
> 
> Only God can be perfect.

Thats No excess to ruin the game for everyone

**Comment by Riflerat** [comment]
My game is not ruined by cathook. This is open source, we can check that does it make ruin of game or not. All of my games are healthy, cathook didn't ruin them. Maybe you use windows and lmabox with viruses that makes your games ruined?

**Comment by Riflerat** [comment]
What is for autism? That's a sickness that is not dangerous for your games.

**Comment by Hampusm** [comment]
> My game is not ruined by cathook. This is open source, we can check that does it make ruin of game or not. All of my games are healthy, cathook didn't ruin them. Maybe you use windows and lmabox with viruses that makes your games ruined?

What i mean by that you ruin the game (tf2) is that you ruin the enjoyment of playing the games for others

**Comment by kritzsie** [comment]
Cathook is the best thing that has happened to TF2 in years. We're just making it fun again. Valve are the ones ruining every aspect of TF2 for everyone.

**Comment by surepy** [comment]
pIssue

Your game is more likely ruined by lmaobox, lithium or nullcore (or any windows cheat) by the way.

Just look at the player numbers of linux

**Comment by official-maxbox** [comment]
I can understand were you guys are coming from, but this just ruins everyones fun and doesn't help the tf2 community in any sort of way.

**Comment by Hampusm** [comment]
@kritzsie Yeah. Making tf2 fun for you maybe. But not anyone else

**Comment by Hampusm** [comment]
@official-maxbox Hello fake Max Box
