### ISSUE TITLE
Crashes when aimbot shots sentry

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#569]
Hello All,

Version:  85995a1
Description: Aimbot on, autoshot on, aimbot on sentries is on. Aimbot turns to sentry, shots and cathooc crashes.
Crashlog: https://pastebin.com/REnsJnQx

**Comment by TotallyNotElite** [comment]
This is somehow still a thing... Looking into this now.

**Comment by TotallyNotElite** [comment]
Don't have time right now but error is in this function: https://github.com/nullworks/cathook/blob/b224125a18676bad59061180611b6de4a159f8d1/src/visual/EffectChams.cpp#L8
Target must be a player in order to not cause crashes.

**Comment by Riflerat** [comment]
> cathook/src/visual/EffectChams.cpp

Even if I don't use chams?

**Comment by Riflerat** [comment]
> cathook/src/visual/EffectChams.cpp

Even if I don't use chams?

**Comment by Riflerat** [comment]
Again when aiming and shooting to a sentry.
https://pastebin.com/xXVAdxbK
version:  6ad3cae

I won't report is anymore, I just signed this bug is still alive.

**Comment by BenCat07** [comment]
fixed since a while
