### ISSUE TITLE
Crashed donno why

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#571]
Hello all, 

Description: nothing extra, just gaming. Suddenly crashed.
Version: 44f1182 
Crashlog: https://pastebin.com/6E03h4L5

**Comment by Riflerat** [comment]
Same again, crashlog: https://pastebin.com/Bx34YVYx .

**Comment by Riflerat** [comment]
I upgraded cathook to most fresh 3b5172d , but crashed in regular situation but there was no crashlog file now.,

**Comment by Riflerat** [comment]
Again. :-(  (version: 3b5172d ) https://pastebin.com/dJ4ATCHh

**Comment by Riflerat** [comment]
> Do you mind uploading your config and telling me what class you're playing as? There is no pattern in the crashlogs.

Sorry TotallyNotElite, I coudn't see your ask. Here's the config: https://pastebin.com/S8GWiMhw.
But I have to say in last few days this crash didn't come out.

**Comment by BenCat07** [comment]
These seem to just be arbitary crashes that aren't really fixable.

**Comment by Riflerat** [comment]
In last 10 days I didn't meet this bug. Did you fix it?
