### ISSUE TITLE
Wish: forced aimbot on melee weapons when...

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#572]
Hello Developers,

I ask forced aimbot on melee weapons option when "rage only" active. I mean "force aimbot on melee" would be active or deactive when "rage only" option is on.
It should be useful when sniper aiming and an enemy (usually a spy) is going close to sniper. Because "rage only" is active the aiming not active on all.

Thank you.

**Comment by ByGlimmer** [comment]
That defeats the whole purpose of a rage target only aimbot. However, by all means, clone cathook and do some ghetto fix for your problem.

ok lemme help you:
go to line 453 of aimbot.cpp, AFTER the curly bracket
make a space
type in "if (GetWeaponMode() != weapon_melee) {" without the quotation marks
go to the end of the curly bracket after the "return false;"
make a space
type in "}"
save the file
compile

it should look like this:
        if (rageonly)
        { if (GetWeaponMode() != weapon_melee) {
            if (playerlist::AccessData(entity).state !=
                playerlist::k_EState::RAGE)
            {
                return false;
            } }
        }

then make it look better. im not gonna make it look good cuz im lazy

if you cant find out how to make the simple code look good, i have no faith in you.

**Comment by Riflerat** [comment]
Hello ByGlimmer,

Thank you very much for your code, Of course I understand your code and I know the syntactics. I just don't know the subroutines of cathook.
Also I don't understand what your code is for? As I see that does actually nothing:

```
if (rageonly)  {
                     if (GetWeaponMode() != weapon_melee) {
                          if (playerlist::AccessData(entity).state != playerlist::k_EState::RAGE)  {
                                   return false;
                          } 
                    }
}
```

**Comment by Riflerat** [comment]
I don't wanna rough anybody up the wrong way. So I made my idea with a bind script. (There's a little different, but that's more than enough for me. )

**Comment by ByGlimmer** [comment]
> Hello ByGlimmer,
> 
> Thank you very much for your code, Of course I understand your code and I know the syntactics. I just don't know the subroutines of cathook.
> Also I don't understand what your code is for? As I see that does actually nothing:
> 
> ```
> if (rageonly)  {
>                      if (GetWeaponMode() != weapon_melee) {
>                           if (playerlist::AccessData(entity).state != playerlist::k_EState::RAGE)  {
>                                    return false;
>                           } 
>                     }
> }
> ```

check if the rage only option is enabled
if yes, check if your weapon is NOT a melee weapon
if yes, check if target is NOT a rage target on the playerlist
if yes, return false, so dont aim

**Comment by Riflerat** [comment]
The solution was more easier with scripts. I use this only with sniper and triggering mode!

...->tf->cfg->sniper.cfg
> [...]
> unbind shift
> bind shift +toggleState
> alias +toggleState "exec ro_off.cfg" //rage only off
> alias -toggleState "exec ro_on.cfg //rage only on
> [...]
> 

ro_off.cfg
> > [...]
> > cat set aimbot.hitbox-mode 2
> > cat set aimbot.target.ignore-non-rage 0
> > [...]
> 

ro_on.cfg

> [...]
> cat set aimbot.hitbox-mode 1
> cat set aimbot.target.ignore-non-rage 1
> [...]
