### ISSUE TITLE
Menu visual and cat_load (again) bug

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#573]
Hello,

Description: I was playing some rounds with a loaded config, I left the server, I connected to other server. I felt there is no my config in cathook but I just left a server and connected an other one. I tried to cat_load myconfig but no results. I happened to press "ins" and saw 2 menu windows:

![screenshot_20180921_110803](https://user-images.githubusercontent.com/38861107/45871815-aa010780-bd8e-11e8-8ae4-b4ffed6d964e.png)

The right one is myconfig the left is a "stranger" config. I tried to cat_load myconfig again - during I was watching 2 menus. Nothing changed. Then I checked a cathook option: `cat get aimbot.enable` . That was false. It meant the active "config" in memory is the "stranger", the left one and cathook is not able to load myconfig, but somehow cathook can show that.
Version: 3b5172d 
Crashlog: none, no caused crash.

**Comment by BenCat07** [comment]
Reload the gui and if mouse gets stuck i added cat_fix_cursor
