### ISSUE TITLE
Disable NavBot if FollowBot finds a target within activation distance.

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#574]
Was part of the reason I suggested #213 

Have NavBot leave spawn to try and get closer to the target, then use FollowBot to follow the target's exact movement once within range. 

If FollowBot loses all targets within activation distance, switch back to NavBot to attempt to find a way to another roaming target.

**Comment by Riflerat** [comment]
Just little additional info: I never used NavBots, but 2-3 weeks ago I tried, then NavBot didn't work already. I thought I did something wrong... So it should be a little bit older bug.

**Comment by BenCat07** [comment]
Yes

**Comment by TotallyNotElite** [comment]
This is added now
