### ISSUE TITLE
cat_load bug (an other) and locked mouse cursor

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#575]
Hello,

Description: I forgot to cat_load myconfig after I started TF2. I connected upto a server, and after I called command cat_load myconfig. That caused a partial result. (Eg.: aimbot.enable, aimbot.backtrace.enable etc. loaded, but glow.enabled didn't.) I couldn't find any relationships if only visuals or only  aimbot. values loaded or not. That was a mix.
I used the cat_gui.reload command after the cat_load. Then the variables loaded well, but the active mouse cursor stayed on screen. (We were talked about it afternoon. Now I could reeducated that.) The locked cursor was blocking my ingame turning around.
I couldn't find out how to unlock mouse cursor, so I closed TF2 client and I need to restart.

**Comment by TotallyNotElite** [comment]
This could be fixed now? IDK how to test it reliably.

**Comment by Riflerat** [comment]
Just tested: seems like ok. But need more tests (need more restart and cat_load), to be sure 100%.

**Comment by Riflerat** [comment]
Seems like it fixed. I close it if you don't mind.
