### ISSUE TITLE
navbot/navfollowbot not working!!

### ISSUE THREAD

**Issue by abrohIagoksi** [nullworks/cathook#576]
I turned on the checkmarks in menu, but they don't do anything. this is how they look like https://i.imgur.com/DCJiG7N.jpg , the max range slider is on 1000.00, i tried turning off "enable navbot" and only have "enable navfollowbot" on but it didnt work, i also tried turning off "enable pathing", but not work. also, idk how to take screenshot in linux so i took camera photo with my phone, so sorry for low quality photo.

**Comment by BenCat07** [comment]
NAV bot, you actually need the nav meshes first, see:
https://github.com/BenCat07/catbot-database/tree/master/nav
Nav Bot followbot needs NavBot to be disabled btw.
