### ISSUE TITLE
Cathook crashing TF2

### ISSUE THREAD

**Issue by oliwerejder** [nullworks/cathook#578]
I get this when doing sudo ./attach and also TF2 gets frozen
`Running instances: 8244
Attaching to 8244
loading /tmp/.glQGEJGP to 8244
[New LWP 8245]
[New LWP 8247]
[New LWP 8248]
[New LWP 8249]
[New LWP 8250]
[New LWP 8251]
[New LWP 8252]
[New LWP 8253]
[New LWP 8257]
[New LWP 8260]
[New LWP 8261]
[New LWP 8284]
[New LWP 8286]
[New LWP 8289]
[New LWP 8290]
[New LWP 8291]
[New LWP 8292]
[New LWP 8307]
[New LWP 8308]
[New LWP 8309]
[New LWP 8310]
[New LWP 8311]
[New LWP 8312]
[New LWP 8315]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0xf7fc4de9 in __kernel_vsyscall ()
[New Thread 0xcced4b40 (LWP 8378)]

Thread 1 "hl2_linux" received signal SIGSEGV, Segmentation fault.
0xf7bd0bd9 in std::string::_Alloc_hider::_Alloc_hider (__a=..., __dat=0x3ee50f4c '\n' <repeats 200 times>, this=0xf0129d80 <clear>) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/ext/new_allocator.h:81
81	/build/gcc/src/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/ext/new_allocator.h: No such file or directory.
The program being debugged was signaled while in a function called from GDB.
GDB remains in the frame where the signal was received.
To change this behavior use "set unwindonsignal on".
Evaluation of the expression containing the function
(dlopen) will be abandoned.
When the function is done executing, GDB will silently stop.
'dlerror' has unknown return type; cast the call to its declared return type
History has not yet reached $2.
Catchpoint 1 (syscalls 'exit' [1] 'exit_group' [252])
[Inferior 1 (process 8244) detached]
`

**Comment by oliwerejder** [comment]
Im just bumping it incase it goes unnoticed

**Comment by BenCat07** [comment]
seems to be eithr a bad stf::strign or a bad Window/Desktop manager.

**Comment by oliwerejder** [comment]
I use antergos but i dont under what a bad stf::strign  is

**Comment by BenCat07** [comment]
std::string*

**Comment by oliwerejder** [comment]
Okay i use antergos openbox. How to fix this??? I can run games even wine geometry dash and CS GO with hacks

**Comment by BenCat07** [comment]
anyways, we had an initializer that made an std::string with 200 newlines, it just crashes for you. seems to be your Window/Desktop manager, can't really do alot about it.

**Comment by oliwerejder** [comment]
Okay so you say that the problem is very likely Windows/Desktop manager???

**Comment by TotallyNotElite** [comment]
Github wtf. Whatever. You can kill tf2 using "sudo killall -9 hl2_linux" or your task manager of choice. I've pushed a possible fix for your issue. Please update cathook using ./update and report back.

**Comment by oliwerejder** [comment]
I install it completely again i will report back when its done.

**Comment by BenCat07** [comment]
no need to reinstall completely

**Comment by BenCat07** [comment]
just ./update

**Comment by oliwerejder** [comment]
Its too late but its nearly done with downloading i think.

**Comment by oliwerejder** [comment]
Okay wtf. Now TF2 crashed after like 10 seconds. It worked for like 2 seconds before freezing and then came the crash.

**Comment by oliwerejder** [comment]
wait wtf. Dont close it but wait

**Comment by oliwerejder** [comment]
Okay GG it works thanks for the help!!!

**Comment by oliwerejder** [comment]
Do you have any rage configs for me? Please post no hvh only rage

**Comment by TotallyNotElite** [comment]
You can make your own! The UI is amazing for this!
