### ISSUE TITLE
cathook-online will crash the game if it's down.

### ISSUE THREAD

**Issue by surepy** [nullworks/cathook#579]

**Comment by surepy** [comment]
disabling cathook-online with EnableOnlineFeatures set to 0 (#580) fixed the crash.

**Comment by TotallyNotElite** [comment]
We have made the decision to no longer support cathook online due to nullifiedcat no longer working on the project.

**Comment by surepy** [comment]
So it's just gonna be removed soon right?

**Comment by TotallyNotElite** [comment]
Removed by default.  Closed.
