### ISSUE TITLE
Not injecting at all.

### ISSUE THREAD

**Issue by halfeatenhotdoglol** [nullworks/cathook#583]
Running instances: 27840
Attaching to 27840
cp: cannot stat 'bin/libcathook.so': No such file or directory
loading /tmp/.glCe2309 to 27840
[New LWP 27841]
[New LWP 27843]
[New LWP 27846]
[New LWP 27847]
[New LWP 27880]
[New LWP 27882]
[New LWP 27889]
[New LWP 27890]
[New LWP 27891]
[New LWP 27892]
[New LWP 27905]
[New LWP 27906]
[New LWP 27907]
[New LWP 27908]
[New LWP 27909]
[New LWP 27910]
[New LWP 27911]
[New LWP 27912]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0xecf51653 in ?? () from /home/lolno/.local/share/Steam/steamapps/common/Team Fortress 2/bin/vguimatsurface.so
$1 = (void *) 0x0
'dlerror' has unknown return type; cast the call to its declared return type
History has not yet reached $2.
Catchpoint 1 (syscalls 'exit' [1] 'exit_group' [252])
rm: cannot remove '/tmp/.glCe2309': No such file or directory

The last line was not there when it did work but everything else is the same, tf2 does not crash it just does not inject and I have no idea what i'm doing wrong.

**Comment by Sx50** [comment]
You didn't build cathook, hence "cp: cannot stat 'bin/libcathook.so': No such file or directory"

**Comment by halfeatenhotdoglol** [comment]
It worked before and I haven't changed anything, it started doing this yesterday.

**Comment by Riflerat** [comment]
What does say 
 **`ls -lR [path where your cathook dir. is]/cathook/bin/`** 
command?
