### ISSUE TITLE
"Can't move and shot" bug

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#585]
Hello Developers,

Description: Aimbot is only at rages option on, triggering on, zoomed only on. A "rage" aimed, scope zoomed but from that time I coudn't shot or move. (Exactly the movement is minimal but pointless. )
Edit: And couldn't unzoom too.
Version:  5f90fe3 
Video: https://youtu.be/b0c-ogtDzjQ (sorry for quality)

**Comment by BenCat07** [comment]
wtf

**Comment by BenCat07** [comment]
i can't reproduce it either

**Comment by Riflerat** [comment]
> i can't reproduce it either

As I see it's a map-specificated bug. I never memorized the map names but you see in video on that map it is reproducible. On that map this bug comes out different places too.

**Comment by TotallyNotElite** [comment]
If this issue is no longer relevant, please close it @Riflerat.

**Comment by BenCat07** [comment]
Stalemate
