### ISSUE TITLE
aimbot.backtrack, aimbot.autoshoot and aiming

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#586]
Hello Dear Developers,

I'm not sure is that bug or there is a reason why, but when
aimbot.backtrack=true and
aimbot.autoshoot=false, then
no aiming.
After aimbot.backtrack set false aiming is working. (In this config no need autoshot.)
Version:  5f90fe3

**Comment by BenCat07** [comment]
If you enable backtracking you need to enable fake latency and the actual Backtrack too
