### ISSUE TITLE
Aimbot/Triggerbot hitbox confusion

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#588]
Hello,

As I see well, when aimbot active, autoshot disabled, but triggerbot is enabled, then after the aiming when cathook shots, cathook uses aimbot's hitbox's settings not triggerbot's hitbox's settings.
Eg.: aimbot's hitbox is set as static head then triggerbot's hitbox's settings can be anything the "player" shots headshots.
Well, it can be logical of course, 'cos when aiming is active eg. to static headshot, then triggerbot "can't" do anything just shot where that can do. Ok, but the triggerbot's hitbox accuracy option is a nice feature that is not act upon to aiming as a "fine tuning".
So I'm a little bit confused: is that a bug or better call it as a wish.

**Comment by BenCat07** [comment]
yes and no, it's a bug and not at the same time, you shouldn't have head only on one and not on the other, that's pretty much it.
