### ISSUE TITLE
Wish: escape  from "last man standing" server

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#591]
Hello All,

Nightly my character is playing followbot and sometimes I find my character alone at the servers.
May be there an option somewhere that is watching the number of players at current server by eg. 5 minutes, and when the number of players is converting to 1 (or a bit higher), then  the bot should left this and find an other server.

**Comment by BenCat07** [comment]
see CBU, it has options 
![image](https://user-images.githubusercontent.com/13179138/46408896-eed45900-c713-11e8-8ee0-1f9471262991.png)
lte == Less than or equal
gte == Greater than or equal

**Comment by Riflerat** [comment]
Thank you, BetCat. I'm sorry I didn't know that.
