### ISSUE TITLE
Demoman is not aiming

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#598]
Hello,

In current version (and for a long time) demoman is not aimbotting.
I have to edit this issue: Demoman is not aimbotting **all the time**.

**Comment by BenCat07** [comment]
okay what, do you have chargeaim.enable true?

**Comment by Riflerat** [comment]
Hmm... Sorry I deatached from git. From a while possibility I had a partial old version. (Thank you Ben.) 
It would be closed.
