### ISSUE TITLE
Confusion in config once in a while

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#600]
Hello,

My bot was "working" last night and I'm sure there was all ok before I slept. At morning many settings was different in Cathook. Morning I was vague that config just changes "by myself", but now I was playing a long time and after a map changing almost all of my Cathook settings changed.
I tried cat_load my_conig back, but didn't work and the mouse cursor bug is came again.
(Sorry for many issues in a day.)

**Comment by BenCat07** [comment]
uhhh what

**Comment by BenCat07** [comment]
fixed tm
