### ISSUE TITLE
cat_nav_find causes crash

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#601]
Hello,

The NavBot was running on map but can't find targets just ran out from spawn, ran some "circles", but couldn't find the rest players, whom were fighting 2 spawns ahead. I tried cat_nav_init that didn't help after I tried the cat_nav_find then TF2 crashed.
Crashlog: https://pastebin.com/0WiFYhmg

**Comment by BenCat07** [comment]
cat_nav_find is debug stuff, the running in circled was most likely the map, i'd need a .nav file to debug further

**Comment by BenCat07** [comment]
Or atleast the map name

**Comment by Riflerat** [comment]
Upward, 1st blue spawn.

**Comment by Riflerat** [comment]
I close it. Ben fixed that.
