### ISSUE TITLE
Auto Sapper (Legit/Rage Options)

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#603]
Have Spy auto-sap nearby enemy buidings. 

Legit: User must be looking at the building to auto-sap. This should act more like a triggerbot.
Rage: Use aimbot to aim at all nearby buildings and sap 'em all.

Obviously the user must be a spy and hold the sapper out, and obviously you shouldn't try to sap items already sapped.

Correct me if I'm wrong, but I didn't see this feature within Cathook.

**Comment by BenCat07** [comment]
Huh yes this should be added

**Comment by TotallyNotElite** [comment]
This actually sounds super useful. Silent angles spin and sap everything.

**Comment by SylveonBottle** [comment]
Requesting update on this.

Currently seems to aim at buildings with your aimbot's FOV range, but I'm prefering that it would aim at buildings all around - as well as actually click on them, perhaps.
Also, shouldn't aim at buildings already sapped - this way it'll get them all instead of targeting a single one constantly.

**Comment by BenCat07** [comment]
~~TNEEEEEEEEE~~ Will look into this issue

**Comment by TotallyNotElite** [comment]
Invalid, already doing all that.

**Comment by BenCat07** [comment]
all file now
