### ISSUE TITLE
Fake Ping

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#609]
In another TF2 chat that shall not be named, you can run the following commands:

`cl_interp 0
setcvar cl_interp_ratio 0
setcvar sv_client_min_interp_ratio 0
setcvar cl_cmdrate -9999
cl_cmdrate -9999
setcvar cl_cmdrate 66`

This will result in your ping being displayed at 300 less than it really is, without any negative side-effects of the strange cl_cmdrate. 

It's just for the lols, having 1 ping is awesome. Especially if you have navbot medics running around with "BOT" in their name, everyone thinks it's a real server bot with 1 ping. 

So, p:low I suppose.

**Comment by BenCat07** [comment]
multiple things: 
1. No need for cl_interp 0, it would just fuck your own hitrate, 
2. sv_interp_ratio doesn't need to be touched either 
3. For some reason ping goes r
To normal level in cathook if you set cl_cmdrate back to 66 
4. cl_cmdrate -1 has the same effect as -9999

**Comment by BenCat07** [comment]
cat_set exists too y'know
