### ISSUE TITLE
Engineer bot kicked for too many commands - rarely places down sentry properly.

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#612]
I have a map with a nav mesh.

Navbot is set to engineer mode.

It walks out to a location, takes out the sentry, and then madly jumps and tries to left/rightclick it. 80% of the time it'll fail to place the sentry, then decide to walk to a random spot in the map - either spawn or in the middle of 2fort/harvest for some reason. Then it'll attempt to walk back to the sentry spot and do the same thing - jump, left/right click like a mad man, give up instantly and walk away.

10% of the time it'll successfully put a sentry down, the other 10% of the time the bot will get kicked for too many commands.

I don't see why engineer bot is using +attack/+jump/+crouch 30 times a second for any other reason than somebody decide to just "make it do everything and hope that it works" when they made navbot.

**Comment by BenCat07** [comment]
the bot ran somewhere else because of stay near, and yes i got to say i need to rework engineer navbot

**Comment by TotallyNotElite** [comment]
Engineer navbot was kind of a joke so don't expect it to work, if at all

**Comment by TotallyNotElite** [comment]
Engi bot has been removed

**Comment by SylveonBottle** [comment]
Damn, I actually had fun with this when it was working.  
Being able to just let cathook deal with the constant respawns until a proper sentry is up was pretty neat.

**Comment by BenCat07** [comment]
I may readd it with better code
