### ISSUE TITLE
crit only killsay

### ISSUE THREAD

**Issue by BenCat07** [nullworks/cathook#614]
![image](https://user-images.githubusercontent.com/13179138/47101596-c9c70680-d23a-11e8-98c8-37cf955404b0.png)

**Comment by BenCat07** [comment]
`event->GetInt("damagebits", 0) & (1 << 20)`

**Comment by TotallyNotElite** [comment]
wtf when did i add the newui milestone

**Comment by BenCat07** [comment]
Do.tm

**Comment by BenCat07** [comment]
yes

**Comment by BenCat07** [comment]
test

**Comment by martsklav** [comment]
Alright this is epic

**Comment by BenCat07** [comment]
a

**Comment by buyBread** [comment]
Leave a comment

**Comment by martsklav** [comment]
Hey ben   cat      o7

**Comment by AutismGaming228** [comment]
Ni gg er ???? ok fuck mah pussy like a microwave oven le xD!

**Comment by TotallyNotElite** [comment]
> Ni gg er ???? ok fuck mah pussy like a microwave oven le xD!

this is unacceptable

**Comment by AutismGaming228** [comment]
> > Ni gg er ???? ok fuck mah pussy like a microwave oven le xD!
> 
> this is unacceptable

no why wait

**Comment by AutismGaming228** [comment]
stop
