### ISSUE TITLE
Crashes or hangs

### ISSUE THREAD

**Issue by ItzNop** [nullworks/cathook#618]
I have no idea what im doing wrong (im probably just retarded)
when i run `sudo ./attach-libnamed.sh` it prints out this:

Running instances: 11651
Attaching to 11651
loading librt-2.26.3.4.so to 11651
[New LWP 11652]
[New LWP 11653]
[New LWP 11658]
[New LWP 11659]
[New LWP 11677]
[New LWP 11678]
[New LWP 11679]
[New LWP 11680]
[New LWP 11691]
[New LWP 11692]
[New LWP 11693]
[New LWP 11694]
[New LWP 11695]
[New LWP 11696]
[New LWP 11697]
[New LWP 11699]
[New LWP 11700]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0xf7efa059 in __kernel_vsyscall ()
[New Thread 0xdfeb2b40 (LWP 11723)]
$1 = (void *) 0x313f6940
'dlerror' has unknown return type; cast the call to its declared return type
History has not yet reached $2.
Catchpoint 1 (syscalls 'exit' [1] 'exit_group' [252])
[Inferior 1 (process 11651) detached]

and it crashes tf2 after 5 seconds.

running `sudo ./attach-backtrace-scramble.sh` will print the following:

Running instances: 11739
Attaching to 11739
sudo: ./detach: command not found
loading /tmp/.glyo9Khx to 11739
[New LWP 11740]
[New LWP 11741]
[New LWP 11743]
[New LWP 11744]
[New LWP 11763]
[New LWP 11764]
[New LWP 11765]
[New LWP 11766]
[New LWP 11776]
[New LWP 11777]
[New LWP 11778]
[New LWP 11779]
[New LWP 11781]
[New LWP 11782]
[New LWP 11783]
[New LWP 11785]
[New LWP 11786]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0xf7f1c059 in __kernel_vsyscall ()
[New Thread 0xdff54b40 (LWP 11812)]
$1 = (void *) 0x30f34000
'dlerror' has unknown return type; cast the call to its declared return type
A syntax error in expression, near `'.
Catchpoint 1 (syscalls 'exit' [1] 'exit_group' [252])
warning: Error reading shared library list entry at 0x4000
warning: Error reading shared library list entry at 0x4280
[Thread 0xe1ca2b40 (LWP 11786) exited]
[Thread 0xe24a3b40 (LWP 11785) exited]
[Thread 0xf26fbb40 (LWP 11783) exited]
[Thread 0xe73c9b40 (LWP 11777) exited]
[Thread 0xf517fb40 (LWP 11740) exited]
[Thread 0xf5180980 (LWP 11739) exited]
[Thread 0xe8e5cb40 (LWP 11764) exited]
[Thread 0xe8f5db40 (LWP 11763) exited]
[Thread 0xdff54b40 (LWP 11812) exited]
[Thread 0xe71c7b40 (LWP 11779) exited]
[Thread 0xe68c5b40 (LWP 11782) exited]
[Thread 0xe72c8b40 (LWP 11778) exited]
[Thread 0xe74cab40 (LWP 11776) exited]
[Thread 0xe8c5ab40 (LWP 11766) exited]
[Thread 0xe70c6b40 (LWP 11781) exited]
[Thread 0xf08f3b40 (LWP 11744) exited]
[Thread 0xf10f4b40 (LWP 11743) exited]
[Thread 0xf2a25b40 (LWP 11741) exited]

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
No stack.

(I had to force close tf2 since it just hangs and doesnt respond)

i ran the automatic install and it seemed to install every package and build cathook, but i have no idea what i'm doing wrong

(im running Kubuntu 18.04 minimal, fully updated)

**Comment by BenCat07** [comment]
We'd need a backtrace after you use attach-libnamed (/tmp/(username)-(pid).segfault.log)

**Comment by ItzNop** [comment]
Weird enough, i found a really weird way to launch it.
I execute `sudo ./attach-backtrace-scramble.sh` and i wait until it prints `warning: Error reading shared library list entry at 0x4280` then i kill it and i can use cathook.

Anyway, here's the segfault

[cathook-kasutaja-5013-segfault.log](https://github.com/nullworks/cathook/files/2514524/cathook-kasutaja-5013-segfault.log)

**Comment by BenCat07** [comment]
Is your ram Okay?

**Comment by ItzNop** [comment]
should be

**Comment by ItzNop** [comment]
i downloaded lubuntu 18.10 and now it works perfectly, dont know why it didnt work with kubuntu.

**Comment by BenCat07** [comment]
Yeah me neither, from your `warning: Error reading shared library list entry at 0x4280` it seems tf2 didn't load all shared libraries correctly or your ram was having issues

**Comment by crwn1337** [comment]
i found out what was the issue, nvidia drivers didnt work with cathook (i have an old gpu) and nouveau worked perfectly
