### ISSUE TITLE
[suggestion]Following priority

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#619]
Hello Developers,

Sometimes the bot is following a player pointlessly, eg. when the followed player is (or will be) an engineer. Also pointless following with heavy a sniper or a scout - heavy will lost path. Etc.
I suggest, the followed class(es) could be defined with priority. I guess 1-3 priority level are enough to reach the continuous movement of follower.

**Comment by BenCat07** [comment]
Already there.

**Comment by BenCat07** [comment]
Well only for medics

**Comment by Riflerat** [comment]
That was very fast, thank you!
Sorry, I can't see the form of priority levels.
