### ISSUE TITLE
um

### ISSUE THREAD

**Issue by Clairnet** [nullworks/cathook#625]
clairnet@arch ~/cathook (git)-[master] % sudo ./attach -b
./attach: line 15: [: -b: integer expression expected
Running instances: 21224
Attaching to 21224
loading /tmp/.glqtSdbh to 21224
[New LWP 21225]
[New LWP 21227]
[New LWP 21230]
[New LWP 21231]
[New LWP 21247]
[New LWP 21248]
[New LWP 21249]
[New LWP 21256]
[New LWP 21257]
[New LWP 21258]
[New LWP 21259]
[New LWP 21274]
[New LWP 21275]
[New LWP 21276]
[New LWP 21277]
[New LWP 21278]
[New LWP 21279]
[New LWP 21280]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0xf7f28de9 in __kernel_vsyscall ()
[New Thread 0xec0deb40 (LWP 21348)]
$1 = (void *) 0x16d3d180
'dlerror' has unknown return type; cast the call to its declared return type
History has not yet reached $2.
Catchpoint 1 (syscalls 'exit' [1] 'exit_group' [252])
[Inferior 1 (process 21224) detached]

**Comment by BenCat07** [comment]
1. why would you type -b
2. the Warnings are just fine.
