### ISSUE TITLE
chams turn into missing texture if disconnect or cat_fix_black_chams

### ISSUE THREAD

**Issue by surepy** [nullworks/cathook#626]
![missing texture](https://steamuserimages-a.akamaihd.net/ugc/960850363680814864/4AEEB03CAC218076DA783B199255377DB2B4296A/)

**Comment by BenCat07** [comment]
Reconnect normally fixes

**Comment by BenCat07** [comment]
not always, but sometimes, a small prcie to pay to fix chams tbh.
