### ISSUE TITLE
[bug?]Minigun's spin doesn't stop

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#627]
Hello Developers,

After minigun ran out of ammo, its spinning doesn't stop for a while and heavy (when only best weapon off) can't change to secondary weapon.

Please fix it.

**Comment by BenCat07** [comment]
The heavy should stop spinning his barrel instantly after running out of ammo, i even added additional checks, and the bot should head for ammo once the minigun is empty

**Comment by Riflerat** [comment]
Ben, I feel a lot of time passes with spinning empty minigun still.
There would be best, empty minigun can be changeable asap.
[suggestion]Could you all make a select option for: changing 1st weapon to 2n or 2rd ones ASAP when bullets ran out?

**Comment by ByGlimmer** [comment]
> Ben, I feel a lot of time passes with spinning empty minigun still.
> There would be best, empty minigun can be changeable asap.
> [suggestion]Could you all make a select option for: changing 1st weapon to 2n or 2rd ones ASAP when bullets ran out?

There is no known way to do this right now. You have to accept the limitations of the game, until a way to do this is found.

**Comment by Riflerat** [comment]
If Cathook can read the number of bullets, probably when number of bullets == 1, Cathook would change current weapon to 2nd or 3rd, thus empty spinning is avertable, preventable.

**Comment by ByGlimmer** [comment]
> If Cathook can read the number of bullets, probably when number of bullets == 1, Cathook would change current weapon to 2nd or 3rd, thus empty spinning is avertable, preventable.

you have to wait to unrev to switch weapons. try revving your minigun and switching weapons. tell me what you find.

**Comment by BenCat07** [comment]
i'll log the ammo counts on the minigun to find a fix.

**Comment by Riflerat** [comment]
Re-Opened:
When minigun just ran out of ammo,. but no one close to him, heavy can change weapon almost suddenly. This fixed.
But when minigun just ran out of ammo and an **enemy is close to heavy**, than minigun don't wan't stop spinning and the player can't select other weapon.
