### ISSUE TITLE
aaa omega bad

### ISSUE THREAD

**Issue by buyBread** [nullworks/cathook#628]
hello dear developers of my favourite free and open source training software for valve's overwatch. at this point in time the aaa is extreme miss, i would like it to hit p all the time :D

**Comment by Riflerat** [comment]
**A**nti-**A**nit-**A**im?

**Comment by buyBread** [comment]
thanks for useless reply!

**Comment by Riflerat** [comment]
Oh, dear. What "aaa" extreme do you miss?

**Comment by SparklyCatTF2** [comment]
#hiremoredevs

**Comment by buyBread** [comment]
hello you didn't fix random angle machine why did you close

**Comment by BenCat07** [comment]
because there's no information at all? also it is not random, each miss makes it try a different combination which only gets updated in CreateMove to prevent the angles from ACTUALLY spazzing and the resolver not working
