### ISSUE TITLE
Re-Opened: not perfect

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#634]
When minigun just ran out of ammo,. but no one close to him, heavy can change weapon almost suddenly. This fixed.
But when minigun just ran out of ammo and an **enemy is close to heavy**, than minigun don't wan't stop spinning and the player can't select other weapon.

_Originally posted by @Riflerat in https://github.com/nullworks/cathook/issues/627#issuecomment-437700990_

**Comment by BenCat07** [comment]
Yes, fixing that now, 'scuse me

**Comment by BenCat07** [comment]
Yes, fixing that now, 'scuse me

**Comment by BenCat07** [comment]
#d6035a6762c5fe36d7fd9596b51e5811cddc1b15

**Comment by BenCat07** [comment]
#

**Comment by TotallyNotElite** [comment]
This issue was not fixed. Reopening...

**Comment by BenCat07** [comment]
now it is
