### ISSUE TITLE
Stucks by unusable/unserviceable doors

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#636]
**Describe the Bug**
Bots stuck near by doors out of order, sometimes for a few ten seconds, sometimes forever.

**To Reproduce**

1. Eg.: for long time stuck: 

![stuckbw](https://user-images.githubusercontent.com/38861107/48603527-0475a900-e977-11e8-8ca3-3a11e2d2cd35.png)

2. Eg. forever stuck:

![sw](https://user-images.githubusercontent.com/38861107/48604117-03de1200-e979-11e8-89e6-f9509748d79d.png)

**Additional context**
Probably bots would keep off these doors if their state is recognizable, or after 3-4 seconds would search an other way.

**Note**

By the "forever stuck doors" cat_nav_init didn't helped.

**Comment by TotallyNotElite** [comment]
This issue should be fixed. Please check again.

**Comment by TotallyNotElite** [comment]
This issue should be fixed. Please check again.
