### ISSUE TITLE
Fine tune suggested for autojump

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#638]
**Describe the Bug**
Around an invisible spy scout bot begins jumping insanely and doesn't care the rest things in map. It can be long wasted time.

**To Reproduce**
Near by all invisible spies.

**Additional context**
I suggest 2 different possibility changes to resolve this.
Of course these would work when there is no more enemy in the area of scout.

1, Ignore lonely invisible spy and go ahead to "frag".
2, Continue jumping, and scout begins automatically shoot around spy, pretends search spy. And after some (randomly: 3-6) shoots "fortunately" finds and finishes spy.

**Comment by BenCat07** [comment]
making navbot look at shoot cloaked spies options

**Comment by Riflerat** [comment]
> making navbot look at shoot cloaked spies options

I think, all killed cloaked spy will whine and ask kick of bot.

**Comment by Riflerat** [comment]
Same as https://github.com/nullworks/cathook/issues/672
