### ISSUE TITLE
i can't do a pullrequest because my internet is shit but it should be obvious how to fix this

### ISSUE THREAD

**Issue by no-boot-device** [nullworks/cathook#642]
https://github.com/nullworks/cathook/blob/master/src/helpers.cpp#L42
you're checking autoexec instead of matchexec

**Comment by TotallyNotElite** [comment]
What.the.fuck. Thanks.

**Comment by TotallyNotElite** [comment]
Will close once merged into master (after navbot rewrite)

**Comment by BenCat07** [comment]
lol
