### ISSUE TITLE
Legit auto-backstab

### ISSUE THREAD

**Issue by ItzNop** [nullworks/cathook#651]
add it cause i want to play legit kthank

**Comment by raspbianlike** [comment]
wontfix.club

**Comment by TotallyNotElite** [comment]
Will fix. Super simple.

**Comment by TotallyNotElite** [comment]
I can probably push it to testing branch today. Will have to readd backtrack backstab first before we merge it to master though.

**Comment by TotallyNotElite** [comment]
It's on testing branch now

**Comment by TotallyNotElite** [comment]
Merged into master today. Closing.

**Comment by ItzNop** [comment]
@TotallyNotElite This is not what i really had in mind, I meant legit backtrack autobackstab, I should of been more clear.

**Comment by BenCat07** [comment]
you can't really make it legit

**Comment by ItzNop** [comment]
@BenCat07 How so? Couldn't you just make a triggerbot for the backtrack autobackstab so i don't flick and cause suspicion?
