### ISSUE TITLE
Namestealer steals name from kicked person

### ISSUE THREAD

**Issue by henrydatei** [nullworks/cathook#657]
**Describe the Bug**
Namestealer steals name from a person which was previously kicked

**To Reproduce**
1. steal a name
2. wait until everybody wants you to kick
3. start a vote to kick the person from that the name was stolen
4. person gets kicked
5. namestealer steals a new name
6. do/wait steps 2 to 4 again
7. namestealer steals a new name, but in my case it was the name from the person that was firstly kicked

**Expected behavior**
I expect that the name will be stolen from a person that is currently in the round

**Comment by Riflerat** [comment]
Sounds good, but, I guess, name stealing is no more just a fun, before you will be kicked finally. All looks your and the "victim"s profile image. Steal of profile image should be more joke, but I guess that is impossible or essentially very-very difficult from the TF2 client.

**Comment by henrydatei** [comment]
The problem is not the stealing from the profile image, the problem is that the namestealer changes my name not often enough

**Comment by henrydatei** [comment]
It would be ok when the namestealer steals a new name when someone is kicked

**Comment by BenCat07** [comment]
It doesn't steal the name from kicked people, and we sadly can only change our name once every 5 minutes, I will add better handling for name changing though.

**Comment by BenCat07** [comment]
This should be fixed in one of the newer commits
