### ISSUE TITLE
Can't inject on Arch

### ISSUE THREAD

**Issue by ElectfriedTheGod** [nullworks/cathook#658]
sudo ./attach
 
 
Auto Updater: Updating cathook in the background

Running instances: 26091
Attaching to 26091
cp: cannot stat 'bin/libcathook.so': No such file or directory
loading /tmp/.glEDbzPm to 26091
[New LWP 26092]
[New LWP 26093]
[New LWP 26094]
[New LWP 26095]
[New LWP 26096]
[New LWP 26097]
[New LWP 26098]
[New LWP 26099]
[New LWP 26103]
[New LWP 26104]
[New LWP 26105]
[New LWP 26127]
[New LWP 26129]
[New LWP 26155]
[New LWP 26156]
[New LWP 26157]
[New LWP 26158]
[New LWP 26314]
[New LWP 26315]
[New LWP 26316]
[New LWP 26317]
[New LWP 26318]
[New LWP 26319]
[New LWP 26320]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0xf7f3ddd9 in __kernel_vsyscall ()
$1 = (void *) 0x0
'dlerror' has unknown return type; cast the call to its declared return type
History has not yet reached $2.
Catchpoint 1 (syscalls 'exit' [1] 'exit_group' [252])
[Inferior 1 (process 26091) detached]
rm: cannot remove '/tmp/.glEDbzPm': No such file or directory
[noob@anarchy:~/cathook]$ remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
error: Server does not allow request for unadvertised object 97d35f638a1ba0f19f0372b76204432d1b7c77af
Fetched in submodule path 'external/chirc', but it did not contain 97d35f638a1ba0f19f0372b76204432d1b7c77af. Direct fetching of that commit failed.
 
 
Auto Updater: Failed to pull from github!

Have tried running 'install-all' and 'update'.

**Comment by buyBread** [comment]
arch user 100

**Comment by surepy** [comment]
`error: Server does not allow request for unadvertised object 97d35f638a1ba0f19f0372b76204432d1b7c77af
Fetched in submodule path 'external/chirc', but it did not contain 97d35f638a1ba0f19f0372b76204432d1b7c77af. Direct fetching of that commit failed.`

fixi

**Comment by ElectfriedTheGod** [comment]
@TotallyNotElite 
Thank you, this resolved my issue

**Comment by surepy** [comment]
clos e

**Comment by BenCat07** [comment]
No
