### ISSUE TITLE
Aimbot will look straight down if target is directly overhead 

### ISSUE THREAD

**Issue by no-boot-device** [nullworks/cathook#66]
This is easy to reproduce: go onto walkway, have launchpad set to a yellow power, and then just have silent aim and active when can shoot off and have fov be 20 or less, and just hold down your aimkey while watching a soldier go overhead. Eventually, a soldier will go over you and the aimbot will get confused and look down.

**Comment by BenCat07** [comment]
either fixed or dissappeared on it's own
