### ISSUE TITLE
Cat bot follows cloaked spy

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#669]
**Describe the Bug**
Not a really bug. We were talking about scout bot begins jumping near by cloaked spies. It's more better now, and thank you for changing. Actually scout bots don't jump by cloaked spies, but bots search spies and waste time a lot.

**Additional context**
Please make an option that cathookers bots can ignore cloaked spies in game.

Thanks you

**Comment by BenCat07** [comment]
Fixed in latest commit :+1:

**Comment by Riflerat** [comment]
Re-opened, guys:

In current version ( c14cf74) bot follows cloaked spies again.
