### ISSUE TITLE
Cat bot follows cloaked spy (2) and visual option Remove Cloak bug

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#672]
**Describe the Bug**
Sorry I have no right to re-open same issue topic (https://github.com/nullworks/cathook/issues/669) and I'm not sure that you will see new content automatically from a closed issue-
There  happened an other problem:

Unfortunately in current ( c27a062) version bot still stops and following cloaked spy.
That was very hazy situation and I was unsure bot was looking for a new path or following a spy, thus I turned "Remove cloak" option on: the spy was behind the bot. Bot just turned back and killed spy after bot was running to where the rest enemies were.
This pointed to an other bug: if the visual option "Remove cloak" (remove.cloak=true) overwrites the behavior of "NOT Cloaked Spy" (aimbot.target.ignore-cloaked-spies=true) option.

`if (CE_GOOD(last_target) && (!last_target->m_bAlivePlayer() || !last_target->m_bEnemy() || player_tools::shouldTarget(last_target) != player_tools::IgnoreReason::DO_NOT_IGNORE || (hacks::shared::aimbot::ignore_cloak && IsPlayerInvisible(last_target))));
{
`

I didn't checked exactly those variables means but reading names of variables I'm not sure that all needed to compare. Should be enough to check only hacks::shared::aimbot::ignore_cloak, 'cos (maybe) the rest variables are pointless in this situation???

**Comment by BenCat07** [comment]
if you uncloak a spy the spy is uncloaked so the aimbot shoots him, this is intentional

**Comment by BenCat07** [comment]
If you want to see him maybe use ESP or LightESP for that matter

**Comment by BenCat07** [comment]
And no, all the variables in that check are needed
