### ISSUE TITLE
Crash when changing key rvar without visuals

### ISSUE THREAD

**Issue by TotallyNotElite** [nullworks/cathook#689]
**Describe the Bug**
Crash when changing any Keyboard RVAR without visuals

**To Reproduce**
1. Compile cathook without visuals
2. Change a Keyboard RVAR
3. Crash

**Expected behavior**
Don't crash lmao

**Logs**
Empty crash log

**Comment by TotallyNotElite** [comment]
To fix: Link against SDL even when visuals are off

**Comment by BenCat07** [comment]
fixed by using textmode compile
