### ISSUE TITLE
Can't Inject Kubuntu 18.04 LTS

### ISSUE THREAD

**Issue by lbaldim** [nullworks/cathook#694]
Hi, when i try to inject i get this:

Auto Updater: Updating cathook in the background

Running instances: 4839
Attaching to 4839
loading /tmp/.gljziWiV to 4839
[New LWP 4842]
[New LWP 4847]
[New LWP 4849]
[New LWP 4850]
[New LWP 4939]
[New LWP 4942]
[New LWP 4960]
[New LWP 4961]
[New LWP 4962]
[New LWP 4963]
[New LWP 5052]
[New LWP 5053]
[New LWP 5054]
[New LWP 5055]
[New LWP 5056]
[New LWP 5058]
[New LWP 5075]
uyarı: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0xf7f34059 in __kernel_vsyscall ()
[New Thread 0xdb411b40 (LWP 5350)]
$1 = (void *) 0x2b19b400
'dlerror' has unknown return type; cast the call to its declared return type
History has not yet reached $2.
[Inferior 1 (process 4839) detached]
emiralp@akkus:~/cathook$ remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
HEAD is now at 568ae5a tf2 ayou forget how to RGBA
Stripping info from library
Unknown --info item: "flist"
rsync error: syntax or usage error (code 1) at options.c(453) [client=3.1.2]
make[3]: *** [CMakeFiles/data] Error 1
make[2]: *** [CMakeFiles/data.dir/all] Error 2
make[1]: *** [CMakeFiles/data.dir/rule] Error 2
make: *** [data] Error 2
 
 
Auto Updater:Failed to update /opt/cathook/data directory

And it gives me a popping error-ingame:
![screenshot_20190303_020344](https://user-images.githubusercontent.com/42888536/53688679-9bb11180-3d58-11e9-9e43-4dc29e72d4cb.png)

When i try sudo ./install-data i get this:
nstalling cathook data to /opt/cathook/data
Unknown --info item: "flist"
rsync error: syntax or usage error (code 1) at options.c(453) [client=3.1.2]

I did "sudo ./install-all" and i did everything written in the README and "install-all".

I am using Kubuntu 18.04 LTS.

Thank you.

**Comment by BenCat07** [comment]
Your rrsync is outdated, either get a newer one or copy the *content* of
the data file to /opt/cathook/data (if folder not in place: sudo mkdir -p
/opt/cathook/data;sudo chmod 777 -R /opt/cathook

**Comment by lbaldim** [comment]
Thank you! This fixed my problem.

But i have a question:
Although you said Linux Mint is not supported i got no errors while downloading and compiling with Linux Mint. I got the same error i got in Kubuntu. Does that mean Linux Mint is now supported? Can i use it in Linux Mint?

Thanks!

**Comment by BenCat07** [comment]
I mean you may be able to, but this happened to other users:
https://github.com/nullworks/cathook/issues/563

**Comment by lbaldim** [comment]
Thanks a lot!
I don't think these will happen to me.
I didn't meet any problems (other than this) while trying to use it in Linux Mint.
Thanks again!

**Comment by BenCat07** [comment]
No problem
