### ISSUE TITLE
Crash with AA and Voicechat

### ISSUE THREAD

**Issue by TotallyNotElite** [nullworks/cathook#700]
**Describe the Bug**
Antiaim in combination can cause a crash. 

**To Reproduce**
1. Enable AA (Probably fake AA because of bSendPackets)
2. Use Voicechat
3. Crash

**Expected behavior**
Don't crash

**Additional context**
Reported by @nosebeer on telegram.

**Comment by BenCat07** [comment]
TODO: either find out if net msg is being sent for voice and stop aa or do not write voice data if aa is on

**Comment by TotallyNotElite** [comment]
Fixed in 6685dff84067b4039c50aa272761385337f2eaec
