### ISSUE TITLE
AA breaks grappling hook

### ISSUE THREAD

**Issue by TotallyNotElite** [nullworks/cathook#701]
**Describe the Bug**
Grappling hook goes to AA viewangles instead of the cursor position.

**To Reproduce**
1. Enable AA
2. Use grappling hook
3. Grappling hook gets shot into the direction of AA instead of cursor

**Expected behavior**
Grappling gets shot into direction of cursor

**Additional context**
Reported by crwn in @nullworks on telegram.

**Comment by BenCat07** [comment]
TODO: first 2 ticks of on use disable aa for grappling hook (enable afterwards to enable aa midair)

**Comment by BenCat07** [comment]
This has been fixed at some point
