### ISSUE TITLE
[suggestion] Option for Autoreport: all, RAGE, etc...

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#705]
**Describe the Suggestion**

I would welcome there would be an option where I can select which players will be auto-reported. I mean I use the RAGE state and I would like report only those players.

**Comment by Riflerat** [comment]
As SylveonBottle wrote in #715 I suggest following options:

0. All
1. Non-party
2. Enemy
3. Rage

**Comment by BenCat07** [comment]
I am removing auto report as it has no function anymore

**Comment by TotallyNotElite** [comment]
Reporting has no effect anymore. Closing...
