### ISSUE TITLE
[suggestion] Custom Anti aim

### ISSUE THREAD

**Issue by acuifex** [nullworks/cathook#707]
Make option to use different real and fake angles
and also to set different offsets to real and fakes.
It should be really really easy to make. Even i'm did this
P.s. My english still broken Xd

**Comment by BenCat07** [comment]
I once had this, it was so convuluted that i remeoved it

**Comment by acuifex** [comment]
Would be really nice to make as option to antiaim and leave old antiaims

**Comment by BenCat07** [comment]
This was added and also turns out that this issue is a duplicate
