### ISSUE TITLE
Aimbot Inaccuracy

### ISSUE THREAD

**Issue by KaylinOwO** [nullworks/cathook#710]
Sorry for the color issue but heres a video https://youtu.be/8jD6d4TKIeo

No clue what the problem is, I assume its my config but I've tried switching it but the issue persists.

**Comment by BenCat07** [comment]
1. Either use backtrack or don't. You do both at once right now (Backtrack
enabled but aim at backtrsck is disabled)
2. Disable nolerp, makes you miss way more often

**Comment by KaylinOwO** [comment]
alright, thanks, that worked
didnt think nolerp would have a negative effect, I tried disabling backtrack before.
its also worth noting that "Auto" hitbox doesnt work very well, it baims a lot when the head is visible as sniper.

**Comment by BenCat07** [comment]
Priority order for auto on sniper:
- Bodyshots if head not visible
- Bodyshots if it would kill
- Headshots

**Comment by KaylinOwO** [comment]
hm that doesn't seem to work properly for me, it was bodyaiming people at full hp when heads were clearly visible
