### ISSUE TITLE
Autotaunt safety range

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#711]
https://github.com/nullworks/cathook/blob/d20705d4d1178083767eba3265aabfc8d3fa08e5/src/hacks/AutoTaunt.cpp#L29

Could get a separate module for autotaunt to not taunt if within range of an enemy?

`autotaunt.safety <distance>`

0 by default for disabled. Add a quick " || !" check to AutoTaunt.cpp#L29, where if an enemy is within <distance>, skip taunting entirely regardless of chance.

With this, setting `autotaunt.chance 100` and `autotaunt.safety 1000` could allow for automatically taunting after killing a group of enemies - and, no taunting if within an enemy's range. This could make autotaunting reliable for non-bot users as well, since we can surely taunt when no other danger is actively present.

**Comment by BenCat07** [comment]
Sounds good to me

**Comment by SylveonBottle** [comment]
Auto-taunt hasn't been working for me since this was introduced, unless set to 0.

Maybe it's just my settings? It isn't checking for dead entities - or the one we just killed - is it?

**Comment by BenCat07** [comment]
I will look into the issue

**Comment by BenCat07** [comment]
fixed
