### ISSUE TITLE
Silent angles break nav/followbot

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#717]
**Describe the Bug**
While using navbot, enabling anti-backstab (activating) and anti-aim will cause navbot to go off course drastically.

**To Reproduce**
1. Enable navbot, and anti-aim

Watch as the bot attempts to follow the nav line, but will walk randomly off-course depending on the anti-aim settings.

1. Enable followbot, and anti-backstab (can't remember if silent should be on or not)
2. Wait for spy to attempt to backstab you.

The bot will attempt to counter the backstab by looking towards the spy and, in return, will start walking directly towards the spy despite being told to follow a user.

**Comment by TotallyNotElite** [comment]
I'm not sure how to fix this as of right now. FixMovement function looks interesting but i'll have to look into this more.

**Comment by TotallyNotElite** [comment]
Ok, experienced this myself yesterday. This is a high priority issue that should be resolved ASAP.

**Comment by TotallyNotElite** [comment]
@BenCat07 says this is solved. Confirmation would be great.

**Comment by TotallyNotElite** [comment]
fixed since forever
