### ISSUE TITLE
Huntsman shoots at random angles

### ISSUE THREAD

**Issue by KaylinOwO** [nullworks/cathook#719]
It literally just shoots at a random angle lol
https://youtu.be/KcbtqsCsJfc

**Comment by TotallyNotElite** [comment]
Gday. Could you provide reproduction steps for this issue? There's usually an issue template but it seems like you deleted it for whatever reason.

**Comment by BenCat07** [comment]
I cannot identify what is going on either, Frames too low on recording

**Comment by KaylinOwO** [comment]
my bad, wheres the cathook config location? Ill just send that
Ill re-record with the video with better OBS settings in a bit

**Comment by BenCat07** [comment]
`/opt/cathook/data/configs`

**Comment by KaylinOwO** [comment]
https://anonfile.com/C1y7m8T2m5/casual_conf

**Comment by KaylinOwO** [comment]
I cant exactly get OBS working properly but to sum some more info is it seems to only happen when anyone is in view (including teammates as far as I can tell)

**Comment by BenCat07** [comment]
It actually may be Aimkey mouse1 + autoshoot arrow

**Comment by KaylinOwO** [comment]
autoshoot is disabled

**Comment by BenCat07** [comment]
i mean arrow charge rvar

**Comment by KaylinOwO** [comment]
huntsman-autoshoot? if so, I tried changing it to 0, nothing seems to have changed

**Comment by SylveonBottle** [comment]
I can confirm that I'm receiving this error.

Config: | https://pastebin.com/XSGiMVcX
Video: | http://www.youtube.com/watch?v=22IvRw79gqw

Watch as the arrows always shoot off towards blue spawn, regardless of where I'm actually aiming.

it's not consistantly the blue spawn, just happens to be where it aims at on this map. On other maps it'll be other random directions, but it always shoots towards the same direction per-map.

**Comment by BenCat07** [comment]
Seems to be a mix of aimkey m1 and autoshoot on huntsman? I will see what i can do

**Comment by BenCat07** [comment]
Probably shooting 0 0 0

**Comment by BenCat07** [comment]
Ahhhhh

**Comment by TotallyNotElite** [comment]
I have no clue on how to replicate this at all. I've been trying for the last 10 minutes.

**Comment by TotallyNotElite** [comment]
Was never able to replicate this
