### ISSUE TITLE
Replace huntsman-autoshoot manual delay with wait-for-charge

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#720]
Instead of letting the user change how charged the huntsman must be for huntsman-autoshoot to activate, we should make this dynamic by "predicting" how much damage the shot will do similar to that of sniper's wait-for-charge.

Scenario: User is a sniper, and a scout is running head-on.
Currently the bow will wait until it's half charged, then shoot - wasting time charging when a single leftclick would work. With this method, wait-for-charge would charge the bow up to 1% then aim at the scout's head (or higher if aimbot is targeting the body, preferably the head if user is using `hitbox-mode=1`), then fire that.

Another scenario would be if a heavy is 'rounding the corner. Currently, the aimbot would just shoot at 50% which may or may not kill the heavily, and especially won't do shit if it's a body shot. The aimbot should instead continue charging the bow until it's ensured a one-hit-kill. 

This would be valuable since it would make the huntsman shoot faster against low-health targets, as well as properly charge higher-health ones. We shouldn't have to charge up to 50% for a heavy with 2hp.

**Comment by BenCat07** [comment]
noted

**Comment by TotallyNotElite** [comment]
Added
