### ISSUE TITLE
Crash: FireGameEvent

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#721]
**Describe the Bug**
Game crashes upon joining match.

**To Reproduce**
1. Config: https://hastebin.com/otidabilof.coffeescript
2. Join game.

**Logs**

https://hastebin.com/olemetayaz.js
```
cathook-esp-7976-segfault.log
/usr/include/c++/7/bits/stl_vector.h:573
3x Unknown
/usr/include/c++/7/fstream:738
1x Unknown
/home/esp/cathook/include/entitycache.hpp:106
/home/esp/cathook/src/visual/EventLogging.cpp:140
2x Unknown
/home/esp/cathook/src/hooks/FireEventClientSide.cpp:19
23x Unknown
```

**Comment by BenCat07** [comment]
Seems to be a crash related to Improper GetPlayerForUserID handleing, fixing

**Comment by TotallyNotElite** [comment]
Crash happens at the m_iTeam call in EventLogging.cpp Line 93 (handlePlayerSpawn)

**Comment by SylveonBottle** [comment]
Appears that my copy of cathook is `./update`'ing to the testing branch, therefor I did not receive this patch.

This issue may be resolved.

**Comment by BenCat07** [comment]
It's fixed now
