### ISSUE TITLE
Anti-afk pops uber

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#722]
**Describe the Bug**
Anti-afk enabled pops uber when fully charged as medic.
**To Reproduce**
1. Enable Anti-AFK
2. Idle in spawn as medic with full uber (preferably with auto-heal
Watch as anti-afk pops uber.

**Expected behavior**
Anti-afk shouldn't waste uber.

**Comment by SylveonBottle** [comment]
Could probably just stop it from right-clicking, but doesn't LB's version just move forward every so slightly?

**Comment by BenCat07** [comment]
Todo: don't spam random buttons and just use IN_DUCK every once in a whilr

**Comment by TotallyNotElite** [comment]
Fixed in 0b9893a5cbf60eb6ec9d7a2df071a7e614811f7e but @BenCat07 didn't close for some reason.
