### ISSUE TITLE
Auto-heal ignoring silent for followbot target

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#726]
**Describe the Bug**
When followbot and autoheal are enabled (autoheal silent disabled), auto-heal will not look at the follow target. When another target gets within range, auto-heal will consistently look towards them, but not towards the follow target.

**To Reproduce**
1. Enable auto-heal
2. Disable autoheal silent
3. Enable navbot and followbot
Notice that auto-heal will follow targets not on the path, or not the current follow target.

**Expected behavior**
Auto-heal should respect the user's `silent` setting and watch the auto-heal target if silent is disabled.

**Screenshots**
Bot is following a heavy off-screen, but is currently targeting a pyro nearby. This is expected as per `silent` being disabled.
![image](https://user-images.githubusercontent.com/17802843/54874566-cfadae80-4dbb-11e9-9e52-07964664db1d.png)
Followbot currently has a target, and auto-heal is indeed healing them, but is not aiming at them. This is not expected behavior, as silent is disabled.
<Image not provided>

**Comment by TotallyNotElite** [comment]
I think I remember fixing this, but don't quote me.

**Comment by SylveonBottle** [comment]
I believe so after a bit of testing a few days ago.
