### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#728]
**Describe the Bug**
Game crashed.

**To Reproduce**
1. Config: https://hastebin.com/agunoqohoh.cpp
Unexpected crash ~2 hours within gameplay. 

**Logs**
cathook-segfault: https://hastebin.com/ebaqeperuj.bash

```
cathook-esp-21010-segfault.log
/usr/include/c++/7/bits/stl_vector.h:573
3x Unknown
/usr/include/c++/7/fstream:738
15x Unknown
```

**Additional context**
This may not be related to Cathook.

**Comment by TotallyNotElite** [comment]
Not related to cathook. (Unless you can reproduce it somehow)

**Comment by BenCat07** [comment]
@SylveonBottle bottle himself said to close it
