### ISSUE TITLE
Aimbot Enhancements 

### ISSUE THREAD

**Issue by oneechanhax** [nullworks/cathook#73]
Some really REALLY nice improvements that the aimbot could use.
1. Aimresolver
Would allow users to hit fake aims.
2. Multipoint
Would allow users to easily hit edging/peeking players by searching for another point on a hitbox to hit.
3. Engine prediction
Would allow users to not need to use net settings and will fix instances of aimbot missing/hitting the walls next to the enemy peeking. The cheat way to make this is to check if the aimbot would hit before autoshooting but would not work for people not using autoshoot.

**Comment by BenCat07** [comment]
all of these are there
