### ISSUE TITLE
Add aimbot.fov-circle.enable to GUI

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#730]
https://github.com/nullworks/cathook/blob/75fbce033b026654f74d8ef600ea19345b0ce6df/src/hacks/Aimbot.cpp#L65

GUI currently has an option to change the fov opacity but cathook doesn't actually have it enabled by default, nor is it shown in the GUI.

While you're at it, could you add followbot breadcrumbs to gui, too?

**Comment by BenCat07** [comment]
Aimbot Fov is long added to the menu, you probably just did not run `make data`

**Comment by SylveonBottle** [comment]
I can confirm that it's not.

I'm using the install-all script, as well as `./update`. If these are not running `make data` by themselves then the scripts are at fault and should be updated.

![image](https://user-images.githubusercontent.com/17802843/55153592-d708eb00-5120-11e9-80d5-447d1366daa9.png)


As you can see, there is "FOV" and then "FOV Opacity". Regardless of what you set the fov opacity to, `aimbot.fov-circle.enabled` is disabled by default and can **not** be found within the menu.

**Comment by SylveonBottle** [comment]
What this fixed with https://github.com/nullworks/cathook/commit/2d0f38bf9edb71da19f36be016198b81a60a7d35 ?

**Comment by BenCat07** [comment]
Yes
