### ISSUE TITLE
Auto backstab attempts to backstab even when it can't

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#732]
**Describe the Bug**
Autobackstab will visually change your view direction for other players despite not being able to backstab under absolute circumstances.

**To Reproduce**
1. Enable auto-backstab, enable third-person and third-person view angles
2. Equip deadringer, pull it out

Watch as autobackstab will look at target despite not being able to attack.  
The same may go for when invisible, haven't really checked. 

**Expected behavior**
Auto-backstab shouldn't be changing angles at these times when it's technically impossible to actually backstab.

**Comment by BenCat07** [comment]
TODO

**Comment by SylveonBottle** [comment]
Can confirm that autobackstab attempts to backstab while the user is invisible, as well as against ubered/bonked targets.

**Comment by SylveonBottle** [comment]
Fixed with https://github.com/nullworks/cathook/commit/cfac779542e6c3a5b2783361d946b4da3fbee67a?

**Comment by BenCat07** [comment]
Half
