### ISSUE TITLE
Glow ESP on domination

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#736]
Would be nice in casual gameplay to see who's dominating you and target them.

Also, maybe something else to show players you're dominating - that way we can focus on making them even more pissed? lol

**Comment by BenCat07** [comment]
Choose to use the Domination icon instead, makes it less confusing, Added in one of the latest commits, not on Stable release yet

(To use this you must manually run ./scripts/developer, git pull will then put you on the latest commit, you will have to manually build with git pull;cd build;make -j(\`nproc\`);make data

**Comment by SylveonBottle** [comment]
Was this fully added with https://github.com/nullworks/cathook/commit/20e87c02e45753a5c5891611b37a061f3264908e ?

**Comment by BenCat07** [comment]
Yes
