### ISSUE TITLE
Can't Install cathook Linux Mint 18.1

### ISSUE THREAD

**Issue by SirPidoras** [nullworks/cathook#742]
https://pastebin.com/NpWQvj96 (cmakeoutput.log)
I did it according to the manual, since Linux Mint 18.1 is Ubuntu 16.04, so installing one command does not help me. What kind of log should I grunt?
(translated by google, ama ze rashan)

**Comment by BenCat07** [comment]
"16.10 or above"

**Comment by BenCat07** [comment]
Your cmake is too old, either build a new version from source, get it with snap, or use ubuntu 17.10 or newer

**Comment by SirPidoras** [comment]
> Ваш cmake слишком стар, либо создайте новую версию из исходного кода, получите ее с помощью snap, либо используйте Ubuntu 17.10 или новее

cmake version 3.14.3

**Comment by BenCat07** [comment]
I am not sure right noe which you need but Ubuntu's is outdates

**Comment by BenCat07** [comment]
Update your CMAKE

**Comment by BenCat07** [comment]
@BenCat07 Nevermind my bad, I do not know what you did but you are missing all build flags, please delete the build folder contents and run ./update again

**Comment by SirPidoras** [comment]
changed the distribution for ubuntu 18.04, after changing the distribution and updates, сathuk began to work
(translated by Google)
