### ISSUE TITLE
Install script installs outdated cathook

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#744]
https://github.com/nullworks/cathook/blob/c374b29cdab60a33a0b83b5f3a62c6ff9b6ce380/install-all#L28

Unable to use install-all script just for the fact that I end up with a heavily outdated cathook install.  Most if not all of bugs I find are already patched on the main branch, and suggestions I'd like to make seem to already have been implemented.

**Comment by BenCat07** [comment]
this Is intentional. It installs the **stable** branch (https://github.com/nullworks/cathook/tags/latest ), if you want to switch to master run ./scripts/developer and then run the update script
