### ISSUE TITLE
wrong magic number in src/trace.cpp kills traces prematurely in mvm

### ISSUE THREAD

**Issue by elitepleb** [nullworks/cathook#745]
**Describe the Bug**
An old magic number in src/trace.cpp makes the mvm medic shield kill traces prematurely.

**Fix**
in trace::FilterDefault::ShouldHitEntity change CTFKnife to CTFMedigunShield
For reference the last value of CTFMedigunShield was 225 and now is 230

**Suggestions**
Replace the other magic numbers in there

**Comment by TotallyNotElite** [comment]
Thanks for the report! This will be fixed in the commits I'll make today.

**Comment by TotallyNotElite** [comment]
fixed in 6be70d9beb6294511d69b6f5ca630a62d44beeeb

**Comment by TotallyNotElite** [comment]
Todo: Replace all magic numbers with numbers that are supported by the dynamic generator.
