### ISSUE TITLE
Path Prediction

### ISSUE THREAD

**Issue by EricSmith17** [nullworks/cathook#747]
I just want to request this feature.
Draw Path Prediction = It will draw line from origin pos of entity To predicted point and showing how gamemovement works, bounce of the wall, etc., Code below is good but it cant be used to draw predicted path of player (entity).
```
float time = step_len (from proj pred)
frametime = time;
ProcessMovement( entity, &moveData );
```

This code that cathook uses in engine_prediction is not bad for projectile prediction but engine_prediction returns predicted position of Entity, so that cannot be used to draw predicted path because it will just draw direct line without showing how gamemovement functions work.

PS: Im not gay valve developer, i just copy name to scare cheat developers

**Comment by BenCat07** [comment]
Not like we'd be afraid of your name, so Let me get this right, you want us to use the above code or NOT use that code? The best we can do is use it and set time to 1s/66

**Comment by BenCat07** [comment]
And draw each Point ofv

**Comment by EricSmith17** [comment]
i just want feature that will simulate movement of player for custom time and be able to visualy see the predicted path line

**Comment by EricSmith17** [comment]
For example:
here is old code made by V952
https://pastebin.com/Eyc8rXaa

PredictPath function is smilliar that you need, it predicts path of entity and drawing line (UTIL_DrawDebugArrow)
but problem is that it doesnt contains all functions from gamemovement, so it only have PhysicsClipVelocity function that just reflect your predicted path on world, walls, etc. and its not perfect because its fucked up when you walk up stairs so thats why is ProcessGamemovement better because it calls everything in gamemovement and simulating it perfectly.
:)

**Comment by EricSmith17** [comment]
This is what i want https://streamable.com/mwbmy .

**Comment by TotallyNotElite** [comment]
> 
> 
> This is what i want https://streamable.com/mwbmy .

Looks neat. I'll give this a low priority marker since there are easier issues to tackle. Additionally, @BenCat07 and I are quite busy right now. I mean if you have the "know how" you can give us a hand ;).

**Comment by TotallyNotElite** [comment]
@EricSmith17 I did some digging and found out that we already have this as a feature. The RVar is debug.engine-pred-others. Turns out that @BenCat07 and I still don't know everything about the cathook codebase :+1:. Could you close this issue if you're happy with it? I'll probably make the line more visible tho.

**Comment by TotallyNotElite** [comment]
Ok, it's currently a bit buggy xd

**Comment by EricSmith17** [comment]
Can you please post screenshot of it here ?

**Comment by TotallyNotElite** [comment]
Hello. We also added the RVar `debug.pp-draw` which does not use the engine to predict players, while still correctly predicting slopes. This has an enormous performance advantage compared to engine prediction. We also fixed the issues with engine prediction teleporting players around.
