### ISSUE TITLE
Crash when backtrack is enabled in the GUI

### ISSUE THREAD

**Issue by crwn1337** [nullworks/cathook#748]
**To Reproduce**
1. … Inject the cheat
2. … Open the menu and change to another tab while backtrack is enabled
3. … Crash

**Logs**
[cathook-kasutaja-14547-segfault.log](https://github.com/nullworks/cathook/files/3242198/cathook-kasutaja-14547-segfault.log)

**Config**

[cfg.txt](https://github.com/nullworks/cathook/files/3242206/cfg.txt)

**Comment by crwn1337** [comment]
**More info**
I tested on 2 computers, both had proprietary nvidia drivers and both crashed.
Only tested on clicking the "Movement" tab.

**Comment by TotallyNotElite** [comment]
Looking into this now

**Comment by TotallyNotElite** [comment]
Can't reproduce. Master branch commit be5b48bf5fb91d281f58a98ce1075b7f5f02d831

**Comment by TotallyNotElite** [comment]
Can you please run ./symbolize-crash-log after crashing and send the output here?

**Comment by TotallyNotElite** [comment]
Ok this was one issues causing crashes everywhere in the cathook codebase at once. Fixed in caa9e7c84e4658dea3482ba401da83008ee53e56
