### ISSUE TITLE
guarantee a sniper headshot by waiting 200 ms after scoping

### ISSUE THREAD

**Issue by elitepleb** [nullworks/cathook#751]
https://wiki.teamfortress.com/wiki/Sniper_Rifle
Update history
February 14, 2008 Patch
Added a small delay (200 ms) before a zoomed Sniper shot can get a critical hit.

**Comment by BenCat07** [comment]
Which is what we do.

**Comment by TotallyNotElite** [comment]
https://github.com/nullworks/cathook/blob/master/src/helpers.cpp#L1318

**Comment by elitepleb** [comment]
yup, i didn't notice that on my first look.
Sorry for the useless issue.
