### ISSUE TITLE
Smooth aimbot to disable Navbot "look at path"

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#754]
1. Enable Navbot, look-at-path
2. Enable Aimbot, set smooth to 10

What happens: 
bot is never able to hit a target unless the target happens to be infront of the bot's walkpath

What should happen:
Bot aims at target, fires & kills, then goes back to looking at path

Suggested fix:
Disable look-at-path when aimbot (with smooth aim) has a target

**Comment by SylveonBottle** [comment]
Small issue was talked about in telegram where a target going behind a wall would make the bot look back at path, which would be an issue if they came right back out.

Suggested fix was to add a small delay before re-enabling look-at-path.

**Comment by BenCat07** [comment]
Fixed in 22e8a6afef1dbb3994f04282679f7f2318e3d965

**Comment by SylveonBottle** [comment]
Actually it would be nice if we could do this without smooth aim either.

Just whenever silent is disabled. 

I got silent disabled for pyro, but the smooth aim is also set to 0 because it won't shoot anyone. So I set smooth to 0 so it can hit everyone, but silent set to 0.. but now it's just flicking back and forth between aiming and look-at-path.

So, yeah. Can we switch this from "when smooth aim is enabled" to "when silent aim is disabled"?

**Comment by SylveonBottle** [comment]
Yeah it would be really awesome to see this work only when silent aim is disabled.
Currently the only choices are to have smooth aimbot set and miss constantly with projectile weapons, flick constantly behind enemies with 0 smooth aim, or use silent aim with an FOV that only shoots infront.

-Have smooth aim set (which results in miss/not shoot constantly with projectile wepaons (soldier/demoman/pyro)
-Have no smooth aim set (resulting in constant flicking back and forth between target and look-at-path, which was why I created this issue in the first place)
-Have silent aim enabled, with a low FOV that isn't *too* obvious (which results in the bot not hitting people it's pathing away from)
