### ISSUE TITLE
Execute Commands via Chat

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#757]
Allow other users to send commands to the bot via user-created chat commands.

CMD: `cat_cmd_add "[invoker]" "[command to execute]"`

Uses:
-Custom exec files (used to provide other cathook-related executions, see Example 2)
-Request music to play (#756 `cat_cmd_add "!request &A&" "cat_mpv_play &A&"`)
-Get bot to switch class, i.e. go to medic (`cat_cmd_add "!class medic" "join_class medic ; cat_load medic_bot"`)
-Provide information to users upon request (`cat_cmd_add "!telegram" "say To join my telegram, visit <url>!"`)

Variables would be used similar to killsay's.

----------- 
**Example 0: Test example**
`cat_cmd_add "!test" "echo hello %NAME%!"`
```
Player1 : !test
user : hello Player1!
```
----------- 
**Example 1: Cathook user wants to create an "!ignore" command for bots, but not to save them forever.**
`cat_cmd_add "!ignore" "cat_pl_set_sate '%NAME%' 'FRIEND' ; echo '%NAME% added to ignore list!' ; wait '108000' ; cat_pl_set_state '%NAME%' 'DEFAULT'"`
```
randomuser1 : !ignore
] cat_pl_set_state randomuser1 FRIEND
user : randomuser1 added to ignore list!
>30 minutes pass
] cat_pl_set_state randomuser1 DEFAULT
```
----------- 
**Example 2: User wants to vote for the bot to leave.**
`exec vote-leave.cfg && cat_cmd_add "!leave" "vote-to-leave"`

Within cat_autoexec (or similar): 
```
alias "vote-to-leave" "0-yes"
alias "0-yes" "alias 'vote-to-leave' '1-yes' ; say '%NAME% has voted for me to leave! (1/3)'" 
alias "1-yes" "alias 'vote-to-leave' '2-yes' ; say '%NAME% has voted for me to leave! (2/3)'"
alias "2-yes" "alias 'vote-to-leave' '3-yes' ; say '%NAME% has voted for me to leave! (3/3) ; cat_disconnect '[Cathook] Voted off by users!' ; alias 'vote-to-leave' '0-yes'"
```
```
Player1 : !leave
user : Player1 has voted for me to leave! (1/3)
. . .
user : Player3 has voted for me to leave! (3/3)
user left the game ([Cathook] Voted off by users!)
```
----------- 

I could really make an infinite amount of examples that would prove beneficial as a sorta bot program. For example,
`cat_cmd_add "!pocketme" "cat_autoheal_heal_steamid %ID% ; say Now following %NAME%!"`

**Comment by SylveonBottle** [comment]
Obviously make it so the user has to enable chat-commands for these commands to work. Don't want people spamming `!leave` on you while you're actually playing lol

Also, option to only accept chat-commands via all/team/party-chat

**Comment by BenCat07** [comment]
cat_irc_exec_all is a thing

**Comment by BenCat07** [comment]
As for the music part, don't catch your chickens before they hatch

**Comment by BenCat07** [comment]
This idea itself looks interesting though, i will look into it

**Comment by TotallyNotElite** [comment]
i think we can consider this done now.
