### ISSUE TITLE
navbot.get-health-and-ammo to treat dispensers as both

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#759]
Path navbot close (enough) to dispenser, disable once within 60 hu until at full health. Then have nav-bot continue on it's merry way.

**Comment by BenCat07** [comment]
Should probably add that.

**Comment by BenCat07** [comment]
Added in 3434478d7b0e873d2d9607679764def8d62f172e

**Comment by SylveonBottle** [comment]
Oh, could you make it not use sapped dispensers?

**Comment by BenCat07** [comment]
Wait i forgot that

**Comment by SylveonBottle** [comment]
Bot should prefer large healthpacks if there are any nearby, and it only wants to get health.

Had bot just walk right by a large healthpack and instead walk alll the way back to spawn to get a dispenser. lol
