### ISSUE TITLE
Auto-pop on user requesting pop

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#761]
Have auto-uber pop charge when the target uses "7. Activate Charge!", regardless of health. Follow the user and don't switch off until uber ends.

This is useful for those chad gamers out there who really need a solid medic uber/kritz right about now.

**Comment by SylveonBottle** [comment]
Optional setting would be to select a heal target that does this command incase catbot is healing random people at that moment, with a setting to make this work with friends-only.

**Comment by BenCat07** [comment]
fixed
