### ISSUE TITLE
Show Toggle status under label

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#762]
If user has aimbot/triggerbot/etc set to TOGGLE, display "Aimbot Enabled"(/etc) underneath cathook logo.

**Comment by Retarded-Skid** [comment]
We were playing yesterday and I would lose track of some of the hacks I had on toggle and what their status was. A simple list showing what is toggled on would be very helpful for people with bad memory like me.

**Comment by TotallyNotElite** [comment]
I consider this to be a duplicate of #164
