### ISSUE TITLE
Anti-balance & auto-abandon clash

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#766]
**Describe the Bug**
Having both enable results in the user leaving the server then not being able to rejoin.

**To Reproduce**
1. Enable anti-balance, enable auto abandon
2. Get half of the other team to leave
3. If you're about to be team-swapped, cathook disconnects and then abandons the game

**Expected behavior**
Cathook shouldn't abandon if the user disconnected via anti-team switch

**Comment by BenCat07** [comment]
fixing this very moment

**Comment by TotallyNotElite** [comment]
2 hours later...

**Comment by BenCat07** [comment]
bruh, i'm not doing one line commits, i'm pushing like 10 fixes at once

**Comment by BenCat07** [comment]
Pushed in 59079c431ff6ac26eca76b9c4c9530c0843b9b51
