### ISSUE TITLE
Skinchanger

### ISSUE THREAD

**Issue by taybu** [nullworks/cathook#771]
I was trying to use the skinchanger, but it looked like the commands were not working, somebody help me please

**Comment by BenCat07** [comment]
Which commands did you use

**Comment by taybu** [comment]
cat_skinchanger_set
cat_skinchanger_save
cat_skinchanger_load
cat_skinchanger_redirect

**Comment by BenCat07** [comment]
I've fixes this issue in the newest commit on **master** branch
