### ISSUE TITLE
Show fake angles in thirdperson

### ISSUE THREAD

**Issue by ghost** [nullworks/cathook#776]
Currently only an option that shows real angles in thirdperson.
There was talk of this with https://github.com/nullworks/cathook/issues/702 but it was closed?

**Comment by SylveonBottle** [comment]
Saw a cheat somewhere that would display your fake angle as a ghost version of yourself, and your real angle as.. well, your real body. Could we do this? 

Just change "show fake angles" in the world UI to instead show this ghost version.

"Ghost" version could be either a transparent chams or perhaps wireframe model version.

**Comment by Trapacid** [comment]
Already exists labeled "Show angles in thirdperson".
