### ISSUE TITLE
killstreak

### ISSUE THREAD

**Issue by taybu** [nullworks/cathook#778]
I was using the killstreak option of cathook, and I realized that killstreaks count in 2 kills and when I kill killstreaks with a gun and then change weapon, the killstreak in killfeed does not equal the actual weapons, it continues where it left off with the last weapon

**Comment by BenCat07** [comment]
ah yeah i should fix that possibly

**Comment by taybu** [comment]
thanks

**Comment by TotallyNotElite** [comment]
Don't close unsolved issues??

**Comment by taybu** [comment]
ok
