### ISSUE TITLE
"only shoot when able" breaks huntsman aimbot

### ISSUE THREAD

**Issue by FrontStreet** [nullworks/cathook#779]
**Describe the Bug**
When using the aimbot with "only shoot when able"  on the huntsman, the bow gets pulled back and never fires until the aimbot has nothing to aim at, and then fires at nothing.

**To Reproduce**
Use the aimbot with "only shoot when able" on while using the huntsman.

**Expected behavior**
The aimbot should just aim, and nothing else.

**Screenshots**
https://youtu.be/L6eWbX2iaq8

**Comment by BenCat07** [comment]
This has been fixed (on master) because i rewrote the whole huntsman jank
