### ISSUE TITLE
Legit Mode on auto sticky doesn't work

### ISSUE THREAD

**Issue by FrontStreet** [nullworks/cathook#780]
**Describe the Bug**
When using Legit Mode on auto sticky, it never detonates.

**To Reproduce**
Turn on Legit Mode with Auto Sticky on

**Expected behavior**
Stickies should detonate when a target is visible and within range.

**Screenshots**
https://youtu.be/db3WtuL_TyI

**Comment by TotallyNotElite** [comment]
https://github.com/nullworks/cathook/blob/master/src/hacks/AutoSticky.cpp#L193 :man_facepalming:  @BenCat07
