### ISSUE TITLE
[Non-Bug] Uninstaller script and precompiled binary request

### ISSUE THREAD

**Issue by databoose** [nullworks/cathook#781]
This software seems to install **a lot** of libraries, mostly being dev libraries which makes the entire removal process quite annoying when a user no longer wants to use the software, if there is such a streamlined installer, why not the same for an uninstaller? Manually uninstalling each and every library that has been installed in order to compile the software to run it is quite a hassle in comparison to the ease of use about everything else of the software.

Another thing i may add is software should **always** be distributed pre-compiled if it is targeted towards end users, i know linux users are usually tech literate enough to compile, however it's an extra step that just flat out should not be there at all for the end user no matter what operating system and no matter how tech-savvy your target userbase is, i would compare this to a pizza parlor (minus the paying part, obviously) giving out unbaked pizza, sure the pizza is technically there, but you have to bake it at home, it's not a complete product.

You could argue, "This is absolutely free, and you are entitled to nothing", and that is true, i agree with you on that, however if you really went to this **drastic** extent of investing so much time and effort into an extremely advanced piece of software to distribute it all for no profit, why is the simple, small extra step of distributing it as compiled an issue?

**Comment by BenCat07** [comment]
We **CANNOT** just uninstall the libraries we installed. The user may be using them for other applications, which means we'd be uninstalling their applications.

As for **precompiled Libraries**, we could try to provide them, but depending on compile options the library we provide may be too big for proper use.

**Comment by databoose** [comment]
> We **CANNOT** just uninstall the libraries we installed. The user may be using them for other applications, which means we'd be uninstalling their applications.

Why not log what packages depend on what library packages before installation, log them for uninstallation script to parse, and then exclude uninstalling those certain libraries that were logged as being dependencies for other packages?

If needed, i can write this myself, have it reviewed by the developers, tested and released to the git page.

**Comment by TotallyNotElite** [comment]
@databoose The current dependencies required for cathook on ubuntu are the following:
`software-properties-common build-essential git g++ g++-multilib libboost-all-dev gdb libsdl2-dev:i386 libglew-dev:i386 libfreetype6-dev:i386 cmake dialog rsync`

Here's a breakdown for what each package is needed for:
software-properties-common: Apt, PPA support, very likely preinstalled
build-essential: Packages like `make` that are needed for the compilation process
git: Obvious, likely preinstalled
g++: c++ compiler
g++-multilib: 32 bit support
libboost-all-dev: boost libraries
gdb: for attach
libsdl2-dev:i386: 32 bit SDL library, functions needed for button presses etc, dynamically linked
libglew-dev:i386: 32 bit OpenGL library needed for libglez and imgui draw modes, dynamically linked
libfreetype6-dev:i386: Support for fonts in menu, esp, etc, dynamically linked
cmake: Needed for compilation
dialog: Configuration utility
Rsync: /opt/cathook/data installation and sync with cathook repo

> why is the simple, small extra step of distributing it as compiled an issue?

We would most likely face library mismatches, processor instruction set mismatches among other issues. Statically linking would solve some of these issues, but would make the library unnecessarily large. Additionally, this would complicate our distribution and updating process further.

> i would compare this to a pizza parlor (minus the paying part, obviously) giving out unbaked pizza, sure the pizza is technically there, but you have to bake it at home, it's not a complete product.

Some pizzas are frozen and can be baked at any point within a few minutes, in the case of cathook, within of 1 minute and 30 seconds. This means the pizza is fresher and hotter than a pizza you ordered to your house. In the case of cathook, this means that cathook can be compiled using all instructions your CPU supports (faster) while also using up to date libraries provided by your system (without increasing cathooks file size). Additionally, the pizza can be stored in its frozen state as long as you want, you can even time travel to the past and eat a pizza you already ate! In the case of cathook that means you can use and compile older versions of cathook without any problems, even if a potential build server already deleted those binaries.

> i know linux users are usually tech literate enough to compile

The cathook installation and update process does not require the user to know how to compile a binary. It's all done by our scripts and does not require user intervention.
