### ISSUE TITLE
Votelogger-autovote randomized delay

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#783]
Just realized it's suspicious af instantly having 5 F2's happen all at once when a vote is called.

Would look hell of a lot more legit for users who party with other cheats and catbots if the auto vote was given a small delay, between 1s-5s. 

Having lots of delayed F2's like that would make it look like the majority of your team really is voting no, and others should too - other than it being obvious "votebots".

**Comment by BenCat07** [comment]
Already added in 47722e5faa071b5446625806e6f6df6a64d44473

**Comment by BenCat07** [comment]
actually i'm afraid i may have built in a small bug preventing it from working

**Comment by BenCat07** [comment]
Fixed in 75128a2f17aa92997da2456a0c2f1af5e4c5f536

**Comment by SylveonBottle** [comment]
I didn't even realize it was added lol. Glad to see I somehow caused a bug to be found though
