### ISSUE TITLE
Backtrack Backstab mode consistently butterknifes

### ISSUE THREAD

**Issue by FrontStreet** [nullworks/cathook#784]
**Describe the Bug**
When using backtracking and the Backtrack auto backstab mode, it consistently butterknifes/facestabs

**To Reproduce**
Turn on backtracking and use Backtrack auto backstab mode

**Expected behavior**
It should only backstab, not facestab

**Comment by rustyvans** [comment]
A workaround is to use spin (181 speed) but that's less than ideal. Also are you using a very high fake latency? You should be using 600 max, I believe most cheats have issues with anything past that.

**Comment by BenCat07** [comment]
I Cannot confirm this issue, i'd need a video clip if possible in order to observe it.



> A workaround is to use spin (181 speed) but that's less than ideal. Also are you using a very high fake latency? You should be using 600 max, I believe most cheats have issues with anything past that.

No, we have no issues with 800ms, we adjust it properly. and using spin aa is not a real solution

**Comment by FrontStreet** [comment]
https://www.youtube.com/watch?v=zxeBLWDqUhk&feature=youtu.be

**Comment by BenCat07** [comment]
Now try to replicate it with nolerp switched off

**Comment by BenCat07** [comment]
@FrontStreet didn't post this here, but the issue is nolerp, don't use nolerp if you don't have sub 20md

**Comment by FrontStreet** [comment]
well you technically fixed it by removing nolerp
