### ISSUE TITLE
Q: What is happening with updates ?

### ISSUE THREAD

**Issue by EricSmith17** [nullworks/cathook#792]
Are you on vacation or what ? :'(

**Comment by TotallyNotElite** [comment]
Internship.

**Comment by TotallyNotElite** [comment]
I'll fix critical bugs whenever needed. Iirc @BenCat07 has a lot of free time now, so maybe he can start working on the issue backlog. Additionally, I'm spending my free time working on accgen.cathook.club right now.

**Comment by BenCat07** [comment]
My pc is starting rn actually
