### ISSUE TITLE
[TODO] add cat_toggle

### ISSUE THREAD

**Issue by BenCat07** [nullworks/cathook#793]
It will work like this:
`cat_toggle (rvar) (Value 1) (Value2)`
If rvar is `Value 1` set it to `Value 2`, Else set to Value 1. Allows easier binds.

**Comment by SylveonBottle** [comment]
Doesn't something like this exist in source engine already?

`toggle "sv_cheats" 0 1`

So wouldn't `toggle "cat set aimbot" 0 1` work?

**Comment by UNKN-0WN** [comment]
> Doesn't something like this exist in source engine already?
> 
> `toggle "sv_cheats" 0 1`
> 
> So wouldn't `toggle "cat set aimbot" 0 1` work?

No, no it won't, toggle only accepts convars, which cathook ditched for rvars which are set via the cat command.

**Comment by BenCat07** [comment]
@SylveonBottle We use rvars. Not cvars. You cannot use normal toggle.

**Comment by BenCat07** [comment]
and toggle is not a macro, it does  not expand the thing you enter and send it off as a command, it just straight up sets the cvar mentioned directly
