### ISSUE TITLE
cant open menu with key "insert"

### ISSUE THREAD

**Issue by nikita-tarasov3** [nullworks/cathook#795]
I cant open menu with key "Insert". My OS - Manjaro, but in game i have Cathook in top left. How to fix this? help please

**Comment by BenCat07** [comment]
We also use manjaro, issue may be your Insert key not being recognized by tf2, use cat set visual.open-gui-button to rebind it

**Comment by BenCat07** [comment]
(e.g. cat set visual.open-gui-button F11)

**Comment by nikita-tarasov3** [comment]
in game?

**Comment by TotallyNotElite** [comment]
Your keyboard may also just require FN to be pressed in addition to insert.

**Comment by BenCat07** [comment]
@nikita-tarasov3 Just Enter it in your tf2 console

**Comment by BenCat07** [comment]
Since there is no response i'm closing this issue.
