### ISSUE TITLE
[suggestion] Invert "Best weapon" on pyro

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#798]
**Describe**
Pyro's primary weapon is rather a "melee". (flamers) While the secondary weapons can be aimed weapons like scorch or detonator. 

I suggest to be an invert mode for Best weapon then the pyro bots can be configured more better: in game they can use flamers for enemies in close and can use eg. scorch for higher distance.

**Comment by Riflerat** [comment]
Just saw now you built in! Thank you! That's great. Now pyro-bot is very funny.

**Comment by BenCat07** [comment]
I forgot to close this, oops
