### ISSUE TITLE
Add voice command spam to GUI

### ISSUE THREAD

**Issue by ghost** [nullworks/cathook#799]
Self explanatory. Spam voice command (number), with delay and randomize options

**Comment by BenCat07** [comment]
Did you know spam.voicecommand was already a thing?

**Comment by rustyvans** [comment]
> Did you know spam.voicecommand or was it voicechat?) was already a thing?

micspam, and if voicecommand spam is in cathook then it isn't in the gui.

**Comment by BenCat07** [comment]
@rustyvans it is a thing, not in GUI tho

**Comment by BenCat07** [comment]
Already fixed it seems?
