### ISSUE TITLE
Log files growing in memory

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#800]
**Describe the Bug**
While bots running Cathook takes more memory.

**To Reproduce**
I tried to clear a log file with an empty character, but next time when Cathook writes the log file that will write the all original lines. That means Cathook keeps whole and all log files in memory. A log file can be more hundred megabytes. That is too much.

```
root@ASZTALI:/tmp# ls -l | grep 2820
-rw-rw-r-- 1 l        l       23474828 júl   29 07:35 cathook-l-2820.log
root@ASZTALI:/tmp# echo "" > cathook-l-2820.log 
root@ASZTALI:/tmp# ls -l | grep 2820
-rw-rw-r-- 1 l        l             1 júl   29 07:35 cathook-l-2820.log
root@ASZTALI:/tmp# ls -l | grep 2820
-rw-rw-r-- 1 l        l       23475345 júl   29 07:35 cathook-l-2820.log

```
Would you please fix it? Probably a variable includes all lines of a log not only the last line.

**Comment by BenCat07** [comment]
You can disable logging as a compile option. We also cannot really shrink the log file, as that would remove imporrant information for debugging.

**Comment by TotallyNotElite** [comment]
What he's asking for is that we should stop keeping the log file content in memory, because that will inevitably end in a memory leak. I think these are valid concerns and the issue should be kept open. 

A solution for this would be appending to the file instead.

**Comment by BenCat07** [comment]
#f7406d20fee1ec8fe5585379259d3b31844ba93e
