### ISSUE TITLE
Sniper navbot switches between primary/secondary "randomly"

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook#802]
Bot's unable to properly attack anyone within ~200 due to switching delays. Players are likely to run around and flank the sniper bot, resulting in the bot constantly switching back and forth between the two weapons - occasionally getting a single bullet out with the secondary every so often.

Suggesting to just double this range, or add a small delay before switching back to primary

**Comment by BenCat07** [comment]
I will add like a "Neutral" range where the bot will keep the current weapon
