### ISSUE TITLE
Cmake Error

### ISSUE THREAD

**Issue by kranercc** [nullworks/cathook#803]
PS: everything that could help me i already ran ( from the read me)

CMake Error at CMakeLists.txt:19 (include):
  include could not find load file:

    cotire

-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- broken
CMake Error at /usr/share/cmake-3.13/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "/usr/bin/c++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/krane/cathook-latest/build/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_184c7/fast"
    /usr/bin/make -f CMakeFiles/cmTC_184c7.dir/build.make CMakeFiles/cmTC_184c7.dir/build
    make[1]: Entering directory '/home/krane/cathook-latest/build/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_184c7.dir/testCXXCompiler.cxx.o
    /usr/bin/c++    -m32    -o CMakeFiles/cmTC_184c7.dir/testCXXCompiler.cxx.o -c /home/krane/cathook-latest/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    Linking CXX executable cmTC_184c7
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_184c7.dir/link.txt --verbose=1
    /usr/bin/c++  -m32   -m32 -L/usr/lib32  -rdynamic CMakeFiles/cmTC_184c7.dir/testCXXCompiler.cxx.o  -o cmTC_184c7 
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/8/libstdc++.so when searching for -lstdc++
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/8/libstdc++.a when searching for -lstdc++
    /usr/bin/ld: cannot find -lstdc++
    collect2: error: ld returned 1 exit status
    make[1]: *** [CMakeFiles/cmTC_184c7.dir/build.make:87: cmTC_184c7] Error 1
    make[1]: Leaving directory '/home/krane/cathook-latest/build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:121: cmTC_184c7/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:31 (project)

-- Configuring incomplete, errors occurred!
See also "/home/krane/cathook-latest/build/CMakeFiles/CMakeOutput.log".
See also "/home/krane/cathook-latest/build/CMakeFiles/CMakeError.log".

**Comment by kranercc** [comment]
Solved: 

`wget -O - https://raw.githubusercontent.com/nullworks/One-in-all-cathook-install/master/install-all | bash`

**Comment by BenCat07** [comment]
You didn't install the dependencies, which install-all dud
