### ISSUE TITLE
Process not found

### ISSUE THREAD

**Issue by kranercc** [nullworks/cathook#804]
sent 181 bytes  received 19 bytes  400.00 bytes/sec
total size is 369.92K  speedup is 1,849.62
Built target data

Cathook updated successfully

pgrep: invalid user name: hl2_linux
TF2 isn't running!
krane@pop-os:~/cathook$ pgrep hl2_linux
11611
krane@pop-os:~/cathook$ 

it's running but it doesn't find it

**Comment by kranercc** [comment]
i removed the line in attach
"pgrep -u $sudo user"
with pgrep hl2_linux and it fixed

**Comment by TotallyNotElite** [comment]
Hello! Seems like you're not running this script as root. Please run the script as root.

**Comment by TotallyNotElite** [comment]
> i removed the line in attach
> "pgrep -u $sudo user"
> with pgrep hl2_linux and it fixed

Please keep in mind that this is not a fix at all. You won't be able to attach without GDB knowing what PID to attach to.

**Comment by BenCat07** [comment]
sudo ./attach should work as long as you are not running sudo as root, the prep for sudo user is needed so you don't just attach to catbots
