### ISSUE TITLE
Crithack is wrong about some weapons' random crit abilities

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [nullworks/cathook#81]
Some weapons (gunslinger, etc) will attempt to randomly crit despite not being able to. I know this is sorta a known issue but it's been bothering me enough that I decided to make an issue for it.

My current theory is `WeaponCanCrit()` is doing what it says on the tin: not checking if the weapon can _randomly_ crit, just saying a weapon can crit on it's own, even if due to something non-random.

I mean, this makes the most sense because it would explain why the Gunslinger is marked as being able to randomly crit and the Sniper Rifle is suddenly marked as randomly critting when you scope in.

**Comment by BenCat07** [comment]
Should probably hook CanRandomCrit instead of CanCrit.
