### ISSUE TITLE
[bug] Crashes by pressing TAB

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#818]
Crashes by pressing TAB

Affected version: 891ff002ccefb708298458ad1173cff1ba8be916 stable

**Comment by Riflerat** [comment]
In 2919982dfe5e036a9007a23e7a1d1fb9ccec3917 that fixed, thx., that was fast!

**Comment by TotallyNotElite** [comment]
What?

**Comment by Riflerat** [comment]
Sorry, that is still crashes, but after some pressings of TAB.

**Comment by TotallyNotElite** [comment]
@Riflerat can you confirm if all your issues are still valid?

**Comment by Riflerat** [comment]
> @Riflerat can you confirm if all your issues are still valid?

Yes.

**Comment by TotallyNotElite** [comment]
> > @Riflerat can you confirm if all your issues are still valid?
> 
> Yes.

You're still crashing when pressing tab?

**Comment by TotallyNotElite** [comment]
Closing because of this:

![image](https://user-images.githubusercontent.com/38938720/65937655-daa76280-e420-11e9-9b27-2c3e859b24c1.png)
