### ISSUE TITLE
[bug] Catbots can't run

### ISSUE THREAD

**Issue by Riflerat** [nullworks/cathook#820]
While Catbots ./start-ed once I got an ask for sudo password for catbot, it misses packages those installed yet. The catbots can't run.
Linux is Ubuntu 18.04

#
![konz](https://user-images.githubusercontent.com/38861107/65494887-fefdbf00-deb5-11e9-98db-33f8a8a42526.png)

**Comment by BenCat07** [comment]
Don't use the preload branch with ubuntu

**Comment by Riflerat** [comment]
That's not preload branch, that's the "as this is installed automatically" branch. Nothing changed, just installed.
