### ISSUE TITLE
Backstab Backtrack isn't working

### ISSUE THREAD

**Issue by xXTevinOfficialXx** [nullworks/cathook#840]
**Describe the Bug**
Backtrack isn't backstabbing the enemy even when you can backstab him on backtrack and dont show the skeleton neither the backtrack enemy

**To Reproduce**
1. Activate Backtrack on Aimbot Section
2. Go to Trigger section, then Auto Backstab
3. Select Backtrack or Legit Backtrack
…
999. Backtrack dont recognize that can backstab and do nothing (result)

**Expected behavior**
Backstab the enemy when behind the backtrack

**Screenshots**
https://imgur.com/oVdDhdw.png
https://imgur.com/FTfMZNQ.png
https://imgur.com/0kWYR7Y.png
**Logs**
[cathook-tevin-4064.log](https://github.com/nullworks/cathook/files/3748285/cathook-tevin-4064.log)

**Comment by TotallyNotElite** [comment]
I can't reproduce this. Used it today with @BenCat07 in a game. Do you observe the same behavior in casual?

**Comment by TotallyNotElite** [comment]
Can you send the output of `git rev-parse ` here?

**Comment by BenCat07** [comment]
We need your response to work on it

**Comment by xXTevinOfficialXx** [comment]
> Can you send the output of `git rev-parse HEAD` here?

this is what it gave when i used that command
59957b1f7b862d3b0078e54e8e3cf824b38cd461

**Comment by iraizo** [comment]
Same thing as https://github.com/nullworks/cathook/issues/842
