### ISSUE TITLE
Auto Backstab fails to backstab quite often

### ISSUE THREAD

**Issue by buyBread** [nullworks/cathook#842]
**Describe the Bug**
Auto Backstab 2/4 times fails to backstab. Last time I've used Nullcore the fail ratio was far lower, practically wasn't a thing in most of the games I played, so I consider this an issue that needs to be fixed (this only applies to Rage modes, Legit and Legit Backtrack, iirc, worked "alright" last time I used them).

**To Reproduce**
1. Enable Auto Backstab
2. Miss around half the backstabs

**Expected behavior**
Hit backstabs. I don't mind missing sometimes, but not on the level where half of my kills using this feature aren't backstabs.

**Comment by BenCat07** [comment]
Turns out this may be an issue in valve's implementation of Normalization of 3D Vectors, as 3D vectors get assigned a z value of 1.0f when they really should not have 1.0f, but 0.0f as a z value, which breaks our DotProduct Math

**Comment by Trapacid** [comment]
Can anyone verify this issue still persists? Considering it's almost two years old, I'm sure backstabbing has improved greatly.
If any issues still exist, post config and video please.

**Comment by iraizo** [comment]
If not the new backtrack branch will fix it.
