### ISSUE TITLE
Custom FOV zoom in/out delay

### ISSUE THREAD

**Issue by buyBread** [nullworks/cathook#843]
**Describe the Bug**
There's a delay when you Zoom in/out while having a custom Zoom FOV set, it sets back your FOV to 20 then in a few moments returns to normal FOV.

**To Reproduce**
1. Set a custom Zoomed FOV

**Expected behavior**
Zoom in/out should be instant without any weird behavior. I think you can set set `m_flFOVRate` to 0 to fix this?

**Comment by BenCat07** [comment]
where precisely would this `m_flFOVRate` even be?

**Comment by Rtas-17** [comment]
Not entirely sure if this was fixed in a commit somewhere, can't find a reference to it in the commit history, however this issue does appear to have been resolved.

**Comment by BenCat07** [comment]
Nothing was changed

**Comment by Rtas-17** [comment]
odd, must have been a client side issue of some description. are you able to check it works fine on your machine?

**Comment by BenCat07** [comment]
i marked it as need more info because i had no idea how to even trigger it

**Comment by buyBread** [comment]
Fixed. I'm not sure when this was changed, but before when you'd return to 20 FOV for a brief moment when unscoping then see the FOV change back to 90 or whatever custom value you had.
