### ISSUE TITLE
Glow doesn't follow the player state

### ISSUE THREAD

**Issue by buyBread** [nullworks/cathook#845]
**Describe the Bug**
While Chams and ESP all follow the player state (by that I mean that they actually change the colors) Glow just doesn't do it and always stays as the player's team color.

**To Reproduce**
1. Set a Player's state to something else

**Expected behavior**
Glow to change the color that the state dictates.

**Comment by BenCat07** [comment]
glow is one bruh moment

**Comment by BenCat07** [comment]
Fixed through @buyBread's Pull request

**Comment by BenCat07** [comment]
nevermind, this is a seperate issue

**Comment by iraizo** [comment]
This has been closed by https://github.com/nullworks/cathook/pull/850
