### ISSUE TITLE
Menu Separators are off by 1 pixel 

### ISSUE THREAD

**Issue by buyBread** [nullworks/cathook#853]
**Describe the Bug**
The Separators that separate different Tabs are off by 1 pixel.

**Expected behavior**
Not get triggered.

**Screenshots**
![Screenshot from 2019-10-24 18-19-39](https://user-images.githubusercontent.com/32032674/67502114-11724080-f68e-11e9-8b95-219b2c431c4d.png)

**Comment by TotallyNotElite** [comment]
Fun fact: Nvidia issue.

**Comment by buyBread** [comment]
Not cool Nvidia

**Comment by TotallyNotElite** [comment]
![image](https://user-images.githubusercontent.com/38938720/67518088-50ab8c00-f6a4-11e9-8d3f-3de6f675a933.png)
Intel IGPU. Same on AMD cards. Truly shows how epic NVIDIA drivers are.
