### ISSUE TITLE
[suggestion] No Scope that shows the sniper

### ISSUE THREAD

**Issue by xXTevinOfficialXx** [nullworks/cathook#856]
The title says basicly everything.
You guys could add a No Scope option that instead of just removing the scope UI, make the Sniper weapon visible

**Comment by BenCat07** [comment]
i'll also have to bytepatch equip weapons then

**Comment by TotallyNotElite** [comment]
Yes!!! This would be epic! Too bad I don't know how to bytepatch 🤦‍♂

**Comment by BenCat07** [comment]
not sure how this will work either

**Comment by TotallyNotElite** [comment]
I did that actually :shrug:
