### ISSUE TITLE
[Suggestion] Add option to Auto-Reflect  to ignore specific projectiles

### ISSUE THREAD

**Issue by raphael-costa** [nullworks/cathook#862]
I don't know if this is possible but reflecting flares doesn't achieve much (wasted ammo most of the time) and it also looks a bit fishy. It would be interesting if we had an option to ignore it.

Stickies and Direct Hit rockets are also very hard to reflect.

**Comment by TotallyNotElite** [comment]
+1

**Comment by infoman-cor** [comment]
@TotallyNotElite added #901
