### ISSUE TITLE
[Q] What ubuntu is recommended ?

### ISSUE THREAD

**Issue by EricSmith17** [nullworks/cathook#863]
im doing dualboot, but idk what ubuntu to choose plz help

**Comment by TotallyNotElite** [comment]
https://manjaro.org

**Comment by EricSmith17** [comment]
> 
> 
> https://manjaro.org

https://i.imgur.com/new2u2w.png

what edition to choose ?

**Comment by TotallyNotElite** [comment]
Pick KDE. Good bet in most situations.

**Comment by EricSmith17** [comment]
ok

**Comment by EricSmith17** [comment]
what is size of installed OS of manjaro KDE ?

**Comment by TotallyNotElite** [comment]
I don't know. At least 4x smaller than windows.

**Comment by EricSmith17** [comment]
can i install it on HDD ? my SSD is full of visual studio and unity shit

**Comment by EricSmith17** [comment]
ok thx
but i will not lose data on hdd yes ?

**Comment by TotallyNotElite** [comment]
There should be an option to do a "parallel install"

**Comment by EricSmith17** [comment]
okay, so i format USB and use Rufus with iso file, then restart pc and boot from usb ?

**Comment by TotallyNotElite** [comment]
I suggest you use [etcher](https://www.balena.io/etcher/) instead, because rufus had problems with non hybrid ISOs recently. Others have told me that rufus works properly now, but I haven't verified it myself.

**Comment by EricSmith17** [comment]
yes, when i boot from usb, i select try ubuntu without installing(or how its callled or Install ubuntu ? (manjaro)

**Comment by TotallyNotElite** [comment]
Manjaro is not ubuntu based (this is a good thing!).

Btw, if you have an nvidia card, read this: https://t.me/nullworks/148628 (join that channel in general. Talking in github issues is stupid :+1:)

**Comment by TotallyNotElite** [comment]
It is not. Just follow the instructions I sent you.

**Comment by EricSmith17** [comment]
can you go online pls :D

**Comment by EricSmith17** [comment]
how to install telegram ? https://i.imgur.com/XipzUvo.png

**Comment by al14s4** [comment]
this entire issue is just embarrassing

**Comment by TotallyNotElite** [comment]
> this entire issue is just embarrassing

Totally agree. This isn't a chat room.
