### ISSUE TITLE
Can't open a cheat menu

### ISSUE THREAD

**Issue by snowy31TF** [nullworks/cathook#872]
I can't open cathook menu by pressing any Insert key - insert(delete) & insert(0)
I am using manjaro linux
Please help me to solve this!

**Comment by TotallyNotElite** [comment]
Does this issue solve it for you?
https://github.com/nullworks/cathook/issues/795

**Comment by snowy31TF** [comment]
Wow I solved it
fn + insert

**Comment by TotallyNotElite** [comment]
That's what I thought.
