### ISSUE TITLE
Glow isnt on players

### ISSUE THREAD

**Issue by xXTevinOfficialXx** [nullworks/cathook#874]
**Describe the Bug**
The glow option on Cathook is way on the left of the screen instead of on the players

**To Reproduce**
1. Enable Glow
…
999. The glow will just appear way in the left of the players  (result)

**Expected behavior**
Glow appear normally in the players

**Screenshots**
https://i.imgur.com/5PLgiZw.png
https://i.imgur.com/ToT3KDS.png

**Logs**
[cathook-tevin-1841.log](https://github.com/nullworks/cathook/files/3816599/cathook-tevin-1841.log)

**Additional Content**
I'm using Linux Manjaro 19.02 Xfce

**Comment by BenCat07** [comment]
wait what, this makes no sense

could you try if glow has the same issue?

**Comment by xXTevinOfficialXx** [comment]
Chams dont have the same issue, only glow

**Comment by lbaldim** [comment]
Your resolution causes this. Set resolution to native.

**Comment by xXTevinOfficialXx** [comment]
Thanks anyway but i fixed already, btw, i was running at native resolution
