### ISSUE TITLE
./attach after automatic installation

### ISSUE THREAD

**Issue by kranercc** [nullworks/cathook#875]
[New LWP 3002]
[New LWP 3009]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
warning: Breakpoint address adjusted from 0xf7de0aa4 to 0xfffffffff7de0aa4.
warning: Breakpoint address adjusted from 0xf7d0460e to 0xfffffffff7d0460e.
warning: Breakpoint address adjusted from 0xf7b5a140 to 0xfffffffff7b5a140.
warning: Breakpoint address adjusted from 0xf7f60be0 to 0xfffffffff7f60be0.
warning: Breakpoint address adjusted from 0xf7f61195 to 0xfffffffff7f61195.
warning: Breakpoint address adjusted from 0xf7f62d1c to 0xfffffffff7f62d1c.
warning: Breakpoint address adjusted from 0xf7f62924 to 0xfffffffff7f62924.
warning: Breakpoint address adjusted from 0xf7f709b3 to 0xfffffffff7f709b3.
warning: Breakpoint address adjusted from 0xf7f71401 to 0xfffffffff7f71401.
warning: Breakpoint address adjusted from 0xf7f71706 to 0xfffffffff7f71706.
warning: Breakpoint address adjusted from 0xf7de0aa4 to 0xfffffffff7de0aa4.
warning: Breakpoint address adjusted from 0xf7d0460e to 0xfffffffff7d0460e.
warning: Breakpoint address adjusted from 0xf7b5a140 to 0xfffffffff7b5a140.
warning: Breakpoint address adjusted from 0xf7de0aa4 to 0xfffffffff7de0aa4.
warning: Breakpoint address adjusted from 0xf7d0460e to 0xfffffffff7d0460e.
warning: Breakpoint address adjusted from 0xf7b5a140 to 0xfffffffff7b5a140.
0xf7f5cb49 in __kernel_vsyscall ()
warning: Breakpoint address adjusted from 0xffa8cb3f to 0xffffffffffa8cb3f.

Thread 1 "hl2_linux" received signal SIGTRAP, Trace/breakpoint trap.
0xffa8cb40 in ?? ()
warning: Unable to restore previously selected frame.
The program being debugged was signaled while in a function called from GDB.
GDB remains in the frame where the signal was received.
To change this behavior use "set unwindonsignal on".
Evaluation of the expression containing the function
(tc_malloc(size_t)) will be abandoned.
When the function is done executing, GDB will silently stop.
'dlerror' has unknown return type; cast the call to its declared return type
History has not yet reached $2.
rm: cannot remove '/tmp/.glSIVlUv': No such file or directory

**Comment by kranercc** [comment]
The following packages have unmet dependencies:
 libfreetype6-dev:i386 : Depends: libc6-dev:i386 but it is not going to be installed or
                                  libc-dev:i386
                         Depends: zlib1g-dev:i386 but it is not going to be installed or
                                  libz-dev:i386
                         Depends: libpng-dev:i386 but it is not going to be installed
 libsdl2-dev:i386 : Depends: libibus-1.0-dev:i386 but it is not going to be installed
                    Depends: libmirclient-dev:i386 but it is not going to be installed
                    Depends: libpulse-dev:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.





#######33
I've installed :amd64, but i386 doesn't work to be installed

**Comment by BenCat07** [comment]
What distrobution of linux are you using?

**Comment by kranercc** [comment]
> What distrobution of linux are you using?

What is this question? Are you interested in the kernel or do you ask this just for the sake of asking a question?

**Comment by TotallyNotElite** [comment]
> > What distrobution of linux are you using?
> 
> What is this question? Are you interested in the kernel or do you ask this just for the sake of asking a question?

He's asking because this is a bug related to your distributions package manager.

**Comment by TotallyNotElite** [comment]
Stale issue. Contact on telegram if you need further help, because this is not a cathook bug.
