### ISSUE TITLE
[Suggestion] Option to make Autobackstab with Backtrack wait some miliseconds before trying to stab

### ISSUE THREAD

**Issue by xXTevinOfficialXx** [nullworks/cathook#889]
Make an option that when checked, it will wait a determined time in miliseconds (like 2 miliseconds) for being sure that will backstab the player when using Backtrack, example making a checkbox that its the option, and a textbox below it, to determine the time (e.g 2 for 2 miliseconds)

**Comment by BenCat07** [comment]
Anything below 15ms wouldn't do anything. It will also not fix backstab backtrack issues, they're caused through backtrack's code
