### ISSUE TITLE
Is it normal cathook dont mark you as a cathook user after accidentally changing your status?

### ISSUE THREAD

**Issue by xXTevinOfficialXx** [nullworks/cathook#899]
Was messing around with playerlist when accidentally marked myself as a normal player, then i couldn't get cathook user status again

**Comment by BenCat07** [comment]
It marks you as a cathook user again given enough time.

**Comment by xXTevinOfficialXx** [comment]
I'm still marked as a normal player, this already happened some days ago

**Comment by TotallyNotElite** [comment]
Does it even matter?

**Comment by xXTevinOfficialXx** [comment]
Eh, not that much but mainly because i wanted to see the rainbow thing on the learderboard lol
