### ISSUE TITLE
Terminal says that cathook was injected, but nothing happens on TF2

### ISSUE THREAD

**Issue by xXTevinOfficialXx** [nullworks/cathook#904]
Just installed Manjaro LXDE (18.1.0 Juhraya), downloaded TF2, installed Cathook with all the dependencies that it needed, but when i tried to attach it with "sudo ./attach", it outputs that was compiled successfully and all those misterious codes that i never understood, then when i go to the TF2 window, nothing happened, Cathook didn't attach, console didnt change, nothing, could anyone help me here?

**Comment by BenCat07** [comment]
Give us some output

**Comment by xXTevinOfficialXx** [comment]
My bad, forgot to close, already fixed.
