### ISSUE TITLE
Cathook makes my tf2 crash after 5-10 minutes playing on the tf2 menu or on a match

### ISSUE THREAD

**Issue by xXTevinOfficialXx** [nullworks/cathook#914]
Well, after i installed Manjaro XFCE, cathook started making my game crash, at  first i thought that it was just a temporary error, but then the weeks passed, tf2 started crashing more often, then some days ago, i tried tf2 without cathook to see if it was the cheat that was crashing my game, and guess what, tf2 actually ran without any issues, no crashes, nothing wrong, so i thought that the issue was fixed, attached cathook, and at the first minute of the match, tf2 crashed.

My specs:
CPU: Intel Celeron N3350 1.10 GHz
GPU: Integrated GPU (Intel HD Graphics 500)
Ram: 4 GB

**Comment by BenCat07** [comment]
I don't recommend attaching ingame. Also next time use the template we provided, i need a crash log and cathook log

**Comment by TotallyNotElite** [comment]
Need more info. What's your commit hash?

**Comment by TotallyNotElite** [comment]
> I don't recommend attaching ingame.

Why's that? As far as I'm aware, this is fully supported behavior.

**Comment by BenCat07** [comment]
> > I don't recommend attaching ingame.
> 
> Why's that? As far as I'm aware, this is fully supported behavior.

Timers

**Comment by xXTevinOfficialXx** [comment]
First of all, i'm not attaching ingame, im attaching at the menu of tf2 before getting into a match, and second of all, what the heck is commit hash and segfault log? where could i get the cathook log?

**Comment by BenCat07** [comment]
commit hash is in top left under cathook label. logs are in /tmp/

**Comment by xXTevinOfficialXx** [comment]
The commit hash is: #4606970
This is the log that i found on /tmp/
[cathook-tevin-2100.log](https://github.com/nullworks/cathook/files/4206635/cathook-tevin-2100.log)

**Comment by xXTevinOfficialXx** [comment]
Fixed
