### ISSUE TITLE
How to run appimage as root user

### ISSUE THREAD

**Issue by ghost** [nullworks/cathook#920]
As in tittle how can i run appimage cathook as root user?

**Comment by TotallyNotElite** [comment]
No.

**Comment by TotallyNotElite** [comment]
What are you trying to achieve?

https://en.wikipedia.org/wiki/XY_problem

**Comment by BenCat07** [comment]
> how can i run appimage cathook as root user?

You never run something as root unless it forces you to

**Comment by Trapacid** [comment]
There is absolutely no reason to run the appimage as root, nor would things work properly if you did.
