### ISSUE TITLE
Suggestion/Idea

### ISSUE THREAD

**Issue by xXTevinOfficialXx** [nullworks/cathook#922]
You guys could make a AA that the fake AA (the one the server would see i think), look like normal, as if nothing was happening, while the real AA, flick using the aimbot, or aiming at the back using auto backstab.This way it could look more like a silent auto backstab/aimbot
Well, thats just a suggestion/idea, if this could work or not, i dont know

**Comment by BenCat07** [comment]
Doesn't work on autobackstab and already being applied for Aimbot

**Comment by xXTevinOfficialXx** [comment]
Ok, thanks for the answer.
