### ISSUE TITLE
not injecting

### ISSUE THREAD

**Issue by debilekjsem** [nullworks/cathook#923]
I looked through a lot of issues that were similar as mine, but I didnt find any working solution.
Game doesnt crash. What happens after `sudo ./attach` :

Running instances: 2759
Attaching to 2759
loading /tmp/.glFepqH9 to 2759
[New LWP 2760]
[New LWP 2783]
[New LWP 2784]
[New LWP 2802]
[New LWP 2804]
[New LWP 2810]
[New LWP 2811]
[New LWP 2832]
[New LWP 2833]
[New LWP 2834]
[New LWP 2835]
[New LWP 2836]
[New LWP 2837]
[New LWP 2840]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0xefcd59fc in ?? () from /home/bpt/.steam/steam/steamapps/common/Team Fortress 2/bin/shaderapidx9.so
$1 = (void *) 0x0
'dlerror' has unknown return type; cast the call to its declared return type
History has not yet reached $2.
[Inferior 1 (process 2759) detached]

**Comment by BenCat07** [comment]
$1 usually is not 0x0


What Distro of linux are you using?

**Comment by debilekjsem** [comment]
Ubuntu 19.10

**Comment by BPTdevelopment** [comment]
So is there a way to fix it?

**Comment by BenCat07** [comment]
$1 being 0x0 usually means the compile/link process did not go well, did you try rebuilding cathook via ./update?

**Comment by debilekjsem** [comment]
Yes. Now its slightly different:  


Running instances: 3450
Attaching to 3450
loading /tmp/.glntCodu to 3450
[New LWP 3452]
[New LWP 3454]
[New LWP 3459]
[New LWP 3460]
[New LWP 3526]
[New LWP 3528]
[New LWP 3534]
[New LWP 3535]
[New LWP 3622]
[New LWP 3623]
[New LWP 3624]
[New LWP 3625]
[New LWP 3626]
[New LWP 3627]
[New LWP 3628]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0xf7fc1b49 in __kernel_vsyscall ()
$1 = (void *) 0x0
'dlerror' has unknown return type; cast the call to its declared return type
History has not yet reached $2.
[Inferior 1 (process 3450) detached]

**Comment by BenCat07** [comment]
still $1 = (void *) 0x0

what does
`ldd bin/libcathook.so`
output?

**Comment by debilekjsem** [comment]
"not a dynamic executable"

**Comment by BenCat07** [comment]
You ran that from the cathook folder?

**Comment by debilekjsem** [comment]
yeah

**Comment by BenCat07** [comment]
what does `ldd build/bin/libcathook.so` output?

**Comment by debilekjsem** [comment]
same thing "not a dynamic executable"

**Comment by BenCat07** [comment]
Something is very wrong. We tell it to build a dynamic executable, yet it doesn't.
Does `./scripts/dependencycheck`
do anything?

**Comment by debilekjsem** [comment]
nothing...

**Comment by BenCat07** [comment]
I've honestly got no idea why it is not building a dynamic executable. Maybe `cmake --version` can help us here?

**Comment by debilekjsem** [comment]
ver: 3.13.4

**Comment by BenCat07** [comment]
Looks fine, `file bin/libcathook.so`

**Comment by debilekjsem** [comment]
well, it says its empty

**Comment by BenCat07** [comment]
This is making less and less sense
`ls -l --block-size=KB bin/libcathook.so `

**Comment by debilekjsem** [comment]
-rwxr-xr-x 1 user 0kB Feb 28 16:06 bin/libcathook.so

**Comment by BenCat07** [comment]
Whatever it is, it is not compiled. ./update does nothing?

**Comment by debilekjsem** [comment]
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
HEAD is now at 4606970 Fix edge case in ubuntu dependency install script
~/cathook/build ~/cathook
-- cotire 1.8.0 loaded.
-- Boost version: 1.67.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/cathook/build
[100%] Built target cathook
Installing cathook data to /opt/cathook/data
sending incremental file list
./
fonts/
menu/
menu/nullifiedcat/
menu/nullifiedcat/misc/
menu/nullifiedcat/trigger/
menu/nullifiedcat/visuals/
sound/
textures/

sent 2.46K bytes  received 285 bytes  5.49K bytes/sec
total size is 7.28M  speedup is 2,654.43
sending incremental file list
./

sent 182 bytes  received 19 bytes  402.00 bytes/sec
total size is 369.92K  speedup is 1,840.41
Built target data
~/cathook

**Comment by BenCat07** [comment]
cd build;make clean;cd ..;./update

**Comment by debilekjsem** [comment]
ok now its building some things

**Comment by debilekjsem** [comment]
Ok, its working. Thanks for your help.

**Comment by BenCat07** [comment]
No problem, i wonder how this happened though...
