### ISSUE TITLE
Failed to compile cathook  on Kali linux 

### ISSUE THREAD

**Issue by Imikeeee** [nullworks/cathook#924]
Installation error on fresh installed Kali linux 

In the program

HEAD is now at 4606970 Fix edge case in ubuntu dependency install script
~/Desktop/cathook/cathook/build ~/Desktop/cathook/cathook
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find SDL2 (missing: SDL2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  external/FindSDL2.cmake:167 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:110 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/onion/Desktop/cathook/cathook/build/CMakeFiles/CMakeOutput.log".
See also "/home/onion/Desktop/cathook/cathook/build/CMakeFiles/CMakeError.log".
 
 
Failed to compile cathook

CMakeOutput.log 

https://pastebin.com/Lasb64iL

CMakeError.log

https://pastebin.com/49rLyRNQ

Uname -a 

Linux onion 5.4.0-kali4-amd64 #1 SMP Debian 5.4.19-1kali1 (2020-02-17) x86_64 GNU/Linux

**Comment by BenCat07** [comment]
We only support Ubuntu (newer versions) and Manjaro as of right now. Kali Linux uses Debian as a base, it's packages are too old. If you want to use cathook on Kali linux you will have to find the packages with new enough versions yourself.

**Comment by BenCat07** [comment]
> Could NOT find SDL2 (missing: SDL2_INCLUDE_DIR)

You are missing SDL 2.

**Comment by TotallyNotElite** [comment]
User: is not a security engineer/researcher
Also user: uses kali linux
Me: O.o

**Comment by gitblep** [comment]
Real pros use wireshark

**Comment by c00lguy** [comment]
>unable to check logs and install libraries
>uses kali linux
