### ISSUE TITLE
[Suggestion] Adding Tooltips to Menu Items

### ISSUE THREAD

**Issue by LightPower392** [nullworks/cathook#926]
I noticed that autoheal.xml has this `tooltip="Pop ubercharge if rocket is near and health is less than" min="0" max="450"`
This tooltip doesn't show up in the game however, but I think this would be a good way to make cathook more new user friendly. I tried adding it in src/visual/menu/menu/Text.cpp but couldn't get it to work. Any suggestions on how a tooltip system could be added?

**Comment by TotallyNotElite** [comment]
This looks like a bug. I'll look at when I can find some time to debug this or @BenCat07 will have to take a look.
