### ISSUE TITLE
Not injecting after sudo ./attach

### ISSUE THREAD

**Issue by thelightofday** [nullworks/cathook#941]
Hi there, when I was checking for issues since my cathook wasn't working, I saw this in the console after doing the debug.
Running instances: 36706 51742
Attaching to 36706
loading /tmp/.gl24YAZ6 to 36706
[New LWP 36708]
[New LWP 37099]
[New LWP 38126]
[New LWP 41641]
[New LWP 41966]
[New LWP 42509]
[New LWP 44740]
[New LWP 45221]
[New LWP 46462]
[New LWP 46647]
[New LWP 47851]
[New LWP 48032]
[New LWP 48122]
[New LWP 50124]
[New LWP 50210]
[New LWP 50682]
[New LWP 51729]
[New LWP 51900]
warning: Could not load shared library symbols for 19 libraries, e.g. /tmp/.glRVO0Nq.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0xf7fb8b49 in __kernel_vsyscall ()
[New Thread 0xb7fb3b40 (LWP 53125)]
$1 = (void *) 0xa568680
'dlerror' has unknown return type; cast the call to its declared return type
History has not yet reached $2.
Thread 1 "hl2_linux" received signal SIGINT, Interrupt.
0xf7fb8b49 in __kernel_vsyscall ()
#0  0xf7fb8b49 in __kernel_vsyscall ()
#1  0xf59dad07 in __pthread_clockjoin_ex () from /usr/lib32/libpthread.so.0
#2  0xf59daa4a in pthread_join () from /usr/lib32/libpthread.so.0
#3  0xf5bd00d8 in ?? ()
#4  0xf581f3b6 in __run_exit_handlers () from /usr/lib32/libc.so.6
#5  0xf581f595 in exit () from /usr/lib32/libc.so.6
#6  0xf5806ef1 in __libc_start_main () from /usr/lib32/libc.so.6
#7  0x080488e5 in _start ()
[Inferior 1 (process 36706) detached]

Is the "Thread 1 'hl2_linux' received..." and the 0xfxxxxxxx the reason why it's not working?

**Comment by thelightofday** [comment]
My distro is Manjaro incase you are wondering.

**Comment by LightPower392** [comment]
Did you install using the .AppImage?

**Comment by TotallyNotElite** [comment]
> My distro is Manjaro incase you are wondering.

Install the package steam-native and try again.

**Comment by thelightofday** [comment]
After installing steam-native I get this.
Running instances: 3064
Attaching to 3064
chown: changing ownership of '/tmp/dumps': Operation not permitted
loading /tmp/.gliVUxyF to 3064
ptrace: Operation not permitted.
No symbol table is loaded.  Use the "file" command.
You can't do that without a process to debug.
No symbol table is loaded.  Use the "file" command.
History has not yet reached $2.
The program is not being run.

**Comment by thelightofday** [comment]
Wait, forgot to sudo this part.
