### ISSUE TITLE
[Requesting Feedback] Config List in Menu

### ISSUE THREAD

**Issue by LightPower392** [nullworks/cathook#948]
Currently, creating and loading configs is done through the console. I have made a development version that adds a delete command, then lets all of this functionality be done through a menu option.
![configs](https://user-images.githubusercontent.com/60998601/78820932-77792880-798d-11ea-907a-34e5e649a659.png)
There is a text input to save, load, or delete a config as well as a list of all of your configs that updates whenever a config is created or deleted. I am asking for feedback of people's thoughts on this.

**Comment by TotallyNotElite** [comment]
Much better than having no GUI at all for this, but requiring entry in an input field is not ideal.

**Comment by LightPower392** [comment]
The way the text inputs work is when you enter a string the field is automatically cleared. This is like how "xd" automatically unchecks itself.
