### ISSUE TITLE
Could not load shared library

### ISSUE THREAD

**Issue by luimu64** [nullworks/cathook#951]
When I try to run cathook in source mode in GUI or when using CLI version with ./attach I get error:

warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0xf2259d28 in ?? () from /home/luimu/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
[New Thread 0xc408db40 (LWP 9953)]
$1 = (void *) 0x2c8fc2c0
'dlerror' has unknown return type; cast the call to its declared return type
History has not yet reached $2.
[Inferior 1 (process 8108) detached]

With GUI binary mode everything works fine.
I am using Manjaro.

**Comment by BenCat07** [comment]
it's a warning, not error.

**Comment by luimu64** [comment]
I tested it before and it gave that and did not work but now when I tested it again it gave the warning and worked. Guess this was useless issue then.
