### ISSUE TITLE
Game crashing when joining a server

### ISSUE THREAD

**Issue by telephonemast** [nullworks/cathook#963]
**"Out of memory or address space. Texture quality setting may be too high."**

So I've read this issue has to do with running out of vram, sort of strange considering my RX 5700 has 8gb. If it's an issue with plain old ram i have 16gb. All my video settings are set to the lowest they can get. 
I've tried joining custom servers and official servers.
I've tried using the GUI cathook and the terminal version
I've tried starting TF2 linux version normally and with Valve proton
*I installed chris' config - which lowers gfx settings - and this was able to delay the crash for at least 30 seconds.

the issue is recreated every time... is there a way to only load in half of the bells and whistles that come with cathook at a time, so that it is not as big a load? I'm really not sure what could be causing this issue, any help is greatly appreciated.
btw I'm running Ubuntu 18.04.4 LTS

**Comment by BenCat07** [comment]
This is a tf2 issue. you can easily replicate it by typing "map tr_walkway_rc2" while already on the map, i have no say or control over this, ans cannot fix the isssue as it ia not related to cathook, but how linux tf2 handles memory
