### ISSUE TITLE
Killsay is not working properly 

### ISSUE THREAD

**Issue by aimnotacheater** [nullworks/cathook#976]
**Describe the Bug**
I changed killsays.txt in config_data , but messages in-game are still default (shit about macro and and "change this to actual phrases").

**To Reproduce**
1. change config.
2. kill someone.
3. Profit.

**Expected behavior**
Change phrase after kill.

**Screenshots**
No screen needed.

*Logs*

[cathook-sonofstan-18658.log](https://github.com/nullworks/cathook/files/4536567/cathook-sonofstan-18658.log)
[cathook-sonofstan-19207.log](https://github.com/nullworks/cathook/files/4536568/cathook-sonofstan-19207.log)

**Additional context**
Yes, i reloaded game and cat after changing config, twice. Yes, i updated cat. No, config for cat was default.

**Comment by BenCat07** [comment]
config_data is a **one time change and not your data directory**

The file you want to change is in either /opr/cathook/data (if available), or ~/.local/share/cathook

**Comment by aimnotacheater** [comment]
Thanks, that worked!
