### ISSUE TITLE
./reattach crashes cathook

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [nullworks/cathook#98]
Honestly, having reattach as an option would make dev so much easier.

**Comment by nullifiedcat** [comment]
I have no idea why it does that.

**Comment by Tehcatninja** [comment]
Probably cause what reattach does is unattach's it an reattaches it.
So that would more than likely cause it to crash if you didnt have it attached

**Comment by no-boot-device** [comment]
Detaching does not crash if not injected.
I'm not sure if it crashes when injected.

**Comment by nullifiedcat** [comment]
Probably a hook that never gets properly disposed, probably some resource never gets released.

**Comment by gir489** [comment]
Looks like you're not unhooking the VTables during your Shutdown call. They're probably trying to still access your replaced function which now no longer exists.

**Comment by nullifiedcat** [comment]
>Looks like you're not unhooking the VTables during your Shutdown call. They're probably trying to still access your replaced function which now no longer exists.

I do, the unhooking is done in the destructor of VMTHook
