### ISSUE TITLE
[Request] Exclusive option to have projectile weapons aim only at the feet.

### ISSUE THREAD

**Issue by totallynotspook** [nullworks/cathook#994]
While setting in aimbot settings the aimbot to static and to aim at either right or left feet works, it also forces the shotgun to aim only at the feet, I know auto/auto-closest can be used as well but just a suggestion.

**Comment by TotallyNotElite** [comment]
Duplicate of #750, if you disagree then just tell me here

**Comment by BenCat07** [comment]
they already aim at the feet, if the enemy is on ground that is, else it shoots at hip
